### ISSUE TITLE
[FeatureRequest] Add option to show/hide arrow and modify arrow style

### ISSUE THREAD

**Issue by deckyfx** [hossein-zare/react-native-dropdown-picker#1]
Nice picker!
Might be good to give option to  show/hide arrow and modify arrow style

i modify it to like this
`{this.props.showArrow ? (
              <View
                style={[
                  {
                    opacity: disabled ? 0.5 : 1,
                  },
                  this.props.arrowStyle,
                ]}>
                {!this.state.visible ? (
                  <Feather name="chevron-down" size={15} />
                ) : (
                  <Feather name="chevron-up" size={15} />
                )}
              </View>
            ) : null}`

**Comment by hossein-zare** [comment]
> Nice picker!
> Might be good to give option to show/hide arrow and modify arrow style
> 
> i modify it to like this
> `{this.props.showArrow ? ( <View style={[ { opacity: disabled ? 0.5 : 1, }, this.props.arrowStyle, ]}> {!this.state.visible ? ( <Feather name="chevron-down" size={15} /> ) : ( <Feather name="chevron-up" size={15} /> )} </View> ) : null}`

Thank you for the request. 😉
Some new features have been added to the package.
Check out the props.
