### ISSUE TITLE
Picker background color

### ISSUE THREAD

**Issue by jonathanwijaya** [hossein-zare/react-native-dropdown-picker#10]
Hi, I have trouble modyfying the css for the background color on the component, as you can see i can only alter the background color,  but the problem is the background color is not covering all of the component. 
![82481ae9-9bb9-45e4-8593-776d4cab9077](https://user-images.githubusercontent.com/23584235/82795058-a4ca5900-9e9d-11ea-896a-68a5c9615ead.jpg)

How can I modify the styling for that and how can I change the arrow color using this library 

below is snippet of my code

 defaultIndex={0}
            containerStyle={{height: 40}}
            itemStyle={{
              backgroundColor: '#303030',
              alignItems: 'center',
              flex: 1,
            }}
            arrowStyle={{marginLeft: 10}}
            onChangeItem={(item) =>
              this.setState({
                memberShiptype: item.value,
              })
            }
            style={{
              backgroundColor: '#303030',
            }}

**Comment by hossein-zare** [comment]
Hello,

I added a new property, You have to specify the backgroundColor for both the `style` and `dropDownStyle` properties.

**Update the package to v2.1.3**

```javascript
<DropDownPicker
    items={[
        {label: 'Item 1', value: 'item1'},
        {label: 'Item 2', value: 'item2'},
    ]}

    style={{backgroundColor: '#fafafa'}}
    dropDownStyle={{backgroundColor: 'fafafa'}}

    defaultIndex={0}
    containerStyle={{height: 40}}
    onChangeItem={item => console.log(item.label, item.value)}
/>
```

**Comment by jonathanwijaya** [comment]
Hi, thanks for the fast response, I will try it once I am able to. Does it include the modifying the arrow color?
Which also mean I need to change your library version in my package.json to 2.1.3? I'm quite new to using library.

**Comment by hossein-zare** [comment]
No, but you can take advantage of the `customArrowUp` and `customArrowDown` properties where you can define custom arrow icons with color.
DropDownPicker uses `react-native-vector-icons/Feather`
```javascript
// Icon
import Feather from 'react-native-vector-icons/Feather';

<DropDownPicker
    ...
    customArrowUp={<Feather name="chevron-up" size={15} color="#000" />}
    customArrowDown={<Feather name="chevron-up" size={15} color="#000" />}
    ...
/>
```

**Comment by hossein-zare** [comment]
**New Version**
I just released **v2.1.4**
Now it's possible to specify the arrow color.
```javascript
arrowColor="#2cbe4e"
```

**Comment by jonathanwijaya** [comment]
Hi, I'm sorry for the very late response, but thanks for the update and it works!

**Comment by sushmitg** [comment]
Is it possible to change the background color of the dropdown only when a value is selected?
