### ISSUE TITLE
how to go over another DropDownPicker

### ISSUE THREAD

**Issue by pikooli** [hossein-zare/react-native-dropdown-picker#101]
hello , i got a little problem , when i put 2 DropDownPicker one just a little higher than the other , 
the one higher got not render over the second one , we can see the second one.

how to fixe that ? i try zindex in a view container , in the style props and itemstyle props but it doesn't  work 

it on ios and android 

here a snack 
[snack](https://snack.expo.io/@pikl/droplist)

**Comment by pikooli** [comment]
ok fixe it , it should be render together :/ , i did put it in different hook

**Comment by pikooli** [comment]
Not it was a stupid flex that have nothing to do here : /

**Comment by hossein-zare** [comment]
Hello,
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

Snack:
https://snack.expo.io/uGcjMvOYV

**Comment by patrickml** [comment]
I solved this by useing the zIndex prop on the picker its self
```
<DropDownPicker zIndex={9}>
<DropDownPicker zIndex={8}>
<DropDownPicker zIndex={7}>
```
