### ISSUE TITLE
Search TextInput should be clear when I select any value

### ISSUE THREAD

**Issue by mitesh-db** [hossein-zare/react-native-dropdown-picker#105]
Hi @hossein-zare ,
Is there anything I'm missing for search?
When I search & select something, picker closes.. When reopening picker old search text is not getting clear.

Here is the screenshot: https://prnt.sc/uatnsj

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-dropdown-picker": "3.6.3",

**Comment by hossein-zare** [comment]
Hello,

I'll fix the issue, Thank you for reporting.
