### ISSUE TITLE
RTL Support doesn`t work

### ISSUE THREAD

**Issue by ma3x-rus** [hossein-zare/react-native-dropdown-picker#106]
Hi there!
I updated react-native-dropdown-picker but it still doesn`t work for me
help please, what can I do wrong?
my styles:
itemStyle={{flexDirection: 'row-reverse', justifyContent: 'flex-end'}}
style={{
backgroundColor: 'rgba(255,22,255,0)',
width:width(47),
borderRadius:width(0),
flexDirection: 'row-reverse',
borderColor: 'rgba(255,22,255,0)',
},}

**Comment by ma3x-rus** [comment]
UPD: sometimes it shows correctly, sometimes not(when I rebuild my project), when I don`t change styles

**Comment by hossein-zare** [comment]
Hello,

`npm start -- --reset-cache`
