### ISSUE TITLE
Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by shorya-stanza** [hossein-zare/react-native-dropdown-picker#108]
Suppose there are two drop-downs, 
Select Value of first drop-down and re-initialise the second drop-down to default then select value of second drop-down.

Then again Change the value of first and reset the value of second drop-down using state

[https://snack.expo.io/@stanzaliving/8ffd2c](url)

**Comment by hossein-zare** [comment]
Hello,
None of the keys of your items are empty, All of them are `usa`
```javascript
const selectValue = (key, item) => {
    if(key==='first'){
        setFirst(item.value);
        setSecond(''); // MUST BE:     setSecond(null);
    } else {
        setSecond(item.value)
    }
}
```

**Comment by shorya-stanza** [comment]
Thanks.

**Comment by GnApollo** [comment]
![image](https://user-images.githubusercontent.com/46991581/93565296-b63fef80-f9bd-11ea-9643-52012800b1cc.png)
