### ISSUE TITLE
backgroundColor or elevation in ContainerStyle brick switch function (android)

### ISSUE THREAD

**Issue by niklasklupiec** [hossein-zare/react-native-dropdown-picker#11]
If elevation or backgroundColor are defined in the ContainerStyle, its not possible to switch between items.

**Comment by hossein-zare** [comment]
Hello,
Please add them to the `style` property, You also have to add `backgroundColor` to the `dropDownStyle` property.

```javascript
style={{elevation: 1, backgroundColor: '#fafafa'}}
dropDownStyle={{backgroundColor: '#fafafa'}}
```

> The containerStyle property.
> Use this to adjust the outer part of the picker such as margin, width, height.

**Comment by niklasklupiec** [comment]
This works fine. Though the reason I wanted to use `elevation` and `backgroundColor` in the `ContainerStyle` is, that I wanted to change the `borderRadius` of the picker.

I did this with `width: '90%', borderWidth: 0` in the `style` property and 
`elevation: 10, backgroundColor: '#f00' `  in the `ContainerStyle` property (causing a disabled switch function)

Is there another way to change the `borderRadius` ?

PS: I just switched to your Picker from @react-native-community/picker and its amazing. Keep up the good work. I really appreciate your quick response to issues.

**Comment by hossein-zare** [comment]
Yes, but `borderRadius` won't work as you expect.
There are two props called `style` and `dropDownStyle` responsible for the apperance of the picker.

Here's an example:
```javascript
style={{
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10
}}
dropDownStyle={{
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10
}}
```
If `elevation` doesn't work with the `style` prop please let me know.

Thanks for the feedback.

**Comment by niklasklupiec** [comment]
Works perfectly, thank you
