### ISSUE TITLE
Dropdown Arrow Icon missing

### ISSUE THREAD

**Issue by hunainaslam** [hossein-zare/react-native-dropdown-picker#110]
**Describe the bug**
Dropdown Arrow Icon missing for me when I add the picker. Do i need to import something else?

**To Reproduce**
Attached screenshot

**Screenshots**
<img width="267" alt="Screen Shot 2020-09-08 at 2 13 08 pm" src="https://user-images.githubusercontent.com/9814296/92432515-b54cd800-f1dd-11ea-970f-bfa7e1cdbd18.png">

**Info (please complete the following information):**
 - OS: iOS 13.5
 - "react-native": "0.61.5",

**Comment by who-is-apo** [comment]
Hey @hunainaslam . Did you find a solution? I came across the same issue, and don't know what to do.

**Comment by marcozciuffini** [comment]
looking into the other closed issues, this is a react-native-vector-icons issue and was solved by 

react-native link react-native-vector-icons

I'm pretty sure in the newer versions of react-native they _should_ auto-link however this solved my issue

**Comment by hunainaslam** [comment]
@karolsw3 Yeah I fixed it by manually adding icons. Wasn't fixed by react-native link as i'm using RN 0.61.5

```customArrowDown={() => <MaterialIcon name='arrow-drop-down' size={Constants.DEFAULT_SIZE} color={Constants.SELECTED_COLOR} />}```
```customArrowUp={() => <MaterialIcon name='arrow-drop-up' size={Constants.DEFAULT_SIZE} color={Constants.SELECTED_COLOR} />}```
