### ISSUE TITLE
Can't click when its in modal

### ISSUE THREAD

**Issue by mtalhagaoglu** [hossein-zare/react-native-dropdown-picker#112]
Hi. I'm trying use a searchable dropdown in modal. Actually its very basic design but didn't work. I think its because of background color because when i set a backgroundcolor its not working. but i have to use a backgroundcolor. is there a way use both background color and this lib?

<Modal  style={{backgroundColor: "white"}} isVisible={true}>
<Dropdown/>
</Modal>

**Comment by mtalhagaoglu** [comment]
i removed childeren's style and added customBackdrop to Modal. its working now but definitely not the true solution

**Comment by hossein-zare** [comment]
Hello,

Yes, it's because of  `backgroundColor`.
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

There's no solution, React Native has to take responsibility for the issue.
