### ISSUE TITLE
activeItemStyle not working right

### ISSUE THREAD

**Issue by ma3x-rus** [hossein-zare/react-native-dropdown-picker#113]
Hi there!
When I set the activeItemStyle, it applies to all values in the drop-down list, but should only apply to one. How do I fix this?

**Comment by ma3x-rus** [comment]
the same problem with activeLabelStyle

**Comment by hossein-zare** [comment]
Hello,

Attach your code and Snack please if possible.

**Comment by ma3x-rus** [comment]
<DropDownPicker
            items={leftButtonData}
            containerStyle={{height:height(6)}}
            style={styles.LeftButton2}
            itemStyle={{justifyContent: 'flex-start', height:height(4)}}
            dropDownMaxHeight={height(45)}
            isVisible={this.props.isVisibleLeft}
            scrollViewProps={{showsVerticalScrollIndicator:false}}
            // activeItemStyle={{backgroundColor: 'black'}}
            dropDownStyle={{flexDirection: 'column', 
                            backgroundColor: 'rgba(255,255,255,0)', 
                            borderWidth: width(0),
                            width:width(47)}}
            labelStyle={styles.buttonBottomTextLeft}
            placeholderStyle={{fontSize: width(3.5)}}
            placeholder={this.props.placeholderLeft}
            onOpen={this.props.onOpenLeft}
            onClose={this.props.onCloseLeft}
            onChangeItem={this.props.onSelect}
            arrowColor={'white'}
            arrowSize={22}
          />

         onSelect={(item,index)=>this.myFunc(item,index)}

         myFunc(item, value) {
          const {leagueCalendar} = this.state;
          this.setState({activeTeam: item, leagueCalendar});
         };

**Comment by hossein-zare** [comment]
Also add items.

**Comment by ma3x-rus** [comment]
{"image": "/images/teams/f1.png", "label": "F1", "name": "F1", "short_name": "F1", "team_id": 30} for example

**Comment by ma3x-rus** [comment]
Thank you, I need also add 'value' for all items

**Comment by ma3x-rus** [comment]
but answer me please, how can I add icon only for active element?

**Comment by hossein-zare** [comment]
@ma3x-rus That's not possible.
