### ISSUE TITLE
Picker not working in android

### ISSUE THREAD

**Issue by BasappaBaligar** [hossein-zare/react-native-dropdown-picker#115]
**Describe the bug**
Not able to select the picker items in android with or without zIndex as mentioned in the documents. If I don't use the Index, picker view goes below the nested views. 

It works good only in iOS, completely useless for android.

**To Reproduce**

Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
Hello,

**zIndex Conflicts**
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

You can also send me your code.

**Comment by brokenarm1903** [comment]
> Hello,
> 
> **zIndex Conflicts**
> https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers
> 
> You can also send me your code.


Hello, 

I have similar issue about this. How to handle nested views without zIndex in android? 
Thank you for your help and this library :)

@hossein-zare
