### ISSUE TITLE
SearchInput throws TypeError:item.label.toLowerCase is not a function.

### ISSUE THREAD

**Issue by Danish64** [hossein-zare/react-native-dropdown-picker#118]
Hey Its been awesome experience to use react-native-dropdown-picker truly an angel work . Thanks for the package.

**Describe the bug**
I have an array like this 
`responseArray = ["1"," 24", "BS-44", "TY-45" ... ]`

Numerical and AlphaNumeric values also...

Whenever I search the dropdown it gives  TypeError:item.label.toLowerCase is not a function.

**I never made a function toLowerCase**

**Screenshots**
![searchError](https://user-images.githubusercontent.com/27826581/93777895-bc90ce80-fc3e-11ea-951c-41c08f3ff891.jpg)

**Info**
 - OS: [ Android]
 - Package version [6.14.5]

**Comment by hossein-zare** [comment]
Hello,

Are `["1"," 24", "BS-44", "TY-45" ... ]` set as your items?

Your items must look like this:
```javascript
items={[
    {label: 'UK', value: 'uk'},
    {label: 'France', value: 'france'},
]}
```

Please add your code snippet, items and the Package Version, [6.14.5] is not correct.

**Comment by Danish64** [comment]
> Hello,
> 
> Are `["1"," 24", "BS-44", "TY-45" ... ]` set as your items?
> 
> Your items must look like this:
> 
> ```js
> items={[
>     {label: 'UK', value: 'uk'},
>     {label: 'France', value: 'france'},
> ]}
> ```
> 
> Please add your code snippet, items and the Package Version, [6.14.5] is not correct.
Yes Yes It is like 
`responseArray = [{label: '1', value:  '1}]`
Yup package version is 3.6.8 ..I reinstalled it...

Thanks For such quick response ..Thank You

**Comment by Danish64** [comment]
I think the issue was due to **asyncronous nature of my data** (data comes from api which is taking too long 5-6 s).... The array data was not populated before it was passed ....
