### ISSUE TITLE
Tap Outside To Close Dropdown

### ISSUE THREAD

**Issue by djpetenice** [hossein-zare/react-native-dropdown-picker#119]
**Is your feature request related to a problem? Please describe.**
To be able to tap outside of the dropdown box to close the dropdown.

**Comment by dcangulo** [comment]
I don't know if this is the right way but I do mine like this:

Demo: https://snack.expo.io/@dcangulo/close-dropdown-on-outside-click

```js
import * as React from 'react';
import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';
import DropDownPicker from 'react-native-dropdown-picker';

export default function App() {
  const dropDownRef = React.useRef();

  return (
    <TouchableWithoutFeedback onPress={() => dropDownRef.current.close()}>
      <View style={styles.container}>
        <DropDownPicker
          items={[
            {label: 'UK', value: 'uk'},
            {label: 'France', value: 'france'}
          ]}
          containerStyle={{height: 40}}
          itemStyle={{justifyContent: 'flex-start'}}
          controller={(instance) => dropDownRef.current = instance}
        />
      </View>
    </TouchableWithoutFeedback>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    flex: 1
  }
});
```

**Comment by hossein-zare** [comment]
Hello @dcangulo ,

@dcangulo's answer is the only way to close the dropdown from outside.

**Comment by hossein-zare** [comment]
Hello @dcangulo ,

@dcangulo's answer is the only way to close the dropdown from outside.

**Comment by djpetenice** [comment]
@dcangulo Can't get the reference to work in your example above - throwing an error.

**Comment by hossein-zare** [comment]
@djpetenice What's the error?

**Comment by djpetenice** [comment]
@hossein-zare Invalid hook call. I have class extends component rather than export default function.

**Comment by hossein-zare** [comment]
Here's the docs:
https://github.com/hossein-zare/react-native-dropdown-picker#controller

**Comment by djpetenice** [comment]
@hossein-zare still having issues getting the ref to work but I have a question about the solution. Isn't this method going to block any other clickable content on screen if there's a TouchableWithoutFeedback covering it?

The previous library I was using (react-native-modal-dropdown) closed when clicking outside without a need for this type of method.

**Comment by hossein-zare** [comment]
@djpetenice https://snack.expo.io/ArCaOzCAL (for Class Components)

No, It won't overlay nested touchables.
The **modal** in **react-native-modal-dropdown** is Touchable which overlays other elements.

**Comment by Majda995** [comment]
@hossein-zare Hey i have the same Problem and i couldnt solve it with ure Solution , can u pls give me some Infirmation about it? thnx

**Comment by hossein-zare** [comment]
Hi @Majda995 ,
Please share a simplified version of your code.

**Comment by Majda995** [comment]
> Hi @Majda995 , Please share a simplified version of your code.

Hey, can u give me ure mail so i can share with u? Thanks

**Comment by hossein-zare** [comment]
@Majda995 
Share it here

**Comment by Majda995** [comment]
@hossein-zare so i receive a Code wich has different Classes and Component. My Task is that to close The DropDown when i click outside from it. 
The DropDown component is written in DropDownMenuComponent class and is called in SettingsPage Class. Here is 2 Photos from the Code. 
![DropDownMenu_Component](https://user-images.githubusercontent.com/84143401/136082058-7584bd39-aa72-4706-b13b-9e8515084758.PNG)
![SettingsPage](https://user-images.githubusercontent.com/84143401/136082062-d6bec8c0-66fa-4406-a35c-ed47ad777f2a.PNG)

**Comment by hossein-zare** [comment]
@Majda995 Nothing visible in your screenshots.

`TouchableWithoutFeedback` must be the first element in your component.

```jsx
const [open, setOpen] = useState(false);

<TouchableWithoutFeedback onPress={() => setOpen(false)}>
  <Text>Header</Text>

  <DropDownPicker
    open={open}
    setOpen={setOpen}

    ... />

  <Text>Footer</Text>
</TouchableWithoutFeedback>
```

You can also use `TouchableOpacity` with `activeOpacity={1}` prop.
```jsx
<TouchableOpacity onPress={() => setOpen(false)} activeOpacity={1}>
  ...
```

**Comment by Majda995** [comment]
It worked actually Thanks :) but when i build multiple DropDown they will show all at the same Time how can i resolve that?

**Comment by hossein-zare** [comment]
@Majda995 You should create new state variables (`useState`) for each component.

```jsx
const [open1, setOpen1] = useState(false);
const [open2, setOpen2] = useState(false);
...

const [value1, setValue1] = useState(null);
const [value2, setValue2] = useState(null);
...

<DropDownPicker
  open={open1}
  setOpen={setOpen1}
  value={value1}
  setValue={setValue1}
  ... />

<DropDownPicker
  open={open2}
  setOpen={setOpen2}
  value={value2}
  setValue={setValue2}
  ... />
```

**Comment by CaptainHaider** [comment]
Hacky way, to solve it if you have create custom dropDown
on Parent component use

```
const [closeDropDown, setCloseDropDown] = useState(false);
 <TouchableNativeFeedback
        onPress={() => {
          setCloseDropDown(!closeDropDown);
        }}>
....
```

Here is Child Component
```


export const CustomDropDown = ({
closeDropDown,
  ...props
}: Props) => {
  const [open, setOpen] = useState(false);
useEffect(() => {
    setOpen(false);
  }, [closeDropDown]);

  return (
    <View>
      <DropDownPicker
        {...props}
      />
    </View>
  );
};


```

**Comment by senghuotlay** [comment]
it seems like when we're using it in a child component, we do have to wrap the entire parent with     `<TouchableWithoutFeedback onPress={() => setOpen(!open)}>` , otherwise this wouldn't work

**Comment by AhmedHF** [comment]
> I don't know if this is the right way but I do mine like this:
> 
> Demo: https://snack.expo.io/@dcangulo/close-dropdown-on-outside-click
> 
> ```js
> import * as React from 'react';
> import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';
> import DropDownPicker from 'react-native-dropdown-picker';
> 
> export default function App() {
>   const dropDownRef = React.useRef();
> 
>   return (
>     <TouchableWithoutFeedback onPress={() => dropDownRef.current.close()}>
>       <View style={styles.container}>
>         <DropDownPicker
>           items={[
>             {label: 'UK', value: 'uk'},
>             {label: 'France', value: 'france'}
>           ]}
>           containerStyle={{height: 40}}
>           itemStyle={{justifyContent: 'flex-start'}}
>           controller={(instance) => dropDownRef.current = instance}
>         />
>       </View>
>     </TouchableWithoutFeedback>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     padding: 20,
>     flex: 1
>   }
> });
> ```

not working
any anther solution?

**Comment by abdenassar01** [comment]
here is my code for a custom drop down with nativewind and have this functionality using a touchable opacity to wrap screen when opened and attach event to close the drop down automatically when user clicks outside the dropdown content.

```/* eslint-disable react-native/no-inline-styles */
import {Dimensions, TouchableOpacity, View} from 'react-native';
import React, {useState} from 'react';
import {MainText, Spacer, TranslatedHeading, TranslatedText} from '../../..';
import {cn} from '../../../../../utils';
import {Control, useController} from 'react-hook-form';
import {ScrollView} from 'react-native-gesture-handler';
import {Wander} from 'react-native-animated-spinkit';
import colors from '../../../../../../configs/colors';

type Props = {
  items: any[];
  extractValue: (item: any) => any;
  extractDisplayMember: (item: any) => string;
  control: Control<any>;
  name: string;
  label: string;
  loading?: boolean;
  className?: string;
  defaultText?: string;
  wrapperClassName?: string;
};

export function DropDown({
  className,
  control,
  extractDisplayMember,
  extractValue,
  items,
  label,
  name,
  loading,
  defaultText,
  wrapperClassName,
}: Props) {
  const [showDropdown, setShowDropdown] = useState<boolean>(false);
  const [displayMember, setDisplayMember] = useState<string>('');

  const {
    fieldState: {error},
    field: {onChange},
  } = useController({
    name,
    control,
  });
  return (
    <>
      <View className="relative" key={`dropdown-${name}`}>
        <View className={cn(wrapperClassName)}>
          <TranslatedHeading
            className="text-sm text-text dark:text-textdark mb-1"
            tranlationKey={label}
          />
          <TouchableOpacity
            onPress={() => setShowDropdown(prev => !prev)}
            className={cn(
              'rounded-md bg-backgroundSecondary pl-2 py-3 text-text dark:bg-backgroundSecondaryDark dark:text-textdark',
              className,
            )}>
            {loading ? (
              <Wander size={14} color={colors.main} />
            ) : (
              <TranslatedText
                className="text-base"
                tranlationKey={displayMember || defaultText || 'Select Item'}
              />
            )}
          </TouchableOpacity>
          <MainText className="text-error text-xs">{error?.message}</MainText>
        </View>

        <View
          style={{elevation: 3}}
          className={cn(
            'absolute z-20 top-[70px] w-full max-h-[200px] rounded bg-backgroundSecondary dark:bg-backgroundSecondaryDark',
            showDropdown ? 'flex' : 'hidden',
          )}>
          <ScrollView className="flex-grow ">
            {items.map(item => (
              <TouchableOpacity
                key={`dropdown-item-${displayMember}-${Math.random()}`}
                className="mx-3 py-3 border-b-[.5px] border-background dark:border-backgroundDark"
                onPress={() => {
                  setDisplayMember(extractDisplayMember(item));
                  onChange(extractValue(item));
                  setShowDropdown(false);
                }}>
                <MainText>{extractDisplayMember(item)}</MainText>
              </TouchableOpacity>
            ))}
            <Spacer vertical={20} />
          </ScrollView>
        </View>
      </View>
      {showDropdown && (
        <TouchableOpacity
          style={{
            width: Dimensions.get('screen').width,
            height: Dimensions.get('screen').height,
          }}
          onPress={() => setShowDropdown(false)}
          className="absolute z-10"
        />
      )}
    </>
  );
}
```

feel free to use it in your projects if you find it useful and if there is any room for improvement please inform me.

**Comment by archi-kozin** [comment]
I recommend use for web useClickAway hook https://github.com/streamich/react-use/blob/master/src/useClickAway.ts

Create a wrapper component for DropDownPicker

```
<Wrapper>
  <DropDownPicker />
</Wrapper>
```

- Wrapper
  - index.tsx
  - index.web.tsx

`Wrapper/index.tsx`
```
import { PropsWithChildren } from "react";
import OutsidePressHandler from "react-native-outside-press";

type WrapperProps = PropsWithChildren<{
  onClick(): void;
}>;

export const Wrapper = ({ children, onClick }: WrapperProps) => {
  return <OutsidePressHandler onOutsidePress={onClick}>{children}</OutsidePressHandler>;
};
```

`Wrapper/index.web.tsx`
```
import { PropsWithChildren, useRef } from "react";
import { View } from "react-native";
import { useClickAway } from "../../../../../hooks/useClickAway/index.web";

type WrapperProps = PropsWithChildren<{
  onClick(): void;
}>;

export const Wrapper = ({ children, onClick }: WrapperProps) => {
  const ref = useRef(null);

  useClickAway(ref, onClick);

  return <View ref={ref}>{children}</View>;
};
```
