### ISSUE TITLE
Placeholder text is not replaced by selection

### ISSUE THREAD

**Issue by fabian0409** [hossein-zare/react-native-dropdown-picker#12]
Hi there!

I'm not sure if it's a bug, or if I'm not using it correctly, but if I use `defaultNull` with a `placeholder`, the placeholder text is not replaced by the selected value.

Here's my code:

<DropDownPicker
  items={[
  {label: 'Dr.', value: 'DR'},
  {label: 'Prof.', value: 'PROF'}
  ]}
  defaultNull
  placeholder="Title"
  onChangeItem={(t)=>this.setState({title:t.value})}
  dropDownMaxHeight={240}
/>

Expected result:
After selecting e.g. "Dr." from the dropdown, "Title" should be replaced with "Dr."

**Version: 2.1.4**

**Comment by hossein-zare** [comment]
Hello,

Dynamic placeholders only work with conditions so here's what you need:
`this.state = { title: null }` & `defaultNull={this.state.title === null}`

**Code snippet:**
```javascript
this.state = {
    title: null
}

<DropDownPicker
    items={[
        {label: 'Dr.', value: 'DR'},
        {label: 'Prof.', value: 'PROF'}
    ]}
    defaultNull={this.state.title === null}
    placeholder="Title"
    placeholderStyle={{fontWeight: 'bold'}}
    onChangeItem={(t)=> {
        this.setState({
            title: t.value
        });
    }}
    dropDownMaxHeight={240}
/>
```

**Comment by fabian0409** [comment]
Hey @hossein-zare!

Thanks for your help. Just to double-check...did I miss this in the documentation, or did you add the example afterwards? ;)

Sorry, for bothering you if it was there all along...

**Comment by hossein-zare** [comment]
Yes, I added the example to the dynamic placeholder section after you created this issue to clarify it.
