### ISSUE TITLE
A method to know whether the dropdown is open or closed

### ISSUE THREAD

**Issue by dcangulo** [hossein-zare/react-native-dropdown-picker#120]
**Is your feature request related to a problem? Please describe.**
I need to know whether the dropdown is open or not.

**Describe the solution you'd like**
Maybe we can add a method in the controller such as `this.controller.isOpen()` that returns a `boolean` whether the dropdown is open or closed.

**Describe alternatives you've considered**
Currently, I do this:
```js
import React, { useState } from 'react';
import DropDownPicker from 'react-native-dropdown-picker';

export default function App() {
  const [isOpen, setIsOpen] = useState(false);
  
  return (
    <DropDownPicker
      onOpen={() => setIsOpen(true)}
      onClose={() => setIsOpen(false)}
      // ... other props
    />
  );
}
```

**Additional context**
Looking at the source code, this seems doable and I can create a PR for it if you are interested in this API.

**Comment by hossein-zare** [comment]
Hello,
Yes, You can create a PR.

Thanks.

**Comment by ijlal321** [comment]
You can easily check that, here is example code, its simple

`function App() {
const [isOpen, setIsOpen] = useState(false);
  
  const componentRef = useRef(null);
  
    const selectClickHandle = (event) => {
  
      if (componentRef.current) {
        const rect = componentRef.current.getBoundingClientRect();
        const { clientX, clientY } = event;
  
        const isInComponent =
          clientX >= rect.left &&
          clientX <= rect.right &&
          clientY >= rect.top &&
          clientY <= rect.bottom;
  
        console.log(isInComponent);
        if (isInComponent == false) {
          setIsOpen(false);
        }
      }
    }
  
    const selectBlurHandle = () => {
      console.log("blur");
      setIsOpen(false);
    }
  
    const selectkeyHandle = (event) => {
      console.log("key");
      if (event.key === 'Enter' || event.keyCode === 13 || event.key === ' ' || event.keyCode === 32) {
        setIsOpen(true);
      }
    };
  
    const selectMousePress = (event) => {
      console.log("mouse");
      setIsOpen(!isOpen);
    }
    return (
      <div className="App">    
<h1 style={{ paddingTop: "200px" }}>currently closed {isOpen ? "true" : "false"}</h1>
      <div id="outer-container"
      >
        <select id="fruit" name="fruit"
          ref={componentRef}
          onMouseDown={selectMousePress}
          onClick={selectClickHandle}
          onBlur={selectBlurHandle}
          onKeyDown={selectkeyHandle}
        >
          <option value="apple" >Apple</option>
          <option value="banana">Banana</option>
          <option value="grape">Grape</option>
        </select>
        {/*         
        <div className='hidden-copy'
        >
          {isOpen && options.map((item, idx) => (
            <p key={idx} style={{ fontSize: "0.95rem" }}>copy</p>
          ))}
        </div>
        </div> */}
      </div>
  );

}
export default App;`

also if you need further clarification, you can visit my medium artcile about this for better understanding.
https://medium.com/@ijlal.tanveer294/how-to-know-if-a-select-dropdown-is-open-555a304e7dda

**Comment by ijlal321** [comment]
you can check it like this 






```

function App() {
const [isOpen, setIsOpen] = useState(false);
  
  const componentRef = useRef(null);
  
    const selectClickHandle = (event) => {
  
      if (componentRef.current) {
        const rect = componentRef.current.getBoundingClientRect();
        const { clientX, clientY } = event;
  
        const isInComponent =
          clientX >= rect.left &&
          clientX <= rect.right &&
          clientY >= rect.top &&
          clientY <= rect.bottom;
  
        console.log(isInComponent);
        if (isInComponent == false) {
          setIsOpen(false);
        }
      }
    }
  
    const selectBlurHandle = () => {
      console.log("blur");
      setIsOpen(false);
    }
  
    const selectkeyHandle = (event) => {
      console.log("key");
      if (event.key === 'Enter' || event.keyCode === 13 || event.key === ' ' || event.keyCode === 32) {
        setIsOpen(true);
      }
    };
  
    const selectMousePress = (event) => {
      console.log("mouse");
      setIsOpen(!isOpen);
    }
    return (
      <div className="App">    
<h1 style={{ paddingTop: "200px" }}>currently closed {isOpen ? "true" : "false"}</h1>
      <div id="outer-container"
      >
        <select id="fruit" name="fruit"
          ref={componentRef}
          onMouseDown={selectMousePress}
          onClick={selectClickHandle}
          onBlur={selectBlurHandle}
          onKeyDown={selectkeyHandle}
        >
          <option value="apple" >Apple</option>
          <option value="banana">Banana</option>
          <option value="grape">Grape</option>
        </select>
        {/*         
        <div className='hidden-copy'
        >
          {isOpen && options.map((item, idx) => (
            <p key={idx} style={{ fontSize: "0.95rem" }}>copy</p>
          ))}
        </div>
        </div> */}
      </div>
  );

}
export default App;


```

if you need further clarification, you can visit my medium article about it


https://medium.com/@ijlal.tanveer294/how-to-know-if-a-select-dropdown-is-open-555a304e7dda
