### ISSUE TITLE
Can't click dropdown on android

### ISSUE THREAD

**Issue by TruongNguyen95** [hossein-zare/react-native-dropdown-picker#122]
```
     <View style={[styles.dropdownContainer, {zIndex: zIndex}]}>
        <Text style={styles.label}>
          {label}
          <Text style={styles.required}>{' *'}</Text>
        </Text>
        <DropDownPicker
          items={data}
          placeholder={placeHolder}
          searchable={true}
          searchablePlaceholder="Tìm kiếm"
          searchablePlaceholderTextColor="gray"
          searchableError={() => <Text>{'Không tìm thấy'}</Text>}
          containerStyle={{height: 40, marginTop: 10}}
          style={{
            backgroundColor: Palette.white,
            borderWidth: 0,
            borderBottomWidth: 0.5,
          }}
          itemStyle={{
            justifyContent: 'flex-start',
          }}
          dropDownStyle={{backgroundColor: Palette.white}}
          onChangeItem={item => console.log(item)}
        />
     </View>
     <View style={[styles.dropdownContainer, {zIndex: zIndex}]}>
        .....
     </View>
```
i have create 2 dropdown and ios click ok but android not working =(( please help !!!!

**Comment by hossein-zare** [comment]
Hello,
You should read https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers _(Nested Views & The Third Case)_

**Comment by TruongNguyen95** [comment]
@hossein-zare thanks you but i can't scroll list item please help =((

**Comment by TruongNguyen95** [comment]
Just first item can scroll

**Comment by TruongNguyen95** [comment]
I have new problem when scroll list item drop and screen scroll too, how i can fix that @hossein-zare

**Comment by VanDinh18** [comment]
@TruongNguyen95  Do you have a solution?

**Comment by mikehardy** [comment]
That's in the documentaiton. You need scrollview mode

**Comment by VanDinh18** [comment]
@mikehardy I added listMode={'SCROLLVIEW'} but not work

**Comment by TruongNguyen95** [comment]
> @TruongNguyen95 Do you have a solution?

You can read documentation and code, my issue is about conflict style, you can check style may be it confict and not work, good luck.
