### ISSUE TITLE
Floating label 

### ISSUE THREAD

**Issue by RicardoBrito1938** [hossein-zare/react-native-dropdown-picker#124]
Hello guys, me again, last question ( i swear !!)

Is it possible to make the effect of "floating label" on placeholder ?

**Comment by hossein-zare** [comment]
Hello,
Unfortunately, no. 😕

**Comment by RicardoBrito1938** [comment]
all right, i  will keep this issue open for a few hours just while i figure some solution feasible which may integrate fine and help others

**Comment by edwardigates** [comment]
@RicardoBrito1938, hi did you find a solution for the floating label?

**Comment by RicardoBrito1938** [comment]
> @RicardoBrito1938, hi did you find a solution for the floating label?

Hello, sorry for delay, yes, i just did not the default placeholder and made my own floating using the Animatable lib, after done, just a -bottom was enough to make the floating label
