### ISSUE TITLE
Font Feather

### ISSUE THREAD

**Issue by hueyAtFetchly** [hossein-zare/react-native-dropdown-picker#126]
**Describe the bug**
Get error unrecognized font Feather. 

**To Reproduce**
Just install the app and run it.
 
**Expected behavior**
It should not error on fresh install 
 
**Additional context**
The issue it seems can be solved by adding, installing and linking a new dep. But you shouldn't have to.

Why should anyone do this because of a font? I do not need a heavy vector/icon dep for a font on a simple picker, and will likely patch your library for my own use.

```
//THIS IS A BAD SOLUTION
import Feather from "react-native-vector-icons/Feather";
Feather.loadFont();
```

**Comment by hossein-zare** [comment]
Hello,

What exactly is your solution to the issue ?

**Comment by hueyAtFetchly** [comment]
Sorry if that came off strong. Couldn't we just remove the dependency for Feather. And use system fonts instead? If not, happy to delete the issue altogether.... but that seems like the most straightforward solution to make your library less dependent.

**Comment by hossein-zare** [comment]
Yeah, alternatively `customArrowUp|Down` & `customTickIcon` can be used instead.
I'll replace `react-native-vector-icons` with SVG icons anyway to get rid of `react-native-vector-icons`

Thank you.

**Comment by hueyAtFetchly** [comment]
Thanks Hossein, 

btw, really like your work here. Thanks!
