### ISSUE TITLE
Add support to automated and unit testing with testID and AccessbilityLabel

### ISSUE THREAD

**Issue by MFrat** [hossein-zare/react-native-dropdown-picker#127]
**Is your feature request related to a problem? Please describe.**
It is impossible to automated tests work without testID and accessiblityLabel.
Also there is no support for unit testing. There is no way to simulate press event.
Really annoying.

**Describe the solution you'd like**
Pass testID and accessiblityLabel to container view receiving the click event.

**Describe alternatives you've considered**
Wrap DropDownPicker inside another view with onPress and testID and triggering open event with the controller object.

**Comment by hossein-zare** [comment]
Hello,
Your feature request will be added in the next version.

Thanks.

**Comment by yuvraj-scalex** [comment]
@hossein-zare - Can you please confirm if this is been added?
Also, can you pl share a small snippet to access the dropdown with testID prop?
It is not working at my end.

Thanks.

**Comment by hossein-zare** [comment]
@yuvraj-scalex Not yet but very soon.
You can follow https://github.com/hossein-zare/react-native-dropdown-picker/pull/454

**Each item can have a testID (available in v5.2)**
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#test-id

**Comment by sagupta1001** [comment]
How can we leverage the testID functionality added in v5.2 for a Dropdown Picker item to simulate a test environment to click on the Dropdown picker and select a different item?

We tried to add a `testID` for all our Dropdown Picker items and then tried to retrieve them based on the `testID` using `getByTestID` method in the `@testing-library/react-native` library - however the test was not able to find the Dropdown picker item.

Any code example/snippet for this would be much appreciated.
