### ISSUE TITLE
Is it possible to adjust the height using "container Style"?

### ISSUE THREAD

**Issue by itakurashingo** [hossein-zare/react-native-dropdown-picker#128]
Is it possible to adjust the height using "container Style"?
I want the textboxes to dynamically increase in height when long text is selected.
Actually, in the case of Andorid, it goes out of the text box, and in the case of iOS, it fits in the text box, but the height of the text box does not change.

**Comment by hossein-zare** [comment]
Hello,
```javascript
containerStyle={{width: 150, height: 70}}
```

You can create a snack for a better understanding.

**Comment by itakurashingo** [comment]
Thank you for your reply.
I'm still a beginner and I'm not fluent in English.
I'm sorry if I said something stupid.

I understand how to set a fixed value.
Is there a way to automatically change the height of the textbox in the exposed style properties?
It doesn't have to be "containerStyle" if it can be achieved with other properties.
If the selected text is broken into two lines, I want to close the dropdown and then add that much height to the textbox.

**Comment by itakurashingo** [comment]
The problem has been resolved.
After all it seems that I heard something stupid.

`containerStyle={{ flexDirection:'row' }}`
