### ISSUE TITLE
Cannot select from the dropdown in android after re rendering the picker

### ISSUE THREAD

**Issue by redwolfgang24** [hossein-zare/react-native-dropdown-picker#130]
I have a page where I render input, dropdown picker, radio button.
On this page, there's only one input view either input, dropdown picker, or radio button.
When I render the dropdown picker for the first time it's working fine, but when I render the input field then click the back button and re-render the dropdown picker on the same page I can't select from the dropdown picker. This only happens in android in iOS it's working fine. Kindly advise me on what to do to fix this issue. Thank you very much.

@hossein-zare can you help me with this issue?

**Comment by AAfify1** [comment]
Same issue here

**Comment by hossein-zare** [comment]
Hello,

I'll try to figure out what's causing the issue.
Please add an expo snack to reproduce the behavior & send me your code..

Access the package `src/index.js` file and **remove** `this.props.controller(this);` from the render method then test it.
There's another possibility, Comment out the `componentDidUpdate` method and let me know if solved or not.
PRs will be appreciated!

**Comment by muteshi** [comment]
I have a slightly different issue. The drop-down is not showing the drop down values onclick. I have tried the above workarounds..not working

**Comment by krishna-bhatta** [comment]
> Hello,
> 
> I'll try to figure out what's causing the issue.
> Please add an expo snack to reproduce the behavior & send me your code..
> 
> Access the package `src/index.js` file and **remove** `this.props.controller(this);` from the render method then test it.
> There's another possibility, Comment out the `componentDidUpdate` method and let me know if solved or not.
> PRs will be appreciated!

I'm having the same problem, the dropdown is freezing when re-rendering it. I have multiple dropdowns on the same screen as well. I tried @hossein-zare 's suggestion but no luck!

**Comment by tylerolechnowicz** [comment]
I also have the same issue as @muteshi. The dropdown is not showing the selected values on click. It it assigned the selected value correctly, but just now showing it in the drop down.

**Comment by pedrocardoz0** [comment]
Im facing the same issue here. Does anyone knows how to fix it? I tried the `this.props.controller(this);`approach but it still not working for me. In my case i tried to simply run on ios and it crashed.

At android it works perfectly, but ios sucks

**Comment by 01297462246** [comment]
I have the same issue. Dropdown picker don't operator when I insert it in the view and set backgroundColor for view so amazing :v

**Comment by hossein-zare** [comment]
Hello guys,
to fix the bugs if there are any, I need to see them, Please consider creating a Snack for your issues.
https://snack.expo.io

**Comment by Khaled-92** [comment]
same issue ...

**Comment by RogerioEduardo** [comment]
> Hello guys,
> to fix the bugs if there are any, I need to see them, Please consider creating a Snack for your issues.
> https://snack.expo.io

I'm having the same issue, when clicking on the dropdown, nothing happens. Maybe I'm doing something wrong, I'm a begginner on React-Native.

Link to the code
https://snack.expo.io/NsuiSWOV2

PS.: Use the android option to see on snack expo

**Comment by hossein-zare** [comment]
Hello @RogerioEduardo ,
Your issue is unrelated to the current issue.

**Here's a simple example of the Package:**

_Functional components:_
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#single-item

_Class components:_
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#class-components
