### ISSUE TITLE
Problem with the zIndex where my picker goes under below Views

### ISSUE THREAD

**Issue by petkovv** [hossein-zare/react-native-dropdown-picker#134]
Hi everyone. Sorry if this has already been asked but I couldn't find a working solution. So My code is this: 
`
<View style={styles.oddsSelectorContainer}>
                    <Text style={styles.oddsShownLabel}>ODDS SHOWN</Text>
                    <View
                      style={{
                          ...(Platform.OS !== 'android' && {
                              zIndex: 10,
                          }),
                      }}
                    >
                        <DropDownPicker
                          items={[
                              { label: 'UK', value: 'uk', icon: () => <Icon name="flag" size={18} color="#900" /> },
                              { label: 'France', value: 'france', icon: () => <Icon name="flag" size={18} color="#900" /> },
                          ]}
                          defaultValue={this.state.country}
                          style={{ backgroundColor: '#fafafa', width: 174 }}
                          itemStyle={{
                              justifyContent: 'flex-start',
                          }}
                          dropDownStyle={{ backgroundColor: '#fafafa' }}
                          onChangeItem={(item) => this.setState({
                              country: item.value,
                          })}
                        />
                    </View>
                </View>
`
And the picker still goes under the views which are under it. Tried to increase the wrapping View zIndex also added zIndex to teh Dropdown picker but nothing seems to work for me. Thanks in advance. :). If more information is needed I will add it.

**Comment by mawans** [comment]
Hi, I have the same problem and this works for me https://www.npmjs.com/package/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by shmagdy** [comment]
This works fine for iOS but not for Android yet

**Comment by petkovv** [comment]
So what I managed to achieve is to fix the problem on iOS. Since my dropdown picker is used in Flatlist's ListHeaderComponent I added to the flatlist also ListHeaderComponentStyle={{zIndex: 10}} and from then it seemed to work fine but only on iOS. Today I faced the same issue (the dropdown goes under the below Views on Android ) and the best I managed to do so far is to make the dropdown to go over everything as it should be, but unfortunately it is not clickable. The only way worked for me was to add these lines of code to the flatlist

```javascript
CellRendererComponent={({ children, index, style, ...props }) => {
                          const cellStyle = [
                              style,
                              {
                                  zIndex: -1,
                                  elevation: -1,
                              },
                          ];

                          return (
                <View style={cellStyle} index={index} {...props}>
                    {children}
                </View>
                          );
                      }}
```
 
So now the dropdown is on the top of the world but not clickable :D .... Is there any way for the dropdown to remain where it is and to appear on the top but to be clickable.  I know that the elevation makes the dropdown untouchable but just could seem to find another way. Thanks in advance guys.

**Comment by petkovv** [comment]
Actually is there any way that to happen? I am starting to think that there is no way this to work the way I need it.

**Comment by hossein-zare** [comment]
Hello,
This issue can't be fixed for Android devices.
You need to wait until React Native fixes the issue or use other packages instead.

**Comment by petkovv** [comment]
Hi everyone. Thanks all for the help. Let me share what I found out and how I managed to fix my problem. So I managed to rework my component. Initially I had a component with Flatlist which Flatlist had ListHeaderComponent and all of the content that had to be rendered above the items, so basically the whole screen was a flatlist :D. And I managed to make it work on iOS with the zIndex in ListHeaderComponentStyle of the Flatlist, but the only way to show the dropdown above the items on Android was to use elevation, which elevation was simply making the dropdown not touchable. The solution was to remove the ListHeaderComponent from the Flatlist and to put the header in separate function which I called above the Flatlist (of course you can put the content of the ListHeaderComponent in separate component, function or just in a View or Fragment above the Flatlist). That way it just worked as it should on Android with no workarounds and hacks, the only thing I needed to add was:
```javascript
 <View style={{
                ...(Platform.OS !== 'android' && {
                    zIndex: 10,
                }),
            }}
            >
```

SO the dropdown goes above the items of the Flatlist in iOS also. Only the check is needed because otherwise on Android the dropdown becomes untouchable again. I added the View that way -> 

```javascript
...
 <View style={{
                ...(Platform.OS !== 'android' && {
                    zIndex: 10,
                }),
            }}
            >
   <BookmakerSelectionDropdown /> // That is my component which contains the dropdown
</View
....
```

I will close the issue, if anyone had same problems feel free to reopen it and I will try to help :)

**Comment by RobertStuff** [comment]
@petkovv  How do you make the header to be scroll able?

**Comment by muhammadrofiq** [comment]
same with me in IOS 14, dropdown item is bellow the flatlist ,, but if comonent after the dropdown is text or someting its Work well

**Comment by crackerjackjay21** [comment]
```<>
  <View style={{zIndex: 2000}}>
    <DropDownPicker />
  </View>
  <View style={{zIndex: 1000}}>
    <DropDownPicker />
  </View>
 </>
```
worked for me 👍

**Comment by GeorgeXCV** [comment]
> 
> 
> So what I managed to achieve is to fix the problem on iOS. Since my dropdown picker is used in Flatlist's ListHeaderComponent I added to the flatlist also ListHeaderComponentStyle={{zIndex: 10}} and from then it seemed to work fine but only on iOS. Today I faced the same issue (the dropdown goes under the below Views on Android ) and the best I managed to do so far is to make the dropdown to go over everything as it should be, but unfortunately it is not clickable. The only way worked for me was to add these lines of code to the flatlist
> 
> ```js
> CellRendererComponent={({ children, index, style, ...props }) => {
>                           const cellStyle = [
>                               style,
>                               {
>                                   zIndex: -1,
>                                   elevation: -1,
>                               },
>                           ];
> 
>                           return (
>                 <View style={cellStyle} index={index} {...props}>
>                     {children}
>                 </View>
>                           );
>                       }}
> ```
> 
> So now the dropdown is on the top of the world but not clickable :D .... Is there any way for the dropdown to remain where it is and to appear on the top but to be clickable. I know that the elevation makes the dropdown untouchable but just could seem to find another way. Thanks in advance guys.

Thank you! I had issue with Dropdown options not appearing in FlatList. Adding `ListHeaderComponentStyle={{zIndex: 10}}` fixed the issue.

**Comment by MahiBuger** [comment]
> Hi everyone. Thanks all for the help. Let me share what I found out and how I managed to fix my problem. So I managed to rework my component. Initially I had a component with Flatlist which Flatlist had ListHeaderComponent and all of the content that had to be rendered above the items, so basically the whole screen was a flatlist :D. And I managed to make it work on iOS with the zIndex in ListHeaderComponentStyle of the Flatlist, but the only way to show the dropdown above the items on Android was to use elevation, which elevation was simply making the dropdown not touchable. The solution was to remove the ListHeaderComponent from the Flatlist and to put the header in separate function which I called above the Flatlist (of course you can put the content of the ListHeaderComponent in separate component, function or just in a View or Fragment above the Flatlist). That way it just worked as it should on Android with no workarounds and hacks, the only thing I needed to add was:
> 
> ```js
>  <View style={{
>                 ...(Platform.OS !== 'android' && {
>                     zIndex: 10,
>                 }),
>             }}
>             >
> ```
> 
> SO the dropdown goes above the items of the Flatlist in iOS also. Only the check is needed because otherwise on Android the dropdown becomes untouchable again. I added the View that way ->
> 
> ```js
> ...
>  <View style={{
>                 ...(Platform.OS !== 'android' && {
>                     zIndex: 10,
>                 }),
>             }}
>             >
>    <BookmakerSelectionDropdown /> // That is my component which contains the dropdown
> </View
> ....
> ```
> 
> I will close the issue, if anyone had same problems feel free to reopen it and I will try to help :)

It makes flatlist unscrollable. If i put component in ListHeaderComponent it was scrollable. Do you have any idea on this?

**Comment by t3hfx** [comment]
If you have this issue, use the solution [in this comment](https://github.com/hossein-zare/react-native-dropdown-picker/issues/134#issuecomment-713589391), but I would suggest to wrap the function in useCallback

And for absolute positioned touchables use TouchableOpacity from 'react-native-gesture-handler'

**Comment by blarz-bix** [comment]
This was my solution.
Considerations :
1.  `zIndex` property is for IOS and `elevate` for Android.  
2.  Take into consideration when a sibling of the dropdown is present with a shadow and with the `elevate` property - only for Android. In my case, the problem was that on a few screens the next element had the `elevate` property


# For IOS

```
<View style={[styles.dropdownWrap, Platform.OS !== "android" ? { zIndex:1} : null]}>
          <DropDownPicker
            items={items}
            placeholder="Select a item"
            defaultValue={1}
            containerStyle={{ height: 40 }}
            style={//any style}
            itemStyle={{ justifyContent: "flex-start" }}
            labelStyle={{
              fontSize: 14,
              textAlign: "left",
              color: "#000",
            }}
            selectedLabelStyle={{ color: "#000" }}
            onChangeItem={(item) => this.changeItem(item)}
          />
        </View>

       const styles = StyleSheet.create({
            dropdownWrap: { 
                    marginHorizontal: 18, 
                     marginVertical: 18 
           }
       });

```

# For Android

## Solution 1 - Use `elevate` property on parent's dropdown 

```
 <View style={[styles.dropDownContainer,Platform.OS !== "android" ? { zIndex:1} : null]}>
          <DropDownPicker
            items={items}
            placeholder="Select a item"
            defaultValue={1}
            containerStyle={{ height: 40 }}
            style={//any style}
            itemStyle={{ justifyContent: "flex-start" }}
            labelStyle={{
              fontSize: 14,
              textAlign: "left",
              color: "#000",
            }}
            selectedLabelStyle={{ color: "#000" }}
            onChangeItem={(item) => this.changeItem(item)}
          />
        </View>

const styles = StyleSheet.create({
  dropDownContainer: {
    marginHorizontal: 18,
    marginVertical: 18,
    elevation: 10,
  },
});

```

## Solution 2 - Use `minHeight` property on parent's dropdown with position `absolute` and your own needs (top,margin...)

```
<View style={[styles.dropDownContainer,Platform.OS !== "android" ? { zIndex:1} : null]}>
          <DropDownPicker
            items={items}
            placeholder="Select a item"
            defaultValue={1}
            containerStyle={{ height: 40 }}
            style={//any style}
            itemStyle={{ justifyContent: "flex-start" }}
            labelStyle={{
              fontSize: 14,
              textAlign: "left",
              color: "#000",
            }}
            selectedLabelStyle={{ color: "#000" }}
            onChangeItem={(item) => this.changeItem(item)}
          />
        </View>

        const style = StyleSheet.create({
           dropDownContainer: {
              minHeight: 200,
              width: "92%", //change based on your needs
              position: "absolute",
              marginHorizontal: 18,
              marginBottom: 30, //change based on your needs
              top: -1, //change based on your needs
              elevation: 10,
              zIndex: 1,
           },
       });

```

**Comment by mikehardy** [comment]
I just went on a deep dive on this one and learned more than I wanted to about zIndexing, sibling views, android layout optimizations, elevation etc. Would you believe if you have nested views you can reuse the dropdown open state to dynamically change container zindex all by itself and it seems to work ? Maybe solution, pending feedback #376

**Comment by sumit-metafic** [comment]
Just Specify zIndex property in outer view of dropdown and it will work.


           <View
                      style={{
                        paddingTop: 10,
                        flexDirection: "row",
                        width: "100%",
                        zIndex: 1,
                      }}
                    >
                      <DropDownPicker
                        containerStyle={{
                          width: "30%",
                        }}
                        open={open}
                        value={value}
                        items={items}
                        setOpen={this.setOpen}
                        setValue={this.setValue}
                        setItems={this.setItems}
                        onOpen={() => {
                          Keyboard.dismiss;
                        }}
                      />
                     </View>

**Comment by JSONRice** [comment]
What worked for me was something much simpler than all the previous convoluted answers. I could never get `zIndex` to work properly on the current `DropDownPicker` This hack worked for me:

```
const FirstDropdown = styled(StyledView)`
  z-index: 15;
`;

const SecondDropdown = styled(StyledView)`
  z-index: 10;
`;
```

Here I'm using styled-components but you can do the same thing with passed in styles, classes, etc. I just wrapped my dropdowns in these views and that did the trick. Very easy to do and it works.

**Comment by xyn22** [comment]
This issue should not be closed. The solutions provided are all hack that does not always work. It only work if the first opens down and the second opens up. Not reliable.

**Comment by next6leo** [comment]
ya this problem has been happening so long

**Comment by mczolko-lego** [comment]
same problem here

**Comment by morou34** [comment]
For anyone still facing this issue here is the best solution that works for both IOS and Android : https://github.com/hoaphantn7604/react-native-element-dropdown

    import { Dropdown } from "react-native-element-dropdown";


I tried so many package but this is by far the best one and it's so customizable and easy to use. i wish i found this early when i started working on my project.
Thank me later.

**Comment by munirktk** [comment]
> For anyone still facing this issue here is the best solution that works for both IOS and Android : https://github.com/hoaphantn7604/react-native-element-dropdown
> 
> ```
> import { Dropdown } from "react-native-element-dropdown";
> ```
> 
> I tried so many package but this is by far the best one and it's so customizable and easy to use. i wish i found this early when i started working on my project. Thank me later.

This package also have an issue of scrolling, if we use two dropdown in a row direction, second dropdown will not scroll.
