### ISSUE TITLE
Undefined is not an object (evaluating '_ref3.label')

### ISSUE THREAD

**Issue by nicolas-wl** [hossein-zare/react-native-dropdown-picker#137]
This error appears when I fill in a text field (not even selecting an option).

```
<DropDownPicker
          items={[
            {
              label: 'Cm',
              value: 'cm',
            },
            {
              label: 'Mm',
              value: 'mm',
            },
          ]}
          defaultValue={sizeUnit}
          containerStyle={styles.selectContainer}
          style={styles.select}
          itemStyle={{
            justifyContent: 'flex-start',
          }}
          dropDownStyle={styles.selectDropdown}
          onChangeItem={(item) => setRoom({sizeUnit: item.value})}
/>
```

**Comment by rheng001** [comment]
Facing the same problem

**Comment by bastienvizzini** [comment]
I'm facing the same problem. It crashed on the iOS simulator. On an android emulator, it works fine.

![image (2)](https://user-images.githubusercontent.com/57344384/96873787-aceeea80-1475-11eb-80c5-0c09ab9d3946.png)

**Comment by hossein-zare** [comment]
Hello,
in ```defaultValue={sizeUnit}``` the sizeUnit is undefined or its value doesnt exist in the items.
Make sure the variable is valid.

**Comment by hossein-zare** [comment]
Hello,
in ```defaultValue={sizeUnit}``` the sizeUnit is undefined or its value doesnt exist in the items.
Make sure the variable is valid.

**Comment by feraraujofilho** [comment]
I am facing the same issue here: 

`const [country, setCountry] = useState({ country: 'uk' });
  return (
    <View style={styles.container}>
      <DropDownPicker
        items={[
          {
            label: 'UK',
            value: 'uk',
            // icon: () => <Icon name="flag" size={18} color="#900" />,
          },
          {
            label: 'France',
            value: 'france',
            // icon: () => <Icon name="flag" size={18} color="#900" />,
          },
        ]}
        defaultValue={country}
        containerStyle={{ height: 40 }}
        style={{ backgroundColor: '#fafafa' }}
        itemStyle={{
          justifyContent: 'flex-start',
        }}
        dropDownStyle={{ backgroundColor: '#fafafa' }}
        onChangeItem={(item) =>
          setCountry({
            country: item.value,
          })
        }
      />`

**Comment by feraraujofilho** [comment]
I am having the same issue here, using exactly the example provided on https://www.npmjs.com/package/react-native-dropdown-picker

`const [country, setCountry] = useState({ country: 'uk' });

  return (
    <View style={styles.container}>

      <DropDownPicker
        items={[
          {
            label: 'UK',
            value: 'uk',
            // icon: () => <Icon name="flag" size={18} color="#900" />,
          },
          {
            label: 'France',
            value: 'france',
            // icon: () => <Icon name="flag" size={18} color="#900" />,
          },
        ]}
        defaultValue={country}
        containerStyle={{ height: 40 }}
        style={{ backgroundColor: '#fafafa' }}
        itemStyle={{
          justifyContent: 'flex-start',
        }}
        dropDownStyle={{ backgroundColor: '#fafafa' }}
        onChangeItem={(item) =>
          setCountry({
            country: item.value,
          })
        }
      />`

**Comment by hossein-zare** [comment]
@feraraujofilho 
Try `const [country, setCountry] = useState('uk');` & ...

```javascript
onChangeItem={(item) => setCountry(item.value)}
```

**Comment by GuentonBrooks** [comment]
taking a look at their code in src/index.js at line 26/27 reveals:
`if (props.defaultValue || props.defaultValue === 0) 
                choice = props.items.find(item => item.value === props.defaultValue);`

in my own scenario I got this error because my list of choices is populated from a server so the "props.defaultvalue" isn't in the list because the list isn't available at render yet. The state updates when the server responds. to solve it, create a list with the default value in it (rather than initializing state with an empty list);

**Comment by ace3** [comment]
i'm having this issue as well, since i populate the list from server also.

i fixed it by using the controller props.

then on set the dropdown value after all the API call is completed.

**Comment by Mitdd9707** [comment]
Anyone can help us?
When I am select item in dropdown 
a default value not set in the setState 

I am getting this type of error 
### **Undefined is not an object (evaluating '_ref3.label')** 

her is my code 


constructor(props) {
    super(props);
    this.state = {
      Value: null,
    };
    this.controller;
  }
render () {
.....
 const { Value } = this.state;
return (
.....
     <DropDownPicker
              items={["type1", "type2"]}
              placeholder={"Select Type"}
              defaultValue={Value}
              controller={(instance) => (this.controller = instance)}
              onChangeItem={(item) => {
                this.setState({ BidValue: item });
              }}
              searchable={false}
            />
)
}

**Comment by hossein-zare** [comment]
@Mitdd9707 
Hello,
Your items can't be `items={["type1", "type2"]}`

**Example:**
```javascript
items{[
  {label: 'Type 1', value: 'type1'},
  {label: 'Type 2', value: 'type2'},
]}
```

**Comment by Mitdd9707** [comment]
@hossein-zare Thanks its work.

**Comment by Mitdd9707** [comment]
@hossein-zare 
in the dropdown scroll is possible?

**Comment by shahjahanpak** [comment]
Whatever you put in the **defaultValue** has to be present in **itemsList**
