### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by gllo3211** [hossein-zare/react-native-dropdown-picker#139]
**Describe the bug**
I am trying to run the application on the web. I am faced with the error "Cannot read property 'style' of undefined".

**To Reproduce**
1) start expo 
2) run in web browser

**Expected behavior**
it should work.

**Screenshots**
![errorDropDownPicker](https://user-images.githubusercontent.com/73510697/97251443-7bda3580-183a-11eb-97a4-4dfc8e6b5577.png)

**Info (please complete the following information):**
 - OS: WEB 
 - Package version ["version": "3.7.0"]

**Comment by hossein-zare** [comment]
I released v3.7.1
Try to update the package.
