### ISSUE TITLE
Bug zIndex when use FlatList 

### ISSUE THREAD

**Issue by nghiahung-dev** [hossein-zare/react-native-dropdown-picker#141]
![image](https://user-images.githubusercontent.com/52577080/97271528-3f6eff80-1863-11eb-9ddc-71ead69cf853.png)

I don't fix zIndex 
I used zIndex in parent View 

![image](https://user-images.githubusercontent.com/52577080/97271635-6299af00-1863-11eb-9d73-b01288f425b4.png)
![image](https://user-images.githubusercontent.com/52577080/97271665-69c0bd00-1863-11eb-96a3-7b520bd57701.png)

Can you help me?

**Comment by hossein-zare** [comment]
Hello,

Continue your issue here: https://github.com/hossein-zare/react-native-dropdown-picker/issues/134

**Comment by carlmagumpara** [comment]
same here

**Comment by nghiahung-dev** [comment]
> Hello,
> 
> Continue your issue here: #134

i don't fix this :((

**Comment by nghiahung-dev** [comment]
Sorry, i can't fixed it.
