### ISSUE TITLE
bugs don't show value

### ISSUE THREAD

**Issue by nghiahung-dev** [hossein-zare/react-native-dropdown-picker#144]
I don't show value :( can you help me ?
![image](https://user-images.githubusercontent.com/52577080/97442094-0cf4fd80-195c-11eb-8e14-e6f40cd86fd3.png)
![image](https://user-images.githubusercontent.com/52577080/97442195-25fdae80-195c-11eb-80b8-88a4f432fe31.png)
![image](https://user-images.githubusercontent.com/52577080/97442219-2dbd5300-195c-11eb-8b04-5161379e5a93.png)

**Comment by tungst993** [comment]
Add this selectedLabelStyle={{ color: Color.BLACK }}
like:
    <DropDownPicker
        items={items}
        style={{ borderColor: isError ? Color.RED_1 : Color.GRAY }}
        // dropDownStyle={{ zIndex: 2, opacity: 1 }}
        onChangeItem={onChangeItem}
        selectedLabelStyle={{ color: Color.BLACK }}
        placeholderStyle={{ color: Color.GRAY }}
        {...rest}
      />

**Comment by nghiahung-dev** [comment]
Thank you ! tungst993
