### ISSUE TITLE
React Native Dropdown Picker => Can't resolve 'react-native-web/dist/exports/ViewPropTypes'

### ISSUE THREAD

**Issue by itsmetambui** [hossein-zare/react-native-dropdown-picker#145]
Hello everyone !

I'm using library react-native-dropdown-picker in my project, but when access page contains this library => Error will occur. After that I try to remove ViewPropType in index.js file => It's work fine. Seem ViewPropTypes in your import was unused. Could you help to resolve my stuck ? Thank you very much.

![Screenshot_9](https://user-images.githubusercontent.com/39029320/97546164-a379fb00-19fe-11eb-984e-d52da6e9a7bd.png)

**Comment by hossein-zare** [comment]
Hello, Which version are you using?

**Comment by itsmetambui** [comment]
> Hello, Which version are you using?

Hi guys, I'm using this version 
![Screenshot_16](https://user-images.githubusercontent.com/39029320/97647603-41180d80-1a85-11eb-8f25-f3815345e67d.png)

**Comment by hossein-zare** [comment]
Just update the package . I'd released **v3.7.1** days ago.
Let me know if it's been solved.

**Comment by itsmetambui** [comment]
Hello guys, after upgrade to version 3.7.1, It still occurs error. I also see that in index.js ViewPropTypes was unused.
![Screenshot_18](https://user-images.githubusercontent.com/39029320/97823491-be44bc00-1ceb-11eb-8685-df2977efdb4c.png)
![Screenshot_19](https://user-images.githubusercontent.com/39029320/97823540-e2080200-1ceb-11eb-848a-0e918444d61b.png)

**Comment by itsmetambui** [comment]
> Just update the package . I'd released **v3.7.1** days ago.
> Let me know if it's been solved.

Could you guys help me to resolved my stuck like my description & image above

**Comment by loopingz** [comment]
I fixed it in this PR: https://github.com/hossein-zare/react-native-dropdown-picker/pull/161

Just waiting for a new release, the next release should fix this issue
