### ISSUE TITLE
Bugs don't show label

### ISSUE THREAD

**Issue by nghiahung-dev** [hossein-zare/react-native-dropdown-picker#146]
![image](https://user-images.githubusercontent.com/52577080/97562317-03c76780-1a14-11eb-9d46-855af1dcc0bc.png)

**Comment by hossein-zare** [comment]
Hello, You need to set `height` in the `containerStyle` property.

**Comment by nghiahung-dev** [comment]
@hossein-zare I did it but it don't work :(( Help mee

**Comment by huynguyen0304** [comment]
@nnhunguet i think my code will help you something
**<DropDownPicker
                                items={this.state.itemsSupplier}
                                placeholder={this.props.item ? this.props.item : I18n.t("voucher.supplier")}
                                containerStyle={{ height: Constants.INPUT_HEIGHT }}
                                style={{ backgroundColor: Colors.WHITE, borderColor: Colors.BLUE }}
                                labelStyle={{ fontSize: Fonts.FONT_SIZE_MEDIUM, color: Colors.PRIMARY }}
                                itemStyle={{ justifyContent: 'flex-start', color: Colors.PRIMARY }}
                                dropDownStyle={{ backgroundColor: Colors.WHITE, borderColor: Colors.BLUE, marginTop: Constants.SPACE }}
                                arrowStyle={{ color: Colors.PRIMARY }}
                                onChangeItem={item => this.onSelectSupplier(item)}
                            />**
