### ISSUE TITLE
picker beeing rendered below other components

### ISSUE THREAD

**Issue by thlindustries** [hossein-zare/react-native-dropdown-picker#148]
**Describe the bug**
I can open the picker but when i open it the items are rendered below other components and they can't be touched, i've read some topics about it in the documentation but I couldn't find a solution on my own

**To Reproduce**
To reproduce this error open your react-native project (i have started a project with CRNA and not using EXPO) and:
- Create a screen
- Place a View inside the screen and into this View place my CustomDropdown (the code of the component is right below)
- Give some items to the dropdown
**Here are some items to make it easy:**
```
[
  { label: 'January', value: 'jan' },
  { label: 'February', value: 'fev' },
  { label: 'Mars', value: 'mar' },
  { label: 'April', value: 'apr' },
  { label: 'May', value: 'may' },
  { label: 'June', value: 'jun' },
  { label: 'July', value: 'jul' },
  { label: 'August', value: 'ago' },
  { label: 'September', value: 'set' },
  { label: 'October', value: 'out' },
  { label: 'November', value: 'nov' },
  { label: 'December', value: 'dec' },
]
```
- Place some Text outside the View which contains the dropdown component

**I have made a custom component for the dropdown, it's only a Container wrapper arround the dropdown to give some aditional styles**
CustomDropdown.tsx
```
import React, { Dispatch, SetStateAction } from 'react';

import DropDownPicker from 'react-native-dropdown-picker';

import { Container } from './styles';

interface DropwDownProps {
  selectedValue: string;
  setSelectedValue: Dispatch<SetStateAction<string>>;
  items: Array<{ label: string; value: string }>;
  contrast?: boolean;
  size?: string;
}

const DropDown: React.FC<DropwDownProps> = ({
  selectedValue,
  setSelectedValue,
  items,
  contrast = false,
  size = 'small,',
  ...rest
}) => {
  return (
    <Container contrast={contrast} size={size} {...rest}>
      <DropDownPicker
        items={items}
        defaultValue={selectedValue}
        containerStyle={{
          height: '100%',
          width: size === 'small' ? 100 : 170,
        }}
        style={{ backgroundColor: 'transparent' }}
        selectedLabelStyle={{ color: contrast ? '#002d72' : '#fff' }}
        arrowColor={contrast ? '#002d72' : '#fff'}
        onChangeItem={(item) => console.log(item.value)}
      />
    </Container>
  );
};

export default DropDown;

```

styles.ts
```
import styled, { css } from 'styled-components/native';

interface ContainerProps {
  contrast: boolean;
  size: string;
}

export const Container = styled.View<ContainerProps>`
  border-radius: 6px;

  justify-content: center;
  margin-right: 20px;

  ${(props) =>
    props.size === 'small'
      ? css`
          height: 40px;
          width: 100px;
        `
      : css`
          height: 45px;
          width: 170px;
        `}

  ${(props) =>
    props.contrast
      ? css`
          border: solid 1px #002d72;
        `
      : css`
          border: solid 1px #fff;
        `}
`;

```

**Expected behavior**
The expected behavior was that the items of the dropdown should be clickable and above all other components

**Screenshots**
*Android screenshot*
<p align="center">
  <img alt="tenda" title="#androidbug" src="https://i.imgur.com/pfp36tO.jpg" width="420px">
</p>

*iOS screenshot*
<p align="center">
  <img alt="tenda" title="#iosbug" src="https://i.imgur.com/RtCkcsL.jpg" width="420px">
</p>

**Info (please complete the following information):**
 - OS: [iOS, Android]

**Additional context**
It's my first time opening an issue, sorry if i forgot something, just let me know it and i'll improve it for you, thanks for any help <3

**Comment by TN-Figueiredo** [comment]
Up

**Comment by TN-Figueiredo** [comment]
I was browsing between other issues reported and I found a solution for this problem I'm using the component inside a Flatlist header and adding the zIndex to it made it work for me.

<Flatlist
...
ListHeaderComponentStyle={{ zIndex: 10 }}
/>

**Comment by thlindustries** [comment]
> I was browsing between other issues reported and I found a solution for this problem I'm using the component inside a Flatlist header and adding the zIndex to it made it work for me.
> 
> <Flatlist
> ...
> ListHeaderComponentStyle={{ zIndex: 10 }}
> />

I'm not sure if you got the problem,  my problem is that the items of the dropdown are untouchble because they are bellow other components,
I can't see a solution using Flatlist since my problem isn't with the list of cards but with the dropdown items!
Help me to understand what you mean, you want me to use the Flatlist component with zIndex.. okay but reading this documentation https://reactnative.dev/docs/flatlist the use of Flatlist component is something like this:

```
<FlatList
        data={DATA}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        extraData={selectedId}
/>
```
I don't see any logic in using a Flatlist to encompass the dropdown component since the dropdown is not a list

**Comment by Shedav** [comment]
any updates?

**Comment by inancatil** [comment]
I am using dropdown inside a popup modal so I ended up using `dropDownStyle={{ elevation: 999 }}` and changed my modal height dynamically according to dropdown height because it was not clickable outside of the modal box.

**Comment by evg1n** [comment]
> I am using dropdown inside a popup modal so I ended up using `dropDownStyle={{ elevation: 999 }}` and changed my modal height dynamically according to dropdown height because it was not clickable outside of the modal box.

Thank you! This solved my issue:
![carbon](https://user-images.githubusercontent.com/10906736/100199354-244ce980-2f0e-11eb-8cce-6ba5831a628a.png)

**Comment by the-habu** [comment]
This problem makes it unusable for me. Nether zIndex nor elevation works for me.

**Comment by gregoryfm** [comment]
Facing the same issue, any update?

**Comment by thlindustries** [comment]
@gregoryfm @the-habu  .. nah, I couldn't find any solutions yet and I've switched to react-native-picker :(
For me zIndex and elevation didn't worked to

**Comment by gregoryfm** [comment]
Thanks @thlindustries, yeah I've seen react-native-picker, but in my case, it won't work because I need the search feature.
I'm gonna test another package.

**Comment by KalAvroniev** [comment]
I'm seing the exact same issue as well. Also if the dropdown is at the bottom of the screen it does not pop up above.

**Comment by renielsalvador** [comment]
In my case, Popup is showing on top of other elements after adding zIndex to its container. The problem is, it is not clickable on android.

**Comment by MichDreby** [comment]
Guys, you can solve this problem via elegant manipulation with you mark up.

Actual reason of this problem is that the DropDownItems have position = 'absolute', for this reason DropDownItems are out of the screen flow and other elements "don't see" absolute positioned elements and become under.

You need to add position = 'absolute' to the rest of your mark up (elements are below DropDownPicker), but don't forget to put them upper in the mark up so that you will get something like this:

`<View>`
`.  <View style={{ position: 'absolute', top: ... }}>`
`.  .  <SomethingBelowDropDownPicker />`
`.  </View>`
`.  <DropDownPicker />`
`</View>`


https://user-images.githubusercontent.com/24464317/103084900-398e6400-45f1-11eb-8c75-22ba55db866c.mov

**Comment by Xplosive06** [comment]
For me:

```
<View>
  <View style={{ zIndex: 10 }}>
    <DropDownPicker />
  </View>
  <SomethingBelowDropDownPicker />
</View>
```

did the trick.

I'm in a modal.

**Comment by thlindustries** [comment]
> Guys, you can solve this problem via elegant manipulation with you mark up.
> 
> Actual reason of this problem is that the DropDownItems have position = 'absolute', for this reason DropDownItems are out of the screen flow and other elements "don't see" absolute positioned elements and become under.
> 
> You need to add position = 'absolute' to the rest of your mark up (elements are below DropDownPicker), but don't forget to put them upper in the mark up so that you will get something like this:
> 
> `<View>`
> `. <View style={{ position: 'absolute', top: ... }}>`
> `. . <SomethingBelowDropDownPicker />`
> `. </View>`
> `. <DropDownPicker />`
> `</View>`
> 
>  example.mov

Thanks for it bro, I'll Test then I come back to tell you if it worked for me !

**Comment by notThatPlatypus** [comment]
> position: 'absolute'

Didn't work for me either

**Comment by Jose24San** [comment]
I have a similar issue where I have a dropdown picker and then some example text underneath it as a part of a form but when ever I open up the dropdown picker there is a z-index issue where I cannot select first item in the dropdown because for some reason my example text has a higher z-index and it clicks the text instead of the dropdown selection. I went through the source code and added high z-index values of like 1000 to everything in the render method and that did not fix anything. Then I added a negative z index to my example text and my dropdown works again. 

`<Text style={zIndex: -1}>My blocking example text</Text>`


Doing this should work for anything that is static and does not need to be interacted with like a button, if you have a button or some other interactable element then change the design, probably a lot easier.

**Comment by vishalcherian** [comment]
I can echo @Jose24San. I had a similar issue with this, where the dropdown box would render behind two Button elements. I tried using z-index in the View wrapper for the picker, but that didn't seem to do anything. 

However, I set the z-index to a negative value in the View that wrapped around those buttons, and that seemed to do the trick. So perhaps trying to set a negative z-index on all the other elements that appear over the picker is a quick fix.

Roughly something like this:

```
<View>
    <DropDownPicker ... />
</View>
<View style={{ zIndex : -5 }}>
    <Button ... />
    <Button ... />
</View>
```

**Comment by marcoshevaristo** [comment]
> I can echo @Jose24San. I had a similar issue with this, where the dropdown box would render behind two Button elements. I tried using z-index in the View wrapper for the picker, but that didn't seem to do anything.
> 
> However, I set the z-index to a negative value in the View that wrapped around those buttons, and that seemed to do the trick. So perhaps trying to set a negative z-index on all the other elements that appear over the picker is a quick fix.
> 
> Roughly something like this:
> 
> ```
> <View>
>     <DropDownPicker ... />
> </View>
> <View style={{ zIndex : -5 }}>
>     <Button ... />
>     <Button ... />
> </View>
> ```

LEGEND <3

**Comment by Bluebird2000** [comment]
Got this working by setting a state together with zIndex property set to `2` to control the `isVisible` props from the package
P:S
``` Javascript
 returnCurrencyLayout = () => {
        let currencies = [{
            id: 1,
            name: 'USD',
        }, {
            id: 2,
            name: 'CAD'
        }, {
            id: 3,
            name: 'NGN'
        }]
        
            return (
                <View>
                    <>
                        <DropDownPicker 
                            onOpen={() => this.setState({ isVisible: true })}
                            onClose={() => this.setState({ isVisible: false })}
                            items={currencies.map((data) => ({ label: `${data.name}`, value: data }))}
                            defaultValue={null}
                            isVisible={this.state.isVisible} // Add this
                            placeholder="Select Currency"
                            containerStyle={{height: 50}}
                            style={{ ...styles.input, backgroundColor: '#f7f7f7' }}
                            itemStyle={{ justifyContent: 'flex-start' }}
                            labelStyle={{ color: COLORS.textPrimary, fontSize: SIZES.h3 }}
                            dropDownStyle={{ backgroundColor: '#ffffff'}}
                            onChangeItem={item => this.setState({ currency: item.value })}
                        /> 
                    </>
                </View>
            );
    }
 ```
 
 ``` Javascript
  <View 
        style={this.state.isVisble ? { zIndex: 2}  // Add this
        : {}>
        <Text style={{
            marginBottom: SIZES.margin / 2,
            fontSize: SIZES.h4, 
            color: COLORS.textPrimary,
            fontFamily: FONTS.medium
            }}>
                <Text style={styles.requireFields}>* </Text>
                Currency
        </Text>
        { this.returnCurrencyLayout() }
    </View>
  ```

**Comment by taeh98** [comment]
Is there any news or a roadmap as to when this issue might be fixed? I'm having the same problem of the list being rendered underneath other components (on iOS). The most annoying thing is that although I can use zIndex as a hack to fix it on iOS, doing so then makes the list unable to detect touches on Android - which was originally working. I can use conditional styling based on the OS of the device but that's pretty ugly. Having to do these kind of dirty workarounds shouldn't really be necessary and harms the ability for people to use this package in projects that require maintainability and interoperability with other packages. And that's a shame because apart from this issue I really like this package.

**Comment by fostimus** [comment]
Any update on if this is going to be fixed? I've tried all the hacks on this thread, to no avail for iOS.

**Comment by akinlekan28** [comment]
@fostimus  wrap the dropdown component in a view like this `<View style={{
            ...(Platform.OS !== "android" && {
              zIndex: 999999,
            }),
          }}
        ></View>`

**Comment by evg1n** [comment]
Setting `dropDownContainerStyle` prop to `{position: relative, top : 0}` solved it for me.

DISCLAIMER: This overrides the default behavior of rendering. So the dropdown box will not render over the below picker but "above" it. 

Below is my code:
```
import React, { useState, useEffect, useCallback } from "react";
. . .
import DropDownPicker from "react-native-dropdown-picker";

const Product = ({ . . . }) => {

. . . 
  return (
    <Portal>
      . . . 
      <View style={styles.container}>
        <KeyboardAwareScrollView
          style={styles.scrollArea}
          enableOnAndroid={true}
          extraScrollHeight={50}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={refreshProduct}
            />
          }
        >
          . . . 
         
          <View>
            <DropDownPicker
              containerStyle={styles.dropdownStyle}
              dropDownContainerStyle={styles.dropDownContainerStyle}
              items={[
                {
                  value: 999,
                  key: "no-tax",
                  label: "No Tax",
                },
                ...taxRates.map((taxRate) => ({
                  value: taxRate.id,
                  key: "key-" + taxRate.id,
                  label: taxRate.name + ":" + `${taxRate.rate}`,
                })),
              ]}
              multiple={false}
              onOpen={() => toggleCategoryDropdown(false)}
              open={taxRateDropdown}
              placeholder={"Select Tax Rate"}
              selectedItemLabelStyle={styles.selectedItemLabelStyle}
              selectedItemContainerStyle={styles.selectedItemContainerStyle}
              setOpen={toggleTaxRateDropdown}
              searchable={false}
              setValue={setTaxRate}
              style={styles.dropdown}
              tickIconStyle={styles.tickIconStyle}
              value={product.tax_rates[0]}
              zIndex={4000}
              zIndexReverse={1000}
            />

            <DropDownPicker
              containerStyle={styles.dropdownStyle}
              dropDownContainerStyle={styles.dropDownContainerStyle}
              items={categories.map((category, index) => ({
                value: category.id,
                key: "key-" + index,
                label: category.name,
              }))}
              multiple={true}
              multipleText={"d categories selected"}
              onOpen={() => toggleTaxRateDropdown(false)}
              open={categoryDropDown}
              placeholder={"Select Categories"}
              searchable={false}
              selectedItemLabelStyle={styles.selectedItemLabelStyle}
              selectedItemContainerStyle={styles.selectedItemContainerStyle}
              setOpen={toggleCategoryDropdown}
              setValue={setSelectedCategories}
              style={styles.dropdown}
              tickIconStyle={styles.tickIconStyle}
              value={product.categories}
              zIndex={1000}
              zIndexReverse={4000}
            />
          </View>
        </KeyboardAwareScrollView>
        <View style={[styles.multiField, { marginBottom: 20, paddingTop: 5 }]}>
          <Button
            color={STYLING.COLORS.red}
            roundness={10}
            title={"Back"}
            onPress={closeModal}
            style={styles.buttonWrapper}
            textColor={STYLING.COLORS.white}
          />
          <View style={styles.spacer} />
          {action === "add" ? (
            <Button
              roundness={5}
              title="Add"
              onPress={addProduct}
              textColor={STYLING.COLORS.white}
              roundness={10}
              style={styles.buttonWrapper}
            />
          ) : (
            <Button
              onPress={updateProduct}
              roundness={10}
              textColor={STYLING.COLORS.white}
              title="Update"
              style={styles.buttonWrapper}
            />
          )}
        </View>

        { . . . }
      </View>
    </Portal>
  );
};

const styles = StyleSheet.create({
  appBar: {
    width: "100%",
  },
  button: {
    flex: 1,
  },
  buttonWrapper: {
    flex: 1,
    height: 50,
  },
  container: {
    flex: 1,
    backgroundColor: STYLING.COLORS.white,
    width: "100%",
    padding: 5,
  },
  dropdown: {
    borderRadius: 2,
    borderColor: STYLING.COLORS.black + "AA",
  },

  dropdownStyle: {
    marginVertical: 5,
    borderColor: STYLING.COLORS.black + "99",
    borderRadius: 2,
    zIndex: 4000,
  },
  dropDownContainerStyle: {
    position: "relative",
    top: 0,
    borderColor: STYLING.COLORS.black + "99",
    borderRadius: 2,
  },
  fieldElement: {
    flex: 1,
  },
  formContainer: {
    paddingVertical: 5,
    //borderRadius: 5,
  },
  multiField: {
    //flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pickerContainer: {
    paddingVertical: 10,
  },
  selectedItemLabelStyle: {
    fontWeight: "bold",
  },
  selectedItemContainerStyle: {
    backgroundColor: STYLING.COLORS.hoverBlue + "55",
  },
  scannerWrapper: {},
  scrollArea: {
    flex: 1,
    width: "100%",
  },
  spacer: {
    width: 5,
  },
  textInput: {
    paddingVertical: 5,
  },
  tickIconStyle: {
    tintColor: STYLING.COLORS.hoverBlue,
  },
});
export default Product;

```

**Comment by gusma296** [comment]
> I can echo @Jose24San. I had a similar issue with this, where the dropdown box would render behind two Button elements. I tried using z-index in the View wrapper for the picker, but that didn't seem to do anything.
> 
> However, I set the z-index to a negative value in the View that wrapped around those buttons, and that seemed to do the trick. So perhaps trying to set a negative z-index on all the other elements that appear over the picker is a quick fix.
> 
> Roughly something like this:
> 
> ```
> <View>
>     <DropDownPicker ... />
> </View>
> <View style={{ zIndex : -5 }}>
>     <Button ... />
>     <Button ... />
> </View>
> ```

this worked for me, please @hossein-zare update this libs for fix this bug thanks

**Comment by thlindustries** [comment]
Sorry for my late answer, I stopped using @hossein-zare  lib and as a work arround I've used react-native-picker-select, it's an uglier lib but it was what I had hehe,

**Comment by thlindustries** [comment]
> her with zIndex property set to `2` to control the `isVisible` props from

This worked man, i've tested, <3 <3 <3 <3

**Comment by thlindustries** [comment]
Therefore, considering that there is a work arround and a solution, I will close this issue, feel free to reopen it if you have any news!

**Comment by mikehardy** [comment]
I just went on a deep dive on this one and learned more than I wanted to about zIndexing, sibling views, android layout optimizations, elevation etc. Would you believe if you have nested views you can reuse the dropdown open state to dynamically change container zindex all by itself and it seems to work ? Maybe solution, pending feedback #376

**Comment by OliverLSanz** [comment]
I'm still facing this issue. Maybe it should be re-opened until there is a fix in the component itself or at least the workaround is documented.

**Comment by mark-yacoub** [comment]
> Setting `dropDownContainerStyle` prop to `{position: relative, top : 0}` solved it for me.
> 
> DISCLAIMER: This overrides the default behavior of rendering. So the dropdown box will not render over the below picker but "above" it.
> 
> Below is my code:
> 
> ```
> import React, { useState, useEffect, useCallback } from "react";
> . . .
> import DropDownPicker from "react-native-dropdown-picker";
> 
> const Product = ({ . . . }) => {
> 
> . . . 
>   return (
>     <Portal>
>       . . . 
>       <View style={styles.container}>
>         <KeyboardAwareScrollView
>           style={styles.scrollArea}
>           enableOnAndroid={true}
>           extraScrollHeight={50}
>           refreshControl={
>             <RefreshControl
>               refreshing={refreshing}
>               onRefresh={refreshProduct}
>             />
>           }
>         >
>           . . . 
>          
>           <View>
>             <DropDownPicker
>               containerStyle={styles.dropdownStyle}
>               dropDownContainerStyle={styles.dropDownContainerStyle}
>               items={[
>                 {
>                   value: 999,
>                   key: "no-tax",
>                   label: "No Tax",
>                 },
>                 ...taxRates.map((taxRate) => ({
>                   value: taxRate.id,
>                   key: "key-" + taxRate.id,
>                   label: taxRate.name + ":" + `${taxRate.rate}`,
>                 })),
>               ]}
>               multiple={false}
>               onOpen={() => toggleCategoryDropdown(false)}
>               open={taxRateDropdown}
>               placeholder={"Select Tax Rate"}
>               selectedItemLabelStyle={styles.selectedItemLabelStyle}
>               selectedItemContainerStyle={styles.selectedItemContainerStyle}
>               setOpen={toggleTaxRateDropdown}
>               searchable={false}
>               setValue={setTaxRate}
>               style={styles.dropdown}
>               tickIconStyle={styles.tickIconStyle}
>               value={product.tax_rates[0]}
>               zIndex={4000}
>               zIndexReverse={1000}
>             />
> 
>             <DropDownPicker
>               containerStyle={styles.dropdownStyle}
>               dropDownContainerStyle={styles.dropDownContainerStyle}
>               items={categories.map((category, index) => ({
>                 value: category.id,
>                 key: "key-" + index,
>                 label: category.name,
>               }))}
>               multiple={true}
>               multipleText={"d categories selected"}
>               onOpen={() => toggleTaxRateDropdown(false)}
>               open={categoryDropDown}
>               placeholder={"Select Categories"}
>               searchable={false}
>               selectedItemLabelStyle={styles.selectedItemLabelStyle}
>               selectedItemContainerStyle={styles.selectedItemContainerStyle}
>               setOpen={toggleCategoryDropdown}
>               setValue={setSelectedCategories}
>               style={styles.dropdown}
>               tickIconStyle={styles.tickIconStyle}
>               value={product.categories}
>               zIndex={1000}
>               zIndexReverse={4000}
>             />
>           </View>
>         </KeyboardAwareScrollView>
>         <View style={[styles.multiField, { marginBottom: 20, paddingTop: 5 }]}>
>           <Button
>             color={STYLING.COLORS.red}
>             roundness={10}
>             title={"Back"}
>             onPress={closeModal}
>             style={styles.buttonWrapper}
>             textColor={STYLING.COLORS.white}
>           />
>           <View style={styles.spacer} />
>           {action === "add" ? (
>             <Button
>               roundness={5}
>               title="Add"
>               onPress={addProduct}
>               textColor={STYLING.COLORS.white}
>               roundness={10}
>               style={styles.buttonWrapper}
>             />
>           ) : (
>             <Button
>               onPress={updateProduct}
>               roundness={10}
>               textColor={STYLING.COLORS.white}
>               title="Update"
>               style={styles.buttonWrapper}
>             />
>           )}
>         </View>
> 
>         { . . . }
>       </View>
>     </Portal>
>   );
> };
> 
> const styles = StyleSheet.create({
>   appBar: {
>     width: "100%",
>   },
>   button: {
>     flex: 1,
>   },
>   buttonWrapper: {
>     flex: 1,
>     height: 50,
>   },
>   container: {
>     flex: 1,
>     backgroundColor: STYLING.COLORS.white,
>     width: "100%",
>     padding: 5,
>   },
>   dropdown: {
>     borderRadius: 2,
>     borderColor: STYLING.COLORS.black + "AA",
>   },
> 
>   dropdownStyle: {
>     marginVertical: 5,
>     borderColor: STYLING.COLORS.black + "99",
>     borderRadius: 2,
>     zIndex: 4000,
>   },
>   dropDownContainerStyle: {
>     position: "relative",
>     top: 0,
>     borderColor: STYLING.COLORS.black + "99",
>     borderRadius: 2,
>   },
>   fieldElement: {
>     flex: 1,
>   },
>   formContainer: {
>     paddingVertical: 5,
>     //borderRadius: 5,
>   },
>   multiField: {
>     //flex: 1,
>     flexDirection: "row",
>     justifyContent: "space-between",
>   },
>   pickerContainer: {
>     paddingVertical: 10,
>   },
>   selectedItemLabelStyle: {
>     fontWeight: "bold",
>   },
>   selectedItemContainerStyle: {
>     backgroundColor: STYLING.COLORS.hoverBlue + "55",
>   },
>   scannerWrapper: {},
>   scrollArea: {
>     flex: 1,
>     width: "100%",
>   },
>   spacer: {
>     width: 5,
>   },
>   textInput: {
>     paddingVertical: 5,
>   },
>   tickIconStyle: {
>     tintColor: STYLING.COLORS.hoverBlue,
>   },
> });
> export default Product;
> ```

setting
```
        <DropDownPicker
          ...
          dropDownContainerStyle={{position: 'relative', top: 0}}
        />
```
worked for me! thanks!!

**Comment by samih-sghier** [comment]
This should be re-opened none of these solutions worked for me :/

**Comment by josh-thompson13** [comment]
Re-open this issue, still not working.

**Comment by bimix** [comment]
> Guys, you can solve this problem via elegant manipulation with you mark up.
> 
> Actual reason of this problem is that the DropDownItems have position = 'absolute', for this reason DropDownItems are out of the screen flow and other elements "don't see" absolute positioned elements and become under.
> 
> You need to add position = 'absolute' to the rest of your mark up (elements are below DropDownPicker), but don't forget to put them upper in the mark up so that you will get something like this:
> 
> `<View>` `. <View style={{ position: 'absolute', top: ... }}>` `. . <SomethingBelowDropDownPicker />` `. </View>` `. <DropDownPicker />` `</View>`
> 
>  example.mov

You clearly have no idea what the f*** you are talking about

**Comment by mikehardy** [comment]
@bimix I have hidden that comment as abusive.

**Comment by mikkowsx** [comment]
`dropDownContainerStyle={{position: 'relative', top: 0}}` works for me as a work around. Would be nice to get real fix for this problem still 👍

**Comment by Mahdi-Farahani** [comment]
This is fixed just with this style for  dropDownContainerStyle:

**dropDownContainerStyle={{position: 'absolute', top: 50}}**

**Comment by feRpicoral** [comment]
Ridiculous that this is an issue for more than 2 years now and it's closed

**Comment by shreykul** [comment]
> I can echo @Jose24San. I had a similar issue with this, where the dropdown box would render behind two Button elements. I tried using z-index in the View wrapper for the picker, but that didn't seem to do anything.
> 
> However, I set the z-index to a negative value in the View that wrapped around those buttons, and that seemed to do the trick. So perhaps trying to set a negative z-index on all the other elements that appear over the picker is a quick fix.
> 
> Roughly something like this:
> 
> ```
> <View>
>     <DropDownPicker ... />
> </View>
> <View style={{ zIndex : -5 }}>
>     <Button ... />
>     <Button ... />
> </View>
> ```

This really seemed to work for me, it works really well atleast for me.😃😃

**Comment by nathantew14** [comment]
> I can echo @Jose24San. I had a similar issue with this, where the dropdown box would render behind two Button elements. I tried using z-index in the View wrapper for the picker, but that didn't seem to do anything.
> 
> However, I set the z-index to a negative value in the View that wrapped around those buttons, and that seemed to do the trick. So perhaps trying to set a negative z-index on all the other elements that appear over the picker is a quick fix.
> 
> Roughly something like this:
> 
> ```
> <View>
>     <DropDownPicker ... />
> </View>
> <View style={{ zIndex : -5 }}>
>     <Button ... />
>     <Button ... />
> </View>
> ```

This worked, until I had 2 dropdowns, one on top of the other. When the lower dropdown is near the bottom of the screen, it opens upwards, then is hidden by the one above...

**Comment by opmat** [comment]
> @fostimus wrap the dropdown component in a view like this `<View style={{ ...(Platform.OS !== "android" && { zIndex: 999999, }), }} ></View>`

This did the magic for me. Thank you, you are a lifesaver

**Comment by sumansaksh** [comment]
> {position: relative, top : 0}

This is the best-suited solution so far, but it still takes up the entire width of the dropdown list on the page instead of opening like a dropdown on top of other elements.
