### ISSUE TITLE
Set and Get different Picker Values

### ISSUE THREAD

**Issue by iamir4g** [hossein-zare/react-native-dropdown-picker#149]
I am working with react-native-dropdown-picker and I have created two states: Country and state.

However, there are two or more countries: USA, Germany,... There is also every country has state USA: NY,.., Germany: Berlin,...

Currently, I have two pickers. One has the Country and the other has State. Regardless of the Country selected, the 2nd picker shows all the State.

But this is what I am trying to achieve:

HOW TO: Instead of showing all the state, I want to show a specific name depending on the Country selected. For example: if the country === USA, then the state picker should display only NY,... And, if Country === Germany, then state picker should display only Berlin,...

thank

**Comment by hossein-zare** [comment]
Hello,

The following example fulfills your case:
```javascript
this.state = {
  country: null,
  states: [],
  state: null,
}

onChangeCountry(country) {
  let states;

  if (country === 'usa') {
    states = [{label: '..', value: '...'}, ...];
  } else if (country === 'germany') {
    states = [{label: '..', value: '...'}, ...];
  }

  this.setState({ country, states, state: null });
}

// Countries
<DropDownPicker
  defaultValue={this.state.country}
  items={[{...}]}
  onChangeItem={(item) => this.onChangeCountry(item.value)}
  ...
/>

// States
<DropDownPicker
  defaultValue={this.state.state}
  items={[this.state.states]}
  onChangeItem={(item) => {
    this.setState({ state: item.value });
  }}
  ...
/>
```

**Comment by iamir4g** [comment]
@hossein-zare  thank you for the answer, but some problems, first in `items` when use `[]` get an error we must use `{}`. second I use functional components I converted your cod into functional components and this in below : 
```
  
    const [countryDropSelect, setCountryDropSelect] = useState('');
    const [stateDropSelect, setSatetDropSelect] = useState('');
    const [myState, setMyState] = useState()
    const [isenable, setIsEnable] = useState(false)
//function countryChange 
  const onChangeCountry = (country) => {
        let states;

        if (country === "Iran") {
            states = [{ label: 'Tehran', value: 'Tehran', }, { label: 'Isfahan', value: 'Isfahan', }];
        } else if (country === "USA") {
            states = [{ label: 'Texas', value: 'Texas', }, { label: 'NY', value: 'NY', }];
        } else if (country === "Germany") {
            states = [{ label: 'Berlin', value: 'Berlin', },]
        }

        setCountryDropSelect(country)
        setMyState(states)
        // this.setState({ country, states, state: null });
    }
//country DropDown
 <DropDownPicker
        items={ { label: 'USA', value: 'USA' },  { label: 'Iran', value: 'Iran', }, { label: 'Germany', value: 'Germany' },]}
          onChangeItem={item => {
                onChangeCountry(item.value)
                   setIsEnable(true)
                       }}
     />
//state DropDown
    <DropDownPicker
            disabled={isenable}
            items={myState}
           onChangeItem={item => setSatetDropSelect(item.value)}
   />
```
after these changes, when comes to this page we use `DropDownPicker` get this error :  

> TypeError: undefined is not an object (evaluating 'props.items.filter')

**Comment by hossein-zare** [comment]
Yes, I made a mistake there, Fixed!
Try setting `defaultValue` and the `items` can't be empty.
```javascript
const [countryDropSelect, setCountryDropSelect] = useState(null);
const [stateDropSelect, setSatetDropSelect] = useState(null);
const [myState, setMyState] = useState([]);
```
Add `defaultValue={countryDropSelect}` to the country dropdown picker.
Add `defaultValue={stateDropSelect}` to the country dropdown picker.

**Comment by iamir4g** [comment]
thank

**Comment by iamir4g** [comment]
thank
