### ISSUE TITLE
using state variable as defaultValue has no effect

### ISSUE THREAD

**Issue by sfarkas1988** [hossein-zare/react-native-dropdown-picker#15]
My defaultValue is a state variable which is updated after I render the DropDownPicker.
I would expect that the DropDownPicker  will change his defaultValue based on my state variable even if it's updated.

```
const [ageFrom, setAgeFrom] = useState(14)

useEffect(() => {        
    if (filter === null) {
      return
    }
    setAgeFrom(filter.ageFrom)
  }, [filter]);


const ageFromDropDown = () => {
    const items = []
    for(var i = 14;i<=21;i++) {
      items.push({label: i, value: i})
    }
    items.push({value: 50, label: 50})    
    return items
  }

return 
<DropDownPicker
   items={ageFromDropDown}
   defaultValue={ageFrom}
   containerStyle={styles.dropDown}
   onChangeItem={item => setAgeFrom(item.value)}
/>
```

What is the best way to update the defaultValue after the DropDownPicker has been rendered?

Or at least I should be able to set the Value myself from outside.

**Comment by hossein-zare** [comment]
Hello
This feature will be available in the next version, I'm planning to release **v3** within the week as a major change.

**Comment by hossein-zare** [comment]
This snack can help you for now temporarily.
https://snack.expo.io/dv6H2oIWm

**Comment by hossein-zare** [comment]
Hello again @sfarkas1988,
I just released **v3.x**.
```javascript
defaultValue={this.state.item}
```
It's now possible to change the default value from outside.

**Comment by lightning331** [comment]
Ok, it looks good.
But it is not possible to change the defaultValue with an empty value.
If I set the defaultValue to an empty value("") from outside, it shows the error.

It can be tested simply from above snack link.

Any solution?
