### ISSUE TITLE
Expose Typescript Props

### ISSUE THREAD

**Issue by alexandreh92** [hossein-zare/react-native-dropdown-picker#151]
**Is your feature request related to a problem? Please describe.**
I need to extend Dropdown props. According to index.d.ts it's not possible today.

**Describe the solution you'd like**
Change index.d.ts from:

```
type DropDownPicker = {..}
{...}
const DropDownPicker: ComponentType<DropDownPicker>;
```
to:

```
export type DropDownPickerProps = {..}
{...}
const DropDownPicker: ComponentType<DropDownPickerProps>;
```

**Comment by hossein-zare** [comment]
Hello,

I merged your PR.

Thanks.
