### ISSUE TITLE
Dropdown view can't be select when overflow the container view

### ISSUE THREAD

**Issue by vandiepbui** [hossein-zare/react-native-dropdown-picker#156]
**Describe the bug**
I design my screen with header and body View. Header view contain a searchBox and a child view horizontal flex box to contain 2 dropdown. I use props zIndex for dropdown and it show above the FlatList but I can't select item from dropdown. I tried to set height for header view about 500, it contain all dropdown height and dropdown item can be select. But it's not the solution, because I need drodown is overflow to the Body view (contain FlatList items).

any solution for that?
please see some images below. 
Thanks!

**Screenshots**]
![image](https://user-images.githubusercontent.com/35633954/100318532-c5ac6c00-2ff0-11eb-9212-24c31a0553ab.png)

![image](https://user-images.githubusercontent.com/35633954/100317014-2c7c5600-2fee-11eb-8593-f58316765466.png)

**Info (please complete the following information):**
 - OS: [iOS, Android]

**Comment by ganholete** [comment]
I have the same problem. How did you solve it?
