### ISSUE TITLE
currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### ISSUE THREAD

**Issue by moedeveloper** [hossein-zare/react-native-dropdown-picker#157]
Hello,

I am really happy with this dropdown picker but unfortunately, I have spent like 3 hours trying to fix the following error :( 

 I am having the latest version of react native, and am getting this error :( any idea how to solve it ? 

I am using the searchable feature, and only there I am getting this error, it has with the text input field to do.

Regards

currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput
- node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/react-native-logs.fx.js:27:4 in error
- node_modules/react-native/Libraries/Components/TextInput/TextInputState.js:39:4 in currentlyFocusedField
* http://192.168.1.93:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:174487:90 in <unknown>
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:416:4 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
![Screenshot 2020-11-30 at 17 59 34](https://user-images.githubusercontent.com/16238332/100639747-dd0f9000-3335-11eb-8818-8b96d3b46abd.png)

**Comment by hossein-zare** [comment]
Hello,
We haven't used `currentlyFocusedField` in the package!

**Comment by hossein-zare** [comment]
Hello,
We haven't used `currentlyFocusedField` in the package!
