### ISSUE TITLE
defaultValue does not work when set to false

### ISSUE THREAD

**Issue by tsirolnik** [hossein-zare/react-native-dropdown-picker#158]
**Describe the bug**
When settings `defaultValue={false}` an item with the `value: false` isn't picked but rather the component treats it as if no default value was provided.

**To Reproduce**

Expo snack: https://snack.expo.io/5P_Zvbo70

```js
<DropDownPicker
                  zIndex={3000}
                  items={[
                    { label: 'No - Default', value: false },
                    { label: 'Yes', value: true },
                  ]}
                  defaultValue={false}
                  placeholder="I should not be shown"
                  containerStyle={{ height: 40 }}
                  style={{ backgroundColor: '#fafafa' }}
                  itemStyle={{
                    justifyContent: 'flex-start',
                  }}
                  labelStyle={{
                    fontSize: 14,
                    textAlign: 'left',
                    color: '#000'
                  }}
                  dropDownStyle={{ backgroundColor: '#fafafa' }}
                />
```

**Expected behavior**
Select the item with the default value of `false`

**Info (please complete the following information):**
 - OS: iOS/Android
 - Package version 3.7.1

**Comment by hossein-zare** [comment]
Hello,
Please use `0` as `false` and `1` as `true`.
Boolean values will be supported in the next version.

**Comment by le0piovesan** [comment]
Are boolean values supported now? 
Because I am facing a similar issue. As a workaround I'm using string values and just then convert to boolean.

**Comment by le0piovesan** [comment]
Are boolean values supported now?
Because I am facing a similar issue. As a workaround I'm using string values and just then converting it to boolean.

**Comment by AugustoAleGon** [comment]
I can confirm that in the current version is working. 🎉
