### ISSUE TITLE
dropdown does not render inside a scrollview

### ISSUE THREAD

**Issue by mikaeljan** [hossein-zare/react-native-dropdown-picker#16]
This issue still persists if the dropdown is being opened inside a scrollview, it does not expand.
Although according to arrows it does register the touched event.
Version:
    "react-native-dropdown-picker": "^2.1.8",

**Comment by hossein-zare** [comment]
Hello,
This happens likely due to wrong styling with the `containerStyle` property.
Please send me your code with the `containerStyle`

**Comment by sathwik77** [comment]
I have the same problem, my containerStyle is just `{{height: 40, width: 100}} `

**Comment by VSV6** [comment]
I've also the same issue. Dropdown doesn't work inside the scrollView. I mean it doesn't scrolls down when the dropdown is open. In fact, it won't show itself. Did you guys find a solution @sathwik77 @hossein-zare @mikaeljan?

**Comment by sathwik77** [comment]
The closest alternative i could use is [react native paper list accordion](https://callstack.github.io/react-native-paper/list-accordion.html) . As i am using react native paper already in my app, i could go for it

**Comment by VSV6** [comment]
OK thank you @sathwik77, I'll try that library.
