### ISSUE TITLE
Accessibility labels and Test Ids

### ISSUE THREAD

**Issue by petkovv** [hossein-zare/react-native-dropdown-picker#160]
Hi @hossein-zare. 
Just wanted to ask when it is planned (if it is) to add the functionality to add accessibility labels and test IDs to the dropdown picker elements. As I remember I saw a topic about that a mount or two ago, but I am not sure, I may wrong. Many thanks :)

PS: If there is a way to do that already I am sorry but just couldn't find out anything.

**Comment by hossein-zare** [comment]
Hello,

These days i'm pretty busy, That's why i can't update the package.
You can submit a PR with the feature, i'll appreciate it.
Thanks. :)

**Comment by petkovv** [comment]
Hey @hossein-zare. I managed to add the functionality for the automation IDs. I will be happy to receive feedback about this and if there is anything that seems too ridiculous I will fix it. :)

https://github.com/hossein-zare/react-native-dropdown-picker/pull/228

**Comment by pivey** [comment]
@petkovv  how does one go about using testID's and accessibilityLabels according to your new implementation? I can't find anything in the documentation about this and when looking in the repo it doesn't look like any TestID's are passed to the touchable opacity

**Comment by mrados7** [comment]
I have same problems. We don't have testID...
