### ISSUE TITLE
List separator

### ISSUE THREAD

**Issue by fuggerstadt1907** [hossein-zare/react-native-dropdown-picker#162]
Hi 🙂  is it possible to introduce a list separator? Or is it already possible and I just didn't see that feature.

Cheers ✌️

**Comment by hossein-zare** [comment]
Hi,
https://github.com/hossein-zare/react-native-dropdown-picker/pull/138 was submitted and already merged, but not released yet in a new version.

**Comment by fuggerstadt1907** [comment]
Hi @hossein-zare  thx for the fast response 🙂 
Is there already a release planned?

**Comment by hossein-zare** [comment]
@fuggerstadt1907 More likely this week i'll release a new version.

**Comment by hossein-zare** [comment]
@fuggerstadt1907 **react-native-dropdown-picker@3.7.5** is out.

**Comment by fuggerstadt1907** [comment]
> @fuggerstadt1907 **react-native-dropdown-picker@3.7.5** is out.

Wow, nice! Thx man 🙂  That was fast 😄

**Comment by xiaohengpan** [comment]
Is there any way to stretch the separator all the way across the popup? Currently there are some paddings/margins on left and right, and I'm having some trouble undoing it... 

![Screen Shot 2021-01-25 at 12 25 08 PM](https://user-images.githubusercontent.com/74780418/105741713-a35b9f80-5f08-11eb-83a2-4c880c13154f.png)
