### ISSUE TITLE
Custom Tick Icon for Single Select

### ISSUE THREAD

**Issue by Vipul-weatherbug** [hossein-zare/react-native-dropdown-picker#163]
unable to add tick icon for single select

**Comment by hossein-zare** [comment]
Hello,
Please share your code.

**Comment by Vipul-weatherbug** [comment]
@hossein-zare : `<DropDownPicker
                items={[
                    { label: 'Summary', value: 'summary' },
                    { label: 'Details', value: 'details' }
                ]}
                controller={instance => controller = instance}
                defaultValue={selectedValue}
                style={{
                    paddingHorizontal:4,
                    paddingVertical:0,
                    backgroundColor:'#486d7f',
                    borderWidth:0,
                    borderTopLeftRadius:15,
                    borderTopRightRadius:15,
                    borderBottomLeftRadius:15,
                    borderBottomRightRadius:15
                }}
                dropDownStyle={{
                    paddingHorizontal:0,
                    height:95,
                    borderWidth:0,
                    backgroundColor:'#355d71'
                }}
                containerStyle={{
                    width:100,
                    height:30,
                    marginRight:8
                }}
                itemStyle={{
                    backgroundColor:'#355d71',
                    paddingHorizontal:8,
                    height:44,
                    borderBottomWidth:0.5,
                    borderColor:'#ffffff',
                    justifyContent:'flex-start'
                }}
                labelStyle={{
                    fontFamily:'Roboto',
                    fontSize:15,
                    fontWeight:'400',
                    color:'rgba(255, 255, 255, 0.8)'
                }}
                selectedLabelStyle={{
                    fontFamily:'Roboto',
                    fontSize: 15,
                    fontWeight:'500',
                    color:'#FFFFFF'
                }}
                activeLabelStyle={{
                    fontFamily:'Roboto',
                    fontSize:15,
                    fontWeight:'400',
                    color:'#FFFFFF'
                }}
                arrowStyle={{
                    paddingHorizontal:3,
                    paddingVertical:0
                }}
                showArrow={true}
                arrowColor='white'
                arrowSize={12}
                customArrowUp={(size: number, color: string) => <ArrowUpIcon/> }
                customArrowDown={(size: number, color: string) => <ArrowDownIcon/> }
                onChangeItem={(item: any, index: number)=>clickEvent(item)}
                onOpen={() => toggleDropdown}
                onClose={() => toggleDropdown}
            />`
