### ISSUE TITLE
user style props are getting overridden

### ISSUE THREAD

**Issue by hashinclude72** [hossein-zare/react-native-dropdown-picker#165]
#### 1. border radius style is overridden by `styles.noBottomRadius`  
https://github.com/hossein-zare/react-native-dropdown-picker/blob/975ff8be5d6f11a40e72531efcb473a2dcd699d2/src/index.js#L385-L398

instead apply the `props.style` at the end of the styles array like

```js
    style={[ 
         styles.dropDown, 
         { 
             flexDirection: 'row', flex: 1 
         }, 
         this.state.isVisible && styles.noBottomRadius ,
         this.props.style, 
     ]} 
```

#### 2. here you cant place dropdown anywhere alse as `top` style gets overridden

https://github.com/hossein-zare/react-native-dropdown-picker/blob/975ff8be5d6f11a40e72531efcb473a2dcd699d2/src/index.js#L429-L438

move `props.dropDownStyle` to the end of  the array

### same issue might be in some other places

**Comment by hossein-zare** [comment]
Hello,
1. `noBottomRadius` is required when the user presses on the component, If the user adds some `borderBottom{x}Radius` to the style property the `noBottomRadius` style gets overridden. In this case the component has `borderBottom{Left & Right}Radius: 5` and the dropdown box has `borderTop{Left & Right}Radius: 0`, This doesn't look good!  

    ```javascript
    noBottomRadius: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
    },
    ```
    This is what we want:

   ![2](https://user-images.githubusercontent.com/56504893/103175415-1a0c6b00-487f-11eb-8808-6cc1e7d7f8c4.png)

2. The `top` property is calculated automatically, If the user wants to change this value, Using `marginTop` does the job.
https://github.com/hossein-zare/react-native-dropdown-picker#dropdown-overflow
    ```javascript
    dropDownStyle={{
      marginTop: ...
    }}
    ```

Thank you anyway, I appreciate your advice.

**Comment by spencewine** [comment]
@hossein-zare:  why not allow the developer to decide what looks good or not for their app? I'm in agreement with @hashinclude72
