### ISSUE TITLE
In searchable when select a value keypad disappear but value is not  selectable for first click 

### ISSUE THREAD

**Issue by Hamza-Liaqat1** [hossein-zare/react-native-dropdown-picker#167]
**Describe the bug**
I am using searchable when I search a value and select a value to set its value, on the first click keypad disappears but the value doesn't select, so again I have to select the value.

This is my code:
`<DropDownPicker
                                
                                items={cityResponse}
                                controller={instance => controller = instance}
                                onChangeList={(items, callback) => {
                                    new Promise((resolve, reject) => resolve(setItems(items)))
                                        .then(() => callback())
                                        .catch(() => { });
                                }}
                                
                                placeholder="Select City"
                                defaultValue={searchValue}
                                searchable={true}
                                searchablePlaceholder="Search for an city"
                                searchablePlaceholderTextColor="gray"
                                seachableStyle={{}}
                                searchableError={() => <Text>Not Found</Text>}
                                itemStyle={{
                                    justifyContent: 'flex-start'
                                }}
                                onChangeItem={item => setsearchValue(item.value)}
                                style={{ paddingVertical: 40 }}
                                dropDownStyle={{ backgroundColor: '#fafafa' }}
                                dropDownMaxHeight={200}
                                containerStyle={{ height: 40 }}

                                labelStyle={{
                                    fontSize: 13,
                                    textAlign: 'left',
                                    color: "#737373"
                                }}
                                selectedtLabelStyle={{
                                    color: '#39739d'
                                }}
                                placeholderStyle={{
                                    textAlign: 'left',
                                    paddingHorizontal: 10,
                                    color: "#b9b9b9"
                                }}
                                arrowStyle={{ marginRight: 10, }}
                                arrowColor="#b9b9b9"
                                arrowSize={25}

                                itemStyle={{
                                    justifyContent: 'flex-start',
                                    marginHorizontal: 5,
                                }}
                                style={{}}
                            />`

**Comment by hossein-zare** [comment]
Hello,
Please read:
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

If not solved, Send me your render() function + styles.

**Comment by roysG** [comment]
Same issue in the latest version, how to fix it?
