### ISSUE TITLE
Always show scroll

### ISSUE THREAD

**Issue by TamaraMalakhova** [hossein-zare/react-native-dropdown-picker#168]
Hello! 
Can you help me, please, how to show always scroll even if user doesn't scroll list of items?

**Comment by hossein-zare** [comment]
Hello,
I didn't understand what you said, Please clarify your issue.

**Comment by TamaraMalakhova** [comment]
> Hello,
> I didn't understand what you said, Please clarify your issue.

I wanna show scroll indicator for user even if he or she isn't scrolling the list of items at this moment.

**Comment by hossein-zare** [comment]
Hi again.
Sorry i forgot to answer your question.

This code keeps the scrollbar visible.
```javascript
<DropDownPicker
  scrollViewProps={{
    persistentScrollbar: true
  }}
  ...
/>
```
https://reactnative.dev/docs/scrollview#persistentscrollbar

**Comment by TamaraMalakhova** [comment]
> Hi again.
> Sorry i forgot to answer your question.
> 
> This code keeps the scrollbar visible.
> 
> ```js
> <DropDownPicker
>   scrollViewProps={{
>     persistentScrollbar: true
>   }}
>   ...
> />
> ```
> 
> https://reactnative.dev/docs/scrollview#persistentscrollbar

But it works only for Android. I have already found this prop, I need some prop like this but for IOS

**Comment by hossein-zare** [comment]
Yes, iOS doesn't support it.

**I found a solution but a bit complicated:**
https://stackoverflow.com/questions/33245589/react-native-scrollview-persistent-scrollbar

Try to implement it and customize the package.
You can also create a Pull Request, I'll appreciate it.

**Comment by codelover1110** [comment]
Hi @hossein-zare 
Can I ask a question about the Always show scroll again?
