### ISSUE TITLE
If items data dont have label field get error

### ISSUE THREAD

**Issue by shurshilov** [hossein-zare/react-native-dropdown-picker#169]
**Describe the bug**
 ERROR    TypeError: undefined is not an object (evaluating 'item.label.length') , when source data dont have 'label' field, but data from my server dont have this field and i do it manualy in loop)))

**Comment by hossein-zare** [comment]
Hello,
Each item must have a label property.
You can use `Array.map(item => { ... })`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by shurshilov** [comment]
> Hello,
> Each item must have a label property.
> You can use `Array.map(item => { ... })`
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

Yes, but it's very inconvenient. For example, my data does not contain such a property, why would I do this extra loop? fix it please
