### ISSUE TITLE
If two dropdowns are implemented, When first one is opened, On clicking the second one, can we close the first one?

### ISSUE THREAD

**Issue by GangadharG** [hossein-zare/react-native-dropdown-picker#17]
Sorry if this issue is already mentioned.

**Comment by hossein-zare** [comment]
Hello,
I'll release v3 today or tomorrow with this feature.

**Comment by hossein-zare** [comment]
@GangadharG, v3.x is now out.

> **Multiple pickers and the open dropdown issue**
> Clicking on another picker doesn't close the other pickers? This can be fixed with the help of state.
[https://github.com/hossein-zare/react-native-dropdown-picker#multiple-pickers-and-the-open-dropdown-issue](https://github.com/hossein-zare/react-native-dropdown-picker#multiple-pickers-and-the-open-dropdown-issue)

**Comment by GangadharG** [comment]
Yeah, Checked it. Thanks

**Comment by MagnasiePro** [comment]
If you want to handle more than 2 dropdown, you can do this:

```ts
...
const [opens, setOpens] = React.useState([false, false, false])

const handleOpen = (value: boolean, index: number) => {
    const newOpens = [...opens]
    newOpens.fill(false)
    newOpens.splice(index, 1, value)
    setOpens(newOpens)
}

return (
<>
  <DropDownPicker
    open={opens[0]}
    setOpen={value => handleOpen(value, 0)}
    ...
  />
  <DropDownPicker
    open={opens[1]}
    setOpen={value => handleOpen(value, 1)}
    ...
  />
  <DropDownPicker
    open={opens[2]}
    setOpen={value => handleOpen(value, 2)}
    ...
  />
</>
)
```

With this way, you can use as x dropdown without adding x function to close other one.
