### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by shurshilov** [hossein-zare/react-native-dropdown-picker#170]
Search function, because i want get for first fetch (mount) component <100 items and after user set 3 symbols and more fetch data from server and show select items from server)

**Comment by hossein-zare** [comment]
Your issue is unclear. Please describe it.

**Comment by shurshilov** [comment]
I want to be able to call a function, after entering characters, which will change the state and the list will be redrawn accordingly, in a similar project this is available as a parameter

**Comment by hwhh** [comment]
+1 Also would like this. Currently, I am fetching the contents used in the dropdown from a BE service which paginates the results, but if you search it only searches the retrieved items, and other matches may exist but haven't been retrieved.

**Comment by hossein-zare** [comment]
Hello,
https://github.com/hossein-zare/react-native-dropdown-picker#searchable-items

I added a new property called `onSearch`.

**Comment by shurshilov** [comment]
Hi, i checked on 4.0.9 and it work good!
Thank you! If you add spinner will be greate)
