### ISSUE TITLE
Empty label when the placeholder color is set

### ISSUE THREAD

**Issue by PatrykG0r** [hossein-zare/react-native-dropdown-picker#174]
**Describe the bug**
I try to change the placeholder color by set the placeholderStyle attribute. It works but when the default color is changed and any item is selected, the label is not displayed. It strange, because when I set any other styles for instance font weight, the problem is not occurred.

**To Reproduce**
- Add DropDownPicker with basic settings
- Set the placeholderStyle object with changed default text color (e.g color: "#ccc")

**Expected behavior**
Label of selected item should be presented when the default placeholder color is changed.

**Screenshots**
Correct behavior with default placeholder color:
<img src="https://user-images.githubusercontent.com/73282676/103551319-76d4da80-4eaa-11eb-9494-7c98806c2260.gif" data-canonical-src="https://user-images.githubusercontent.com/73282676/103551319-76d4da80-4eaa-11eb-9494-7c98806c2260.gif" width="400"/>

Incorrect behavior when the color of placeholder is set:
<img src="https://user-images.githubusercontent.com/73282676/103552153-be0f9b00-4eab-11eb-9f90-37fafff89b93.gif" data-canonical-src="https://user-images.githubusercontent.com/73282676/103552153-be0f9b00-4eab-11eb-9f90-37fafff89b93.gif" width="400"/>

**Info (please complete the following information):**
 - OS: Android 9.0
 - react-native-dropdown-picker package: 3.7.6

**Comment by tylerolechnowicz** [comment]
I am also experiencing this issue.

![image](https://user-images.githubusercontent.com/32344917/103701258-b0254d00-4f73-11eb-8cc5-cec76a4de211.png)

**Comment by hossein-zare** [comment]
Hello,
Please send me your full code of the component (class/function)

**Comment by hossein-zare** [comment]
That was a strange behavior from react native but the solution is to set `labelStyle` when setting `color` using `placeholderStyle` 
```javascript
placeholderStyle={{
  color: 'red'
}}
labelStyle={{
  color: 'black'
}}

**Comment by hossein-zare** [comment]
Install **`react-native-dropdown-picker@3.7.8`**, You don't need to set `labelStyle.color` after updating.

**Comment by PatrykG0r** [comment]
Confirmed, It works correctly after upgrading to the version `react-native-dropdown-picker@3.7.8`. Thank you very much :)
