### ISSUE TITLE
reset the label

### ISSUE THREAD

**Issue by CodeBunny786** [hossein-zare/react-native-dropdown-picker#176]
**Describe the bug**
how can i reset the label of picker ? please help
**To Reproduce**
i am selecting cities on basis of country when i change country i want reset the label but i have used controller but its not reseting

![Screenshot_1609960795](https://user-images.githubusercontent.com/56582059/103810444-11851300-507d-11eb-85dd-f8aa88ba9541.png)

**Comment by hossein-zare** [comment]
Hello,
Please show me your code.

**Comment by LeQuy-123** [comment]
add clear function and use it with the controller, the clear function set everything back to it original state
![image](https://user-images.githubusercontent.com/61301736/103956733-b8e86f80-517b-11eb-918c-71ab347a91ab.png)

**Comment by CodeBunny786** [comment]
<img width="602" alt="Screenshot 2021-01-13 at 2 13 44 AM" src="https://user-images.githubusercontent.com/56582059/104374727-201f6e80-5544-11eb-83be-7b9386a924dd.png">
here is my code

**Comment by CodeBunny786** [comment]
please check it and on cities the picker start flickering

**Comment by CodeBunny786** [comment]
i can show live with my code and running project if you want help is extremely appreciated

**Comment by CodeBunny786** [comment]
this.controller.reset(); not works

**Comment by harunbuljubasic** [comment]
Same problem here :(

**Comment by aqshalfajarputra** [comment]
any update? I can't use this.controller.reset() too :(  somehow it's not working

**Comment by hossein-zare** [comment]
Hello again, I don't get notifications from old/closed issues, Sorry for that.
I'll take a look at your code tonight, i don't have time right now.

**Comment by hossein-zare** [comment]
@CodeBunny786 The logic in your code was not provided, However i created a snack to show you how to reset the city picker and reset the selected city when country changes.

https://snack.expo.io/oSrFEnN-p

**Comment by CodeBunny786** [comment]
@hossein-zare  Wow Thanks man alot for help i lose you will not reply Thanks thats really helpfull
