### ISSUE TITLE
Change the color of the label search

### ISSUE THREAD

**Issue by TheElegantCoding** [hossein-zare/react-native-dropdown-picker#177]
i cant change the color of the label in the search option
i want the text the user puts is in white

![WhatsApp Image 2021-01-06 at 6 24 23 PM](https://user-images.githubusercontent.com/70770072/103826312-fc908b80-504c-11eb-85c0-9fb005c34b40.jpeg)

**Comment by hossein-zare** [comment]
Please send me the package code in your project.

Try:
```javascript
labelStyle={{ color: 'red' }}
```

**Comment by TheElegantCoding** [comment]
labelStyle dont modify the label of the search option, modify the normal label, i already solved the proble i see is not a label in the search option is a input so i use `seachableStyle={{borderColor: '#f7ad1a', color: '#fff'}}` and it works fine

**Comment by hossein-zare** [comment]
Yeah, I didn't read your question correctly. Sorry for that.
😀
