### ISSUE TITLE
Options disappear

### ISSUE THREAD

**Issue by omaarse** [hossein-zare/react-native-dropdown-picker#179]
Hello, I don't know if this is a bug or what but I have this issue, when I select an options sometimes the other ones disappear like this. I hope You can help me, Thank You.

![image](https://user-images.githubusercontent.com/22479573/103965688-8444cb80-511b-11eb-825a-2bced04dfea4.png)

![image](https://user-images.githubusercontent.com/22479573/103966086-6461d780-511c-11eb-944d-f992c5fb92ce.png)

                        <DropDownPicker
                            items={myList.map(r => ({ label: r.description, value: r.id }))}
                            defaultValue=''
                            placeholder='Select an option'
                            searchable={true}
                            searchablePlaceholder='Search'
                            containerStyle={{ height: 60, width: '100%', marginVertical: 12, }}
                            dropDownStyle={{
                                borderBottomLeftRadius: 10,
                                borderBottomRightRadius: 10,
                            }}

                            selectedLabelStyle={{ color: Color.BLACK }}
                            activeItemStyle={{ color: Color.BLACK }}
                            activeLabelStyle={{ color: Color.PRIMARYCOLOR }}
                            itemStyle={{ justifyContent: 'flex-start'}}
                            searchablePlaceholderTextColor='gray'
                            placeholderStyle={defaultStyles.placeholderStyle}

                            onChangeItem={(item) => {
                                setSelectedExpense(item.value)
                            }}
                        />

**Comment by omaarse** [comment]
UPDATE: After some tests I realized that when I comment this line the options don't disappear anymore.

activeLabelStyle={{ color: Color.PRIMARYCOLOR }}

**Comment by hossein-zare** [comment]
Hello,

I keep this issue open if others experience the same behaviors from the package.
