### ISSUE TITLE
Arrow don't show

### ISSUE THREAD

**Issue by F0lamie** [hossein-zare/react-native-dropdown-picker#18]
Hello,

I'll try to explain the best I can my issue as simple as it is.

I added the package to my app and implement it in one of my view, the problem is that a crossed square is at the place of the arrow at the right of the dorpdown.

I tried to add a style to it, like a `marginRight`, but except a slide on the left nothing change, the arrow is still a crossed square.

Do you have a solution ?

**Comment by hossein-zare** [comment]
Hello @F0lamie,

**This is what you're looking for:**
https://github.com/oblador/react-native-vector-icons/issues/661
