### ISSUE TITLE
onChangeItem and scroll does not work on the dropdown

### ISSUE THREAD

**Issue by fabioplaka** [hossein-zare/react-native-dropdown-picker#181]
**onChangeItem and scroll does not work on the dropdown**

I have followed the official documentation but I cannot select any item from the list. The list is appeared correct but I cannot select the item, also I cannot scroll the dropdown.

Here is the code

`

      return (
         <Row style={styles.calendarContainerStyle}>
             <DropDownPicker
                 items={items}
                 onChangeItem={(item) => setValue(item.value)}
                 containerStyle={styles.containerStyles}
                 style={styles.dropDownStyles}
                 dropDownStyle={styles.dropDownStyles}
                 defaultValue={value}
                 labelStyle={styles.labelStyles}
                 placeholderStyle={styles.labelStyles}
                 placeholder="Select Day"
                customArrowDown={() => <ArrowDown width={18} height={18} />}
                customArrowUp={() => <ArrowUp width={18} height={18} />}
                 itemStyle={styles.itemStyles}
               />
              <Container>
                 ...
             </Container>
           </Row>
       );

      const styles = StyleSheet.create({
        calendarContainerStyle: {
        marginHorizontal: 20,
        marginBottom: 22.5,
        justifyContent: 'flex-start',
        alignItems: 'center',
       flexDirection: 'row',
        zIndex: 10,
      },
      containerStyles: {
        minHeight: 50,
        minWidth: 149,
        borderColor: secondaryTextColor,
        borderRadius: 6,
      },
     dropDownStyles: {
      backgroundColor: '#fff',
     },
    labelStyles: {
      color: secondaryTextColor,
      fontSize: fontSizes.body,
      fontFamily: fontFamilies.circularBook,
      textAlign: 'left',
    },
    itemStyles: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
    },
     });};`

Here is a screenshot of the view. Please can you write what is wrong that I cannot choose any item and scroll too

![Capture](https://user-images.githubusercontent.com/32648013/104007498-5194e480-51a8-11eb-949a-eae3790baebb.PNG)

Here is the test on Snack with same behaviour on Android: https://snack.expo.io/xJbBuqNPT. Also I want to mention that on iOS we can change the item, we can scroll but zIndex is not working

**Comment by hossein-zare** [comment]
Hello,

I made your snack work:
https://snack.expo.io/4LEg0LpUD

You should read: https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

There are similar closed issues which are helpful.

**Comment by fabioplaka** [comment]
Thanks, it doesn't  worked because of borderColor
