### ISSUE TITLE
Is there a way to support onBlur event for dropdown?

### ISSUE THREAD

**Issue by chaawlaapooja** [hossein-zare/react-native-dropdown-picker#184]
I just wanted to check is there a way to implement onBlur event on this component as we have onBlur event on TextInput in react native?
I want to change the the borderBottomColor of dropdown based upon whether it is focused or not.
Please help

**Comment by hossein-zare** [comment]
Hello,
Not supported, You have to modify the package yourself.

**Comment by Isaacmeedinaa** [comment]
Will this ever be implemented?
