### ISSUE TITLE
React Native Dropdown Picker Arrow not Visible

### ISSUE THREAD

**Issue by NikolaVujke** [hossein-zare/react-native-dropdown-picker#185]
When I use react-native-dropdown-picker component in my project that I created a few days ago, the arrow icon is not displayed.
I have used this component in another project a few weeks or months ago and everything worked fine.
Also, the placeholder/selected label is set to centre: when I set showArrow to false the text is dead centred but when I set showArrow prop to true it is offset to the left as if there is an invisible arrow in the right.

Does someone have the same issue?

**Comment by ncryer** [comment]
I upgraded my expo-cli version to 4.0.17 and my arrow icon disappeared as well. 
 
Edit: This turned out to be caused by Expo SDK 40 switching up the bundling process (I think). If you've manually configured metro to bundle .svg files to be importable (through a `metro.config.js` as Expo's documentation prescribes), then you will experience this error. 

Removing `metro.config.js` and related SVG import configuration made this error go away. 

OP, can you try this and give an update?

**Comment by NikolaVujke** [comment]
Since I don't know what progress is being made towards solving this issue and since I have to get this working within 7 days, I have decided to do some digging on my own.
The error is located in index.js fie of the node module. If you get to this code:

                    {this.props.showArrow && (
                        <View style={[styles.arrow]}>
                            <View style={[this.props.arrowStyle, {opacity}]}>
                            {
                                ! this.state.isVisible ? (
                                    this.props.customArrowDown(this.props.arrowSize, this.props.arrowColor)
                                ) : (
                                    this.props.customArrowUp(this.props.arrowSize, this.props.arrowColor)
                                )
                            }
                            </View>
                        </View>
                    )}
                    
You find out that if you remove the  style={[styles.arrow]}, the arrow is shown.

**Comment by NikolaVujke** [comment]
<View style={{
                            flexDirection: 'row',
                            justifyContent: 'center',
                            alignItems: 'center',
                            // paddingVertical: 8,
                            backgroundColor: 'teal',
                            borderTopLeftRadius: 0,
                            borderBottomLeftRadius: 0,
                            }}>
                            
The paddingVertical seems to be the problem. The arrow is not centered though.

**Comment by NikolaVujke** [comment]
Okay this is the summary:
paddingVertical style prop adds padding only to the top if the view isn't tall enough. It just pushes the arrow down, hence the 'invisible' arrow.
The best fix for this would be to remove that prop if it isn't necessary for anything and/or set the dropdownpicker height automatically (if the height isn't coded, then the height will be as tall as it needs to be. Currently, in my case at least, it just shrinks to like 10px.)
Also, the entering of the arrow is not ideal, I would recommend that to be fixed.

**Comment by hossein-zare** [comment]
@NikolaVujke 
Hello.
Thank you for debugging the package.
These days I'm busy. Unfortunately I forgot GitHub or I don't have enough time.

Can you please submit a Pull Request?

**Comment by ncryer** [comment]
@NikolaVujke I fixed my issue (https://github.com/hossein-zare/react-native-dropdown-picker/issues/185#issuecomment-760028887), maybe this is relevant to you

**Comment by xiaohengpan** [comment]
> Since I don't know what progress is being made towards solving this issue and since I have to get this working within 7 days, I have decided to do some digging on my own.
> The error is located in index.js fie of the node module. If you get to this code:
> 
> ```
>                 {this.props.showArrow && (
>                     <View style={[styles.arrow]}>
>                         <View style={[this.props.arrowStyle, {opacity}]}>
>                         {
>                             ! this.state.isVisible ? (
>                                 this.props.customArrowDown(this.props.arrowSize, this.props.arrowColor)
>                             ) : (
>                                 this.props.customArrowUp(this.props.arrowSize, this.props.arrowColor)
>                             )
>                         }
>                         </View>
>                     </View>
>                 )}
> ```
> 
> You find out that if you remove the style={[styles.arrow]}, the arrow is shown.

I encountered the same issue, and your suggestion worked for me as well, thank you sir.

**Comment by pea-nut-z** [comment]
> Since I don't know what progress is being made towards solving this issue and since I have to get this working within 7 days, I have decided to do some digging on my own.
> The error is located in index.js fie of the node module. If you get to this code:
> 
> ```
>                 {this.props.showArrow && (
>                     <View style={[styles.arrow]}>
>                         <View style={[this.props.arrowStyle, {opacity}]}>
>                         {
>                             ! this.state.isVisible ? (
>                                 this.props.customArrowDown(this.props.arrowSize, this.props.arrowColor)
>                             ) : (
>                                 this.props.customArrowUp(this.props.arrowSize, this.props.arrowColor)
>                             )
>                         }
>                         </View>
>                     </View>
>                 )}
> ```
> 
> You find out that if you remove the style={[styles.arrow]}, the arrow is shown.

This didn't work for me. Any other ideas? Thanks.
