### ISSUE TITLE
Is there a way to add animations for the drop down list?

### ISSUE THREAD

**Issue by smallzZz8** [hossein-zare/react-native-dropdown-picker#186]
Basically, the title explains it, but I was wondering if I could add an effect like slide down or fade in whenever the dropdown is clicked?

Thanks!

**Comment by hossein-zare** [comment]
Hello,
No, You have to do it manually.

**Comment by thegdznet** [comment]
Hello and many thanks for Your work. Do You have an idea on how we can achieve that?

**Comment by hossein-zare** [comment]
Hello @thegdznet 
https://github.com/hossein-zare/react-native-dropdown-picker/blob/dev-5.x/src/components/Picker.js must be edited.

Use `useEffect` to catch changes (`true` or `false`) in the variable `open`.
`DropDownComponentWrapper` is the animation target.

`PRs` are welcomed.

**Comment by thegdznet** [comment]
Thanks++ Will try and make a PR when done, for sure.

**Comment by jslok** [comment]
@thegdznet were you able to make this work?
