### ISSUE TITLE
Dropdown Tree Select

### ISSUE THREAD

**Issue by trackwell-mike** [hossein-zare/react-native-dropdown-picker#188]
It would be great to extend this component by adding support for a tree view, where you can nest child options under a parent option.

<img width="200" src="https://user-images.githubusercontent.com/61172689/104533656-cc169780-55e0-11eb-8727-26853f005056.png">

There is a popular React component called [react-dropdown-tree-select](https://github.com/dowjones/react-dropdown-tree-select) which illustrates the functionality nicely.

![image](https://user-images.githubusercontent.com/781818/37562235-0ae9e9ec-2a3a-11e8-8266-b0e6b716d0d1.gif)

**Comment by hossein-zare** [comment]
Hello,

Your feature request maybe a plan for major changes in the feature.
Thanks for the request.
