### ISSUE TITLE
In iOS, Dropdown is overlapping with the below content

### ISSUE THREAD

**Issue by GangadharG** [hossein-zare/react-native-dropdown-picker#19]
I have used the code like mentioned in the example in my screen

```
<DropDownPicker
                items={[
                  {label: 'UK', value: 'uk'},
                  {label: 'France', value: 'france'},
                ]}
                defaultValue={'uk'}
                containerStyle={{height: 40}}
                style={{backgroundColor: '#fafafa'}}
                dropDownStyle={{backgroundColor: '#fafafa'}}
                onChangeItem={(item) => {
                  console.log(item);
                }}
              />
```
---
The dropdown in overlapping under the below content as shown like image.

<img width="342" alt="Screenshot 2020-06-04 at 1 23 39 AM" src="https://user-images.githubusercontent.com/9436020/83682795-0b6c1700-a602-11ea-9243-4e49650a0ec1.png">
----
Could you please help me on this?

**Comment by hossein-zare** [comment]
Hello,
Try adding `zIndex={5000}` to the component, if it doesn't work you can put it into a `View` with `zIndex: 5000`.

**Method 1:**
```javascript
<DropDownPicker
   items={[
      {label: 'UK', value: 'uk'},
      {label: 'France', value: 'france'},
   ]}
   defaultValue={'uk'}
   containerStyle={{height: 40}}
   style={{backgroundColor: '#fafafa'}}
   dropDownStyle={{backgroundColor: '#fafafa'}}
   onChangeItem={(item) => {
      console.log(item);
   }}

   zIndex={5000}
/>
```

**Method 2:**
```javascript
<View style={{zIndex: 5000}}>
   <DropDownPicker
      items={[
         {label: 'UK', value: 'uk'},
         {label: 'France', value: 'france'},
      ]}
      defaultValue={'uk'}
      containerStyle={{height: 40}}
      style={{backgroundColor: '#fafafa'}}
      dropDownStyle={{backgroundColor: '#fafafa'}}
      onChangeItem={(item) => {
         console.log(item);
      }}
   />
</View>
```

Try both of them and let me know if it's working please.

**Comment by GangadharG** [comment]
Tried both. Both failed

**Comment by hossein-zare** [comment]
What about this one?
Make sure the items are touchable.
```javascript
containerStyle={{height: 40, zIndex: 5009}}
```

Add your code snippet with styles, I'll try to reproduce the behavior.

**Comment by gillgill12** [comment]
i got same issue
Not best solution
My solution is put `DropDownPicker` into a `View` style `position:'absolute', top:0` 
then put `View` **after** FlatList or Any Component with **marginTop: 40** (DropDownPicker height).
```js
<FlatList
    data={data}
    renderItem={renderItem}
    keyExtractor={(item, index) => 'key' + index}
    onEndReachedThreshold={0.4}
    onEndReached={this.handleLoadMore.bind(this)}
    style={{marginTop: 40}}
/>
<View style={{ position:'absolute', top:0 }}>
    <DropDownPicker
        items={[
            { label: 'UK', value: 'uk' },
            { label: 'France', value: 'france' },
        ]}
        placeholder="Day range"
        containerStyle={{height: 40}}
        style={{ backgroundColor: '#ffffff' }}
        dropDownStyle={{ backgroundColor: 'white' }}
        onChangeItem={item => {
        }}
    />
</View>
```

**Comment by hossein-zare** [comment]
Hello @gillgill12 ,
Did you try the second method?

```javascript
<View style={{zIndex: 5000}}>
   <DropDownPicker
      items={[
         {label: 'UK', value: 'uk'},
         {label: 'France', value: 'france'},
      ]}
      placeholder="Day range"
      containerStyle={{height: 40}}
      style={{ backgroundColor: '#ffffff' }}
      dropDownStyle={{ backgroundColor: 'white' }}
      onChangeItem={item => {
      }}
   />
</View>
<FlatList
    data={data}
    renderItem={renderItem}
    keyExtractor={(item, index) => 'key' + index}
    onEndReachedThreshold={0.4}
    onEndReached={this.handleLoadMore.bind(this)}
    style={{marginTop: 40}}
/>
```

Expo snack doesn't reproduce the behavior unfortunately i can't fix the bug.

**Comment by hossein-zare** [comment]
@GangadharG @gillgill12 
Please run this code and tell me whats been printed:

```javascript
import { Platform } from 'react-native';

componentDidMount() {
    console.log(Platform.OS); // android | ios
}
```
I think there's something going wrong with the `Platform` recognizing operating system.

**Comment by razzium** [comment]
Hey !
Same problem here...

**Comment by hossein-zare** [comment]
Hello @razzium 
@gillgill12 @GangadharG

Please check this out: (Beta Version)
```sh
npm install react-native-dropdown-picker@3.0.1-beta.0
```

**Comment by razzium** [comment]
Same problem with the "3.0.1-beta.0" version...

**Comment by hossein-zare** [comment]
@razzium 
Create an Expo Snack and share the link.
[https://snack.expo.io/](https://snack.expo.io/)

**Comment by razzium** [comment]
Ok i do this when i have time (in 4-5 hours).

**Comment by hossein-zare** [comment]
Ready Environment with `react-native-dropdown-picker` installed & `FlatList` as described in the issues.
https://snack.expo.io/21EPiOOPb

**Comment by razzium** [comment]
Here is the snack to reproduce :
https://snack.expo.io/@rrazzi-digital-paca/dropdown-overlapping-ios

**Comment by razzium** [comment]
(you can notice that it's work fine on android)

**Comment by hossein-zare** [comment]
@razzium 
I made a minor change in the snack, Check it out.
https://snack.expo.io/5I9RQVTzn

**Comment by razzium** [comment]
OK it works :) 

But is this the optimal solution ?

(do you gonna push the new release ?)

**Comment by hossein-zare** [comment]
Yes, It has nothing to do with the packge.
That's because of `position: 'absolute'` which is a requirement for the dropdown box.

> **Nested Views**
> [https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers](https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers)

**v3.0.3** has been published.

**Comment by erald14** [comment]
So what is the solution?

**Comment by erald14** [comment]
Useless library!
