### ISSUE TITLE
dropdown is cut on bottom

### ISSUE THREAD

**Issue by mariolukec** [hossein-zare/react-native-dropdown-picker#190]
**Describe the bug**
Dropdown is cut on bottom if there is no component high enough underneath... (maybe only on android)
If I add empty view with e.g. 60px height, then the dropdown is fully visible

**To Reproduce**

**Expected behavior**
Full dropdown is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/67585018/104924992-7fdfa480-599e-11eb-8253-9043411df496.png)

![image](https://user-images.githubusercontent.com/67585018/104925487-32176c00-599f-11eb-9bda-440a3e39e2c5.png)

**Info (please complete the following information):**
 - OS: Android
 - Package version 3.7.8

**Additional context**

**Comment by kanurenan** [comment]
same issue here!

**Comment by hossein-zare** [comment]
Hello @mariolukec 
The position of the dropdown box is `absolute`, This is the reason.
Adding custom `View` with a fixed height solves the issue as you've done.

**Comment by mariolukec** [comment]
> Hello @mariolukec
> The position of the dropdown box is `absolute`, This is the reason.
> Adding custom `View` with a fixed height solves the issue as you've done.

Okay, I was hoping there was a better way... anyway thanks for the quick reply and explanation!
