### ISSUE TITLE
defaultValue throws label of undefined error

### ISSUE THREAD

**Issue by Gangeshwar3** [hossein-zare/react-native-dropdown-picker#193]
**Describe the bug**
I have a dropdown where i can select an option after selecting that option i am storing it in the redux, when i want to show the selected item from the store as a defaultValue in another screen it is throwing error.
**To Reproduce**

Create an expo snack:
https://snack.expo.io/sg-Ca0dRS

**Expected behavior**
what ever we selected in previous screen, it shows as selected value as default value in another screen

**Screenshots**
![Screenshot from 2021-01-22 12-38-35](https://user-images.githubusercontent.com/39775325/105459957-14087f00-5cb1-11eb-8d0c-258ee0eaf2ed.png)
![Screenshot from 2021-01-22 12-19-23](https://user-images.githubusercontent.com/39775325/105460032-339fa780-5cb1-11eb-9396-16a5747f0638.png)
![Screenshot from 2021-01-22 12-37-21](https://user-images.githubusercontent.com/39775325/105460102-4ade9500-5cb1-11eb-92f3-fdb6105453d3.png)
![Screenshot from 2021-01-22 12-36-16](https://user-images.githubusercontent.com/39775325/105460149-5cc03800-5cb1-11eb-919b-d13492a98fd4.png)

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
Hello,
The `defaultValue` works with `.value` not `.label`
```javascript
const [defaultCountry,setDefaultCountry] = React.useState(props.list.label) // must be props.list.value
```

Make sure the `companyData` matches the following structure:
```javascript
[{ label: 'Label', value: 'value', ... }, ... ]
```

And the `defaultValue` must be `null` before all of the items have been loaded.

**Example:**
```javascript
const [defaultCountry, setDefaultCountry] = React.useState(null);
const [companyData, setCompanyList] = React.useState([]);

const getCompanies = () => {
    API.get().then((data) => {
        // I've not worked with functional components, implement this `this.setState({ list: data }, () => this.setState({ defaultValue: ... }));` in the functional component way.
        setCompanyList(data);
        setDefaultCountry(props.list.value);
    }).catch(err => {});
}

getCompanies();

...
```
