### ISSUE TITLE
change selected item color in the placeholder position only

### ISSUE THREAD

**Issue by fadylamaa** [hossein-zare/react-native-dropdown-picker#194]
Any idea if I can accomplish the following: After I select an item from the drop down list and it appears as selected on top, I want to change its color to green, but keep the color of all the items in the dropdown list as the default (black) - except maybe the one that is selected. 

If I set activeLabelStyle to green, then that sets the selected item in the menu green, but it doesn't color the item displaying in place of the placeholder. 

If I change the labelStyle to green, then all the items in the menu change to green, as well as the item displaying on top

Is it possible to accomplish what I want? Thanks!

[code.txt](https://github.com/hossein-zare/react-native-dropdown-picker/files/5866014/code.txt)

![image](https://user-images.githubusercontent.com/73326191/105695880-444b5a00-5f0b-11eb-96d9-5dffed070e85.png)

**Comment by hossein-zare** [comment]
Hello,
I'm planning to release a new version with a new property to enable applying the same style to the item on the list.

**Comment by hossein-zare** [comment]
Hello,

```javascript
selectedLabelStyle={{ color: 'green' }}
activeLabelStyle={{ color: 'green' }}
```

**Comment by fadylamaa** [comment]
> Hello,
> 
> ```js
> selectedLabelStyle={{ color: 'green' }}
> activeLabelStyle={{ color: 'green' }}
> ```

That worked!! Thank you.

**Comment by morelgarisi** [comment]
does not work for me
added activeLabelStyle={{ color: 'green' }}
and the selected in the place holder still has the same color as itemstyle

**Comment by morelgarisi** [comment]
oh , apparently you cant add color to item style. only if default color it works
