### ISSUE TITLE
hidden value not working

### ISSUE THREAD

**Issue by morelgarisi** [hossein-zare/react-native-dropdown-picker#195]
hi, 
i'm trying to change hidden value in onChangeItem
so the item chosen will not shown on item list after been chosen
and somehow its still show the chosen item on the list despite the fact his value of hidden has changed to false

**Comment by hossein-zare** [comment]
Hello,
I fixed the bug, Please try it.

Create a snack if you have any issues.
https://snack.expo.io

**New version:**
```
npm i react-native-dropdown-picker@3.8.0
```

**Comment by morelgarisi** [comment]
> react-native-dropdown-picker@3.8.0

hi,
 tnx for the quick response!
it's working great!
