### ISSUE TITLE
on ios simulator does not work

### ISSUE THREAD

**Issue by antinucleus** [hossein-zare/react-native-dropdown-picker#196]
when i use this package on android, it works well but on ios simulator (sim. : iphone11 , os version :14.3) does not work. I pressed the picker and it dropeed down but i can't select any item or i can't write any word on search bar

**Comment by hossein-zare** [comment]
Hello,

**Read the zIndex Conflicts section:**
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by antinucleus** [comment]
Thank you Hossein-Zare. 
This was before my code was fixed; 
<View>
 <DropDownPicker ... />
</Vİew> 
After correction I use <DropDownPicker ... /> without View Tags. Then my problem is fixed
