### ISSUE TITLE
onSearch props not working

### ISSUE THREAD

**Issue by varunSuccessive** [hossein-zare/react-native-dropdown-picker#197]
Hello,
https://github.com/hossein-zare/react-native-dropdown-picker#searchable-items

I added a new property called `onSearch`.

_Originally posted by @hossein-zare in https://github.com/hossein-zare/react-native-dropdown-picker/issues/170#issuecomment-768596707_

**Comment by hossein-zare** [comment]
Hello,
https://snack.expo.io/_F9fqfMo5
```
npm i react-native-dropdown-picker@3.8.0
```
