### ISSUE TITLE
Label of dropdown picker on controler.reset() does not reset

### ISSUE THREAD

**Issue by hkar19** [hossein-zare/react-native-dropdown-picker#198]
**Describe the bug**
I have two dropdowns:

```javascript
const [lang, setLanguage] = useState(null);
const [lib, setLib] = useState('');
const [langOptions, setLangOptions] = useState(str.dataLanguage.en);

let languageControler;

const libraryChange = val => {
    setLib(val)
    let options = pickLangOptions(val)
    setLangOptions(options)
  }
const pickLangOptions = (lib)=>{
    switch (lib) {
      case 'hanoi': return str.dataLanguage.viVN;
      case 'bukarest': return str.dataLanguage.enGB;
      case 'newdelhi': return str.dataLanguage.enGB;
      default: return str.dataLanguage.en;
    }
  }



<View>
  <DropDownPicker
    items={libraryItems}
    onChangeItem={item=>{
                libraryChange(item.value);
                languageControler.reset()
              }}
  />
</View>
<View>
  <DropDownPicker
    controler={ins=>languageControler=ins}
    items={languageItems}
    onChangeItem={item => {
                setLanguage(item.value)
                // console.log({item});
              }}
  />
</View>
  
```

when i picked language, and then i change library, i expected the value picked to be null (which is as expected) but the label persist to be the picked language

**To Reproduce**
as written above

**Expected behavior**
The label should be reset as well

**Info (please complete the following information):**
 - OS: [ Android]
 - Package version [e.g. 30]

**Comment by hossein-zare** [comment]
Hello,
The component needs the `defaultValue` property. Probly that's why it's not working as expected.

**Comment by hkar19** [comment]
please accept my PR on #200 as i did change this it works as expected

**Comment by hkar19** [comment]
oh wait maybe it has problem on multiple dropdown. it works on non multiple dropdown

**Comment by hkar19** [comment]
> Hello,
> The component needs the `defaultValue` property. Probly that's why it's not working as expected.

and yes i have tried assign `defaultValue` to `null`. It didnt work as i call `controler.reset()`

**Comment by hossein-zare** [comment]
I reviewed your PR but is not mergeable because the reset method of the controller works well.
Demo (Single): **https://snack.expo.io/VVMJKW27d**
Demo (Multiple): **https://snack.expo.io/81Idcp-y_**


Please try this code:
```javascript
const [lib, setLib] = useState(null); // Must be null
const languageControlerRef = useRef(null);

...

<DropDownPicker
    defaultValue={lib} // Never do this:   defaultValue: {null}
    items={libraryItems}
    onChangeItem={item=>{
        libraryChange(item.value);
        languageControlerRef.current.reset();
    }}
/>

<DropDownPicker
    defaultValue={lang}
    controler={instance => languageControlerRef.current = instance}
    items={languageItems}
    onChangeItem={item => {
        setLanguage(item.value);
    }}
 />
```

**Comment by hkar19** [comment]
oh right thank you. I have modified version of your multiple dropdown [here](https://snack.expo.io/@hkar19/multiple-dropdownpicker-reset-method-) that works.
