### ISSUE TITLE
How to handle nested scroll here?

### ISSUE THREAD

**Issue by amit-android-dev** [hossein-zare/react-native-dropdown-picker#2]
First of all, it is really nice DropDownPicker.

I have one  ScrollView and inside that scroll view I have multiple dropdowns. however the dropdown scrolling is no more working in that case.

```
<ScrollView>
                <View style={styles.childBaseContainer}>
                  <DropDownPicker/>
                  <DropDownPicker/>
                  <DropDownPicker/>
                </View>
</ScrollView>
```

**Comment by hossein-zare** [comment]
Hello,

Please add the full code (JSX, Styles) + The version of the package you're using.

**Comment by amit-android-dev** [comment]
Just try to add multiple DropDownPicker on a single View then you will found many issues, scroll not work, after apply z-index it does not scroll or click to it Overlap on each other.

**Comment by amit-android-dev** [comment]
Can you please suggest to me how can we dismiss your dropdown by outside touch or any other dropdown touch?

**Comment by hossein-zare** [comment]
Read more:
[https://reactnative.dev/docs/scrollview#nestedscrollenabled](url)

> **nestedScrollEnabled**
> Enables nested scrolling for Android API level 21+. Nested scrolling is supported by default on iOS.

**The bug has been fixed.**
**Uninstall & Install the package.**

**Comment by hossein-zare** [comment]
> Can you please suggest to me how can we dismiss your dropdown by outside touch or any other dropdown touch?
> 
> How we can get callback of that to dismiss or show

There's no way to dismiss/hide the dropdown box yet, I'll work on that later with more features.
