### ISSUE TITLE
Little dot on Android

### ISSUE THREAD

**Issue by razzium** [hossein-zare/react-native-dropdown-picker#20]
Hey Hossein !

On android, a little dot appears when dropdown is closed (and disappears when dropdown is opened), an idea how to fix it ?

![Screenshot 2020-06-04 at 18 46 58](https://user-images.githubusercontent.com/16808336/83787252-cc86a180-a693-11ea-834c-4814ebd005dc.png)

<img width="900" alt="Screenshot 2020-06-04 at 18 47 25" src="https://user-images.githubusercontent.com/16808336/83787284-d7d9cd00-a693-11ea-96d8-2e7967b6014e.png">

**Comment by hossein-zare** [comment]
Hello,

Add `borderWidth: 0` to `hidden: { ... }` in the package index.js file.
```javascript
hidden: {
    position: 'relative',
    display: 'none',

    borderWidth: 0
},
```

Or you can wait for the next release.

**Comment by razzium** [comment]
OK it works, thanks a lot !
When do you gonna push the new release with this fix ?

**Comment by hossein-zare** [comment]
I'm trying to fix the zIndex bug then i'll publish it.

**Comment by razzium** [comment]
OK great !

I'm disconnecting there, but I'm back in about an hour to create an Expo Snack of the iOS zIndex problem.

In addition, I will try to debug it by myself and give contact you back if succeed.
