### ISSUE TITLE
Best way to assign general style e.g same `fontSize` in all part?

### ISSUE THREAD

**Issue by hkar19** [hossein-zare/react-native-dropdown-picker#201]
Hello,

I get confused as there are so many style handler in this dropdown. I want to apply homogeneous `fontSize` for all part, which style handler should i use?

is `containerStyle` suffice?

**Comment by hossein-zare** [comment]
Hello,

No, The `containerStyle` can't be used to style the component (You'll face unexpected behaviors)
Apply your style to `labelStyle` `selectedLabelStyle` `placeholderStyle` `activeLabelStyle` `searchableStyle` props.
In the next version i'll add `globalTextStyle`

**Comment by hossein-zare** [comment]
You can now use `globalTextStyle`

```javascript
globalTextStyle={{
    fontFamily: "MyFontName",
    fontSize: 15
}}
```
