### ISSUE TITLE
selectedLabelStyle not working

### ISSUE THREAD

**Issue by fahry-mohammed** [hossein-zare/react-native-dropdown-picker#203]
**Describe the bug**
When using labelStyle color, selectedLabelStyle's color not working.

Demostration:
[https://snack.expo.io/@fahry/dropdown](https://snack.expo.io/@fahry/dropdown)

**Expected behavior**
The selected value style should even label style is different.

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [3.8.0]

**Additional context**
It seems label style overrides the styles of selectedLabelStyle.

**Comment by hossein-zare** [comment]
Hello,
Fixed the bug.

```
npm i react-native-dropdown-picker@3.8.2
```

**Comment by fahry-mohammed** [comment]
Thank you it works fine now. But `placeholderStyle` text color not works now. When using `labelStyle` color, it overrides placeholder text color. Same as previous.

**Comment by hossein-zare** [comment]
Now?!
```
npm i react-native-dropdown-picker@3.8.3
```

**Comment by fahry-mohammed** [comment]
Great!!! It works now. Thank you for your prompt response. :)
