### ISSUE TITLE
[BLOCKER] undefined is not an object (evaluating 'this.style.globalTextStyle')

### ISSUE THREAD

**Issue by ionutmiftode** [hossein-zare/react-native-dropdown-picker#206]
**Describe the bug**
When you search an item that is not in the list app breaks

**To Reproduce**
open the dropdown, start typing to search an item that doesn't exist

**Expected behavior**
Should work as expected

**Comment by ionutmiftode** [comment]
will be fixed by https://github.com/hossein-zare/react-native-dropdown-picker/pull/207

**Comment by hossein-zare** [comment]
Hello,
I merged the PR and released v4.0.2.
`react-native-dropdown-picker@4.0.2`
