### ISSUE TITLE
Clear/Reset Selected Item when multiselect is true

### ISSUE THREAD

**Issue by markmccoid** [hossein-zare/react-native-dropdown-picker#208]
I'm not sure this is a bug, probably more of me not understanding how to make this work.

I have a list of items with the "multiple" prop set to true.

It is a large list, so I would like to be able to do two things:

1. Clear the list with either a button press or a "Clear" item in the list.
2. Resort the list so selected items are first.

For #1, I thought that using the **controller** and calling reset() or resetItems() might be the way.  Reviewing your code and the results of the reset (calling **onChangeItem** with an empty array does reset my component state, but the dropdown list state still shows the selected items as selected.

I also looked at **onChangeList**, but am unable to figure out what it is supposed to do.  

Thanks

**Comment by hossein-zare** [comment]
Hello,

Here's an example of the `resetItems` method:
https://snack.expo.io/XIvcXUvOZ

The list and the selected items are gone after pressing the **Reset** button.

**Comment by markmccoid** [comment]
Thanks so much!!

My issue was that I was not sending the defaultValue prop as the selected item state.

Your drop down picker is awesome and I appreciate all the time you've spent building and maintaining it.

It's getting a lot of use in the current app I'm building.

Thanks again!
