### ISSUE TITLE
How to add dynamic icon on dropdown list

### ISSUE THREAD

**Issue by gdhelp03** [hossein-zare/react-native-dropdown-picker#210]
How can I add an icon from the database to the dropdown list?

please provide the example

**Comment by hossein-zare** [comment]
Hello,

What do you mean by adding icons from database?
As you see https://github.com/hossein-zare/react-native-dropdown-picker#available-item-properties, There's a property for items called `icon` which is optional and has to be a function that returns a JSX.

Example:
```javascript
import Icon from 'react-native-vector-icons/Feather';

items={[
  {label: 'UK', value: 'uk', icon: () => <Icon name="flag" size={18} color="#900" />},
  {label: 'France', value: 'france', icon: () => <Icon name="flag" size={18} color="#900" />},
]}
```

**Comment by gdhelp03** [comment]
I want to set the Icon value dynamically. for example, I load data from database and accordingly I want to change Icon

**Comment by hossein-zare** [comment]
You have to store the items in the state and change them anytime you want.

```javascript
constructor() {
  super();

  this.state = {
    items: [
      {label: 'UK', value: 'uk', icon: () => <Icon name="flag" size={18} color="#900" />},
      {label: 'France', value: 'france', icon: () => <Icon name="flag" size={18} color="#900" />},
    ]
  }
}

<DropDownPicker
  items={this.state.items}
  ...
/>
```
