### ISSUE TITLE
Avoid Feather Dependency

### ISSUE THREAD

**Issue by hsandhu** [hossein-zare/react-native-dropdown-picker#211]
Hey @hossein-zare, is it possible to integrate this library without the use of Feather icons? I would like to use my own svg for the drop down. 

Thanks!

**Comment by hossein-zare** [comment]
Hello,
You can change all the icons.

See [Props](https://github.com/hossein-zare/react-native-dropdown-picker#props):
`customArrowUp` `customArrowDown` `customTickIcon`

**Comment by anwargul0x** [comment]
> Hey @hossein-zare, is it possible to integrate this library without the use of Feather icons? I would like to use my own svg for the drop down.
> 
> Thanks!

you can always just copy the main code and modify it according to your requirement after all it is just component
