### ISSUE TITLE
Specifying custom label/value field names

### ISSUE THREAD

**Issue by antoinebrtd** [hossein-zare/react-native-dropdown-picker#212]
@hossein-zare would you consider allowing to specify what fields in the item should serve as label/value to provide more flexibility ?

**Comment by hossein-zare** [comment]
Yes, I'll add this feature.

**Comment by fadinasr** [comment]
@hossein-zare I would love to collaborate on implementing it.

**Comment by hossein-zare** [comment]
Hey @fadinasr 
You're free to fork it and submit a PR. 😀

**Comment by hossein-zare** [comment]
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/item-schema
