### ISSUE TITLE
Return object when multiple enabled

### ISSUE THREAD

**Issue by antoinebrtd** [hossein-zare/react-native-dropdown-picker#213]
@hossein-zare when `multiple` is true, `onChangeItem` syncs only the list of `value` fields. Could it be possible to return the  selected items as a list of objects ? 

It would avoid extra logic to build the list of selected items as objects if one wants to display them outside of the dropdown.

**Comment by hossein-zare** [comment]
No, It's good to be added as a new callback.

**Comment by antoinebrtd** [comment]
@hossein-zare hello, did you have time to work on the new callback?

**Comment by hossein-zare** [comment]
Hello, No unfortunately.
You can submit a PR.
