### ISSUE TITLE
Reset and selectItems not working via controller when multiple enabled

### ISSUE THREAD

**Issue by antoinebrtd** [hossein-zare/react-native-dropdown-picker#214]
@hossein-zare it seems like `controller.reset()` and `controller.selectItems(listOfItems)` are not working correctly for me when multiple selection is enabled

**Comment by antoinebrtd** [comment]
See attached when deleting items outside of the dropdown in the bottom sheet. Label changes with the correct count though

https://user-images.githubusercontent.com/34452191/108159158-696b5c80-70b4-11eb-9a3e-f8afa7cb3fed.mp4

**Comment by hossein-zare** [comment]
Hello,
Please create an Expo Snack with the same behavior, I'll try to debug it.
