### ISSUE TITLE
Dynamically updating label for the currently selected value

### ISSUE THREAD

**Issue by neocative** [hossein-zare/react-native-dropdown-picker#219]
**Describe the bug**
Updating the items with new values of label (Keeping values the same) in state does not update the rendered label of the currently selected value.

**To Reproduce**
1. Open the expo snack
2. By default it will have "labelOld-a" selected, and the dropdown will contain "labelOld-a" and "labelOld-b"
3. Click on "Change to New Items"
4. Now, the dropdown contains "labelNew-a" and "labelNew-b". But the currently selected label is not updated to "labelNew-a", and it still shows "labelOld-a"

**Create an expo snack:**
[https://snack.expo.io/CaeUOsPOe](https://snack.expo.io/CaeUOsPOe)

**Expected behavior**
For a given selected value, if the items update the corresponding label, then the new new label should be displayed

**Screenshots**
Before updating the items, "labelOld-a" is the selected value.

<img src="https://user-images.githubusercontent.com/68805324/110915280-49524600-82cc-11eb-9955-3730e3fc7931.png" height="800">

After updating the items, "labelOld-a" is still the selected value.

<img src="https://user-images.githubusercontent.com/68805324/110915279-48b9af80-82cc-11eb-82f1-c46bafaa56bd.png" height="800">

**Info (please complete the following information):**
 - OS: iOS
 - Package version: 4.0.2

**Additional context**
In my project, I present a user with a list of items to select from the dropdown. The items in the dropdown render as "<ItemName>(<count>)". On the screen, the data is loaded with pagination, so a user can click on "Load More" to fetch more data. As more data is fetched, the count of items increase. So, for instance it might go from "Wishlist(10)" to "Wishlist(20)" as more items are loaded.

**Comment by hossein-zare** [comment]
Hello,
You should use The `resetItems` method of the controller.
https://github.com/hossein-zare/react-native-dropdown-picker#controller

**Example (Edited your snack)**
https://snack.expo.io/tCKC0nuLb

**Comment by neocative** [comment]
That worked. Thanks for the prompt response @hossein-zare !
