### ISSUE TITLE
Internal search is overriding custom search

### ISSUE THREAD

**Issue by raphacmartin** [hossein-zare/react-native-dropdown-picker#224]
**Describe the bug**
If I set se `onSearch` prop and make a custom search to fetch the items, this lib still applying its filter in getItems() method. In the most of scenarios it is not a problem, but if you do a little bit more complex search, it can cause trouble:

I'm doing a unnacent search, but when I fetch the data and set in `items` prop the dropDown apply the filter and remove my data, example:

**To Reproduce**

```javascript
const [ items, setItems ] = useState([
   {label: 'Café', value: 'cafe'},
   {label: 'Fianceé', value: 'fiancee'},
   {label: 'Jalapeño', value: 'jalapeno'},
])
let controller;

<DropDownPicker
    items={items}
    controller={instance => controller = instance}
    onChangeList={(items, callback) => {
        new Promise((resolve, reject) => resolve(setItems(items)))
            .then(() => callback())
            .catch(() => {});
    }}
    defaultValue={value}
    onChangeItem={item => setValue(item.value)}
    onSearch={(text) => {
        const _items = [ ...items ]
       // Method to unaccent got here: https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript
        const unaccentedText = text.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
        controller.resetItems(_items.filter(item => item.value.includes(unaccentedText)))
    }}
/>

```

**Expected behavior**
Expected that when I set `onSearch` prop the component don't apply its internal filter

**Info (please complete the following information):**
 - OS: N/A
 - Package version 4.0.2

**Additional context**
My suggestion is refactor `getItems()` method to this:

```javascript
    getItems(parent = false) {
        const items = this.props.items.filter(item => {
            return ((parent !== false && item.parent === parent) || parent === false && ! item.hasOwnProperty('parent')) && (typeof item.hidden === 'undefined' || item.hidden === false);
        });

        if (parent)
            return items;

        const hasCustomSearch = !!this.props.onSearch
        if (!hasCustomSearch && this.state.searchableText) {
            const text = this.state.searchableText.toLowerCase();

            return items.filter((item) => {
                return item.label && (item.label.toLowerCase()).indexOf(text) > -1;
            });
        }

        return items;
    }
```

**Comment by hossein-zare** [comment]
Hello @raphacmartin ,

Sorry for the late reply.
This bug will be fixed in the next version.

**Comment by astriskit** [comment]
@hossein-zare - Hi there. 

Why was this closed? seem to have the same/similar issue - defined onSearch but the stateful "items" are not reflecting in the picker after the search. Thanks. Btw, moving to 5.x is not an option atm;

**Comment by mikehardy** [comment]
>  Btw, moving to 5.x is not an option atm;

With apologies, that's not really an acceptable stance in open source. If maintainer (with limited time) says it will be fixed in next release, and there is a next release, you update to that release to get the fix.

Maintainer time is vastly more valuable then library user time in other words. You should not have the expectation a maintainer will backport some or any fix to an old release, there's just not enough maintainer time available in open source ecosystems to support those kind of expectations

**Comment by hossein-zare** [comment]
Hi @astriskit
The bug has already been fixed by @Kaltoft

No support for deprecated versions.
Fork the corresponding branch (4.x or 3.x) and fix the bug.
