### ISSUE TITLE
Show data from API 

### ISSUE THREAD

**Issue by G-Tox** [hossein-zare/react-native-dropdown-picker#225]
Hello, I new in React-Native I have a problem with this component. I want to show data from a Rest API (Django) into Dropdown picker. This is my code, but not works. 

![image](https://user-images.githubusercontent.com/28832423/111556996-cf9dda80-8759-11eb-837e-c7aac0468004.png)

and this is the data from Django.

![image](https://user-images.githubusercontent.com/28832423/111557050-ec3a1280-8759-11eb-9f4c-6b405f9fd8a3.png)

It's the error

![image](https://user-images.githubusercontent.com/28832423/111557291-61a5e300-875a-11eb-82b2-62def86cb2e0.png)

**Comment by hossein-zare** [comment]
Hello,
Copy-Paste your code here.

```javascript
const [detailha, setDetailha] = useState([]);

// API Data
controller.resetItems(data);
```
