### ISSUE TITLE
Android OS with 'flexDirection: 'row' disables the ability to select items.

### ISSUE THREAD

**Issue by MaxwellHangry** [hossein-zare/react-native-dropdown-picker#227]
Everything works accordingly except for when I place the component inside of a view that has {flexDirection: 'row'}. On only Android OS that makes the items unclickable. If I remove it, everything works again. Every demo I have seen of this library seems to have the dropdown-picker on its own individual line, so maybe this is an intentional limitation instead of a bug? 

Also, I assume I could fix this by making everything {position: 'absolute'} but i'd rather not dive down that hole since I've seen it will take lots of height changes utilizing the controller and such.

**Comment by hossein-zare** [comment]
Hello,

I've described some of the known issues here: https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

You can also reproduce the behavior using the expo snack, I'll help you if possible.
