### ISSUE TITLE
Dropdown height

### ISSUE THREAD

**Issue by dancomanlive** [hossein-zare/react-native-dropdown-picker#23]
**Describe the bug**
Can not adjust dropdown height.

**To Reproduce**
dropDownStyle={{height: 500}}

**Expected behavior**
When adding height to dropDownStyle the dropdown style's height adjusts accordingly.

**Comment by hossein-zare** [comment]
Hello @dancomanlive ,

If you take a look at the table of props, You'll see `dropDownMaxHeight`.
In order to make it work, Try setting `height` or `minHeight` with the `dropDownStyle` prop. You also need to reset the `dropDownMaxHeight` to observe the principles.

```javascript
dropDownStyle={{
    height: 500 // Or     minHeight: 500
}}
dropDownMaxHeight={500} // As     maxHeight: 500

**Comment by YopiRagil** [comment]
I think we have same problem, but it solved because I must add View as parent and I set height View and In dropdown to and its work.
<View style={{height: 300}}>
             <DropDownPicker 
                  dropDownMaxHeight={300}
             />
</View>

**Comment by moedeveloper** [comment]
@hossein-zare  is it possible to make it auto resizable ?? depends on the number of items?

**Comment by raphacmartin** [comment]
> @hossein-zare is it possible to make it auto resizable ?? depends on the number of items?

I could do this creating a custom component. I created it to stylize a single DropDown and use it in all app with the same looking feel, so I created a dynamic height of the dropdown based on the `items` prop length.

```javascript
import React from 'react'
import DropDownPicker from 'react-native-dropdown-picker'
import { array, func, any } from 'prop-types'

export function MyCustomDropDown (props) {
  const { items, onChangeItem, defaultValue, ...rest } = props
  const ITEM_HEIGHT = 42 // I got this value using the inspector in the debug menu
  return (
    <DropDownPicker
      items={items}
      containerStyle={{
        // my custom styles
      }}
      labelStyle={{
        // my custom styles
      }}
      style={{
        // my custom styles
      }}
      dropDownStyle={{
        height: items.length * ITEM_HEIGHT
      }}
      dropDownMaxHeight={items.length * ITEM_HEIGHT}
      onChangeItem={onChangeItem}
      defaultValue={defaultValue}
      {...rest}
    />
  )
}
MyCustomDropDown.propTypes = {
  items: array,
  onChangeItem: func,
  defaultValue: any
}
```

So, when I need to use the component I do:

```javascript
<MyCustomDropDown
  items={[
    { label: 'Brazil', value: 'br', color: '#CCC' },
    { label: 'United States', value: 'us', color: '#CCC' },
    { label: 'Canada', value: 'ca', color: '#CCC' },
  ]}
  onChangeItem={(item) => setCountry(item.value)}
  defaultValue='br'
/>
```

**Comment by roshnet** [comment]
> I think we have same problem, but it solved because I must add View as parent and I set height View and In dropdown to and its work.
> <View style={{height: 300}}>

@YopiRagil thanks mate! Been working to find a fix & this works. You just saved my day!
