### ISSUE TITLE
Value in items array of objects accepts only string data.

### ISSUE THREAD

**Issue by ameyalinge-21** [hossein-zare/react-native-dropdown-picker#230]
I had my head scratching when I was getting "**cannot read property object label of undefined**" error while setting default value.

The items which I was passing to the component had values as **integer**.

**After a lot of research, I tried converting the values to string just to check and the error resolved.**

Please allow any type of value in the data or specify in the documentation the same if not possible.

I hope this is helpful to anyone who is stuck on this issue.

Otherwise, a great package with good examples and documentation.

**Comment by hossein-zare** [comment]
Hello @ameyalinge-21 ,

`value` or `label`?
Currently, You can use Integer values.

**Comment by ameyalinge-21** [comment]
Hi @hossein-zare 
I had my values as integer and I got this error.

**Comment by hossein-zare** [comment]
Make sure you're using the latest version.

**Example**:
https://snack.expo.io/oKSkdgxeS

**Comment by ameyalinge-21** [comment]
I have the latest version. Anyways, closing this issue since the workaround which I mentioned in the question works for me.
Thanks for responding @hossein-zare 👍 .
