### ISSUE TITLE
Style `border` disappears when it is open. 

### ISSUE THREAD

**Issue by dauhn** [hossein-zare/react-native-dropdown-picker#231]
**Is your feature request related to a problem? Please describe.**
I have given borders, but when the items are open, bottom borders disappear. 

Here's my code.
<img width="644" alt="스크린샷 2021-04-01 오전 8 19 30" src="https://user-images.githubusercontent.com/78328337/113223118-6ffc0f00-92c3-11eb-8fd9-68ef4f573486.png">

This is the issue I am having.
<img width="386" alt="스크린샷 2021-04-01 오전 8 23 29" src="https://user-images.githubusercontent.com/78328337/113223253-b3567d80-92c3-11eb-9c65-cbf2feacc009.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hossein-zare** [comment]
Hello,

You should provide your code.

**Comment by dauhn** [comment]
> Hello,
> 
> You should provide your code.

I have edited my question : )

**Comment by hossein-zare** [comment]
@dauhn This issue was reported days ago and its been fixed but not released. Please wait for the next stable version.

**Comment by hossein-zare** [comment]
```batch
npm i react-native-dropdown-picker@4.0.4
```
```javascript
noTopRadius={false}
noBottomRadius={false}
```

**Comment by Dimasprog** [comment]
Try `disableBorderRadius={false}`
