### ISSUE TITLE
Not able to select items on Android

### ISSUE THREAD

**Issue by devs96** [hossein-zare/react-native-dropdown-picker#232]
Hi,
i have implemented dropdown, Works perfect with iOS. Able to select items from dropdown on iOS. When on Android, i click on dropdown, dropdown appears, but not able to select any value from it. (Its like touching any item is not changing anything or calling any method).

My Code - 
<DropDownPicker
          items={[
            {label: 'Daily', value: 'Daily'},
            {label: 'Weekly', value: 'Weekly'},
            {label: 'Monthly', value: 'Monthly'},
            {label: 'Yearly', value: 'Yearly'},
          ]}
          itemStyle={{justifyContent: 'flex-start'}}
          defaultValue={period}
          containerStyle={styles.containerStyle}
          onChangeItem={(item) => setPeriod(item.value)}
          dropDownMaxHeight={200}
        />

It works on iOS but not android. It's embedded in a view like this - 
<View
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'flex-end',
        }}>
<Text> HI </Text>
// dropdown code above ...     </View>

**Comment by azesmway** [comment]
Before:
`import {TouchableOpacity} from "react-native";`
After:
`import {TouchableOpacity} from 'react-native-gesture-handler'`

**Comment by hossein-zare** [comment]
Hello,

First you need to read https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

If still not working, Create a snack.

**Comment by alexzummo** [comment]
I had the same exact issue on android and hossein-zare's solution was correct. I needed to change containerStyle to dropDownStyle in the DropDownPicker options
