### ISSUE TITLE
Direction of dropdown picker should also take into consideration the keyboard

### ISSUE THREAD

**Issue by zaiisao** [hossein-zare/react-native-dropdown-picker#234]
**Describe the bug**
The dropdown picker has logic included in which the direction of its expansion is altered if it extends past the bottom of the screen. This logic fails to take into account the keyboard. If the list extends past the keyboard (but not past the actual screen), then the direction remains the same.

**To Reproduce**
You can create a simple component where the dropdown "hugs" the bottom of the screen, or the keyboard if it is enabled. Then to enable the keyboard, you'll need something like a TextInput.

**Expected behavior**
The logic that changes the direction of the dropdown should be switched depending on the keyboard's visibility as well.

**Screenshots**
![20210407_003504](https://user-images.githubusercontent.com/1892030/113738300-c04af500-9739-11eb-83c4-6944bfe6071a.jpeg)
![20210407_003525](https://user-images.githubusercontent.com/1892030/113738309-c17c2200-9739-11eb-806d-bb34aa8f5776.jpeg)

**Info (please complete the following information):**
 - OS: Android (probably happens on iOS too)
 - Package version 3.8.0

**Comment by zaiisao** [comment]
I noticed when working on #236 that I can simply add the keyboard logic on the parent component of the dropdown and then put the keyboard height into the `bottomOffset` property. This seems to work as a temporary fix, but the logic in the pull request seems to be a necessary built-in bit of logic.

**Comment by akshat-infusion** [comment]
how to automatic close dropdown while clicking outside dropdown? @hossein-zare

**Comment by zaiisao** [comment]
> how to automatic close dropdown while clicking outside dropdown? @hossein-zare

Sorry? What does that have to do with this issue?

**Comment by akshat-infusion** [comment]
there are many textinputs and in between i have added dropdown so first i click on text input and than i click dropdown that open and than again i click on textinput that time dropdown is also open but it should be close. @zaiisao

**Comment by zaiisao** [comment]
@akshat-infusion Please make a **new issue** and talk about your issue.

**Comment by akshat-infusion** [comment]
okay sure

**Comment by hossein-zare** [comment]
Hello,

I'm going to put the PR on trial and merge soon.
