### ISSUE TITLE
Two clicks needed to open the DropdownPicker, when the keyboard is opened from a Textinput

### ISSUE THREAD

**Issue by jakobwak** [hossein-zare/react-native-dropdown-picker#235]
**Describe the bug**
When the user has opened the Keyboard from entering text in an input field, and then wants to select a value from the DropdownPicker, it needs two clicks: The first will close the Keyboard, the second will open the DropdownPicker.

**To Reproduce**
1. Enter text in an <TextInput> field (Keyboard will be opened)
2. Click on the DropdownPicker
3. The Keyboard is closed
4. Click on the DropdownPicker again
5. The DropdownPicker is opened

**Expected behavior**
When the Keyboard is opened from another input field, and the user clicks on the DropdownPicker, the dropdown Picker should open with one click.

**Info (please complete the following information):**
 - OS: Simulator [iPhone 11 (iOS 14.4)
 - Package version: 3.8.3

**Additional context**
I have tried different Approaches with manually Keyboard.dismiss(), this.controller.open() etc., but didn't find a solution yet.

**Comment by akshat-infusion** [comment]
Same issue i have seen it.

**Comment by jakobwak** [comment]
[Comment Edited after testing] The issue was, that I had the same component on two different places. On one it was embedded in a ScrollView without keyboardShouldPersistTaps set like e.g. `<ScrollView keyboardShouldPersistTaps='always'>`, which is required to make it work. This I learned from this comment: https://github.com/facebook/react-native/issues/10138#issuecomment-304656278 . With having the keyboardShouldPersistTaps on all (!) parent ScrollViews and on the DropdownPicker it works like a charm! Thanks!

**Comment by juliscotto** [comment]
I know this is closed but I had the same problem and added `<DropDownPicker flatListProps={{ keyboardShouldPersistTaps: "always" }}>` and now it works! Hope it can help someone.

**Comment by SomnathKadam** [comment]
> o

Thanks working fine in version 5.3.0
