### ISSUE TITLE
while clicking on outsides of dropdown is not closing

### ISSUE THREAD

**Issue by akshat-infusion** [hossein-zare/react-native-dropdown-picker#237]
**Describe the bug**
Bug is while clicking on outsides of dropdown is not closing.

**To Reproduce**
1. in the screen, many text Inputs i have added
2. firstly i click on text inputs so focus go on text input
3. secondly i click on dropdown so it is perfectly open 
4. then i click on again text input so that time dropdown should be close but always open right now.

Create an expo snack:

**Expected behavior**

**Screenshots**
![Screenshot_1617860139](https://user-images.githubusercontent.com/70644417/113974283-490d8200-985b-11eb-8ebf-cdaf66f9a5f5.png)

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - it is not working on android
 - Package version [e.g. 22]
 

**Additional context**

**Comment by akshat-infusion** [comment]
@hossein-zare please help me for solve this issue

**Comment by mynameisthanhdat** [comment]
https://snack.expo.io/@dcangulo/close-dropdown-on-outside-click
You can see this here.

**Comment by akshat-infusion** [comment]
Not working @mynameisthanhdat

**Comment by hossein-zare** [comment]
Hello @akshat-infusion 

The snack mentioned by @mynameisthanhdat  is the only way to fulfill the desired functionality.

**Try this example:**
```javascript
function App() {
  const [dropDownOpen, setDropDownOpen] = useState(false);
  const dropDownRef = useRef(null);

  return (
    <>
      <DropDownPicker
        controller={instance => dropDownRef.current = instance}
        onOpen={() => setDropDownOpen(true)}
        onClose={() => setDropDownOpen(false)}
        containerStyle={{ height: 40, position: 'relative' }}
        zIndex={9000}
        ...
      />

      {dropDownOpen && <TouchableWithoutFeedback style={styles.overlay} onPress={() => dropDownRef.current.close()} />}
    </>
  );
}

const styles = StyleSheet.create({
  overlay: {
    zIndex: 8000,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  }
});
```
