### ISSUE TITLE
Auto width to match with the widest item in the dropdown

### ISSUE THREAD

**Issue by zaiisao** [hossein-zare/react-native-dropdown-picker#239]
**Is your feature request related to a problem? Please describe.**
I am trying to create a horizontal scrolling list with one of these dropdown pickers inside, and there does not seem to be any good way to set the width of the dropdown to the item that would be longest were line breaks not to exist.

**Describe the solution you'd like**
If there was some property that would enable automatic width setting to match this condition, that would be very useful.

**Describe alternatives you've considered**
I am currently trying to figure out some workarounds. One is to manually calculate all of the items I have with the font sizes, retrieve the longest one, and set the width of the entire dropdown component to that. This is a very cumbersome process. Another thought I had was to get onLayout for each of the dropdown items, but then realized that there is no way to directly access that.

**Additional context**
For a basic component that has a Text inside a View, the View's style can be easily configured such that it is automatically resized to match the Text. However, this is no simple component.

**Comment by hossein-zare** [comment]
Hello,

I labeled this as a new feature request but not sure about it.
I'm busy sorry for that.

**Comment by zaiisao** [comment]
That's fine; I'm busy too but I may decide to take a stab on this one.
