### ISSUE TITLE
default value attribute not working 

### ISSUE THREAD

**Issue by vaibhavCisin** [hossein-zare/react-native-dropdown-picker#24]
**Describe the bug**

**To Reproduce**

Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
Hello,
Add your Code Snippet.
