### ISSUE TITLE
Dropdown menu cuts off when component is in a scrollview

### ISSUE THREAD

**Issue by zaiisao** [hossein-zare/react-native-dropdown-picker#240]
**Describe the bug**
If you have a dropdown component in a scroll view, then the options cut off. This issue is not there if a regular view is used.

**To Reproduce**
You can check refer to the Expo snack below.
Expo Snack: https://snack.expo.io/5A3BvxF1w

**Expected behavior**
The options should appear and not be clipped by the boundaries of the scroll view, just like how it does not get clipped when inside a regular view.

**Screenshots**
What it looks like with a ScrollView container:
![IMG_1896](https://user-images.githubusercontent.com/1892030/114165112-0cc74800-9967-11eb-9152-b97b8882ed40.PNG)

What it looks like with a View container:
![IMG_1897](https://user-images.githubusercontent.com/1892030/114165126-105acf00-9967-11eb-940d-7433a577b19e.PNG)

**Info (please complete the following information):**
 - OS: Both iOS and Android
 - Package version 4.0.5

**Comment by zaiisao** [comment]
Setting the style of the scroll view as `overflow: 'visible'` seems to do the trick. Should have done some Googling prior!

**Comment by nathantew14** [comment]
> Setting the style of the scroll view as `overflow: 'visible'` seems to do the trick. Should have done some Googling prior!

setting that prevents scrolling on android. can we get this issue opened again?

Edit: fixed with these props:

```
<View style={{ borderWidth: 1, height: "100%" }}>
  <ScrollView contentContainerStyle={{ flexGrow: 1 }}>
    {content}
  </ScrollView>
</View>;
```
