### ISSUE TITLE
zIndex issue in iOS

### ISSUE THREAD

**Issue by MahiBuger** [hossein-zare/react-native-dropdown-picker#242]
**Describe the bug**
After upgrade v4.0.5, when there is no enough space at bottom dropdown is display in top but items are in background (zIndex issue) while when dropdown in bottom is working fine.

**Expected behavior**
Dropdown should be visible on front irrespective of dropdown position.

**Screenshots**
<img width="871" alt="Screenshot 2021-04-13 at 1 32 12 PM" src="https://user-images.githubusercontent.com/51189214/114520349-fa972380-9c5e-11eb-993a-79215bf42264.png">

**Info (please complete the following information):**
 - OS: iOS
 - Package version v4.0.5

**Additional context**

**Comment by Jumpis** [comment]
I'm having exactly same issue.
Having multiple dropdownpicker, when the picker is open below(facing down) it works as expected, but when its open above(facing up) items are displayed in background.
```js
<DropDownPicker
        controller={(instance): DropDownPickerInstanceType =>
          (objectivePickerRef.current = instance)
        }
        items={objectiveOptionList}
        disabled={!hasTarget || hasTemplate}
        dropDownMaxHeight={300}
        dropDownStyle={m20}
        containerStyle={p20}
        defaultValue={selectedObjectiveList}
        itemStyle={fljfs}
        multiple={true}
        multipleText={"%d objectives."}
        onChangeItemMultiple={(item): void => handleChangeObjective(item)}
        searchable
        searchablePlaceholder="search objectives"
        zIndex={4000}
      />
      <DropDownPicker
        controller={(instance): DropDownPickerInstanceType =>
          (taskPickerRef.current = instance)
        }
        items={taskOptionList}
        disabled={!hasTarget}
        dropDownMaxHeight={300}
        dropDownStyle={m20}
        containerStyle={p20}
        defaultValue={selectedTaskList}
        itemStyle={fljfs}
        multiple={true}
        multipleText={"%d tasks"}
        onChangeItemMultiple={(item): void => handleChangeTask(item)}
        searchable
        searchablePlaceholder="search tasks"
        zIndex={3000}
      />
```

**Comment by hossein-zare** [comment]
Hello,

Please install: `react-native-dropdown-picker@4.0.6`

> **Multiple Pickers**
> The `zIndexInverse` prop must be greater than the first `zIndex` which is `5000`
> ```jsx
> <DropDownPicker zIndex={5000} zIndexInverse={6000} />
> <DropDownPicker zIndex={4000} zIndexInverse={6000} />
> <DropDownPicker zIndex={3000} zIndexInverse={6000} />
> ```

**Comment by Jumpis** [comment]
Thanks for the update!!

**Comment by Jumpis** [comment]
```js
      <DropDownPicker
        controller={(instance): DropDownPickerInstanceType =>
          (objectivePickerRef.current = instance)
        }
        items={objectiveOptionList}
        disabled={!hasTarget || hasTemplate}
        dropDownMaxHeight={300}
        dropDownStyle={m20}
        containerStyle={p20}
        defaultValue={selectedObjectiveList}
        itemStyle={fljfs}
        multiple={true}
        multipleText={"%d objectives."}
        onChangeItemMultiple={(item): void => handleChangeObjective(item)}
        searchable
        searchablePlaceholder="search objectives"
        zIndex={4000}
        zIndexInverse={6000}
      />
      <DropDownPicker
        controller={(instance): DropDownPickerInstanceType =>
          (taskPickerRef.current = instance)
        }
        items={taskOptionList}
        disabled={!hasTarget}
        dropDownMaxHeight={300}
        dropDownStyle={m20}
        containerStyle={p20}
        defaultValue={selectedTaskList}
        itemStyle={fljfs}
        multiple={true}
        multipleText={"%d tasks"}
        onChangeItemMultiple={(item): void => handleChangeTask(item)}
        searchable
        searchablePlaceholder="search tasks"
        zIndex={3000}
        zIndexReverse={7000}
      />
```
still having same issue. should I use the same zIndexReverse value for all components?

**Comment by Jumpis** [comment]
please check this PR.
https://github.com/hossein-zare/react-native-dropdown-picker/pull/244

**Comment by hossein-zare** [comment]
Hello @Jumpis 
I merged your PR.
`react-native-dropdown-picker@4.0.8`

Yes, Use the same `zIndexReverse` for all of them.

**Comment by Jumpis** [comment]
Hello, I've found another zIndex issue.
I have added isVisible state for pickers to close other picker when another picker is opened.
```js
const [pickerVisibleState, setPickerVisibleState] = useState<
    PickerVisibleState
  >({
    isTargetVisible: false,
    isObjectiveVisible: false,
    isTaskVisible: false,
    isFeedbackVisible: false,
  });

  const handleVisibility = (state: Partial<PickerVisibleState>): void =>
    setPickerVisibleState({
      isTargetVisible: false,
      isObjectiveVisible: false,
      isTaskVisible: false,
      isFeedbackVisible: false,
      ...state,
    });
```

```js
<DropDownPicker
        items={targetList}
        dropDownMaxHeight={250}
        dropDownStyle={m20}
        containerStyle={p20}
        defaultValue={selectedTargetValue}
        itemStyle={fljfs}
        isVisible={pickerVisibleState.isTargetVisible}
        onOpen={(): void => handleVisibility({ isTargetVisible: true })}
        onClose={(): void => {
          setPickerVisibleState({
            ...pickerVisibleState,
            isTargetVisible: false,
          });
        }}
        onChangeItem={(item): void => {
          handleChangeTarget(item);
          taskPickerRef.current.reset();
          objectivePickerRef.current.reset();
        }}
        placeholder="target."
        searchable
        searchablePlaceholder="search target"
        zIndex={5000}
        zIndexInverse={6000}
      />
```

For example, when the picker is positioned 
```js
<Picker A zIndex={5000} zIndexInverse={6000}/>
<Picker B zIndex={4000} zIndexInverse={6000}/>
<Picker C zIndex={3000} zIndexInverse={6000}/>
<Picker D zIndex={2000} zIndexInverse={6000}/>
```

if Picker C is open toward to top, when user opens Picker B toward to bottom, zIndex problem occurs.
Plz check the screenshot below.
![image](https://user-images.githubusercontent.com/24471244/114859066-34b22200-9e25-11eb-807b-a41df660625c.png)
![image](https://user-images.githubusercontent.com/24471244/114859079-3845a900-9e25-11eb-8e59-e86b5366a002.png)

**Comment by kimivn** [comment]
@Jumpis you should use a state zIndex to DropDownPicker, when click dropdown set zIndex < zIndexInverse

**Comment by hossein-zare** [comment]
Don't let the user open all of them at the same time.
The `onOpen` and `onClose` properties are useful.

I could add a new property as `direction` to know it's above or below the picker but that just makes it complicated.

**Comment by hossein-zare** [comment]
Don't let the user open them all at the same time.
The `onOpen` and `onClose` properties are useful.

**Comment by MahiBuger** [comment]
@hossein-zare Since i'm using wrapped dynamic pickers where to apply zIndex and zIndexInverse. I mean should i apply zIndex to parent view or dropDown.

<img width="1030" alt="Screenshot 2021-04-19 at 1 50 08 PM" src="https://user-images.githubusercontent.com/51189214/115204533-370ec780-a116-11eb-85fb-879626f4f280.png">

Here i didn't apply zIndex to either DropDown or parent view. It's working charm in android while in iOS, top directed dropdown working fine, and bottom faced dropdown going below to views.

```
export const RenderDropDownPicker = (props) => {
    return (
        <>
            {props.label && <Text>{props.label}</Text>}
            <LMDropDownPicker items={props.items} {...props}/>
            {props.meta.submitFailed && props.meta.error && <RenderInputError errorMessage={props.meta.error} />}
        </>
    );
};
```
```
export const LMDropDownPicker = ( props ) => {
    function _onChange(value) {
        if (props.input) {
            props.input.onChange(value);
        } else {
            props.onChange(value);
        }
    }
    return (
        <DropDownPicker
            containerStyle={Styles.dropDownContainer}
            style={Styles.dropDown}
            itemStyle={Styles.dropDownItem}
            labelStyle={Styles.dropDownLabel}
            selectedLabelStyle={Styles.dropDownLabel1}
            placeholderStyle={Styles.dropDownPlaceHolder}
            onChangeItem={item => _onChange(item.value)}
            zIndex={props.zIndex}
            zIndexInverse={8000}
            {...props}
        />
    );
};
```

**Comment by hossein-zare** [comment]
Hello,
The current version (v4.x) will be deprecated soon (won't be supported anymore), instead i'll publish **v5**.
There will be only one zIndex prop, as a Rule you shouldn't open more than one picker at the same time.

**Comment by MahiBuger** [comment]
@hossein-zare That's great to hear. When can we expect v5.

**Comment by hossein-zare** [comment]
@MahiBuger I think tomorrow, it will be ready but a beta version.

**Comment by mgithubmessier** [comment]
This is looking like it's still a bug in v5.

**Comment by hossein-zare** [comment]
@mgithubmessier https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules#only-one-at-a-time
