### ISSUE TITLE
Adding renderItem prop, and performance improvement.

### ISSUE THREAD

**Issue by tamirhal** [hossein-zare/react-native-dropdown-picker#243]
Hey, I'm enjoying using your library. 

Two main things that are missing and can be very useful is renderItem prop with functionality as in FlatList component.
And also when there are a lot of items that need to render the opening and closing of the dropdown can take a long time. using FlatList instead of ScrollView can improve the performance.

**Comment by hossein-zare** [comment]
Hello, Thanks.

As a known issue, The current version will be deprecated and v5.x will be released due to performance issues.

**Comment by tamirhal** [comment]
Will the next version include some kind of renderItem props ability?

**Comment by hossein-zare** [comment]
Yes, It'll be possible to customize the default `renderItem` function, Most of the current styling properties will be removed in the next version.

**Comment by tamirhal** [comment]
Thanks!
