### ISSUE TITLE
Controller Additems not adding to the drop down list

### ISSUE THREAD

**Issue by dhirajanand014** [hossein-zare/react-native-dropdown-picker#247]
Describe the bug
Drop down picker's controller ref is not adding Items when pushing it programatically. Before calling the controllerRef.current.addItems(values), call to the API is made to fetch the {label, value} pairs. However, when the list is set to this drop down picker by invoking controllerRef.current.addItems(values) - nothing gets added and the drop down list when expanded displays 'Not found'

**Expected behavior**
When the values that are added using the references - controllerRef.current.addItems(values) - they should be populated to the drop down picker. This approach we are using inorder to skip re-render of the state that refreshes the section where the drop down appears.

Screenshots
![Screenshot_2021-04-21-17-38-58-283_com stardom (1)](https://user-images.githubusercontent.com/29733508/115551438-b17f4900-a2c8-11eb-9ccd-c7ce0a44092d.jpg)

Info
 - IOS and Android
 - Package version - 4.0.9

Additional context

Below is the following code  - 

1. This is on th UI JS files as a component

```javascript
let dropDownController = useRef(null);

<DropDownPicker items={props.list} containerStyle={userAuthStyles.dropDownPickerStyle} globalTextStyle={SDGenericStyles.ft16}
    selectedLabelStyle={[SDGenericStyles.bold, SDGenericStyles.fontFamilyNormal, SDGenericStyles.selectedDropDownColor]}
    dropDownStyle={SDGenericStyles.dropDownBackGround} itemStyle={SDGenericStyles.justifyItemsStart}  controller={instance => dropDownController.current = instance}
    onChangeItem={item => onChangeByValueType(inputProps, item.value, props)} defaultValue={props.dropDownDefaultValue}
    placeholder={props.placeHolderText} placeholderStyle={[SDGenericStyles.bold, SDGenericStyles.fontFamilyNormal,
    SDGenericStyles.selectedDropDownColor]} multiple={props.isMultiple} searchable={props.isSearchable}
/>
```

2. This is in the helper where we fetch the[{ label, value }] pairs and set it to additems

```javascript
const categories = await fetchCategoryData();
const postCategories = categories.map(category => { return ({ label: category.categoryTitle, value: parseInt(category.categoryId), icon: () => { } }); });
dropDownController.current.addItems(postCategories);
```

**Comment by dhirajanand014** [comment]
`test`

**Comment by dhirajanand014** [comment]
> d

**Comment by dhirajanand014** [comment]
The code point also comes to the below code and executes without any error - 
```javascript
addItems(array) {
        const items = [...this.props.items, ...array];
        this.setPropState({
            items
        });
    }
```

**Comment by dhirajanand014** [comment]
Closing issue as followed steps mentioned in the docs.

**Comment by dhirajanand014** [comment]
Closing issue as followed steps mentioned in the docs.

**Comment by initreem** [comment]
Hi @dhirajanand014, I'm facing the same issue and despite following documentation not able to figure out why the items are not appearing. Could you tell me what steps you took?
