### ISSUE TITLE
Bug: dropdowns fall behind other content in react-navigation draw menu components

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#248]
# Bug description

Hello, I hope this finds you well.

There is inconsistent behaviour shown by dropdown picker components in bottom tab and drawer menus created with [react-navigation](https://reactnavigation.org/). In [this example](https://github.com/taeh98/react-native-dropdown-picker-react-navigation-drawer-issue), the dropdown picker is hidden behind other content when in (a component in) a drawer menu, but is shown on top of the other content (the expected and desired behaviour) when in (a component in) a bottom tabs menu. This happens despite the exact same component (containing the dropdown picker and other content) being used in both menus.

Please note that in this example, the "other content" is a Text component, within a View component, that includes the _lorem ipsum_ text paragraph. The dropdown picker is also wrapped by a (different) View component. This bug was found on Android. This may or may not also be an issue on iOS; I haven't been able to test it on an iOS device.

Please could you fix this issue? Thank you in advance for your time and effort.

# To reproduce

1. Clone [https://github.com/taeh98/react-native-dropdown-picker-react-navigation-drawer-issue](https://github.com/taeh98/react-native-dropdown-picker-react-navigation-drawer-issue)
2. run npm install
3. run expo start
4. Open the project on an Android device
5. Open the dropdown pickers in the components in the drawer menu and bottom tabs menu

# Desired behavior

Dropdown picker elements in components in both drawer and bottom tabs react-navigation menus should be consistent in how they appear over (desired) or behind other components within the same component being displayed as the current view.

# Actual behavior

Dropdown picker elements in components in drawer and bottom tabs react-navigation menus are inconsistent in how they appear over or behind other components within the same component being displayed as the current view. In (components in) drawer menus, other components appear on top of the dropdown pickers (unexpected and undesired), but in (components in) bottom tabs menus, the dropdown pickers appear on top of other components (expected and desired).

# Screenshots

The following screenshot shows the appearance of an opened dropdown picker in a component in a drawer menu, as part of the aforementioned example, running on my Android phone. You can see the text content appears on top of the dropdown picker. This behaviour is neither expected nor desired.

![drawer](https://user-images.githubusercontent.com/28008958/116127117-5df16e80-a6bf-11eb-9424-672e00c392db.jpg)

The following screenshot shows the appearance of an opened dropdown picker in a component in a bottom tabs menu, as part of the aforementioned example, running on my Android phone. You can see the text content does not appear on top of the dropdown picker. This behaviour is both expected and desired.

![bottom-tab](https://user-images.githubusercontent.com/28008958/116127155-68ac0380-a6bf-11eb-8427-b04304a77af7.jpg)

# Environment info

- Tested only on Android while running locally with Expo
- Package versions can be seen at: [https://github.com/taeh98/react-native-dropdown-picker-react-navigation-drawer-issue/blob/main/package.json](https://github.com/taeh98/react-native-dropdown-picker-react-navigation-drawer-issue/blob/main/package.json)

**Comment by hossein-zare** [comment]
Hello,

I reproduced the behavior, it seems pretty strange and unfixable.
There are some other issues related to yours.
I've added `MODAL` list mode to the latest version as an alternative.

It took me a year to deal with the bug, nothing. Since it's a native Java bug, React Native should fix it.

**Comment by Dastan4r** [comment]
Hey! I have the same issue and just wrapping Dropdown and Content to different <View>. Dropdown View with z-index 10, and content view with z-index 1. It works for me and now dropdown overlap content and show first

**Comment by hossein-zare** [comment]
Hello @Dastan4r ,
on Android?

**Comment by Dastan4r** [comment]
@hossein-zare Good day! Yes, it helps on both, Android and IOS. I checked this right now.  But i use react native cli (not expo), react-native 0.64, and latest version of your plugin

**Comment by hossein-zare** [comment]
@Dastan4r Amazing, Share your code if possible. 😀
Btw are you sure that the picker is in a drawer menu?

**Comment by Dastan4r** [comment]
No, in my case it just a screen in react navigation, but bug will be the same. So maybe it can help on Drawer. About code i can share some dump example

**Comment by Dastan4r** [comment]
```
<View style={styles.filteringContainer}>
<DropDownPicker
	containerStyle={styles.dropdownContainer}
	style={[styles.dropdown, openFilter && styles.dropdownOpened]}
	textStyle={styles.dropdownLabel}
	dropDownContainerStyle={styles.dropdownBoxContainer}
	searchable={false}
	showArrowIcon
	showTickIcon={false}
	open={openFilter}
	value={filterValue}
	items={filterItems}
	setValue={setFilterValue}
	setItems={setFilterItems}
	setOpen={setOpenFilter}
	ArrowDownComponent={() => <ArrowUpIcon />}
	ArrowUpComponent={() => <ArrowUpIcon style={styles.iconUp} />}
/>

<DropDownPicker
	containerStyle={styles.dropdownStyleContainer}
	style={styles.dropdownStyle}
	dropDownContainerStyle={styles.dropdownStyle}
	searchable={false}
	showArrowIcon
	disableBorderRadius
	showTickIcon={false}
	open={openStyleFilter}
	value={filterStyleValue}
	items={filterStyleItems}
	setValue={setFilterStyleValue}
	setItems={setFilterStyleItems}
	setOpen={setOpenStyleFilter}
	ArrowDownComponent={() => <ArrowUpIcon />}
	ArrowUpComponent={() => <ArrowUpIcon style={styles.iconUp} />}
/>
</View>

<View style={{ zIndex: 1,  }}>
<TagsList items={tags} />
</View>
```


in filteringContainer setup zIndex 10

**Comment by hossein-zare** [comment]
@Dastan4r Ughh, If you put it in a drawer menu, it won't work. 😕
Take a look at the first screenshot.

**Comment by Dastan4r** [comment]
Hmm, strange, because i try to reproduce . Setup this navigation with Drawer
```
<DrawerNavigation.Navigator initialRouteName="Library">
<DrawerNavigation.Screen
	name="Library"
	component={Library}
	options={{ headerShown: false }}
/>
</DrawerNavigation.Navigator>
```

And on Library i have code which i paste before and all works fine)) Very strange, but maybe i miss something...

**Comment by taeh98** [comment]
Just as an update, with a little bit of testing with version 5, I think that a DropdownPicker might not be able to open at all when in a drawer component. I need to do some more testing to be sure though.

**Comment by khoana56** [comment]
I have an issue.
It happen on iOS devices. The list container was being overlay by other component due to setting it's zIndex property highest.
On Android devices, the list container isn't but the items couldn't be selected or scrolling in "SCROLLVIEW" mode.

**Comment by hossein-zare** [comment]
Hello @KhoaN56 ,
Please send me a snack.

**Comment by khoana56** [comment]
> Hello @KhoaN56 ,
> Please send me a snack.

I've fixed the overlay issue by setting the overlay component's `zIndex` to -1.
The iOS is working fine now. But on Android devices, the list item is still freezing. I've figured out that only the area that still inside of it's parent component is allowed to select or drag to scroll. (I used Android simulator and my Galaxy S8+ to test)

**Comment by hossein-zare** [comment]
@KhoaN56 This bug cannot be fixed.
React Native has to take responsibility of the bug **View `position: absolute` inside Drawer Menu**.

**Comment by frankl1** [comment]
@Dastan4r  thanks for your trick. Worked for me just by setting the zindex of the containing view to 1
