### ISSUE TITLE
defaultValue should be called value

### ISSUE THREAD

**Issue by tieniber** [hossein-zare/react-native-dropdown-picker#250]
**Describe the bug**
The prop called `defaultValue` is really the `value` prop from any other selector component. It doesn't seem to be a starting point for a new component, but rather in all of the demos it is maintained by the outer component's state. It seems that changing the `defaultValue` prop actually changes the selection in the component.

**Expected behavior**
The prop should be renamed to `value`

**Comment by iamclaytonray** [comment]
If this is accepted, I'm happy to open a PR

**Comment by hossein-zare** [comment]
Hello,
Yes, But no need to rename the prop because i'll publish **v5** with fantastic features, All the other versions will be deprecated.
