### ISSUE TITLE
make clear documents

### ISSUE THREAD

**Issue by thanhdatpd** [hossein-zare/react-native-dropdown-picker#251]
In the example here: [usage#single-item](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#single-item) have prop onChangeValue but it never working or was implement in code but it still exists in the document.
return new value In [setValue](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#setvalue) instead, returns the function. So to get the value you need to call the function was return. I need a couple of time to found a way to get a new value => return value instead function and note this in document ^^

**Comment by hossein-zare** [comment]
Hello,
I changed it to setValue minutes ago.

I'll let you know whether the property can be used to get the new value.
