### ISSUE TITLE
Dropdowns are overlapping and can only be pressed in margins between items

### ISSUE THREAD

**Issue by Petrxss** [hossein-zare/react-native-dropdown-picker#252]
`
return (
        <View>

            <TextInput
                style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
                onChangeText={text => setText(text)}
                value={text}
                keyboardType={'numeric'}
            />
            <DropDownPicker
                containerStyle ={{height: 40, marginTop: 10, marginBottom: 10}}
                dropDownStyle = {{backgroundColor: "#fafafa"}}
                style={{flex: 1, borderColor: 'gray', borderWidth: 1}}
                items={items}
                placeholder="Choose an item"
                defaultValue={1}
                
                onChangeItem={(item: DropdownProp) => {
            
                setAnotherItem(item.value.specific)
                
                }}
            />
            <DropDownPicker
                containerStyle ={{height: 40, marginTop: 10, marginBottom: 10}}
                dropDownStyle = {{backgroundColor: "#fafafa"}}
                style={{flex: 1, borderColor: 'gray', borderWidth: 1}}
                items={otheritems}
                placeholder="Choose an item"
                defaultValue={1}
                
                onChangeItem={(item: DropdownProp) => {
                    
                    setDifferentItem(item.value)
                
                }}
            />

            <Text>{fruit}</Text>
        </View>
    )
}
`
As the title says, the items in the dropdown are overlapping with the other dropdown and I can only select items in the margin area.

I don't really understand what I'm doing wrong here, I'm new to coding. I tried to look through other issues but I didn't find this issue anywhere (at least where I looked)

![180725957_297929668614464_8153692056331975148_n](https://user-images.githubusercontent.com/83551541/116822974-71527d00-ab8a-11eb-9c5f-2467f4a1a767.jpg)

**Comment by hossein-zare** [comment]
Hello,

Add zIndex={2000} to the first Picker, zIndex={1000} to the second one.

**Comment by Petrxss** [comment]
It's still the same, I added both zIndexes, didn't change at all

**Comment by hossein-zare** [comment]
Here you go https://snack.expo.io/gRVWxNxbL

**Comment by Petrxss** [comment]
Thank you very much, It worked!
