### ISSUE TITLE
Updating Formik value state using picker

### ISSUE THREAD

**Issue by tanjoash** [hossein-zare/react-native-dropdown-picker#255]
Hi, I'm really new to React Native and I want to create a form using formik while using this as my picker, realised the latest version of this picker is pretty new so there's not a lot of information about this. I'm trying to get `setValue` to change the initial value that I had stated in formik to the value I had set for each item of the picker.

```
"typescript": "~4.0.0"
"react-native-dropdown-picker": "^5.0.0"
"formik": "^2.2.6"
```

Heres's my code.

```
import { Formik } from 'formik';
import DropDownPicker from 'react-native-dropdown-picker';

const [openDrowndown, setOpenDropdown] = useState(false);
const [dropdownItems, setDropdownItems] = useState([
    {label: '--Select Priority--', value: '0'},
    {label: '1 - low priority', value: '1'},
    {label: '2 - medium priority', value: '2'},
    {label: '3 - high priority', value: '3'}
]);

<Formik
initialValues={{priority: ' ', otherItems: ' '}}
onSubmit={values => console.log(values)}>
{({handleChange, submitForm, setFieldValue, values}) => (
/*other stuff*/
<DropDownPicker
    items={dropdownItems}
    setItems={setDropdownItems}
    open={openDrowndown}
    setOpen={setOpenDropdown}
    value={values.priority}
    setValue={dropdownItems => setFieldValue(
      'priority', dropdownItems.value
    )}
    closeAfterSelecting={true}
    searchable={false}
        />
/*other stuff*/
<Button onPress={submitForm}
)}
</Formik>
```

Priority does not logged in the console. only `otherItems` stated in the initial value.
```
console: "Object { 
otherItems: ' '
}"
```

![photo_2021-05-03_12-20-52](https://user-images.githubusercontent.com/78843046/116840949-4445af00-ac0a-11eb-9f31-ea1f85205574.jpg)

Thanks so much for the help!

**Comment by hossein-zare** [comment]
Here you go https://snack.expo.io/gRVWxNxbL

**Comment by hossein-zare** [comment]
Hi,

Try this code:
```jsx
setValue={(state) => {
  let newState = state;

  if (typeof state === "function") {
    newState = state(values.priority);
  }
        
  setFieldValue('priority', newState);
}}
```

The `setFieldValue: (..., value: any, ...) => void` of Formik is not what the picker requests.
The `value` must accept callbacks.

Instead of `{label: '--Select Priority--', value: '0'}` you can change the placeholder.
```jsx
placeholder="Select Priority"
```

**Comment by tanjoash** [comment]
Works Great! Thanks a bunch :) Keep up the good work! 👍

**Comment by barelyhuman** [comment]
@hossein-zare 
Doesn't work with the multiple selection cases, forces the user to use the state callback instead

**Comment by hungvu193** [comment]
@hossein-zare can you provide the example for multiple selection cases please?
