### ISSUE TITLE
Bug: parameter of setValue() callback is a function, not a value

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#256]
Hello,

The setValue prop in DropDownPicker is used to give a callback to the component to allow it to change its value when the user touches dropdown items to change it. The callback should take a single parameter of the new value or values, which can also be null to clear the current value. The callback should then change the value of the dropdown picker in a parent component's state that is passed to the DropDownPicker component as its value prop.

I have found, however, that the parameter passed to the setValue callback is a function rather than a value (or values or null). The type of the parameter should be "ValueType | ValueType[] | null" but I have found that it is actually "function". You can see this with a repo I made to demonstrate the issue: [https://github.com/taeh98/react-native-dropdown-picker-set-value-prop-type](https://github.com/taeh98/react-native-dropdown-picker-set-value-prop-type)

Thank you in advance for your time and help!

**Comment by hossein-zare** [comment]
Hello,

It was almost impossible to use the actual value variable in `useCallback` functions because it caused the `renderListItem` to re-render items.
The solution was `setValue(state => ...)` which returns the same value.

❌ Bad
```jsx
const onPressItem = useCallback((item) => {
  setValue([...value, item.value]);
}, [value]);
```
✔️ Good
```jsx
const onPressItem = useCallback((item) => {
  setValue(state => [...state, item.value]);
}, [setValue]);
```

Thank you for reporting, I'll update the `index.ds.ts` file.

**Comment by taeh98** [comment]
> Hello,
> 
> It was almost impossible to use the actual value variable in `useCallback` functions because it caused the `renderListItem` to re-render items.
> The solution was `setValue(state => ...)` which returns the same value.
> 
> x Bad
> 
> ```js
> const onPressItem = useCallback((item) => {
>   setValue([...value, item.value]);
> }, [value]);
> ```
> 
> heavy_check_mark Good
> 
> ```js
> const onPressItem = useCallback((item) => {
>   setValue(state => [...state, item.value]);
> }, [setValue]);
> ```
> 
> Thank you for reporting, I'll update the `index.ds.ts` file.

Thanks for your reply!

So would the following new type be OK?

`setValue: (setValueCallback: (values: ValueType | ValueType[] | null) => void) => void`

I'm not sure what the parameter/s of setValueCallback() should be. I'm thinking maybe it's currently the (entire) state of the dropdown picker component from your code? I think it would maybe make more sense just to pass the new value/s though, instead of the whole state?

**Comment by hossein-zare** [comment]
Yes it is ok.
> I think it would maybe make more sense just to pass the new value/s though, instead of the whole state?

In this case, The user would have to implement the update state logic such as appending new values to the array, deleting values, ... . Instead another property called `onChangeValue` can be added.

**Comment by taeh98** [comment]
So, as I'm understanding it, the function passed to a DropDownPicker component from a parent component in the setValue prop should take the DropDownPicker's function to change the value in its own internal state, do logic on the current value in the parent component to update it there first, then use the function from DropDownPicker as a parameter to set the new value in the state of the DropDownPicker. Is this right?

Is there no way to use an extra static function to simplify the type of the prop needed? Or an equivalent of shouldComponentUpdate() for a functional class? I think the type is going to confuse a lot of people and make it tricky to use. I understand why a function to change the value is needed though - to update it in the state of the parent component, not just the DropDownPicker.

**Comment by hossein-zare** [comment]
> So, as I'm understanding it, the function passed to a DropDownPicker component from a parent component in the setValue prop should take the DropDownPicker's function to change the value in its own internal state, do logic on the current value in the parent component to update it there first, then use the function from DropDownPicker as a parameter to set the new value in the state of the DropDownPicker. Is this right?

Yes.

If i have to answer you right now, No. I had no choice other than a function.
I know it's going to confuse them but good examples will help on the usage page.

For example in class components:
```jsx
this.state = {
  value: null
}

<DropDownPicker
  setValue={(callback) => {
    this.setState(state => ({
      value: callback(state.value)
    }));
  })
  ...
/>
```

I think the best solution is to introduce helper functions for class components:
```jsx
<DropDownPicker
  setValue={DropDownPicker.HELPERS.setValue(this.setState, 'value')} // a simpler version of what we did above
  ...
/>
```

**Comment by taeh98** [comment]
> > So, as I'm understanding it, the function passed to a DropDownPicker component from a parent component in the setValue prop should take the DropDownPicker's function to change the value in its own internal state, do logic on the current value in the parent component to update it there first, then use the function from DropDownPicker as a parameter to set the new value in the state of the DropDownPicker. Is this right?
> 
> Yes.
> 
> If i have to answer you right now, No. I had no choice other than a function.
> I know it's going to confuse them but good examples will help on the usage page.
> 
> For example in class components:
> 
> ```js
> this.state = {
>   value: null
> }
> 
> <DropDownPicker
>   setValue={(callback) => {
>     this.setState(state => ({
>       value: callback(state.value)
>     }));
>   })
>   ...
> />
> ```
> 
> I think the best solution is to introduce helper functions for class components:
> 
> ```js
> <DropDownPicker
>   setValue={DropDownPicker.HELPERS.setValue(this.setState, 'value')} // a simpler version of what we did above
>   ...
> />
> ```

Would it be at all possible to use a separate (perhaps static) function to turn a function with a type that would be easier to understand and use as the setValue parameter and turn it into a SetStateAction method that's required? Or to use that type to begin with? I don't have experience with hooks in React (I use class components with states) so I'm finding it confusing, as I'm sure new users would too; I know you've said you realise this too. I think we both know it's obvious the best type for the setValue prop, if at all possible, would be as follows:

`setValue: (value: ValueType | ValueType[] | null) => void`

I think you said one of the reasons you can't use a simpler type like this for setValue is that the list items would re-render. Since [React's rendering comparison system](https://reactjs.org/docs/reconciliation.html) uses the keys of nodes in the DOM tree, maybe you could try using a simpler setValue type instead of the current one with a SetStateAction if you assign the list item components keys: maybe React would see that nothing has changed so a fresh render isn't needed? If that doesn't work, maybe you could implement the equivalent of [shouldComponentUpdate()](https://reactjs.org/docs/react-component.html#shouldcomponentupdate) for hooks, [which appears to be memos](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-shouldcomponentupdate)? I think using memos could could fix the problem!

The only reason I'm asking all this is the difficulty I've been having getting the setValue prop to work after upgrading to version 5 myself.

Thanks!

**Comment by hossein-zare** [comment]
`shouldComponentUpdate()` and `memo()` can't compare functions.
The `onPress` function of the component must be updated with a new value. On the other hand this function has been passed to the `RenderListItem` component, basically all the items must get the updated `onPress` func.

I tested the `SET_STATE` helper, it didn't work.

This is the easiest way to update the `value`:
```jsx
export default class App extends Component {
  constructor(props) {
    super(props);
    
    this.state = {
      value: []
    }

    this.setValue = this.setValue.bind(this);
  }

  setValue(callback) {
    this.setState(state => ({
      value: callback(state.value)
    }));
  }

  render() {
    return (
      <DropDownPicker
        setValue={setValue}
        multiple={true}
      />
    );
  }
}

**Comment by taeh98** [comment]
> `shouldComponentUpdate()` and `memo()` can't compare functions.

Ah OK, so when the value updates there are functions that change and need to be updated in list items? Is it just functions or normal variables too?

> The `onPress` function of the component must be updated with a new value. On the other hand this function has been passed to the `RenderListItem` component, basically all the items must get the updated `onPress` func.

You could maybe hold the current value in the state of the Picker (if you aren't already) and either pass it or a constant getter function that returns it to the RenderListItems. Would that mean that onPress() in a RenderListItem would be able to use the same function to get the current value or be able to compare the current value directly in memo()?

> This is the easiest way to update the `value`:

Thanks, I'll have another go!

**Comment by hossein-zare** [comment]
>Ah OK, so when the value updates there are functions that change and need to be updated in list items? Is it just functions or normal variables too?

Just a function.

Holding the value in the picker makes no difference.
You should work with functional components, a bit better than Class components. React Native sucks after all.

I'll try all possible ways in my free time.

**Comment by LGZ04** [comment]
im having problems when I want to select multiple items. When I select one option they throw me this error: _TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method._

Anyone know how to solved this problem?? 

**im using the version:**     "react-native-dropdown-picker": "^5.1.21"
**here is what im doing:**

```
export default class Example extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            openCurrencyDropDown: false,
            currencyData: [
                { label: 'Op1', value: "Op1" },
                { label: 'Op2', value: "Op2" },
                { label: 'Op3', value: "Op3" },
                { label: 'Op4', value: "Op4" },
                { label: 'Op5', value: "Op5" },
                { label: 'Op6', value: "Op6" },
            ],
            currencyCode: [],
        }
        this.setValue = this.setValue.bind(this);
    }

   setValue(callback) {
        this.setState(state => ({
            currencyCode: callback(state.value)
        }));
    }

    render() {
             <DropDownPicker
                   listMode={'MODAL'}
                   multiple={true}
                   min={0}
                   max={5}
                   open={this.state.openCurrencyDropDown}
                   setOpen={this.setOpenCurrencyDropDown}
                   setValue={this.setValue}
                   items={this.state.currencyData}
                   defaultValue={this.state.currencyCode}
                />
    }
}
```

**Comment by KrisLau** [comment]
@hossein-zare Would it be possible to just have an `onPressItem` that is triggered when an item is pressed just so we can somehow detect a difference between value changes caused by non user action vs user action?

**Comment by hossein-zare** [comment]
@KrisLau 

We have a property called `onSelectItem`
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#onselectitem

**Comment by KrisLau** [comment]
@hossein-zare I tested the onSelectItem but it doesn't seem to be triggering?
Snack: https://snack.expo.dev/@kris_lau/react-native-dropdown-picker

**Comment by hossein-zare** [comment]
@KrisLau You're using an old version.
Use v5.3.0.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/changelog

**Comment by KrisLau** [comment]
Oh my bad sorry for all the trouble!
