### ISSUE TITLE
arrowIconColor cannot be changed

### ISSUE THREAD

**Issue by erez-unitronics** [hossein-zare/react-native-dropdown-picker#257]
In previous versions there was 'arrowColor' property.

I tried to set the color like this: 
arrowIconStyle={{ width: 24, top: 2, left: 10, color: 'white' }}
but its not working...

**Comment by hossein-zare** [comment]
Hello,

The icons in old versions were SVG, now They are PNG. so you can't change their color.

You have to change the icons.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/icons#arrowupiconcomponent

**Comment by erez-unitronics** [comment]
@hossein-zare 
Thanks! I changed that
