### ISSUE TITLE
Request/suggestion: port project to TypeScript

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#258]
Hello, I hope this finds you well.

Please could you consider porting this project from JavaScript to native TypeScript? Doing so would provide several advantages:
- static typing with compile-time checks
- easier and quicker to find and fix bugs and mistakes in code
- improved stability and maintainability
- native support for TypeScript projects trying to use this library, without having to maintain a separate TypeScript type declarations file
- ability to uses classes
- better IDE functionality (refactoring, code generation, etc)

Thank you for your consideration.

**Comment by hossein-zare** [comment]
Hello,
Personally I'm not a fan of TypeScript but i keep it in my mind as a future plan.
