### ISSUE TITLE
Is there a TypeScript types file for this component?

### ISSUE THREAD

**Issue by dantaylor** [hossein-zare/react-native-dropdown-picker#26]
**Is your feature request related to a problem? Please describe.**
Not a problem but a really nice to have.

**Describe the solution you'd like**
Have a TypeScript def file for this component that can be used in projects with typescript
Ideally something like this:

npm install @types/react-native-dropdown-picker

**Comment by hossein-zare** [comment]
Hello,
Thank you for the request.

Not yet, I will add it soon.
