### ISSUE TITLE
Arrow icon not displayed

### ISSUE THREAD

**Issue by eldhoshaji** [hossein-zare/react-native-dropdown-picker#27]
The arrow icon inside the dropdown is missing. A square image is displayed in my phone instead of the arrow icon.

 - OS: iOS, Android, Web

<img width="125" alt="picker" src="https://user-images.githubusercontent.com/14539774/84600539-8ac9d800-ae97-11ea-8218-08c172756dd5.png">

**Comment by hossein-zare** [comment]
Hello,
#18

**Comment by eldhoshaji** [comment]
Hi, The vector icons are working fine when I try using them directly in my application. But the arrow in the dropdown doesn't show up.

**Comment by hossein-zare** [comment]
`react-native-vector-icons` is responsible for the behavior, It's been used properly in `react-native-dropdown-package`

Create an issue for `react-native-vector-icons` if it remains unsolved.
https://oblador.github.io/react-native-vector-icons/
