### ISSUE TITLE
Feature request: continuous deployment to npm

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#271]
Hello,

Please could you add continuous deployment to npm from this library? At the moment, I think that only manually created releases are published as updates on npm. You could use a CI workflow with GitHub actions to automatically publish new versions to npm (and also make new versions automatically). I would be happy to help but these links give some good information about this:
- https://docs.github.com/en/actions/guides/publishing-nodejs-packages
- https://github.com/marketplace/actions/npm-publish

Thanks!

**Comment by hossein-zare** [comment]
Hello,

I'll give it a shot, Tomorrow.
