### ISSUE TITLE
It would be nice, if the selected value/the placeholder could be aligned to the left as well

### ISSUE THREAD

**Issue by fabian0409** [hossein-zare/react-native-dropdown-picker#28]
Hi there!

I seem to be unable to align the selected value/the placeholder to the left (instead of center) of the dropdown container (not the list). Setting **style={{alignItems='flex-start'}}** does not seem to have an effect on the alignment of the label.

If this is already possible and I'm just not seeing it, it would be awesome if you could point me in the right direction.

Thanks for your help!

**Comment by hossein-zare** [comment]
Hello @fabian0409 ,
**New Update: v3.0.5**

```javascript
labelStyle={{
    textAlign: 'left' // The selected item
}}
itemStyle={{
    alignItems: 'flex-start' // Items in the dropdown box
}}
placeholderStyle={{
    textAlign: 'center'
}}
```

**Comment by waltershub** [comment]
@hossein-zare I installed 3.0.5 the textAlign for the placeholder is not working for me on both android and IOS

**Comment by hossein-zare** [comment]
@waltershub 
Double-check the version, I've also created a snack for it: https://snack.expo.io/@hossein-zare/textalign (works well)

Send me your props, if the snack didn't help you.

**Comment by fabian0409** [comment]
Thanks a lot @hossein-zare works like a charm.

**Comment by sushmitg** [comment]
Is there a way to also align the arrow to center, right next to placeholder?

![image](https://user-images.githubusercontent.com/22211683/100038035-4b7dbb00-2e29-11eb-8f41-70f1dc0c6a46.png)
Something like this.
