### ISSUE TITLE
Invalid hooks call on newly installed library.

### ISSUE THREAD

**Issue by yasirwahid** [hossein-zare/react-native-dropdown-picker#286]
i have just installed the library and put this comp in my code and getting this error. please review it .
thanks.

![Screenshot 2021-05-06 at 1 10 17 PM](https://user-images.githubusercontent.com/48285343/117264165-69d1f300-ae6c-11eb-8a71-b1284123bafc.png)

![Screenshot 2021-05-06 at 1 08 47 PM](https://user-images.githubusercontent.com/48285343/117263961-355e3700-ae6c-11eb-94d9-46f54f780c35.png)

**Comment by evchut** [comment]
I have the same problem

**Comment by yasirwahid** [comment]
last publish is 9 hours ago, maybe they did a mistake somewhere.

**Comment by hossein-zare** [comment]
Hello,

Yes, I'm going to fix the bug.

**Comment by hossein-zare** [comment]
I just released a new version ~~v5.1.2~~ **v5.1.3**.
