### ISSUE TITLE
Getting dropdown picker to close on next press

### ISSUE THREAD

**Issue by alysiatran** [hossein-zare/react-native-dropdown-picker#29]
Closing dropdown on next click, regardless of whether an item is clicked in the dropdown

**Comment by hossein-zare** [comment]
Hello,
Did you mean clicking outside?

**Comment by alysiatran** [comment]
Hi, thank you for your quick response! Yup, I mean when you click outside, is there a way to get the dropdown to close on click, regardless of whether an item is clicked in the dropdown. Thank you!

**Comment by hossein-zare** [comment]
@alysiatran , As far as i know there's only one way to close the drop-down list when touching outside.
https://snack.expo.io/@hossein-zare/touch-outside

**Comment by alysiatran** [comment]
Thank you! I tried implementing it, but it still doesnt seem to work for me. I am on version 2.1 though, will I need to upgrade to version 3x?

**Comment by hossein-zare** [comment]
Yes. v3.0.5 is available.

> **Caution (incompatibility)**
> x < 3.0.0 Versions are incompatible with the current version.
> It's required to follow the docs in order to upgrade the package to v3.x
> _**https://github.com/hossein-zare/react-native-dropdown-picker#caution-incompatibility**_

**Comment by alysiatran** [comment]
Thank you so much for your help! It works!

**Comment by shulyaev** [comment]
Hi,
What is the best practice to close the drop-down when clicking on other drop-downs, text inputs or buttons?

**Comment by erickponce** [comment]
Hello there,
if you need this behavior on `web`, you can achieve that with this hack:

Import `ReactDOM`:
```
import ReactDOM from 'react-dom';
```

Setup controller on component:
```
controller={(e: any) => element = ReactDOM.findDOMNode(e)}
```

Bind events with `useEffect` (you will need do control DropDown visibility manually with `isVisible`):
```
useEffect(() => {
  if (!document) return;
  const outsideClickListener = (event: any) => {
    if (!element.contains(event.target)) {
      handleClose();
    }
  };

  const removeClickListener = () => {
    document.removeEventListener('click', outsideClickListener);
  };
  document.addEventListener('click', outsideClickListener);
  return removeClickListener;
}, [element]);
```
