### ISSUE TITLE
TypeError when providing default value in DropDownPicker

### ISSUE THREAD

**Issue by cyb3rh4wk** [hossein-zare/react-native-dropdown-picker#291]
I am creating a dropdown picker with remote search enabled. And for the default value I am using value from the redux state. But upon app refresh, I am getting the following error,

```
TypeError: _value.includes is not a function. (In '_value.includes(item[_schema.value])', '_value.includes' is undefined)
```

Current Usage:
```
<DropDownPicker
    addCustomItem={true}
    disableLocalSearch={true}
    items={currentMeta.meta}
    open={pickerState && pickerState[metaKey]}
    onChangeSearchText={
      (searchKey) => handleRemoteDropDownSearch(
        searchKey, currentMeta
      )
    }
    onOpen={() => handleDropDownOpen(metaKey)}
    onClose={() => handleDropDownClose()}
    placeholder={currentMeta.placeholder}
    {...getDropDownStyles(currentMeta.meta.length)}
    searchable={true}
    searchPlaceholder={'Start typing...'}
    setValue={
      (newValue) => handleDropDownChange(
        currentMeta.stateKey, newValue()
      )
    }
    value={userData[currentMeta.stateKey]}
    zIndex={2000}
    {...dropDownSearchStyles}
/>
```
userData has key-values as per the key from currentMeta.stateKey
E.g. If currentMeta.stateKey is `university` then userData[currentMeta.stateKey] return `My University` (string)

It would be great if someone can help on this

@hossein-zare

**Comment by hossein-zare** [comment]
Hello,

Share code of the `handleDropDownChange` function.
The `newValue()` needs the current value in the `setValue` property.
```jsx
setValue={(newValue) => handleDropDownChange(
  currentMeta.stateKey, newValue()
)}
```

If `userData[currentMeta.stateKey]` is your state variable:
```jsx
newValue(userData[currentMeta.stateKey])
```

**Comment by cyb3rh4wk** [comment]
> Hello,
> 
> Share code of the `handleDropDownChange` function.
> The `newValue()` needs the current value in the `setValue` property.
> 
> ```js
> setValue={(newValue) => handleDropDownChange(
>   currentMeta.stateKey, newValue()
> )}
> ```
> 
> If `userData[currentMeta.stateKey]` is your state variable:
> 
> ```js
> newValue(userData[currentMeta.stateKey])
> ```

```
const handleDropDownChange = (metaKey, value) => {
    dispatch(updateUserInfo(metaKey, value));
};
```
Edit: I am not maintainng a component state rather using redux state

Also trying your suggestion. Will let you know if that fixes the issue

**Comment by hossein-zare** [comment]
First install **v5.1.4** (released just now), then `newValue(userData[currentMeta.stateKey])`

**Comment by cyb3rh4wk** [comment]
That fixed it. Thanks a lot!

Would it be possible for you to explain the reason for the fix? For my knowledge :P

**Comment by hossein-zare** [comment]
The callback was returning `undefined` because you'd not passed the current value.
in the `renderListItem` method `undefined.includes` was complaining.

**Comment by orhangazi** [comment]
> Hello,
> 
> Share code of the `handleDropDownChange` function. The `newValue()` needs the current value in the `setValue` property.
> 
> ```js
> setValue={(newValue) => handleDropDownChange(
>   currentMeta.stateKey, newValue()
> )}
> ```
> 
> If `userData[currentMeta.stateKey]` is your state variable:
> 
> ```js
> newValue(userData[currentMeta.stateKey])
> ```

Thank you so much. I am using redux and I was looking for this answer everywhere.
