### ISSUE TITLE
Suggestion: should onChangeValue be required instead of setValue? 

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#293]
Hello,

While upgrading to the newest version of this library and after discussing the setValue prop of dropdown pickers, I thought it might be better to make the field onChangeValue required in the DropDownPickerProps type in index.d.ts instead of setValue. I think that onChangeValue is easier to understand than setValue and is probably what most users require, so I just thought I'd mention the idea.

Thanks!

**Comment by hossein-zare** [comment]
Hello,

No, The `onChangeValue` callback is called when you press an item and the value changes. so `setValue` and `onChangeValue` are not the same thing.

**For your information:**
It returns the `value` variable not `item.value`.
If `multiple={true}`, returns `ValueType[]`. if `false`, `ValueType`. _(null included)_

```jsx
onChangeValue={(val) => {
  console.log("The current value:", val);
})
```

**Comment by AMBTech** [comment]
How to get the whole selected object instead of just it's value?
