### ISSUE TITLE
Request: restore multipleText prop

### ISSUE THREAD

**Issue by taeh98** [hossein-zare/react-native-dropdown-picker#294]
Hello,

I used the multipleText prop for DropDownPicker components with version 4 of this library. I found it useful because it let me write more specific descriptions than "3 items". I think it is now maintained just for translations so is no longer a prop a user can pass to the Picker. Since it could be useful for making better/more specific descriptions of how many items have been chosen, please could you restore this prop and let users set it again?

Thank you!

**Comment by hossein-zare** [comment]
Hello,

In the next version the prop will be added.

**Comment by hossein-zare** [comment]
Added `multipleText` prop, **v5.1.5**.

**Comment by taeh98** [comment]
Thanks!
