### ISSUE TITLE
multipleText Issue

### ISSUE THREAD

**Issue by evg1n** [hossein-zare/react-native-dropdown-picker#298]
When using `multipleText` prop, it will parse the first `d` as `count of selected items`

```
<DropDownPicker
  multiple={true}
  multipleText={"items selected"}
  ...
/>
```

will render `"items selecte2"` (if 2 items were selected)

`"items selectedd"` will render `"items selecte2d"` (if 2 items were selected)

![carbon](https://user-images.githubusercontent.com/10906736/117552566-d871a500-b054-11eb-88c4-5c375ecc0e25.png)

![Simulator Screen Shot - iPhone 8 - 2021-05-08 at 23 26 55](https://user-images.githubusercontent.com/10906736/117552569-e7585780-b054-11eb-8649-2f2cf509e117.png)

Please check `Picker.js` line 473

**Comment by hossein-zare** [comment]
Hello,

Please try `multipleText="\d items selected"`.
I'll fix the bug in the next version.

**Comment by tickietackie** [comment]
This does not work for me on the latest version and also not here:
https://snack.expo.dev/8mHmLfcZf

Is the syntax still the same?
