### ISSUE TITLE
Z Index not working for iOS

### ISSUE THREAD

**Issue by deckyfx** [hossein-zare/react-native-dropdown-picker#3]
in iOS, the selection picker modal is not adhering zIndex

it is working fine in Android
<img width="339" alt="Screen Shot 2020-04-24 at 14 55 02" src="https://user-images.githubusercontent.com/1076192/80188589-989f7180-863b-11ea-8bfe-553b4505fcac.png">

idk, if this is react native issues, or something

Please help

**Comment by hossein-zare** [comment]
Please share your **render()** function.

**Comment by deckyfx** [comment]
my render function is kinda convoluted since I extend your picker component to match my project's need, but basically, try put another view after the picker, for example, <Text />, and try run in iOS and open the picker.

```render(
<View>
    <ReFloatingLabelPicker
            items={businessModelTypeList}
          />
     <Text>This test will not covered by the picker modal</Text>
</View>
)```

**Comment by hossein-zare** [comment]
The bug has been fixed.

**Update the package - v2.0.10**

Don't forget to read the README.md, Some new styling properties have been added to the component such as `containerStyle` you may have to use.

Here's how you can apply the zIndex property to your dropdown picker:
```
<DropDownPicker
    items={[
        {label: 'Item 1', value: 'item1'},
        {label: 'Item 2', value: 'item2'},
        {label: 'Item 3', value: 'item3'},
        {label: 'Item 4', value: 'item4'},
        {label: 'Item 5', value: 'item5'},
        {label: 'Item 6', value: 'item6'},
    ]}
    containerStyle={{height: 40}}
    zIndex={2} 
/>
<DropDownPicker
    items={[
        {label: 'Item 1', value: 'item1'},
        {label: 'Item 2', value: 'item2'},
        {label: 'Item 3', value: 'item3'},
        {label: 'Item 4', value: 'item4'},
        {label: 'Item 5', value: 'item5'},
        {label: 'Item 6', value: 'item6'},
    ]}
    containerStyle={{height: 40}}
    zIndex={1}
/>
```
