### ISSUE TITLE
How to set default value in this picker

### ISSUE THREAD

**Issue by ghost** [hossein-zare/react-native-dropdown-picker#301]

**Comment by tandu** [comment]
I'm not able to set default value too. `value={2}` doesn't work, it still shows placeholder for items `[{value: 1, label: '1'}, {value: 2, label: '2'}]`.

**Comment by hossein-zare** [comment]
Hello @tandu ,

Please use `useState` to store the value.
```jsx
const [value, setValue] = useState(2);
```

What version are you using? and consider creating a snack.

**Comment by tandu** [comment]
It is version 5.
