### ISSUE TITLE
Dropdown getting behind the other Views even with a higher zIndex value

### ISSUE THREAD

**Issue by shubhambattoo** [hossein-zare/react-native-dropdown-picker#302]
React Native version: 0.64
react-native-dropdown-picker: 5.1.7

Dropdown is working fine on an Android device but while running it on an iOS device it is not respecting the zIndex value:

![dropdown](https://user-images.githubusercontent.com/21199053/117822720-6aaebe80-b28a-11eb-8940-2ba7c87fed3a.png)

My code for dropdown:

```javascript
<DropDownPicker
        style={{
          borderTopLeftRadius: 17,
          borderTopRightRadius: 17,
          borderBottomLeftRadius: 17,
          borderBottomRightRadius: 17,
          backgroundColor: '#99ccff',
          height: 35,
        }}
        containerStyle={{
          width: 110,
          marginTop: 10,
          ...containerStyle,
        }}
        itemStyle={{
          flexDirection: 'row',
          justifyContent: 'flex-start',
        }}
        textStyle={{
          fontSize: 10,
          fontWeight: '500',
        }}
        selectedItemLabelStyle={{
          color: '#0066cc',
        }}
        arrowIconStyle={{
          marginVertical: -3,
          paddingTop: 0,
          paddingBottom: 0,
        }}
        zIndex={999999}
        min={5}
        items={items}
        onChangeValue={handleChange}
        searchable={false}
        open={isOpen}
        value={value}
        listMode="SCROLLVIEW"
        setOpen={setIsOpen}
        setValue={setValue}
        onOpen={() => setDropDownOpen(true)}
        onClose={() => setDropDownOpen(false)}
        ref={dropDownRef}
        {...props}
      />
```
I tried giving the view a negative z-index but that did not help either

**Comment by hossein-zare** [comment]
Hello,

Please create a snack.
The picker isn't enough.

**Comment by shubhambattoo** [comment]
Hey @hossein-zare 

I have created a [snack](https://snack.expo.io/@shubhambattoo/dropdown-testing) and the issue is mainly on the iOS device.

**Comment by hossein-zare** [comment]
```jsx
<View style={Platform.OS !== "android" && {zIndex: 999999}}>
  <Dropdown items={product} selection={handleSelection} />
</View>
```

**Comment by shubhambattoo** [comment]
the solution worked on snack, still facing same issues while running the app through xcode emulator

> ```js
> <View style={Platform.OS !== "android" && {zIndex: 999999}}>
>   <Dropdown items={product} selection={handleSelection} />
> </View>
> ```

**Comment by hossein-zare** [comment]
Make sure the `zIndex` value is `999999` everywhere in the `Dropdown`.

**Comment by Jumpis** [comment]
for me dropdown is working fine on iOS but android goes under other component. I have added zindex minus to other components.

**Comment by shubhambattoo** [comment]
Going with the MODAL type of dropdown for the iOS version for now, not able to get the zIndex issue resolved.  Closing the issue as i think something is missing from my end as the snack worked correctly on iOS.
