### ISSUE TITLE
Custom icon 

### ISSUE THREAD

**Issue by hellogbg** [hossein-zare/react-native-dropdown-picker#305]
I am trying to use:
ArrowDownIconComponent={({style}) => <MyArrowDownIcon style={style} />}

and nothing happens in app. Original down-arrow is shown all the time.

I have created new Component that I am importing: 

```
import React from 'react'
import Icon from 'react-native-vector-icons/FontAwesome';

export default MyArrowDownIcon = () => {
  return (
    <Icon name='check' size={45} color="limegreen"  /> 
  )
}
```

This is my DropDownPicker

      <DropDownPicker
        open={open}
        value={value}
        items={items}
        setOpen={setOpen}
        setValue={setValue}
        setItems={setItems}
        searchable={false}
        placeholder={staffName}
        onChangeValue={value => value==='logout' ? dispatch(setSignOut()) : null}

        ArrowDownIconComponent={({style}) => <MyArrowDownIcon style={style} />}
        
        iconContainerStyle={{
          height: 30,
          width: 30,
          backgroundColor:'white'
        }}

        // Styling
        containerStyle={{height: 40}}
        style={{
          backgroundColor: '#222222', 
          borderTopLeftRadius: 0, borderTopRightRadius: 0,
          borderBottomLeftRadius: 0, borderBottomRightRadius: 0,
          borderBottomWidth: 0, borderTopWidth:0,
          borderLeftWidth: 0, borderRightWidth:0,
          paddingTop: 0
        }}
        placeholderStyle={{
          fontSize: 24,
          fontFamily: 'AvenirNextCondensed-Regular',
          color: 'white',
          paddingLeft: 10,
          // textAlign: 'left',
        }}
        dropDownContainerStyle={{
          backgroundColor: '#222', 
          borderWidth:0,
        }}
        listItemLabelStyle={{
          fontSize: 24,
          fontFamily: 'AvenirNextCondensed-Regular',
          color: 'white',
          paddingLeft: 10,
        }}
        labelStyle={{
          fontSize: 24,
          fontFamily: 'AvenirNextCondensed-Regular',
          color: 'white',
          paddingLeft: 10,
          textAlign: 'left',
        }}
      />

**Comment by hossein-zare** [comment]
Hello,

Please install **v5.1.10**.

**Comment by hellogbg** [comment]
Thank you very much Hossein, this solved the issue. 
I don't have bitcoins for a donation, but I would gladly https://www.buymeacoffee.com if you register and post a link :)

**Comment by hossein-zare** [comment]
No problem @avenyproduction ,
Thank you anyway!
