### ISSUE TITLE
Migrating to v5. setValue and setItems give error. Typescript

### ISSUE THREAD

**Issue by AuroPick** [hossein-zare/react-native-dropdown-picker#306]
### setValue error:

![image](https://user-images.githubusercontent.com/53499802/117868377-3810c000-b2a2-11eb-915b-bcf23120da95.png)

### setItems error:

![image](https://user-images.githubusercontent.com/53499802/117868462-5080da80-b2a2-11eb-9735-56acb03489d3.png)

How can i use them

Code:
```js
const [open, setOpen] = useState(false);
const [items, setItems] = useState([
    {
      label: i18n.t("settings.english"),
      value: "en",
      icon: () => <Flag code="US" size={16} type="flat" />,
    },
    {
      label: i18n.t("settings.turkish"),
      value: "tr",
      icon: () => <Flag code="TR" size={16} type="flat" />,
    },
  ]);

const [language, setLanguage] = useState(
    i18n.locale.startsWith("en")
      ? "en"
      : i18n.locale.startsWith("tr")
      ? "tr"
      : "Select Language"
  );

<DropDownPicker
        items={items}
        setItems={setItems}
        value={language}
        open={open}
        setOpen={setOpen}
        setValue={setLanguage}
        arrowColor={colors.text}
        dropDownDirection="BOTTOM"
      />
```

**Comment by AuroPick** [comment]
it is not giving error with this but how can i use callback?

```js
setValue={(callback) => console.log(callback)}
setItems={(callback) => console.log(callback)}
```

**Comment by hossein-zare** [comment]
Hello,

Please install **v5.1.10**.

**Comment by AuroPick** [comment]
> Hello,
> 
> Please install **v5.1.10**.

Thx but I couldn't get how to use setValue. I tried the example in the documentation. Would you give a quick example

**Comment by AuroPick** [comment]
![image](https://user-images.githubusercontent.com/53499802/117972854-51624c80-b334-11eb-8a9b-c95c9680def2.png)

**Comment by hossein-zare** [comment]
This is all you need to do:
```jsx
setValue={setLanguage}
```

**Comment by AuroPick** [comment]
I tried this but didn't work. I have already switch back to v4.

I switched to v5 because zindex conflict but I fixed it.

Thx for your help.

I'm closing this issue.
