### ISSUE TITLE
undefined is not an object (evaluating _reactNative.LogBox.ignoreLogs)

### ISSUE THREAD

**Issue by HighThereDev** [hossein-zare/react-native-dropdown-picker#312]
Issue Im running into is basically as described above. I'm on RN 0.62.2 and thinking that 0.63 might be a requirement? Couldn't find and info on it. 

Has anyone else run it this?

**Comment by hossein-zare** [comment]
Hello,

This is a known issue and will be fixed in the next version (Tomorrow).

**Workaround:**
Open the `./node_modules/react-native-dropdown-picker/src/components/Picker.js` file.

```js
import {
  ...
  LogBox // <<< ❌ Remove ❌
  ...
} from 'react-native';

...

/**
 * componentDidMount.
 */
useEffect(() => {
  LogBox.ignoreLogs(['VirtualizedLists should never be nested']); // <<< ❌ Remove ❌

  ...
}, []);
```
