### ISSUE TITLE
[Android] disabled props make dropdownlist go under other components

### ISSUE THREAD

**Issue by Jumpis** [hossein-zare/react-native-dropdown-picker#313]
```js
<DropDownPicker
        open={kindOpen}
        setOpen={setKindOpen}
        onOpen={onKindOpen}
        // disabled={disabled}
        value={selectedKind}
        items={kindOptions}
        style={[disabled && bdac, la]}
        containerStyle={p20}
        dropDownContainerStyle={[m20, la]}
        labelStyle={disabled ? dc : blc}
        listItemContainerStyle={fljfs}
        setValue={handleSetStatus}
        searchable={false}
        zIndex={5000}
        zIndexInverse={6000}
      />
```
Disabled props make dropdownlist go under other components.
Disabled default value is true when user enters screen.
When user clicks edit button disable value changes to false.
On iOS it works as expected but on Android it doesn't.
When I comment out disabled it works as expected in Android.

**Comment by Jumpis** [comment]
```js
 const pointerEvents = useMemo(() => disabled ? "none" : "auto", [disabled]);

    return (
        <View style={_containerStyle} {...containerProps} pointerEvents={pointerEvents}>
            <TouchableOpacity style={_style} onPress={__onPress} onLayout={__onLayout} {...props} ref={onRef}>
                {_BodyComponent}
                {_ArrowComponent}
            </TouchableOpacity>
            {DropDownBodyComponent}
        </View>
    );
```
It seems like there is a issue between android and pointerEvents props. When I changed the code like 
```js
 // const pointerEvents = useMemo(() => disabled ? "none" : "auto", [disabled]);

    return (
        <View style={_containerStyle} {...containerProps}>
            <TouchableOpacity style={_style} onPress={__onPress} onLayout={__onLayout} {...props} ref={onRef} disabled={disabled}>
                {_BodyComponent}
                {_ArrowComponent}
            </TouchableOpacity>
            {DropDownBodyComponent}
        </View>
    );
```
It works as expected.

**Comment by hossein-zare** [comment]
Hello,

Please reproduce the behavior in a snack.

**Comment by Jumpis** [comment]
https://snack.expo.io/@jumpis/android-bug

its reproducible in this snack

**Comment by Jumpis** [comment]
This issue is caused by pointerEvents. 
I have created PR. https://github.com/hossein-zare/react-native-dropdown-picker/pull/315
Please check the PR.

**Comment by hossein-zare** [comment]
Thanks for the PR.

I released **v5.1.15**.

**Comment by codoffer** [comment]
I am facing a selection issue with the android device (Oneplus 5). I have checked the above example with the expo and having the same selection issue (can't choose result via android and focusing below element). If you try to choose country values, it will open the state dropdown, and will not able to choose "JP".

Can you help me with this?

"react": "17.0.1",
"react-native": "0.64.0",
"react-native-dropdown-picker": "^5.1.15",

**Comment by hossein-zare** [comment]
Hello

**Comment by hossein-zare** [comment]
Hello @codoffer ,
Please create a snack for your issue.
The bug has already been fixed, Most likely there's a zIndex conflict.

**Comment by Mdelacruzmelo** [comment]
Same problem here trying to use version "react-native-dropdown-picker": "^5.1.15", please help :(

**Comment by hossein-zare** [comment]
@Jumpis Are you still facing the same bug?!

**Comment by Jumpis** [comment]
> @Jumpis Are you still facing the same bug?!

Nope! After the update, it works as expected.
@codoffer @Mdelacruzmelo plz check if there are any border related styles in parent elements.
If you keep the rule it may work as expected.
