### ISSUE TITLE
renderListItem

### ISSUE THREAD

**Issue by nicolas-wl** [hossein-zare/react-native-dropdown-picker#319]
Can u please add a more comprehensive example to the documentation on how to use "renderListItem"?
(Right now I can render the items but nothing happens onPress)

```
renderListItem={(props) => (
    <TouchableOpacity {...props}>
        <Text style={{padding: 20}}>{props.item.value}</Text>
    </TouchableOpacity>
)}

**Comment by hossein-zare** [comment]
Hello,

You can see **https://github.com/hossein-zare/react-native-dropdown-picker/blob/5.x/src/components/RenderListItem.js**
Create your own **RenderListItem** component with the code in the file.

```jsx
import CustomRenderListItem from './CustomRenderListItem.js';

renderListItem={CustomRenderListItem}
```
