### ISSUE TITLE
Dropdown background is transparent in IOS app while android has white background

### ISSUE THREAD

**Issue by iarmankhan** [hossein-zare/react-native-dropdown-picker#32]
Hello, I implemented this library some time ago in my react native app and everything was working fine (for android). Today I tested the same app in my iPhone but dropdown background is transparent. I can see the element (in my case text input) behind it and I can even touch it.

I tried updating the library to the latest version and also tried to re-implement it as in docs but still behavior is same on iPhone while android is working perfectly.

**To Reproduce**
Run the app with dropdown on iPhone (I have iPhone 11 (13.5))

**Expected behavior**

Dropdown should look and work similar on both, android and iPhone

**Screenshots**
![Simulator_Screen_Shot_-_iPhone_11_-_2020-06-17_at_03 52 02](https://user-images.githubusercontent.com/40450695/84889717-efaf4900-b0b6-11ea-8318-aaaab46e8337.png)

**Info (please complete the following information):**
 - OS: IOS
 - Package version : 3.0.5

**Comment by hossein-zare** [comment]
Hello,
Please create an expo snack and share it in order to reproduce the behavior.

Make sure you have `dropDownStyle={{backgroundColor: '#fff'}}` set.

**Comment by SirPhemmiey** [comment]
Hey @hossein-zare , thanks for making this great library. 

Please take a look at the attached image. When i click on the dropdown, the items cover the next element and i also can't select it. 

<img width="170" alt="Screen Shot 2020-06-17 at 6 02 32 PM" src="https://user-images.githubusercontent.com/22390818/84907858-c5fd1e80-b0c4-11ea-8137-293756417a5d.png">

**Comment by hossein-zare** [comment]
Hello @SirPhemmiey ,
> **zIndex conflicts**
> https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by iarmankhan** [comment]
Hello @hossein-zare 
it was a zIndex conflict, thank you, it's now solved

**Comment by shubhambali1** [comment]
Hi @iarmankhan can you share the solution, experiencing the same issue

**Comment by mgwedd** [comment]
I can confirm this happens if you nested the dropdown in view(s) but didn't follow the documented instructions on setting the parent view zIndex so that the dropdown isn't buried in the tree.

**Comment by ing-arriola** [comment]
> Hello @hossein-zare
> it was a zIndex conflict, thank you, it's now solved

How did you solve it? could you please share a code example?

**Comment by valeriashpiner** [comment]
I fixed it by putting zIndex: 1 for all parent views.

**Comment by Haris-Noori** [comment]
> Hello, Please create an expo snack and share it in order to reproduce the behavior.
> 
> Make sure you have `dropDownStyle={{backgroundColor: '#fff'}}` set.

**The problem is this issue occurs when you set direction on 'BOTTOM'**
I'm having the issue on iOS Simulator, not working on expo, I have react-native project
I set 
`dropDownDirection='BOTTOM'
  dropDownStyle={{backgroundColor: '#fff'}}`



![simulator_screenshot_6A4150C9-9A06-4ED1-8BC8-E88052438BCC](https://user-images.githubusercontent.com/31158492/177621005-7983b9fe-6bc9-4fad-9e22-af7646b61006.png)

**Comment by thangpq** [comment]
I FIXED this bug.!

SOLUTION 1:

- First you must understand reason: Bug opacity appear in code like below
`<View>
    <View>
      <DropDownPicker />
      <TextInput 1 />
   </View>
   <View>
     <TextInput 2 />
  </View>
<View>`

=> Because dropdownpicker not same level with textinput 2, it only same level with textinput 1 (bug opacity not appear with textinput 1), so now you understand what problem?
So in order to avoid that bug opacity we need design textinput same level view with dropdownpicker. like:
`<View>
    <View>
      <DropDownPicker />
      <TextInput 1 />
     <TextInput 2 />
  </View>
<View>`


SOLUTION 2:
set zIndex={1} to view contain dropdownpicker then everything resolved. 
I spent 1 day to fix that bug :( I REALLY HATE THAT BUG.

**Comment by oguzydz** [comment]
> Hello @hossein-zare it was a zIndex conflict, thank you, it's now solved

Hey @hossein-zare I am on version 5.4.4, it's same.

**Comment by oguzydz** [comment]
> I FIXED this bug.!
> 
> SOLUTION 1:
> 
> * First you must understand reason: Bug opacity appear in code like below
>   `<View> <View> <DropDownPicker /> <TextInput 1 /> </View> <View> <TextInput 2 /> </View> <View>`
> 
> => Because dropdownpicker not same level with textinput 2, it only same level with textinput 1 (bug opacity not appear with textinput 1), so now you understand what problem? So in order to avoid that bug opacity we need design textinput same level view with dropdownpicker. like: `<View> <View> <DropDownPicker /> <TextInput 1 /> <TextInput 2 /> </View> <View>`
> 
> SOLUTION 2: set zIndex={1} to view contain dropdownpicker then everything resolved. I spent 1 day to fix that bug :( I REALLY HATE THAT BUG.

This solution worked in my side, we need to ensure that other inputs must be in the same level.

**Comment by pritamparker** [comment]
I fixed by this approach 

```   
 <View style={{zIndex: 2}}>
          <PrimaryDropdown
            placeholder="Select"
            title="Gender"
            value={gender}
            items={genders}
            open={showGenderDropdown}
            setOpen={openGenderDropdown}
            setValue={setGender}
          />
 </View>
  <View style={{zIndex: 1}}>
          <PrimaryDropdown
            placeholder="Select"
            title="Educational qualification"
            value={qualification}
            items={qualifications}
            open={showQualificationDropdown}
            setOpen={openQualificationDropdown}
            setValue={setQualification}
          />
  </View>

**Comment by loupmasneri** [comment]
any updates on this ? (I've done the zIndex: 1 trick on every parent but not seems to be the cleanest approach)

**Comment by sleekLancelot** [comment]
> I fixed by this approach
> 
> ```
>  <View style={{zIndex: 2}}>
>           <PrimaryDropdown
>             placeholder="Select"
>             title="Gender"
>             value={gender}
>             items={genders}
>             open={showGenderDropdown}
>             setOpen={openGenderDropdown}
>             setValue={setGender}
>           />
>  </View>
>   <View style={{zIndex: 1}}>
>           <PrimaryDropdown
>             placeholder="Select"
>             title="Educational qualification"
>             value={qualification}
>             items={qualifications}
>             open={showQualificationDropdown}
>             setOpen={openQualificationDropdown}
>             setValue={setQualification}
>           />
>   </View>
> ```

Thanks, this solved the issue for me!

**Comment by juzero** [comment]
> I fixed by this approach
> 
> ```
>  <View style={{zIndex: 2}}>
>           <PrimaryDropdown
>             placeholder="Select"
>             title="Gender"
>             value={gender}
>             items={genders}
>             open={showGenderDropdown}
>             setOpen={openGenderDropdown}
>             setValue={setGender}
>           />
>  </View>
>   <View style={{zIndex: 1}}>
>           <PrimaryDropdown
>             placeholder="Select"
>             title="Educational qualification"
>             value={qualification}
>             items={qualifications}
>             open={showQualificationDropdown}
>             setOpen={openQualificationDropdown}
>             setValue={setQualification}
>           />
>   </View>
> ```

Thanks! It worked for me.

**Comment by prabukannan-dev** [comment]
I got this error because I had set height, hence it couldn't adjust the screen to dropdown size. Removing the height solved mine.


**With Height**
![Screenshot 2023-08-15 222614](https://github.com/hossein-zare/react-native-dropdown-picker/assets/65651901/65c82f4b-62f4-4149-b458-bff199b0eea8)


**Without Height**
![Screenshot 2023-08-15 222452](https://github.com/hossein-zare/react-native-dropdown-picker/assets/65651901/c6a15349-b404-41d7-a53d-4bcc65879db8)
