### ISSUE TITLE
Need help with setting DropdownPicker size

### ISSUE THREAD

**Issue by binhchili** [hossein-zare/react-native-dropdown-picker#321]
I have created a Picker component for my project

```jsx
const DropdownPicker = props => {

    const { containerStyle, pickerStyle, labelStyle, errorStyle, searchable, width, height, scrollHeight } = props;
 
    const [open, setOpen] = useState(false);
    const [value, setValue] = useState(field.value);
    const [items, setItems] = useState(itemList);

    return (
        <View style={containerStyle} >
            <View style={horizon && { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', }}>
                <Text style={[style.label, labelStyle]}>{label}</Text>
                <DropDownPicker style={{ width, height, ...pickerStyle, borderWidth: 1, borderColor: Colors.Gray, }} searchable={searchable}
                    dropDownContainerStyle={{ width, ...pickerStyle, borderWidth: 1, borderColor: Colors.Gray, }}
                    dropDownpickerStyle={{ marginTop: 0 }} maxHeight={height * 4} listMode={"SCROLLVIEW"}
                    placeholder='Chon'
                    open={open}
                    value={value}
                    items={items}
                    setOpen={setOpen}
                    setValue={setValue}
                    setItems={setItems}
                />
            </View>
            {errors[name] && <Text style={[style.error, errorStyle]}>{errors[name]?.message}</Text>}
        </View>

    )
}

```

And put it into my form :

```jsx

const MyForm = ()=>{
 return (
        <FormProvider {...formMethods}>
            <View style={style.myForm}}>
                <DropdownPicker name='maKTV' label='Mã kiểm tra viên:' width={SCREEN_WIDTH / 1.6} height={height:SCREEN_HEIGHT / 15}
                    containerStyle={{ width: SCREEN_WIDTH / 1.2, height:SCREEN_HEIGHT / 15 }} itemList={maKTV_list} pickerStyle={{ zIndex: 20,  }} horizon />

                <SectionHeader containerStyle={style.sectionHeader} title='Nhập thông tin yêu cầu' textStyle={{ marginLeft: 15, fontSize: 14 }} />

                <DropdownPicker name='hinhThucNhan' label='Hình thức nhận:' width={style.input.width} height={style.input.width / style.input.aspectRatio}
                    containerStyle={{ marginLeft: 65, marginBottom: 5 }} horizon itemList={hinhThuc_list} pickerStyle={{ zIndex: 10, marginLeft: 40 }} />

             ....
            </View>
        </FormProvider>
    )
}

```

  The problem is when I specify the `width` and `height` of the container (the first `DropdownPicker`) , the dropdown part of picker cannot be interactable because it's outside of the container.  So I come up with the second solution is making the container style depends on child component (the second one) and it works. However in this solution I cannot align the item by using `justifyContent` or `alignItems` like the first one, and I have to change lots of margin style to align them perfectly. I already thought the third solution is make the container size covers all the dropdown part, but when the dropdown close it will create a  blank area between the picker and the input below that I don't want to. Can someone help me to overcome this problem.  Sorry I cannot create Snack cause I'm not familar with it.

For easy understand here is my form and my input picker using the second solution (sorry my app isn't translated to English ) : 
![Screenshot_1621435905](https://user-images.githubusercontent.com/69777410/118834505-77678e00-b8ec-11eb-941f-601552a832a4.png)

![Screenshot_1621435916](https://user-images.githubusercontent.com/69777410/118834536-7b93ab80-b8ec-11eb-8972-d062317f7ce4.png)

**Comment by hossein-zare** [comment]
Hello,

You have to create a snack for your issue or i can't help you, It's pretty easy just like React Native.
