### ISSUE TITLE
Adding custom text for empty list

### ISSUE THREAD

**Issue by Jumpis** [hossein-zare/react-native-dropdown-picker#323]
Empty list text is fixed with supported language only.
I have added custom text for empty list.
Please check the PR #322

**Comment by hossein-zare** [comment]
Hello,
You could use the `translation` property.
```jsx
translation={{
  NOTHING_TO_SHOW: "There's nothing to show!"
}}
```

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/localization#change-the-translation

**Comment by Jumpis** [comment]
thanks!!
