### ISSUE TITLE
dropdown items list gets buried under the another [Android]

### ISSUE THREAD

**Issue by ahmedrowaihi** [hossein-zare/react-native-dropdown-picker#324]
please guys help me with this how can I make it on the top of all other dropdowns?

![Screenshot_3](https://user-images.githubusercontent.com/67356781/119010795-a7954800-b951-11eb-9944-426fc7f5d6c7.png)
![Screenshot_4](https://user-images.githubusercontent.com/67356781/119010811-abc16580-b951-11eb-941b-e6395913a20f.png)

**Comment by hossein-zare** [comment]
Hello,

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers

**Comment by hossein-zare** [comment]
Hello,

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers

**Comment by ahmedrowaihi** [comment]
> Hello,
> 
> https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers

Thank you so much brother Hossein may Allah bless you
