### ISSUE TITLE
display in more lines when i select many items

### ISSUE THREAD

**Issue by TonyFTannous** [hossein-zare/react-native-dropdown-picker#325]
Please how can display many selected items in more than one line, because the display is linear

**Comment by hossein-zare** [comment]
Hello,
Please explain more about your issue, Create a snack if possible.

**Comment by TonyFTannous** [comment]
![image](https://user-images.githubusercontent.com/33982255/119102597-de875e80-ba22-11eb-9ab8-f82a5bce53d4.png)

*** i need the hidden selected items to be bellow each others and not wraped with the scroll

**Comment by hossein-zare** [comment]
Unfortunately it's impossible. You have to make changes to the package yourself.
