### ISSUE TITLE
Searching substrings yield existing result and new item cannot be added

### ISSUE THREAD

**Issue by aravi365** [hossein-zare/react-native-dropdown-picker#326]
For example, if we have items named Application,Apples,Banana in the list and if we search for App, then we'll be getting Apples and Application. But in this case we'll not be able to add the item App in to the list.
Is there any way to handle this case or is it a bug?

<img width="448" alt="Screenshot 2021-05-21 at 2 05 42 PM" src="https://user-images.githubusercontent.com/15327129/119108251-a3465900-ba3d-11eb-9569-8c83bece1551.png">

Expected behaviour: 
An option to add App to the items as App as a string is not a match in the set of items.

**Comment by hossein-zare** [comment]
Hello,

I'll add the feature in the next version.
Thanks for reporting.

**Comment by aravi365** [comment]
`ExceptionsManager.js:179 Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

Error after upgrading to the latest version from "^5.1.15
