### ISSUE TITLE
measureInWindow issue (expo latest)

### ISSUE THREAD

**Issue by dijibiz** [hossein-zare/react-native-dropdown-picker#328]
[Unhandled promise rejection: TypeError: undefined is not a function (near '...pickerRef.current.measureInWindow...')]

package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/preset-env": "^7.13.15",
    "@babel/preset-react": "^7.13.13",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "@reduxjs/toolkit": "^1.5.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.25.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-react": "^7.23.2",
    "expo": "~41.0.1",
    "expo-status-bar": "~1.0.4",
    "galio-framework": "^0.8.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-country-picker-modal": "^2.0.0",
    "react-native-dropdown-picker": "^5.1.16",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.0.0",
    "react-native-searchable-dropdown": "^1.1.3",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.13.16",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "typescript": "~4.0.0"
  },
  "private": true
}

```

**Comment by asalha** [comment]
I am having the same problem. It happened when I updated to the latest version of this picker.

<img width="865" alt="WindowsTerminal_2RX8VkJV4r" src="https://user-images.githubusercontent.com/4199314/119383674-7c279b80-bc78-11eb-9042-dfe204289b5a.png">

**Comment by nikpaolillo** [comment]
i'm back to 5.0 version and works, same problem with 5.1

sorry for my english :(

**Comment by hossein-zare** [comment]
Hello,

The bug has been fixed. (**v5.1.17**)
Thanks for reporting.

**Comment by nikpaolillo** [comment]
> Hello,
> 
> The bug has been fixed. (**v5.1.17**)
> Thanks for reporting.

Hello! 

![image](https://user-images.githubusercontent.com/17077141/119420627-511e6580-bcd3-11eb-8bd8-b1cbaf3aef70.png)

**Comment by hossein-zare** [comment]
@nikpaolillo 

**Run the following command:**
```
npm start -- --reset-cache
```
Press **`CTRL + C`** if you see **`warning: the transform cache was reset.`**

**Now run your app:**
```
npx react-native run-android
```

**Comment by nikpaolillo** [comment]
> @nikpaolillo
> 
> **Run the following command:**
> 
> ```
> npm start -- --reset-cache
> ```
> 
> Press **`CTRL + C`** if you see **`warning: the transform cache was reset.`**
> 
> **Now run your app:**
> 
> ```
> npx react-native run-android
> ```

thanks so much! the new version works perfect
