### ISSUE TITLE
Multiple Picker dropdown gets hidden below another Picker component in Android 

### ISSUE THREAD

**Issue by sudhirkumarojhaa** [hossein-zare/react-native-dropdown-picker#33]
**Describe the bug**
When the dropdown is opened. It gets behind another picker component below it.

**To Reproduce**
<DropDownPicker
        items={data}
        placeholder={title}
        containerStyle={inlineStyles.container}
        labelStyle={inlineStyles.label}
        style={inlineStyles.box}
        zIndex={3000}
      />
<DropDownPicker
        items={genderData}
        placeholder={title}
        containerStyle={inlineStyles.container}
        labelStyle={inlineStyles.label}
        style={inlineStyles.box}
        zIndex={2000}
      />
Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**
the visible dropdown should override every other component

**Screenshots**

Supposed to work like this in both platforms
iOS screenshot

![Screenshot 2020-06-18 at 6 24 07 PM](https://user-images.githubusercontent.com/24911219/85022507-07f39680-b191-11ea-8755-0d4c72ebaa12.png)

Works like this in Android which is an issue

![Screenshot 2020-06-18 at 6 21 47 PM](https://user-images.githubusercontent.com/24911219/85022225-a2070f00-b190-11ea-83de-5482caacbb0f.png)

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
Hello,

Please read **zIndex conflicts**.
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by hossein-zare** [comment]
#32

**Comment by kaurrJaspreet** [comment]
I am still getting this issue

**Comment by kaurrJaspreet** [comment]
anyone can share the sample code please?

**Comment by hossein-zare** [comment]
Hello @jaspreetjk 
https://snack.expo.io/@hossein-zare/823437

If this doesn't help you, You can share your own code snippet with the `containerStyle` prop.

**Comment by turch** [comment]
@hossein-zare
https://snack.expo.io/4PUy_IzLh

Your snippet, modified to show the bug.

**Comment by hossein-zare** [comment]
@turch 
> **DropDownPicker wrapped by `<View style={{backgroundColor: '...'}}>`**
> Remove the backgroundColor from the parent element.
> https://github.com/hossein-zare/react-native-dropdown-picker/issues/40#issuecomment-651744446

> **Multiple Pickers**
> `<DropDownPicker zIndex={5000} />`
> `<DropDownPicker zIndex={4000} />`
> `<DropDownPicker zIndex={3000} />`

```javascript
<View
    style={{
        ... // No backgroundColor

        ...(Platform.OS !== 'android' && {
            zIndex: 20
        })
    }}
>
    <DropDownPicker ... />
</View>
<View
    style={{
        ... // No backgroundColor

        ...(Platform.OS !== 'android' && {
            zIndex: 10
        })
    }}
>
    <DropDownPicker ... />
</View>
```

https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by turch** [comment]
Ah my bad, I saw the thing about the background color but missed the increasing zIndex.

From reading some other issue report, not being able to use background color is a React Native issue, correct?

**Comment by hossein-zare** [comment]
Yes, There are some other properties that cause unexpected behaviors.

**Comment by sudhirkumarojhaa** [comment]
Hi Hoseein

I have integrated the Dropdown picker in the flatlist so it is rendering it multiple times. In the android the dropdown overalps with the rest of the content which is not dropdown. I have added all the zindex and others which are laid in the REadme. Can you help

**Comment by yogendrajs** [comment]
hi @hossein-zare, I see how zIndex works for multiple pickers at this page - https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers
but, if a dropdowns is dependent on another dropdown (where disabled prop is being used), zIndex & zIndexInverse don't seem to work for me, can you please help?
