### ISSUE TITLE
Dropdown list mode "Modal" can't select item

### ISSUE THREAD

**Issue by FashionCStar** [hossein-zare/react-native-dropdown-picker#331]
```
              <DropDownPicker
                open={isCountryOpen}
                listMode="MODAL"
                placeholder=""
                searchable={true}
                items={countryList}
                value={country}
                itemKey="value"
                containerStyle={{ height: 40 }}
                textStyle={{ fontSize: 20 }}
                style={{ borderRadius: 0, borderWidth: 0, borderBottomWidth: 1, borderBottomColor: '#cad4db' }}
                setOpen={() => this.setState({ isCountryOpen: true })}
                onClose={() => this.setState({ isCountryOpen: false })}
                setValue={(callback) => this.setState(state => ({ country: callback(state.country) }))}
                onChangeValue={(country) => this.onChangeCountry(country)}
              />
```

I have upgraded to v5.1.17 and got this issue.
When I change the listMode to "Flatlist" or "Default", I can select the item, but with "Modal", I cant select item.

**Comment by randspace0** [comment]
Which version you're using before? I had the same issue and I want to rollback the version

**Comment by FashionCStar** [comment]
I used v5.1.16 before and v5.1.16 had measureInWindow issue, so I upgraded to the latest version

**Comment by hossein-zare** [comment]
Hello,

was v5.1.16 working fine?

**Comment by FashionCStar** [comment]
v5.1.15 worked properly, but v5.1.16 & v5.1.17 not working well

I just tried with v5.1.15 and it's not working with "Modal" list mode...

:(

**Comment by hossein-zare** [comment]
@FashionCStar @andraantariksa 
Please install **v5.1.19**.

**Comment by FashionCStar** [comment]
@hossein-zare , v5.1.19 work properly...

Thanks

**Comment by tomzhou87** [comment]
I used v5.1.19，ios is work properly，but android not work properly...

**Comment by tomzhou87** [comment]
> @hossein-zare , v5.1.19 work properly...
> 
> Thanks

I used v5.1.19，ios work properly，but android it's not work properly...
