### ISSUE TITLE
Error: Unable to resolve module `constants`

### ISSUE THREAD

**Issue by marconett** [hossein-zare/react-native-dropdown-picker#334]
Hi, the package broke with the following commit: https://github.com/hossein-zare/react-native-dropdown-picker/commit/221b3d3b39a6697fe1b9fb169cf85804a46b6ee0#diff-061558149a9afd5e198ceb1803a0e9a3a03ae303060dc10f4121095d446213d9R1

It tries to resolve `constants` as a package, rather than the folder. Needs to be changed to `../constants`.

**Comment by hossein-zare** [comment]
Hello,

Thanks for reporting.
I fixed the broken import.

**v5.1.19**
