### ISSUE TITLE
Does not seem to work with react-navigation/stack

### ISSUE THREAD

**Issue by sfouser1** [hossein-zare/react-native-dropdown-picker#338]
I used the component in a simple project on IoS and it seems to work fine.

In a different project, where I use the following two components, 
---
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
----
the component doesn't seem to work.
These are the additional components I use in this project, and it doesn't seem to be compatible.

Doesn't work with setOpen and setValue.
The component is visible when the open state is true. But fails when I start with 'open' state as false.
When I click on the component to dropdown/open, it creates the following exception.
"Possible Unhandled Promise Rejection (id: 12):
TypeError: undefined is not a function (near '...pickerRef.current.measureInWindow...')". 

This is on IoS.
Please help.

**Comment by hossein-zare** [comment]
Hello,

Upgrade to v5.1.19.

**Comment by sfouser1** [comment]
That's the version I use.

 "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "expo": "~41.0.1",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    **"react-native-dropdown-picker": "^5.1.19",**
    "react-native-gesture-handler": "^1.10.3",
    "react-native-keychain": "^7.0.0",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.0.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },

**Comment by hossein-zare** [comment]
If your issue is related to https://github.com/hossein-zare/react-native-dropdown-picker/issues/248, I'm sorry.

If not, Send me your code.

Don't forget to reset cache:
```
npm start -- --reset-cache
```

**Related issues**
#328 measureInWindow issue (expo latest)
#248 Bug: dropdowns fall behind other content in react-navigation draw menu components

**Comment by sfouser1** [comment]
@hossein-zare Thank you!
The reset-cache command you had asked fixed the issue magically.
What does that do!?

**Comment by hossein-zare** [comment]
@sfouser1 There was a `measureInWindow` bug in older versions which was cached in your app. NodeJS couldn't refresh the package. That's it.

You'll need the command in the future for other apps/packages, Write it down somewhere!

**Comment by sfouser1** [comment]
Yes, I already have it in my checklist - just started my first real app with React Native.
Thank you for your contribution.

**Comment by bayramn** [comment]
It still doesn't work for me.

    "dependencies": {
        "@babel/preset-typescript": "^7.18.6",
        "@react-native-async-storage/async-storage": "^1.17.10",
        "@react-native-masked-view/masked-view": "0.2.7",
        "@react-navigation/bottom-tabs": "^6.4.0",
        "@react-navigation/drawer": "^6.5.0",
        "@react-navigation/native": "^6.0.13",
        "@react-navigation/native-stack": "^6.9.0",
        "@react-navigation/stack": "^6.3.1",
        "axios": "^1.0.0",
        "eas-cli": "^2.2.0",
        "expo": "^46.0.14",
        "expo-application": "~4.2.2",
        "expo-auth-session": "~3.7.1",
        "expo-build-properties": "~0.3.0",
        "expo-constants": "~13.2.4",
        "expo-dev-client": "~1.3.0",
        "expo-dev-menu": "^1.3.0",
        "expo-fast-image": "^1.1.3",
        "expo-file-system": "~14.1.0",
        "expo-firebase-analytics": "~7.2.0",
        "expo-font": "~10.2.0",
        "expo-haptics": "~11.3.0",
        "expo-image-manipulator": "~10.4.0",
        "expo-localization": "~13.1.0",
        "expo-notifications": "~0.16.1",
        "expo-random": "~12.3.0",
        "expo-splash-screen": "~0.16.2",
        "expo-status-bar": "~1.4.0",
        "expo-updates": "~0.14.6",
        "expo-web-browser": "~11.0.0",
        "highlight-words-core": "^1.2.2",
        "onesignal-expo-plugin": "^1.1.2",
        "prop-types": "^15.8.1",
        "react": "18.0.0",
        "react-dom": "18.0.0",
        "react-native": "0.69.6",
        "react-native-dropdown-picker": "^5.4.2",
        "react-native-elements": "^3.4.2",
        "react-native-gesture-handler": "~2.5.0",
        "react-native-highlight-words": "^1.0.1",
        "react-native-modal": "^13.0.0",
        "react-native-onesignal": "^4.4.1",
        "react-native-popup-menu": "^0.16.1",
        "react-native-reanimated": "~2.9.1",
        "react-native-safe-area-context": "4.3.1",
        "react-native-screens": "~3.15.0",
        "react-native-svg": "12.3.0",
        "react-native-vector-icons": "^9.2.0",
        "react-native-version-check": "^3.4.3",
        "react-native-view-shot": "3.3.0",
        "react-native-web": "~0.18.7",
        "react-native-webview": "11.23.0",
        "react-native-youtube-iframe": "^2.2.2",
        "react-navigation": "^4.4.4",
        "uninstall": "^0.0.0"
      },
