### ISSUE TITLE
unrecognized font 'family Feather'

### ISSUE THREAD

**Issue by ravi123saxena** [hossein-zare/react-native-dropdown-picker#34]
**Describe the bug**
unrecognized font family Feather

I have installed react-native-dropdown-picker. and integrate the Dropdown component in my app.
but when i run react-native run-ios. Getting error 'unrecognized font family Feather'. 
Even i installed npm i react-native-vector-icon , still having the same issue. Please help !!!!

**Comment by hossein-zare** [comment]
#8

**Comment by BenHurMartins** [comment]
solution:

```
import Feather from "react-native-vector-icons/Feather";
Feather.loadFont();
```

I did the code above and worked for me
