### ISSUE TITLE
Bug listings items on multiple dropdowns

### ISSUE THREAD

**Issue by felixmois** [hossein-zare/react-native-dropdown-picker#340]
ENV:
"react-native-dropdown-picker": "^4.0.9",
"react-native": "0.63.4",

Description:
I have 2 dropdowns in a modal.
If I open the first one everything is ok, is displaying the item over the 2nd dropdown items.
If I'm opening the second one, again, is display the items over the first one.
The problem is after the 2nd one was opened, the first one will display the items under the 2nd one.

`
<SafeAreaContext
      style={styles.modalStyle}>
      <DropDownPicker
        containerStyle={{ height: 57, marginVertical: 10, zIndex: 0 }}
        items={categories}
        itemStyle={styles.dropdown}
        defaultValue={1}
        globalTextStyle={styles.globalTextStyle}
        zIndex={30}
        multiple
        // onChangeItem={(item, index) => onChange(item, index)}
      />
      <DropDownPicker
        containerStyle={{ height: 57, marginVertical: 10 }}
        items={dropdownItems}
        itemStyle={styles.dropdown}
        defaultValue={1}
        globalTextStyle={styles.globalTextStyle}
        zIndex={20}
        // zIndexInverse={40}
        // onChangeItem={(item, index) => onChange(item, index)}
      />
      <Button
        text="Apply filters"
      />
    </SafeAreaContext>;
`

![image](https://user-images.githubusercontent.com/57527104/119943803-329ebf80-bf9c-11eb-9ddc-5c6fb2b015a1.png)

![image](https://user-images.githubusercontent.com/57527104/119943678-05eaa800-bf9c-11eb-85ed-b8011c8479ac.png)

![image](https://user-images.githubusercontent.com/57527104/119943627-f5d2c880-bf9b-11eb-9b35-f0dc74ce465b.png)
![image](https://user-images.githubusercontent.com/57527104/119943641-fbc8a980-bf9b-11eb-87b3-af15693098e0.png)
![image](https://user-images.githubusercontent.com/57527104/119943659-008d5d80-bf9c-11eb-9b28-7a7e421b3a02.png)

**Comment by hossein-zare** [comment]
Hello,

Upgrade to the latest version (v5.1.19)
https://hossein-zare.github.io/react-native-dropdown-picker-website/
