### ISSUE TITLE
Re-render dropdown 

### ISSUE THREAD

**Issue by moustafahelmi96** [hossein-zare/react-native-dropdown-picker#341]
Can't display new "items" after modifying the items array because the dropdown is not rendering while either change of the items state array or by typing in the search bar

<img width="356" alt="Screen Shot 2021-05-30 at 10 53 09 PM" src="https://user-images.githubusercontent.com/51541292/120119793-02247480-c19a-11eb-920b-57d8a87c964a.png">

<img width="581" alt="Screen Shot 2021-05-30 at 10 53 26 PM" src="https://user-images.githubusercontent.com/51541292/120119800-08b2ec00-c19a-11eb-91f9-e54af3eadb05.png">

**Comment by hossein-zare** [comment]
Hello,

There's no `onSearch` property.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/search#onchangesearchtext

`onChangeSearchText` and `disableLocalSearch` are what you need.
