### ISSUE TITLE
DropDown background transparent

### ISSUE THREAD

**Issue by bala2explore** [hossein-zare/react-native-dropdown-picker#343]
How to set modal background as transparent and want to show the picker as dialog like style.
![2021-06-02 10_59_55-Window](https://user-images.githubusercontent.com/16302598/120428806-f56a7100-c391-11eb-8c20-79adee9b4535.png)

**Comment by bala2explore** [comment]
How to set 
![Uploading 2021-06-02 10_59_55-Window.png…]()

**Comment by hossein-zare** [comment]
Hello,

https://snack.expo.io/cyDmOE9vX
