### ISSUE TITLE
Nothing happening after clicking DropDownPicker on Android

### ISSUE THREAD

**Issue by irfanismaya20** [hossein-zare/react-native-dropdown-picker#344]
Can't click DropDownPicker on android but on ios working

**Comment by harrykok** [comment]
Hi there, i'm facing the same issue. The code runs perfectly in an expo snack, and even when the attributes like backgroundColor are removed, the dropdown elements still cannot be clicked

**Comment by hossein-zare** [comment]
Hello @irfanismaya20 @harrykok ,

Please provide full component code.

**Comment by mohammadrahmanian** [comment]
I think it is the same issue reported here: https://github.com/hossein-zare/react-native-dropdown-picker/issues/351

**Comment by the-smart-home-maker** [comment]
I guess also the same as #362

**Comment by uzmanzawahir** [comment]
I'm having the same issue too. Dropdowns work fine on ios but are unresponsive on android

**Comment by jbaptistadev** [comment]
any solution for this?

**Comment by mikehardy** [comment]
No one provided an example here so speculation is useless and no attempt to help may be attempted
I think #351 has more information with a couple possible ideas to fix. 
Resolving as dupe in favor of 351
