### ISSUE TITLE
Showing Validation Error for SetValue - ReactNative Typescript

### ISSUE THREAD

**Issue by snevula123456** [hossein-zare/react-native-dropdown-picker#346]
I am Using ReactNative TypeScript for the Dropdown picker. I am facing a Type Error for the SetValue, tried with string and array of objects, but still the same. Why is this? I have tried to find the solution for this, but unfortunately couldn't able to find it. Attaching the screenshot for the ref.

[https://lh3.googleusercontent.com/-G7U_1w_qNuo/YLSNPggvHyI/AAAAAAAAD8Q/G7xWahwqmXci0FKz8QvyaHxYwDb7GOkZACJEEGAsYHg/s0/2021-05-31.png?authuser=0]

[https://lh3.googleusercontent.com/-PcZGXJEjYQY/YLSNSzoJEZI/AAAAAAAAD8U/rmQdd_eLYeoiuK_P2ur9dbSGBWrJaiH4gCJEEGAsYHg/s0/2021-05-31.png?authuser=0](url)

languages: [
			{ label: "US", value: "US" },
			{ label: "UK", value: "UK" },
			{ label: "FRENCH", value: "FRENCH" },
			{ label: "GERMAN", value: "GERMAN" },
		],

<DropDownPicker
                        style={subscriptionOrderStyles.countryContainer}
                        dropDownContainerStyle={subscriptionOrderStyles.dropDownContainer}
                        placeholderStyle={subscriptionOrderStyles.countryPlaceHolder}
                        textStyle={subscriptionOrderStyles.dropDownTextStyle}
                        placeholder="Country"
                        dropDownDirection="AUTO"
                        showTickIcon={false}
                        showArrowIcon={true}
                        ArrowDownIconComponent={() => (
                            <Image
                                source={require("../assets/Vectordropdown.png")}
                                style={subscriptionOrderStyles.arrowIconStyles}
                            />
                        )}
                        ArrowUpIconComponent={() => (
                            <Image
                                source={require("../assets/Vectordropdown.png")}
                                style={subscriptionOrderStyles.arrowIconStyles}
                            />
                        )}
                        open={open}
                        value={value}
                        items={items}
                        setOpen={setOpen}
                        setValue={(val: string) => setValue(val)}
                        setItems={setItems}
                    />

**Comment by thimtkfkd05** [comment]
Hello, I found a way to avoid that type error. Try this:
`setValue={callback => setValue(callback as any)}`

The type of setValue property is function (callback: (value: string) => string) => void.
Return value of callback is changed value, so you just need to execute your setValue action with returned value from callback.
I think the main problem is, react type check doesn't think that string is a member of ValueType, then I put `as any` into the back of callback, although type `ValueType = string | number | undefined`.
If anyone who knows the reason why react type check acts like this is here, please let me know..!

**Comment by hossein-zare** [comment]
Hello,
Why would you do `setValue={(val: string) => setValue(val)}`? `setValue={setValue}` is enough!

**Alternative method:**
```jsx
setValue={callback => {
  setValue(state => callback(state));
}}
```

**Comment by thimtkfkd05** [comment]
@hossein-zare 
`setValue={setValue}` isnt enough in typescript, and your another method also not enough. :(

Type checker said "'ValueType | ValueType[] | null' type cannot be assigned in 'string' type." and "'null' type cannot be assigned in 'string' type."

I cannot understand why ValueType cannot be assigned in string.

**Comment by snevula123456** [comment]
I solved the issue by setting value type as any

	// DropDown SetValue Handler
	const handleDropDownChange = (val: any) => {
		setValue(val);
	};

setValue={(value) => handleDropDownChange(value)}

Thanks.

**Comment by hossein-zare** [comment]
@snevula123456 @thimtkfkd05  What version are you using?

**Comment by thimtkfkd05** [comment]
@hossein-zare I'm using 5.1.19 version with RN 0.64.0 && typescript 3.8.3

**Comment by hossein-zare** [comment]
@thimtkfkd05 `"typescript": "^4.2.4"` required in devDependencies.

**Comment by hossein-zare** [comment]
You should also upgrade to **v5.1.21**.
