### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton

### ISSUE THREAD

**Issue by ravirupareliya** [hossein-zare/react-native-dropdown-picker#348]
It shows me this error when trying to use with react navigation.

Not sure what is the exact issue and how to resolve it. Initially project was in Expo but now it has been converted to react-native-cli so I do have react-native-gesture-handler in package.json

![Simulator Screen Shot - iPhone 11 - 2021-06-05 at 10 40 36](https://user-images.githubusercontent.com/17959204/120880854-7b80f480-c5ea-11eb-8efe-a7ebefe6c3bc.png)

**Comment by dale-french** [comment]
Yup - same issue my side when using `react-navigation` and `react-native-gesture-handler`

**Comment by nir102030** [comment]
Same issue for me. I'm using `expo` + `react-navigation` + `react-native-gesture-handler`

**Comment by hossein-zare** [comment]
Hello,

Do the following steps:
### + in `./node_modules/react-native-dropdown-picker/src/components/RenderBadgeItem.js`
  **1. Remove:**
https://github.com/hossein-zare/react-native-dropdown-picker/blob/b6bfcc3241dcc04139ad5740b16b2466c641c0a5/src/components/RenderBadgeItem.js#L10
  **2. Import `TouchableOpacity` from `react-native`**

---

### + in `./node_modules/react-native-dropdown-picker/src/components/RenderListItem.js`
  **1. Remove:**
https://github.com/hossein-zare/react-native-dropdown-picker/blob/b6bfcc3241dcc04139ad5740b16b2466c641c0a5/src/components/RenderListItem.js#L12-L14

  **2. Remove:**
https://github.com/hossein-zare/react-native-dropdown-picker/blob/b6bfcc3241dcc04139ad5740b16b2466c641c0a5/src/components/RenderListItem.js#L156-L160

  **3. Replace `_TouchableOpacity` with `TouchableOpacity`:**
https://github.com/hossein-zare/react-native-dropdown-picker/blob/b6bfcc3241dcc04139ad5740b16b2466c641c0a5/src/components/RenderListItem.js#L163-L169

---

If the error is gone, Let me know to release the bugfix.

**Comment by nir102030** [comment]
That solved the problem. Thanks!

**Comment by dale-french** [comment]
@hossein-zare that fixed the problem for me too - please release the update. Thanks!

**Comment by hossein-zare** [comment]
I just released **v5.1.20**
