### ISSUE TITLE
tap outside to close with controller prop and refs not working anymore, was working with previous version

### ISSUE THREAD

**Issue by rohandavid** [hossein-zare/react-native-dropdown-picker#349]

**Comment by rohandavid** [comment]
https://snack.expo.io/@dcangulo/close-dropdown-on-outside-click
this is the solution i followed and it was working fine until i upgraded to the latest version
and now i get an error : null is not an object evaluating dropDownRef.current.close
 ( dropDownRef=the ref i have given to the picker)

**Comment by hossein-zare** [comment]
Hello,

In the new version we don't have controllers.

```jsx
function App() {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState(null);
  const [items, setItems] = useState([
    {label: 'Apple', value: 'apple'},
    {label: 'Banana', value: 'banana'}
  ]);

  return (
    <TouchableWithoutFeedback onPress={() => setOpen(false)}>
      <DropDownPicker
        open={open}
        value={value}
        items={items}
        setOpen={setOpen}
        setValue={setValue}
        setItems={setItems}
      />
    </TouchableWithoutFeedback>
  );
}
```

**Usage:** https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage

**Comment by hossein-zare** [comment]
I just noticed that you are using v3.6.8 and also the provided snack works well.

**Comment by kaialsh705** [comment]
not work.

**Comment by rohandavid** [comment]
hi @hossein-zare your solution worked thanks
