### ISSUE TITLE
How to set initial value on screen load

### ISSUE THREAD

**Issue by SomnathKadam** [hossein-zare/react-native-dropdown-picker#353]
Hi, how to set value initial value on screen load, as below example, Need to set "BSNL" as default value

If data(items) is pulled from API, using useEffect and once data pulled successfully we set value to second last value like below example

```
const [open, setOpen] = useState(false);
const [value, setValue] = useState(null);
const [items, setItems] = useState([
        { value: 'Airtel', label: 'Airtel' },
        { value: 'BSNL', label: 'BSNL' },
        { value: 'VI', label: 'VI' }
    ]);
```

```
useEffect(() => {
//   data taken from api
  setItems(data);
}, []);
```

`<DropDownPicker
                    items={items}
                    open={open}
                    setOpen={setOpen}
                    value={value}
                    setValue={setValue} /> `

**Comment by hossein-zare** [comment]
Hello,

```jsx
const [value, setValue] = useState("BSNL");
```

**Comment by gessic-apps** [comment]
@hossein-zare  That deoesn't seem to work for me...I set Value and it's always showing as "select an item"

`

    const [value, setValue] = useState('defaultValue');`
 

          <DropDownPicker
                style={defaultStyles.picker} 
                dropDownContainerStyle={defaultStyles.dropdownStyle}
                open={open}
                labelStyle={defaultStyles.dropDownLabels}
                listItemLabelStyle={defaultStyles.dropDownLabels}
                arrowIconStyle={{
                    width: 20,
                    height: 20,
                  }}
                value={value}
                maxHeight={200}
                items={playerProfiles}
                searchable={false}
                setValue={updateProfile}
                // @ts-ignore
                setItems={setPlayerProfiles}
                // @ts-ignore
                setOpen={setOpen}
                />
`

**Comment by kfiggins** [comment]
I'm seeing similar behavior with the single dropdown picker. The initial value exists and if you open the dropdown the correct value is checked, but it's showing the placeholder on the outside instead of the initial value.

![Screen Shot 2021-06-08 at 1 00 04 PM](https://user-images.githubusercontent.com/15788098/121227505-a45af100-c859-11eb-92d8-f34c22d6ee34.png)

Note: It works as intended for my multi-dropdown picker.

**Comment by hossein-zare** [comment]
I just released **v5.1.21**, a Bugfix for the reported bug.

**Comment by SomnathKadam** [comment]
Found issue, 

if value has single datatype, then it work perfectly like 

`{ value: 'Airtel', label: 'Airtel' }`

,but value has complex datatype, like below, then issue 

`{ value: {Name:'Airtel', OpID:3}, label: 'Airtel' }`

**Comment by hossein-zare** [comment]
@SomnathKadam `value` cannot contain `objects`, only `string` `number` `boolean` values are valid.

**Comment by nara15** [comment]
@SomnathKadam I faced the issue. Please check that your data used within the useEffect is not null or undefined.

**Comment by ZentPeople** [comment]
I am facing the same issue. Is there any workaround for this?

**Comment by jjpeeradech** [comment]
try JSON.stringify for value
![image](https://user-images.githubusercontent.com/54398185/124378590-6926d300-dcdc-11eb-9c72-61f0a3bd7d65.png)
