### ISSUE TITLE
Error on dropdown openning : JSON Value '15' of type NString cannot be converted (IOS)

### ISSUE THREAD

**Issue by AntoineJonard** [hossein-zare/react-native-dropdown-picker#354]
**Description**

When i open the drop down to change the current value i get :

![image0](https://user-images.githubusercontent.com/60439431/121077518-ffe49a80-c7d7-11eb-8ac4-94624d9ec9ec.png)

Still the dropped container appears and i can update the value in my state by choosing a new value. So it seems the error has no direct impact on the execution.

**My Code**

`
        constructor(props){
            super(props)
                        
            this.state = {
                open: false,
                value: 'day',
                items: [
                    {label: 'Tous les jours', value: 'day'},
                    {label: 'Toutes les semaines', value: 'week'},
                    {label: 'Tous les mois', value: 'month'}
                ],
            };
          }

    setValue(callback) {
        this.setState(state => ({
            value: callback(state.value),
        }));
    }

    setItems(callback) {
        this.setState(state => ({
            items: callback(state.items)
        }));
    } 
`
The dropdown picker :

`   <DropDownPicker
    style={styles.dropDownPicker}
    containerStyle={styles.selectContainer}
    dropDownContainerStyle={styles.dropDownContainer}
    selectedItemContainerStyle={{
        flex:1,
        flexDirection: "row",
    }}
    selectedItemLabelStyle={{
        fontWeight: "bold",
        color: '#1253bc',
    }}
    listItemLabelStyle={{
        padding: 6,
    }}
    open={open}
    value={value}
    items={items}
    setOpen={(open)=>this.setState({open})}
    setValue={this.setValue.bind(this)}
    setItems={this.setItems.bind(this)}
    itemSeparator={true}
/>
`

**Comment by hossein-zare** [comment]
Hello,

Everything seems to be fine, Check your styles.
I think you've wrapped a 15 with single quotation marks in your styles.

**Example:**
```jsx
myStyle: {
  width: '15' // must be: width: 15
}
```

**Comment by AntoineJonard** [comment]
Hello,

Thanks for this quick response, the error was indeed coming from the css.
Sorry for bothering you for that, but i was kind of stuck on it :).
