### ISSUE TITLE
controller.reset() is undefined

### ISSUE THREAD

**Issue by MahiBuger** [hossein-zare/react-native-dropdown-picker#357]
```
 <DropDownPicker
            containerStyle={Styles.dropDownContainer}
            style={Styles.dropDown}
            itemStyle={Styles.dropDownItem}
            labelStyle={Styles.dropDownLabel}
            selectedLabelStyle={Styles.dropDownLabel1}
            placeholderStyle={Styles.dropDownPlaceHolder}
            onChangeItem={item => _onChange(item.value)}
            zIndex={100}
            zIndexInverse={100}
            {...props}
            controller={instance => controller= instance}
        />
```

I got some instance in controller. But there is no function called reset(). It was undefined. I want to clear selected label in dropdown.

**Comment by hossein-zare** [comment]
Hello,

The `controller` prop has been removed in v5.x.
You should migrate to v5.x (https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage)

**Comment by MahiBuger** [comment]
@hossein-zare I'm ready to move v5.x. How can i reset selected label.

In my case, initially dropDown loaded with some items and one was selected. Then items are changed to empty, here i want to clear selected value. So how can i do this in v5.x?

**Comment by hossein-zare** [comment]
It's pretty simple.

```jsx
const [value, setValue] = useState("fr");

// Reset
setValue(null);
```

**Comment by MahiBuger** [comment]
@hossein-zare Thank you. It's working.
