### ISSUE TITLE
Dropdown isn't working / Unable to select items .

### ISSUE THREAD

**Issue by sreeraagh** [hossein-zare/react-native-dropdown-picker#362]
https://snack.expo.io/@sreeraagh/fascinated-marshmallows

Here is a snack i've made for you to test, Please check.
Cheers!

**Comment by sreeraagh** [comment]
https://snack.expo.io/@sreeraagh/funny-pretzels

this is what i'm trying to bring off

**Comment by Marwollo** [comment]
I see that you're missing the `open` prop for the DropDownPicker component, and also the prop that sets the function that gets called when a dropdown should be opened/closed `setOpen`. Use a state in the `open` prop and switch it in the `setOpen` callback function.
