### ISSUE TITLE
Custom scheme for dropdown

### ISSUE THREAD

**Issue by Parameshvadivel** [hossein-zare/react-native-dropdown-picker#365]
In my JSON I don't have a label, value pair. need trying to list value from JSON.  My JSON looks like

[{
name: demo,
_id: qeq123123qwe,
phoneNu: 421343234,
},]
here trying to list the name, default value name and based on name selected I need to filter the flatlist. Any help much appreciated pls...

**Comment by kkureli** [comment]
use schema prop. https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/item-schema
