### ISSUE TITLE
selected lables in heading not change able  

### ISSUE THREAD

**Issue by MAhtishamShahzad** [hossein-zare/react-native-dropdown-picker#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hossein-zare** [comment]
Hello, Please edit your issue.

**Comment by preetpalsofyx** [comment]
Unable to select the values in dropdown

**Comment by sandeepg1220** [comment]
Unable to select the dropdown values

**Comment by hossein-zare** [comment]
Others haven't faced the issue, Please add your Code Snippet.

**Comment by sandeepg1220** [comment]
```javascript
<DropDownPicker
            items={[
                {label: 'India', value: 'in'},
                {label: 'France', value: 'france'},
            ]}
            defaultValue={this.state.country}
            containerStyle={loginStyles.dropdownStyle}
            style={{backgroundColor: '#fafafa'}}
            dropDownStyle={{backgroundColor: '#fafafa'}}
            onChangeItem={item => this.setState({
                country: item.value
            })}
           
          />
```

**Comment by hossein-zare** [comment]
@sandeepg1220 
https://snack.expo.io/@hossein-zare/change-value-example
If you're using an older version, Update it to the latest version. **(current version: 3.0.5)**

**Comment by sandeepg1220** [comment]
Finally found the issue. Check the below code.
I'm using the latest version only.
```javascript
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';

import DropDownPicker from 'react-native-dropdown-picker'

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      country: null
    }
  }

  render() {
      return (
        <View style={styles.container}>
        <View>
          <DropDownPicker
            items={[
              {label: 'India', value: 'in'},
              {label: 'France', value: 'france'},
               {label: 'France', value: 'france'},
                {label: 'France', value: 'france'},
            ]}
            defaultValue={this.state.country}
            containerStyle={{}}
            style={{backgroundColor: '#fafafa'}}
            dropDownStyle={{backgroundColor: '#fafafa'}}
            onChangeItem={item => this.setState({
              country: item.value
            })}
          />
          </View>
          <Text>Value: {this.state.country}</Text>
          <Text>Some other text </Text>
          <Text>Some other text </Text>
          <Text>Some other text </Text>
        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  }
});
```

**Comment by hossein-zare** [comment]
@sandeepg1220 
It's working fine, or did i miss anything?

**Comment by sandeepg1220** [comment]
Not able to select france country

**Comment by sandeepg1220** [comment]
![Screenshot 2020-06-26 at 2 12 25 PM](https://user-images.githubusercontent.com/57384948/85838391-27a14500-b7b7-11ea-9d70-fb9d4cf3a269.png)

**Comment by hossein-zare** [comment]
https://snack.expo.io/@hossein-zare/change-value-example **(Updated)**

> **Nested Views**
> You have to add zIndex to the nested views which contain the picker.
> Note! zIndex locks the picker on Android, The solution is to use the Platform.OS
> _https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers_

#19

**Comment by sandeepg1220** [comment]
Ok now it's perfect. How to achieve when user click on anywhere in the screen the opened drop down has to close.

**Comment by hossein-zare** [comment]
@sandeepg1220
https://github.com/hossein-zare/react-native-dropdown-picker/issues/29
https://snack.expo.io/@hossein-zare/touch-outside
