### ISSUE TITLE
can't select item in android

### ISSUE THREAD

**Issue by OrataroSunsoftapp** [hossein-zare/react-native-dropdown-picker#370]

**Comment by OrataroSunsoftapp** [comment]
Use SetValue for selected item.

**Comment by yu629** [comment]
+1

**Comment by yu629** [comment]
can't select item in android

**Comment by akbar7352** [comment]
facing same issue

**Comment by mikehardy** [comment]
Everyone +1'ing and "same issuing" this, please understand that this issue, and your comments in no way meet the standard of anything that could be the start of trying to help you.

To get help on the internet for open source packages *you have to do some work*. 

You need to provide details that other people on the internet can use to help you.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by dongdyang** [comment]
+1

**Comment by asurare** [comment]
This package is just not working on Android, that's all. It should be added to the doc though…

**Comment by mikehardy** [comment]
This package is working great for me on Android.

**Comment by asurare** [comment]
> This package is working great for me on Android.

The most basic example with no style props at all and no specific option is not working on Android. The only working mode is through a modal, which is not why I picked this package.

**Comment by asurare** [comment]
Okay, found the "issue":
When not using the `MODAL` mode, you have to give a `marginBottom` equivalent to the number of items to display under the picker. Which gives smth like:

```JSX
<DropDownPicker
          open={open}
          value={value}
          itemSeparator
          style={[s.inputs, { paddingHorizontal: 8 }]}
          items={values}
          setOpen={setOpen}
          setValue={setValue}
          labelStyle={s.itemStyle}
          placeholderStyle={s.itemStyle}
          placeholder={values[0].label}
          listItemLabelStyle={s.itemStyle}
          containerStyle={{ marginBottom: 120 }}
          listItemContainerStyle={{ flexDirection: "row", padding: 8 }}
          itemSeparatorStyle={s.itemSeparator}
          dropDownContainerStyle={s.dropdownContainerStyle}
        />
```

But this isn't really a proper solution. I'll update here if I find anything better.

**Comment by mikehardy** [comment]
I use scrollview mode, works great. I dropped a bunch of code here #376

**Comment by peterchibunna** [comment]
Hi @mikehardy 
I appreciate your efforts in trying to resolve our issues. But this one I'm posting below has baffled me (I might be missing just 1 thing :) )

So it's not exactly that I can't select item but in a way. IF I select an item, it doesn't reflect that I've selected something. The placeholder still shows and if I output the selected item from state, I get a blank, neither null nor undefined.
```
function getItemsArray() {
  return  [{label: 'Apple', value: 'apple'},
	  {label: 'Banana', value: 'banana'},
	  {label: 'Cranberry', value: 'cranberry'},
	  {label: 'Durian', value: 'durian'},
	  {label: 'Eggplant', value: 'eggplant'}]
}

const [open, setOpen] = useState(false);

const [value, setValue] = useState(null);
const [items, setItems] = useState(getItemsArray());
const [canSubmit, setCanSubmit] = useState(false);
const [cropsLoading, setCropsLoading] = useState(false);
...

<DropDownPicker
    open={open}
    value={value}
    items={items}
    setOpen={setOpen}
    setValue={setValue}
    setItems={setItems}
    loading={cropsLoading}
    ActivityIndicatorComponent={({color, size}) => <ActivityIndicator color={color} size={size} />}
    activityIndicatorColor={Colors.blue300}
    searchable={true}
    
    listMode={'MODAL'}
    placeholder={'Choose Food'}
    placeholderStyle={{color: Colors.grey600,fontSize: 16}}
    itemSeparator={true}
    itemSeparatorStyle={{
	    backgroundColor: Colors.grey200, //marginVertical: 5,
    }}
    modalProps={{
	    animationType: 'slide'
    }}
    renderListItem={(props) =><List.Item description={`Category: DEMO`} title={props.label} {...props} />}
					/>
```

I'm testing on iOS simulator.

**Comment by mikehardy** [comment]
I apologize but just to set expectations - I've just come back from travel and have a mountain of work to tackle, I won't be able to provide specific help beyond the working setup I posted in the linked issue. Wish I had infinite time but sadly not the case
