### ISSUE TITLE
Unable to test as testID is missing from available props

### ISSUE THREAD

**Issue by mark-quinn** [hossein-zare/react-native-dropdown-picker#377]
## Problem

TestID is not an available prop for the component therefore cannot select the picker in tests.

## Solution 

Would be nice to see the addition of a testID so that we can select the picker in tests.

**Comment by mark-quinn** [comment]
Workaround is to pass the testID with the `props` object. `props={{testID: 'a-test-id'}}`.
Still think it would be better if this was extracted to being its own prop but it works as mentioned above.

**Comment by valeriashpiner** [comment]
@mark-quinn do you know is it possible to put TestID for items or not?

**Comment by mark-quinn** [comment]
> @mark-quinn do you know is it possible to put TestID for items or not?

I tried but couldn't get it to work. I should also state that even though I got the testID to go onto the dropdown, it actually wouldn't open the items in the test using `scrollView` mode.

**Comment by AWBoulder** [comment]
Having the same problem. Struggling to open the drop down during test. Has anyone been able to test this?

**Comment by AWBoulder** [comment]
was able to solve my issue - I think the onPress wasn't completing due to it trying to measure the screen to figure out which way to open the dropdown.

fix was to pass in `dropDownDirection="BOTTOM"` so that it wouldn't make that check

**Comment by jamie-phlo** [comment]
@hossein-zare would it be possible to have the `RenderItemComponent` accept and set `testID` as a param?

**Comment by mikehardy** [comment]
@jamie-phlo interesting - and I can see how this would be a real benefit in testing. Is passing a testID through as params a common pattern in other libraries? I'm unaware so I'd like to know and see some links to others doing similar - if this is what most other libraries do and you have tried it locally + post a PR, it would work for me.

**Comment by jamie-phlo** [comment]
Hey @mikehardy, I've seen it in quite a few libraries, either allowed as an explicit prop or used by spreading a general props object. Here is an example from a React Native Community Checkbox library that has it as an explicit prop https://github.com/react-native-checkbox/react-native-checkbox#common-props

I've not had a chance to try out locally yet unfortunately but after looking through the source code it seems like it should be possible to extend the ItemType type.

**Comment by mikehardy** [comment]
Great - thanks for the link, this sounds like it could be a really helpful addition if you have the time to give it a shot and post a PR

**Comment by jamie-phlo** [comment]
@mikehardy I've made the change locally and it worked as expected, I've put up in a PR here so let me know if you require any changes https://github.com/hossein-zare/react-native-dropdown-picker/pull/409
