### ISSUE TITLE
How to add a "Select All" item?

### ISSUE THREAD

**Issue by KrisLau** [hossein-zare/react-native-dropdown-picker#381]
For example the "All available slots" item in Signup Genius?
![image](https://user-images.githubusercontent.com/46275463/126999076-db8549ba-9ad7-4121-9ef9-3617f57a2aa7.png)

**Comment by mikehardy** [comment]
Unsure, have you experimented with setting the value of the dropdown to an array that has all the item values in it?

**Comment by KrisLau** [comment]
@mikehardy Just tried it both of these ways: 
```
  const [slotItems, setSlotItems] = React.useState([
    {label: 'Select All', value: ['sweep', 'mop', 'dust', 'dishes']},
    {label: 'Sweep', value: 'sweep'},
    {label: 'Mop', value: 'mop'},
    {label: 'Dust', value: 'dust'},
    {label: 'Dishes', value: 'dishes'},
  ]);
```
```
 const [slotItems, setSlotItems] = React.useState([
    {label: 'Select All', value: () => setSlotValue(['sweep', 'mop', 'dust', 'dishes'])},
    {label: 'Sweep', value: 'sweep'},
    {label: 'Mop', value: 'mop'},
    {label: 'Dust', value: 'dust'},
    {label: 'Dishes', value: 'dishes'},
  ]);
```
I have also tried messing with the `onChangeValue` prop:
```
onChangeValue={value => {
              if (value === 'all') {
                setSlotValue(slotItems.map(x => x.value));
              }
            }}
```


In all of these cases, it only selects the Select All item like this: 
![image](https://user-images.githubusercontent.com/46275463/127225725-c2ffc1e3-fa4b-455c-ad8b-afd079212a9b.png)

**Comment by mikehardy** [comment]
Sorry - that was my best idea. This isn't a use case of mine so I don't have personal experience with it or a need to dive in personally. You might have some luck diving into the code in node_modules (with patch-package to persist your work) if you try to see what happens with multi-selects when you set an array value.

My only other idea is to dynamically add (or remove) icons to the list items in response to "select all" being selected. If they indicated selection satisfactorily you may have an effective solution
