### ISSUE TITLE
Is it Possible to use an Object Schema?

### ISSUE THREAD

**Issue by Bogzzz** [hossein-zare/react-native-dropdown-picker#386]
Hello, Im having an issue with schema. I was wondering is it even possible for me to use schema like 
```
schema={{
          minorCategory: {
            label: 'label',
            value: 'value',
          },
        }}
```

when my Array is of that kind of objects

**Comment by hossein-zare** [comment]
Hello,

Nesting schema is unsupported.

**Comment by Bogzzz** [comment]
Ok , thanks
