### ISSUE TITLE
[docs] searchTextInputProps type is supposed to be TextInputProps

### ISSUE THREAD

**Issue by TomasSestak** [hossein-zare/react-native-dropdown-picker#388]
![Screenshot 2021-08-05 at 10 24 39](https://user-images.githubusercontent.com/27310585/128317651-4430c32e-2f57-4a1d-91b1-82326dfa7479.png)

**Comment by mikehardy** [comment]
Hi there! Please open a PR - it would be great to fix this, but we rely on the community to help move things forward --> https://github.com/hossein-zare/react-native-dropdown-picker-website/tree/main/docs
