### ISSUE TITLE
How to select a default Item/Value?

### ISSUE THREAD

**Issue by AbdullahQureshi1080** [hossein-zare/react-native-dropdown-picker#390]
How we can select a default value? Also how we can style the list items in the drop down box.

**Comment by Renan-Olovics** [comment]
im also with this problem, i cant change the value of 'Select an Item'

**Comment by Renan-Olovics** [comment]
> How we can select a default value? Also how we can style the list items in the drop down box.

looking into the files i have found placeholder which allowed me to change it, 
![image](https://user-images.githubusercontent.com/9964502/128930726-fa376e1e-2359-4cb4-9b6b-b9bd679e691d.png)
there's no mention on documentations about this

**Comment by mikehardy** [comment]
> > How we can select a default value? Also how we can style the list items in the drop down box.
> 
> looking into the files i have found placeholder which allowed me to change it,
> ![image](https://user-images.githubusercontent.com/9964502/128930726-fa376e1e-2359-4cb4-9b6b-b9bd679e691d.png)
> there's no mention on documentations about this

Untrue, https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/placeholder

**Comment by AbdullahQureshi1080** [comment]
> 
> 
> > How we can select a default value? Also how we can style the list items in the drop down box.
> 
> looking into the files i have found placeholder which allowed me to change it,
> ![image](https://user-images.githubusercontent.com/9964502/128930726-fa376e1e-2359-4cb4-9b6b-b9bd679e691d.png)
> there's no mention on documentations about this

Thanks @Renan-Olovics !

**Comment by ahmadsyed** [comment]
Hi @AbdullahQureshi1080 @Renan-Olovics , I am also having same problem. I did not understood above answer. I want to set default values(from API) on load of picker. How can I do it. I did not found any document related to this. I am using badge mode. although In simple MODE , it's showing 2 items selected.
