### ISSUE TITLE
Pickers Overlapping

### ISSUE THREAD

**Issue by KrisLau** [hossein-zare/react-native-dropdown-picker#391]
In the image below, you can see that the pickers seem to overlap each other causing the dropdowns to be hidden behind them.
![image](https://user-images.githubusercontent.com/46275463/128934742-d22bed35-886d-41c4-b8c5-72bed943f54b.png) 

Is there a way I can can only one picker to be open at a time and for the open one to overlap all the others? Like this:
![image](https://user-images.githubusercontent.com/46275463/128935037-346b3149-b5a6-44e1-bbde-7a76fe9c0655.png)
This one was implemented with a different picker package but that one is not consistent across iOS and Android

**Comment by mikehardy** [comment]
@KrisLau you might like https://github.com/hossein-zare/react-native-dropdown-picker/issues/376

**Comment by KrisLau** [comment]
@mikehardy I tried adding `zIndex` and `zIndexInverse` but that didn't seem to work. I also tried copying your solution from one of the comments with some slight modifications but the dropdown is still being overlapped. I might be doing it wrong though haha. Would wrapping the `DropDownComponentWrapper` with `react-native-popup-menu` `Menu`  component help maybe? 

**Attempt 1:**
```
<ListItem bottomDivider containerStyle={styles.row}>
      ...
      <DropDownPicker
        listMode={'MODAL'}
        mode={'BADGE'}
        open={slotOpen}
        value={slotValue}
        items={slotItems}
        setOpen={setSlotOpen}
        setValue={setSlotValue}
        setItems={setSlotItems}
        containerStyle={styles.picker}
        modalProps={{presentationStyle: 'pageSheet'}}
        ArrowDownIconComponent={({style}) => (
          <Icon
            name={'arrow-drop-down'}
            type={'material'}
            color={slotValue === 'paid' ? 'forestgreen' : 'crimson'}
            style={style}
          />
        )}
        ArrowUpIconComponent={({style}) => (
          <Icon
            name={'arrow-drop-up'}
            type={'material'}
            color={slotValue === 'paid' ? 'forestgreen' : 'crimson'}
            style={style}
          />
        )}
        textStyle={slotValue === 'paid' ? styles.paidItem : styles.unpaidItem}
        dropDownContainerStyle={{borderWidth: 0}}
        style={[{borderWidth: 0}, slotOpen && {zIndex: 200000}]}
      />
    </ListItem>
```

**Attempt 2:**
```
<ListItem>
       ...
        <View
          style={[{
            flexDirection: 'row',
            justifyContent: 'space-evenly',}, 
            (Platform.OS === 'ios' ? {zIndex: areaOpen ? 1 : 0} : {})]
          }>
          <View style={{justifyContent: 'center', alignContent: 'flex-end'}}>
            <FontAwesome
              name="puzzle-piece"
              size={30}
              color={styles.blue.color}
            />
          </View>
          <View style={{justifyContent: 'center'}}>
            <DropDownPicker
              open={areaOpen}
              value={areaValue}
              items={areaItems}
              setOpen={setAreaOpen}
              setValue={setAreaValue}
              setItems={setAreaItems}
              listMode="SCROLLVIEW"
              style={styles.dropDownStyle}
              zIndexInverse={7000}
              zIndex={1000}
              dropDownContainerStyle={{width: 200, backgroundColor: 'white'}}
              listItemContainerStyle={{
                width: 200,
              }}
            />
          </View>
        </View>
</ListItem>
```

**Attempt 3:**
```
<ListItem
      bottomDivider
      containerStyle={[
        styles.row,
        Platform.OS === 'ios' ? {zIndex: slotOpen ? 1 : 0} : {},
      ]}>
      ...
      <DropDownPicker
        open={slotOpen}
        value={slotValue}
        items={slotItems}
        setOpen={setSlotOpen}
        setValue={setSlotValue}
        setItems={setSlotItems}
        listMode="SCROLLVIEW"
        zIndexInverse={7000}
        zIndex={1000}
        dropDownContainerStyle={{width: 200, backgroundColor: 'white'}}
        listItemContainerStyle={{
          width: 200,
        }}
        containerStyle={styles.picker}
      />
    </ListItem>
```

**Comment by mikehardy** [comment]
Not sure what the listitem wrapper component is, but the critical thing to understand about zindex is that **zindex is only relative to items in the same view hierarchy**

If you put things in leaf nodes of different view hierarchies, their zindex has no cross relation.

So simplify your view, make all the dropdown pickers view-peers in the same hierarchy, or *worst* case on android react-native has an optimization where flex-only views are collapsed as they go across the native bridge so you may wrap in flex-only views on android, or on ios you can see in my hack that I dynamically pop the zindex of the whole dropdown picker when it's open, which works around the "zindex only applies to peers in the same view hierarchy" restriction

**Comment by KrisLau** [comment]
The `ListItem` wrapper is just a component from React Native Elements component that acts as a `<View style={{flex-direction: row}}` kind of haha. Ohh that  "zindex only applies to peers in the same view hierarchy" restriction might be a problem for me as the structure in my screen is somewhat close to this:
```
<View>
    {list.map((l, i) => (
        <ListItem>
            <Image />
            <Text />
            <DropDownPicker />
        </ListItem>
    ))}
</View>
```
So I can't put the `DropDownPicker` components in the same view hierarchy unfortunately 😢 For now I'll just use the `listMode='MODAL'` as a workaround. Thank you for taking the time to explain it to me!
<br>
**EDIT:** I ended up refactoring my code to use `react-native-popup-menu` since there were only two items I needed in the dropdown and I already use that package in my project. I still use this package for my larger dropdowns however. Just leaving this here in case anyone else happens to be in the same-ish situation
```
<Menu onOpen={() => setIsOpen(true)} onClose={() => setIsOpen(false)}>
  <MenuTrigger>
    <View
        style={{
          flex: 1,
          padding: 5,
          alignItems: 'center',
          flexDirection: 'row',
          justifyContent: 'space-between',
        }}>
      <Text
          style={[{marginRight: 15}, isPaid ? styles.paid : styles.unpaid]}>
        {isPaid ? 'PAID' : 'UNPAID'}
      </Text>
      <Icon
          name={isOpen ? 'arrow-drop-up' : 'arrow-drop-down'}
          type={'material'}
          color={isPaid ? styles.paid : styles.unpaid}
      />
    </View>
  </MenuTrigger>
  <MenuOptions
      customStyles={{
        optionsContainer: {width: 120},
      }}>
    <MenuOption
        text={'PAID'}
        customStyles={{optionText: styles.paid}}
        onSelect={() => setIsPaid(true)}
    />
    <MenuOption
        text={'UNPAID'}
        customStyles={{optionText: styles.unpaid}}
        onSelect={() => setIsPaid(false)}
    />
  </MenuOptions>
</Menu>
```
