### ISSUE TITLE
searchablePlaceholder is renamed to searchPlaceholder

### ISSUE THREAD

**Issue by SuvabBaral** [hossein-zare/react-native-dropdown-picker#393]
searchablePlaceholder doesn't work but using 'searchPlaceholder' changes the text of the search place holder.

**Comment by mikehardy** [comment]
If there is something missing in the code, types, or docs, please open a PR - using the github interface it's just a click on the edit button and it walks you through it.

Without a link to what exactly you're referring to, I'm not sure where the error actually is

**Comment by hossein-zare** [comment]
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/search#searchplaceholder
