### ISSUE TITLE
Change selected items appearance mode

### ISSUE THREAD

**Issue by debotos** [hossein-zare/react-native-dropdown-picker#394]
Currently selected items showing in a Horizontal Scroll View.
Is there is any way to wrap the items? I am attaching a screenshot.

![combine_images](https://user-images.githubusercontent.com/29367677/129661038-dbcfbd4e-7ee3-4d2d-88e8-cf06b0493749.png)

**Comment by hossein-zare** [comment]
Hello,

There's no way.
