### ISSUE TITLE
getting single or multiple item object in addition to just value(s)

### ISSUE THREAD

**Issue by opnsrcntrbtr** [hossein-zare/react-native-dropdown-picker#396]
How do I get single or multiple item object on clicking a dropdown item?
setValue helps me get the selected value(s) but not the selected item object.

eg. 
items={[
              {label: 'English', value: 'en', link:'en_url'},
              {label: 'Deutsch', value: 'de', link:'de_url'},
              {label: 'French', value: 'fr', link:'fr_url'},
          ]}

setValue will help me get the selected value 'en'  but not the selected item object {label: 'English', value: 'en', link:'en_url'}

**Comment by mikehardy** [comment]
All I can think of here is that you'll need to filter your items array testing for the value to get the one that matches https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by WenLonG12345** [comment]
Same here, Is it not possible to pass object?

**Comment by rafalkaczynsky** [comment]
Same here :)

**Comment by hossein-zare** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker/issues/474
