### ISSUE TITLE
Categories don't work as expected

### ISSUE THREAD

**Issue by KrisGilicze** [hossein-zare/react-native-dropdown-picker#397]
That documentation states that:

> NOTE
> The items don't need to be sorted, This will be done automatically.

However, this example from docs:
```
const [items, setItems] = useState([
  {label: 'North America', value: 'na'},
  {label: 'United States', value: 'usa', parent: 'na'},
  {label: 'Canada', value: 'canada', parent: 'na'},

  {label: 'Europe', value: 'eu'},
  {label: 'Norway', value: 'norway', parent: 'eu'},
  {label: 'Belgium', value: 'belgium', parent: 'eu'},
]);
```
works differently than this:
```
const [items, setItems] = useState([
    {label: 'United States', value: 'usa', parent: 'na'},
    {label: 'Canada', value: 'canada', parent: 'na'},
    
    {label: 'Norway', value: 'norway', parent: 'eu'},
    {label: 'Belgium', value: 'belgium', parent: 'eu'},
    {label: 'Europe', value: 'eu'},
    {label: 'North America', value: 'na'},
]);
```
The second code only has item order changed and results in every item without parent being categorized as "Europe". Not sure if this is a bug or the expected behavior. 
If it is a bug I will help tracking down where it comes from, if not I suggest adjusting the documentation.

**Comment by mikehardy** [comment]
Hi there!
Any forward progress in this package is driven by the community

> The second code only has item order changed and results in every item without parent being categorized as "Europe". Not sure if this is a bug or the expected behavior.
> If it is a bug I will help tracking down where it comes from, if not I suggest adjusting the documentation.

If you track it down and there is a code or documentation update, please post a PR and we can merge it, otherwise this likely won't go anywhere unless you or someone else steps up to do the necessary investigation

**Comment by KrisGilicze** [comment]
I only have a little time right now but as far as I can tell this might be an issue on hermes specifically. Array prototype sort is not stable when turning hermes on, see this issue [here](https://github.com/facebook/hermes/issues/212).

**Comment by mikehardy** [comment]
Does not appear that will be fixed soon. I'd accept a patch here that detected the hermes engine and used this Javascript sort instead if on hermes https://github.com/facebook/hermes/issues/212#issuecomment-867898839

**Comment by KrisGilicze** [comment]
I try to do it this weekend, not sure how to detect if hermes is enabled though. Would a patch be fine for all engines?
**Edit:**
Hermes is the de facto standard with react native, and the sort you linked will work on both with no noticable runtime difference.

**Comment by mikehardy** [comment]
@KrisGilicze it appears you may test for `global.HermesInternal` existence (proof: https://github.com/facebook/react-native/blob/2b56011f9cb9f90781428b5b773cbbed5c4fae43/template/App.js#L62) - sorting is a performance concern and it would be better to rely on native if possible I think, in case people have really big dropdowns etc.

**Comment by KrisGilicze** [comment]
Took the weekend off, but I just created a PR with a fix
