### ISSUE TITLE
Searchable error styles

### ISSUE THREAD

**Issue by TheElegantCoding** [hossein-zare/react-native-dropdown-picker#403]
how can i modify the error message, this is in v3 and is not working now

searchableError={() => <Text>Not Found</Text>

**Comment by mikehardy** [comment]
This isn't enough of anything for me to help, sorry --> closing
Try a github link to a line of code, package.json with your versions,, an App.js that represents a https://stackoverflow.com/help/minimal-reproducible-example or something - but the general point is you must imagine some other programmer walked up to you with your problem asking for help, and if their request is missing what you need, you get no help 🤷
