### ISSUE TITLE
Search error styles and text

### ISSUE THREAD

**Issue by TheElegantCoding** [hossein-zare/react-native-dropdown-picker#404]
in the new version of the dropdown picker it seems impossible to modify the error message and the styles of the same, I am talking about the error message in the search

![WhatsApp Image 2021-09-14 at 4 53 01 PM](https://user-images.githubusercontent.com/70770072/133332476-32a89ee9-41b7-4785-8b62-d5c8ca08a76b.jpeg)

Look at the error message that says "there is nothing to show", I want to change the message and the color of the text

in the older version of the dropdown picker, it was possible to pass the prop for change the message and the styles

`searchableError={() => <Text>Not Found</Text>}`

i look at the props types of the component and i don't see anything that can change the style that and in the documentation, there is no information about the error search

**Comment by hossein-zare** [comment]
There are two props you can take advantage of

```
listMessageContainerStyle
listMessageTextStyle
```

**Comment by hossein-zare** [comment]
**Localization**
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/localization#change-the-translation

```jsx
translation={{
  NOTHING_TO_SHOW: "There's nothing to show!"
}}
```

**Comment by TheElegantCoding** [comment]
whit these props I change the color perfectly

```
listMessageTextStyle
listMessageContainerStyle

```
i can change the translation whit 

```
translation={{
  NOTHING_TO_SHOW: "There's nothing to show!"
}}

```

but i am using typescript and that give me this error

`Type '{ NOTHING_TO_SHOW: string; }' is missing the following properties from type 'TranslationInterface': PLACEHOLDER, SEARCH_PLACEHOLDER, SELECTED_ITEMS_COUNT_TEXT`

so i need to put all variables like the documentation

```
translation={{
  PLACEHOLDER: "Sélectionnez un élément",
  SEARCH_PLACEHOLDER: "Tapez quelque chose...",
  SELECTED_ITEMS_COUNT_TEXT: "{count} éléments ont été sélectionnés",
  NOTHING_TO_SHOW: "Il n'y a rien à montrer!"
}}
```

everything works fine whit all variables

**Comment by hossein-zare** [comment]
Please install **`react-native-dropdown-picker@5.1.27`**

**Comment by TheElegantCoding** [comment]
in `react-native-dropdown-picker@5.1.27` all work fine 👍, and I only need one parameter in:

```
translation={{
  NOTHING_TO_SHOW: "No hay coincidencias"
}}
```
