### ISSUE TITLE
When I open any dropdown, field's form is changing

### ISSUE THREAD

**Issue by kozakstar** [hossein-zare/react-native-dropdown-picker#405]
![Снимок экрана 2021-09-15 в 17 46 52](https://user-images.githubusercontent.com/29351195/133473718-bc982b8e-eda4-4c5a-979c-be5dab04e03c.png)
![Снимок экрана 2021-09-15 в 19 34 54](https://user-images.githubusercontent.com/29351195/133473724-201f803a-4af4-45ea-826e-df437a9bdfc5.png)

**Comment by hossein-zare** [comment]
Try `pickerNoBorderRadius={true}`

**Comment by kozakstar** [comment]
`disableBorderRadius={false}`
solved my problem
