### ISSUE TITLE
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

### ISSUE THREAD

**Issue by mwegener-com** [hossein-zare/react-native-dropdown-picker#410]
I'm not able to use this Picker inside a Scroll View. Do you have any idea?

JSX Code: https://pastebin.com/CScKnb5B

<img width="389" alt="Bildschirmfoto 2021-09-22 um 16 58 17" src="https://user-images.githubusercontent.com/64470126/134413298-8aa3a887-bd6e-4d12-880a-417928603f29.png">

**Comment by mikehardy** [comment]
use scrolllist mode as documented: https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes

duplicate #56

**Comment by christocracy** [comment]
Oh, so you've got your fingers dipped in this repo too?  Nice docs.  Do you know what's used to generate those?

**Comment by mikehardy** [comment]
> Oh, so you've got your fingers dipped in this repo too? Nice docs. Do you know what's used to generate those?

Hey :wave: - Yeah, it's the only really cross-platform picker I saw that seemed reasonably maintained and did what I wanted - needed one for a commercial project and it won the bake-off. No idea on docs, I haven't used the repo for long, but they're out-of-tree in their own repo https://github.com/hossein-zare/react-native-dropdown-picker-website

**Comment by christocracy** [comment]
I'm rebuilding the BGGeo demo app from scratch.  I'll prob render about 20 of these in a list for the Settings screen.

**Comment by mikehardy** [comment]
Mind that zIndex - I learned that I knew nothing of zIndex until I attempted to use this package, but it can work if you're careful - #376

**Comment by christocracy** [comment]
I'm just going to use MODAL mode.  zIndex problem is moot, no?

**Comment by mikehardy** [comment]
I believe so, yes!

**Comment by christocracy** [comment]
Did you find [`lawnstarter/react-native-picker-select`](https://github.com/lawnstarter/react-native-picker-select)?  *LawnStarter* is a *long time* customer of mine since 2015.

**Comment by mikehardy** [comment]
I saw a few like that, my UI requirements were non-modal / non-native appearance, they wanted dropdowns to dropdown right from the dropdown like a website select, and I wanted something that was pure js so that could work in react-native-web as well once I was familiar with the package

**Comment by christocracy** [comment]
>from the dropdown like a website select

like this?

![](https://dl.dropbox.com/s/mjhwwpp9xthlrqy/Screen%20Shot%202021-10-16%20at%2010.17.39%20PM.png?dl=1)
