### ISSUE TITLE
custom placeholder component

### ISSUE THREAD

**Issue by mwegener-com** [hossein-zare/react-native-dropdown-picker#411]
It would be great if it would be possible to add a custom component for the placeholder, because then you could add icons etc.
<img width="374" alt="Bildschirmfoto 2021-09-23 um 10 37 24" src="https://user-images.githubusercontent.com/64470126/134517288-7db314a7-7ff2-4d0b-8578-f58e339762e4.png">

**Comment by mikehardy** [comment]
If it was done in a similar style to the other locations where components (with icons and such) are passed through, I'd be open to a pull request implementing the same

**Comment by Dastan4r** [comment]
@mikehardy Hey! Now if i pass icons to placeholder it works fine on IOS, but on android it show only first time, then placeholder icons dissapear. Can you help with setting icons on android?

**Comment by mikehardy** [comment]
@Dastan4r hi there - unfortunately no, I won't have time for that

**Comment by hossein-zare** [comment]
@Dastan4r If you're formatting icons of your items, Most likely you are reformatting already formatted icons!

**Output:**
```function () { [bytecode] }```?!
```jsx
<Image source={{"uri": "http://192.168.1.100:4000/storage/uploads/categories/function () { [bytecode] }"}} />
```

**Solution:**
`useMemo` won't help you here, ineffective like remdesivir.

```tsx
const myItems = useMemo(() => {
  return categories.map((item) => {
    if (typeof item.icon === "function")
      return item;

    const uri = getCategoryImage(item.icon);

    // @ts-ignore
    item.icon = () => <Image source={{uri}} style={styles.light.categoryImage} />;
    
    return item;
  });
}, [categories]);
```

**Comment by haridevks** [comment]
So is there any workaround for that untill we get the proper solution? i am using the version 4.0.9 in my project and i would like to add an icon to the placeholder?

**Comment by haridevks** [comment]
@Dastan4r  How did you add the icon to placeholder?

**Comment by Dastan4r** [comment]
@haridevks I just change my item to`{ icon: () => <SomeIcon />, value: someValue }`.All staff described in docs in advanced folder

**Comment by hadnet** [comment]
Any update on this? I'm trying to do something like this, (setting an icon only on placeholder). Is there a way to do that with this react-native-dropdown-picker, @hossein-zare ?
<img width="329" alt="Screen Shot 2022-09-16 at 5 24 16 PM" src="https://user-images.githubusercontent.com/13828833/190726967-0ef7370d-22ba-4a8c-a352-aff3d7c3ed41.png">

**Comment by TomJamesDuffy** [comment]
This is hacky, but it might help somebody:

Adjust icons/height/tsx as per your requirements.

```
            placeholder={
                <View
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    height: 55 // Size of input box
                  }}>
                  <SwimPlus height={35} width={35}/>
                  <Text style={styles.pickerText}>Select stroke</Text>
                </View>
              }

**Comment by ShadyAK** [comment]
@TomJamesDuffy the placeholder is supposed to be string only, since I'm a newbie to react-native/react am I missing something?

**Comment by ShadyAK** [comment]
I found a workaround for this, what you can do is make a dropdown item invisible and make it be the selected item when the dropdown renders and have an icon in this dropdown item, it will act as a label with icon and not appear in the dropdown list.
Something like this -
```
    const [value, setValue] = useState(null);
    const [items, setItems] = useState([
        {label: 'Auto debit', value: 'url-for-auto-debit', isSelected: true, selectable: true, containerStyle: {display: "none"}},
        {label: 'Generate Pin', value: 'url-for-generate-pin'},
        {label: 'Request add-on card', value: 'url-for-add-on-card'},
        {label: 'Balance Transfer', value: 'url-for-balance-transfer'},
        {label: 'Image Credit Card', value: 'url-for-image-credit-card'}
    ]);
    useEffect(() => {setValue('url-for-auto-debit')}, []) 
```

**Comment by riehum** [comment]
> isSelected: true, selectable: true, containerStyle: {display: "none"}},



> This is hacky, but it might help somebody:
> 
> Adjust icons/height/tsx as per your requirements.
> 
> ```
>             placeholder={
>                 <View
>                   style={{
>                     flexDirection: 'row',
>                     alignItems: 'center',
>                     height: 55 // Size of input box
>                   }}>
>                   <SwimPlus height={35} width={35}/>
>                   <Text style={styles.pickerText}>Select stroke</Text>
>                 </View>
>               }
> ```

But, placeholder should be string, though it worked
