### ISSUE TITLE
Dropdown picker not responding to touch properly on Android but works on Web/IOS

### ISSUE THREAD

**Issue by mattjcl** [hossein-zare/react-native-dropdown-picker#413]
https://snack.expo.dev/@mattjcl/faabec

See the above snack. I'm expecting the  picker to update the value and display it after selecting it. On Android (physical device or emulator) the picker only responds if you press in a very precise location close to the top and center of the item, and only for the first item in the list. The second and third items don't respond to touch.

**Comment by mattjcl** [comment]
Never mind - I broke the inappropriate styles rule with `borderColor: 'red'`

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules/#avoid-inappropriate-styles

**Comment by jp928** [comment]
The rule is annoying, plz make it works with customised styles
