### ISSUE TITLE
Nested Category Dropdown

### ISSUE THREAD

**Issue by justin-seo** [hossein-zare/react-native-dropdown-picker#414]
Does this component have support for multiple levels of categories for the dropdown?

I tried added California under United States but it seems to stay at the same level as United States. Not sure if it's a visual issue or just not possible.

Any help would be appreciated!

`
    const [items, setItems] = useState([
        {label: 'North America', value: 'na'},
        {label: 'United States', value: 'usa', parent: 'na'},
        {label: 'California', value: 'california', parent: 'usa'},
        {label: 'Canada', value: 'canada', parent: 'na'},
        {label: 'Europe', value: 'eu'},
        {label: 'Norway', value: 'norway', parent: 'eu'},
        {label: 'Belgium', value: 'belgium', parent: 'eu'},
    ]);
`

**Comment by justin-seo** [comment]
Skimmed through the code and it seems like it's not possible.. I'm trying to achieve this: [https://382pjronm.csb.app/](https://382pjronm.csb.app/)

**Comment by hossein-zare** [comment]
Hello @justin-seo 
It's not possible.
