### ISSUE TITLE
Focus on selected item whenever dropdown list is displayed.

### ISSUE THREAD

**Issue by JavanHuang** [hossein-zare/react-native-dropdown-picker#415]
Hi @hossein-zare,

I did a [PR](https://github.com/hossein-zare/react-native-dropdown-picker/pull/116) last year regarding the automatic scrolling of selected item so that it's easier for users to refer to their selected item once they open the dropdown list.

I was not able to find the method to trigger the automatic scroll to selected item in the docs so I was wondering if there are any methods that could do that in the recent versions of `react-native-dropdown-picker`.

Version that i'm using currently: `5.1.21`

**Comment by hossein-zare** [comment]
Hey @JavanHuang ,
Yeah i remember your awesome PR.

I had to publish a new version as soon as possible, i forgot to add some of the previous features to the v5.x.
Sorry for that but i'll work on it.

**Comment by hossein-zare** [comment]
`autoScroll` is available on **v5.2.2**.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#autoscroll

**Comment by maartenvandillen** [comment]
I have a lot of items in the list and autoscroll doesn't seem to work. It scrolls a bit but stops somewhere random. I'm using flatlist mode. Is there also an option to just open at the selected item without animated scrolling?
