### ISSUE TITLE
DropDownPicker will shown automatically when item in another Picker above it is selected

### ISSUE THREAD

**Issue by Majda995** [hossein-zare/react-native-dropdown-picker#419]
i build multiple DropDown picker above each other and when i click on an item from a picker, the picker beyond it will shown automaticly . hope i make may issue clear i am new with react :)

**Comment by mikehardy** [comment]
Probable zIndex issues. Please read/think-deeply-about #376

**Comment by Majda995** [comment]
> Probable zIndex issues. Please read/think-deeply-about #376

it really helpt, Thanks a lot!
