### ISSUE TITLE
v4.x to v5.x

### ISSUE THREAD

**Issue by swalahamani** [hossein-zare/react-native-dropdown-picker#421]
Any detailed migration guide or change log?

**Comment by mikehardy** [comment]
I couldn't find one myself, even poking around on older tags / branches, sorry.

**Comment by hossein-zare** [comment]
@swalahamani 
You should renew your components because the package has been rewritten.

**Comment by swalahamani** [comment]
Hi @hossein-zare  Thanks for the response and this beautiful library. It really saved lots of time for us all!

So, there is no official guide for migrating from v4.x to v5.x other than manually figuring out what changed, right?

**Comment by hossein-zare** [comment]
Hi @swalahamani 
Yes. As i said, This package has been reimplemented, it's like comparing apples and oranges.
You should first read the [rules](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules) and check our [examples](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#examples).

**Comment by swalahamani** [comment]
Ok, thanks @hossein-zare for the response.
