### ISSUE TITLE
onChangeValue not trigger when click options

### ISSUE THREAD

**Issue by justb** [hossein-zare/react-native-dropdown-picker#422]
version: 5.1.28
rn version: 0.61.5

```

import DropDownPicker, {DropDownPickerProps} from 'react-native-dropdown-picker';
import React, {useState} from 'react'
export default function App(props: DropDownPickerProps) {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState(null);
  // const [items, setItems] = useState([
  //   {label: 'Apple', value: 'apple'},
  //   {label: 'Banana', value: 'banana'}
  // ]);

  return (
    <DropDownPicker
      {...props}
      value={value}
      zIndex={1000}
      open={open}
      setOpen={setOpen}
      onChangeValue={e=>console.warn(e)}
      // setValue={setValue}
      // setItems={setItems}
    />
  );
}

```

**Comment by hossein-zare** [comment]
It seems that you have a `setValue` callback passed to the component (held in the props variable), While the picker uses a local `value`, So the `value` won't change.

Comment out `const [value, setValue] = useState(null);` and `value={value}`
Pass a `value` along with the setValue callback.

```jsx
<App
  value={value}
  setValue={setValue}
  ... />
```

**Comment by justb** [comment]
Thanks for your answer, it's different from what I used before. I think setValue is liked to change value actively by users themself, use onChangeValue instead of setValue at this moment maybe a little bit better
