### ISSUE TITLE
Custom color for an item in dropdown list

### ISSUE THREAD

**Issue by annh-2003** [hossein-zare/react-native-dropdown-picker#425]
Hello,

Is there any way to custom 1 row about color or text style from the dropdown list?

Example: Dropdown list month from 1 -> 12, and the current month (an example is 10) have different colors with other values.
Specific: 
- 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12: text color is white
- 10: text color is blue.

Thanks.

**Comment by hossein-zare** [comment]
Hello,

You can only specify a single color.

**Comment by annh-2003** [comment]
> Hello,
> 
> You can only specify a single color.

@hossein-zare Can you give me an example for create it?

**Comment by hossein-zare** [comment]
Use https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#listitemlabelstyle

**Comment by hossein-zare** [comment]
**v5.2.2** is out.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#item-specific-styles

**Comment by annh-2003** [comment]
@hossein-zare 
Thank you for your work!
