### ISSUE TITLE
Change width of the picker

### ISSUE THREAD

**Issue by L-mNguyen** [hossein-zare/react-native-dropdown-picker#426]
I'm new to React so please bear with me: how do I change the width of the picker? The default implementation is too wide.

![image](https://user-images.githubusercontent.com/52264769/138229201-81eddaf2-0120-40fa-88ea-3d326ab24dd3.png)

**Comment by nbastoWM** [comment]
You can add this prop:
```containerStyle={{width: 200}}```

**Comment by L-mNguyen** [comment]
Thank you for your help with this, is this a standard React feature? I see that the docs list containerStyle but its blank. 
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#containerstyle

**Comment by hossein-zare** [comment]
@L-mNguyen Hi there, Yes.

**Comment by de-jure** [comment]
Sorry, how can i change dropdownpicker width? I don't need a space between text/placeholder and arrow. And text inside is new every time. Image from Figma:
![image](https://user-images.githubusercontent.com/62948817/151372337-f40f6bd2-05bb-453a-a118-7b723dedb211.png)

**Comment by ravi-roxiler** [comment]
@de-jure have you found any solution for this issue??

**Comment by de-jure** [comment]
> @de-jure have you found any solution for this issue??

no, i used other library (modal-dropdown)

**Comment by Aladdin4u** [comment]
react-native-element-dropdown gives you the flexibility  needed
