### ISSUE TITLE
Disable selected option

### ISSUE THREAD

**Issue by rymkapro** [hossein-zare/react-native-dropdown-picker#429]
Hi everyone. That's a great and flexible package!
But I have a question: how can I disable selected option?
I'm using one options list which is passed to multiple dropdowns.
So I need to disable selected dropdown option in other dropdowns.

Or I need to have multiple states for options list?

Thanks a lot for help!

**Comment by mikehardy** [comment]
I believe you will want to handle state separately for every dropdown, otherwise you will not be able to handle dropdown open/close correctly, as discussed in https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/close-other-pickers
