### ISSUE TITLE
Error to select an item

### ISSUE THREAD

**Issue by MatiasChao** [hossein-zare/react-native-dropdown-picker#43]
When I select one the first values that can I see in the list, Its works fine but when I search other item and I click, I have an error.

The error is:
undefined is not an object (evaluating 'item.value')
* app/screens/ArticleList.js:240:43 in ArticleModal
* [native code]:null in find

I'm putting a console log into the function and the value arrive well.

This is my component:
```javascript
<DropDownPicker
                        items = {
                            products
                        }
                        defaultValue = { article.articleName }
                        containerStyle = {{height: 40}}
                        style = {{backgroundColor: '#fafafa'}}
                        dropDownStyle = {{backgroundColor: '#fafafa'}}
                        onChangeItem = {item => onChangeSetArticle(item.value, 'articleName') }
                        searchable = { true }
                        searchablePlaceholder = "Buscar artículo..."
                        searchableError = "Artículo no encontrado"
                        placeholder = "Selecciona un artículo"
                    />

const onChangeSetArticle = (e, type) => {
            return setArticle({
                ...article, 
                [type]: e
            })
    }
```

**Comment by hossein-zare** [comment]
Hello,
Please remove the `defaultValue` prop see if it's working fine.
Not sure but it seems to be a hook issue, i've not worked with hooks though.

`onChangeItem = {item => console.log(item.value) }`
If this doesn't cause any issues, Take a look your functions such as `onChangeSetArticle` and the `article.articleName` state.

Good Luck!

**Comment by MatiasChao** [comment]
Hello!
Yes, If i remove the defaultValue it works.

It's strange because I'm checking my code and I haven't any bugs.
Maybe the component have any problem with hooks?

Thank you!

**Comment by hossein-zare** [comment]
No, When you're clicking on an item it changes the default value. The function which assigns the new item value to the state is buggy.

The component is bug-free in that!

**Comment by MatiasChao** [comment]
But If I select one of the first three (I see by default 3 items on the list). I haven't any problem, I can switch with the first three. 
But when I write a text for other item and I click one so it's my error.

Thank you!

**Comment by hossein-zare** [comment]
Please create an Expo Snack and reproduce the behavior, I'll find out what's going wrong,
https://snack.expo.io/

**Comment by MatiasChao** [comment]
Hello!

I found the problem.

I have a very long array with a lot of products and I had a ",,"

const products = [
    { label: 'Uno', value: 'Uno' },
    { label: 'Dos', value: 'Dos' },
    { label: 'Tres', value: 'Tres' },
    { label: 'Cuatro', value: 'Cuatro' },, < for example..
    { label: 'Cinco', value: 'Cinco' }
  ]

Really thanks so much for helping me!!!
Greetings :)
