### ISSUE TITLE
Style of "Search" TextInput not working

### ISSUE THREAD

**Issue by vishalsawai** [hossein-zare/react-native-dropdown-picker#44]
Hi,

I'm using this version - "react-native-dropdown-picker": "^3.0.5".
I've tried changing the searchablePlaceholder style by using "searchableStyle" but not able to change the color of the TextInput.

I've added this to the DropDownPicker Component :
```
searchableStyle={{
 fontSize: 13,
 color: '#000',
 backgroundColor: '#fff'
}}
```

This changes the background color and font size but it is not changing the color of the text.

and same with searchableError - how can i change the color of the text.

It should change the color of the text but not changing.

**Comment by hossein-zare** [comment]
Hello,

Yes, It's not possible to apply styles to the placeholder or the error message.
I've planned to add new properties and styling options.
Please wait until i release a new version.

Thanks.

**Comment by vishalsawai** [comment]
Thanks for your reply,

When we can expect the release of a version with the required changes.

**Comment by hossein-zare** [comment]
Not sure, more likely next week.

**Comment by hossein-zare** [comment]
**v3.1.5** is out.
`searchablePlaceholderTextColor` has been added.

**Comment by vishalsawai** [comment]
Thanks working as expected!

**Comment by izzyreal** [comment]
@hossein-zare Would it be possible to specify `fontFamily` as well?
