### ISSUE TITLE
"Value" never appears. Only shows placeholder label

### ISSUE THREAD

**Issue by hsavit1** [hossein-zare/react-native-dropdown-picker#447]
I am using the latest version of this project on react-native-web, RNW 0.17.5

For some reason, even when the `value` prop is hardcoded to a string, the dropdown header always shows the placeholder label, and not the `value` string.

**Comment by hsavit1** [comment]
the problem was that my list items didn't follow the format {label: string, value: string}

answer discovered in this issue https://github.com/hossein-zare/react-native-dropdown-picker/issues/353

**Comment by hsavit1** [comment]
I am reopening this, as I have encountered this problem again, even though I am correctly following the rule stated above

**Comment by hossein-zare** [comment]
Hello @hsavit1 
Please add your code (+state variables)
