### ISSUE TITLE
react-native-dropdown-picker with react hook from

### ISSUE THREAD

**Issue by saicharanpogul** [hossein-zare/react-native-dropdown-picker#448]
Can someone help me out with implementing react-native-dropdown-picker with react-hook-form? How do I use val parameters provided by the react-hook-form Controller?
```
...
const [open, setOpen] = React.useState(false)
const [value, setValue] = React.useState(null)
const [items, setItems] = React.useState(genres)
const validationSchema = yup.object().shape({
  country: yup.string().required('Country is required.')
})
  const {
    handleSubmit,
    control,
    formState: { errors }
  } = useForm({
    resolver: yupResolver(validationSchema)
  })
  const onSubmit = data => {
    console.log(data)
  }
....
<Controller
  defaultValue=""
  name="country"
  control={control}
  render={({ field: { onChange, val } }) => (
    <View style={styles.genre}>
      <DropDownPicker
        open={open}
        value={value}
        items={items}
        setOpen={setOpen}
        setValue={setValue}
        setItems={setItems}
       onChangeValue={value => {
          console.log(value)
          onChange(value)
       }}
      />
    </View>
  )}
  />
<Button title="Submit" onPress={handleSubmit(onSubmit)} />
```

Solution:
```
...
const [open, setOpen] = React.useState(false)
  const [itemValue, setItemValue] = React.useState(null)
  const [items, setItems] = React.useState(genres)
  const {
    handleSubmit,
    control,
    formState: { errors },
    setValue
  } = useForm({
    resolver: yupResolver(validationSchema)
  })
  const onSubmit = data => {
    console.log(data)
  }
...
<Controller
    defaultValue=""
    name="trackGenre"
    control={control}
    render={({ field: { onChange, value, name } }) => (
      <View style={styles.genre}>
        <DropDownPicker
          open={open}
          value={itemValue}
          items={items}
          setOpen={setOpen}
          setValue={setItemValue}
          setItems={setItems}
          onChangeValue={val => {
            console.log(val)
            onChange(val)
            setValue('trackGenre', val)
          }}
        />
      </View>
    )}
  />
  {console.log(errors)}
  <Button title="Submit" onButtonPress={handleSubmit(onSubmit)} />
...
```

**Comment by vyrotek** [comment]
I was able to get this working with the Controller with this configuration.
```
...
<Controller
  ...
  render={({ field }) => (
    <DropDownPicker
       value={field.value}
       setValue={(callback: any) => field.onChange(callback())}
       items={items}
...
```

**Comment by chunghn** [comment]
> 

I tried this method for multiple selections. I can only pick one option every time. Any idea to make it work?

```js
...
  const [open, setOpen] = useState(false)
  const items = [
    { label: "Spain", value: "spain" },
    { label: "Italy", value: "italy" },
    { label: "Finland", value: "finland" },
  ]
...
      <Controller
        defaultValue={[]}
        name="country"
        control={control}
        render={({ field: { onChange, value } }) => (
            <DropDownPicker
              open={open}
              setOpen={setOpen}
              items={items}
              value={value}
              setValue={(callback: any) => onChange(callback())}
              multiple={true}
              mode="BADGE"
            />
        )}
      />
```

edit:
I tried to manipulate the value from callback(), but it's not working properly when I select multiple items. It only keeps the latest selection.
```js
...
    <Controller
...
          setValue={(callback: any) => {
                const prev = value
                const now = [...callback()]

                const commonItems = prev.filter((item) => now.includes(item))
                const uniquePrev = prev.filter(
                  (item) => !commonItems.includes(item)
                )
                const uniqueNow = now.filter(
                  (item) => !commonItems.includes(item)
                )

                onChange([...uniquePrev, ...uniqueNow])
              }}
...
```

Then I added this
```js
  const [key, setKey] = useState(0)
...
    <Controller
...
          onChangeValue={() => setKey(key + 1)}
...
```

Finally it works but still has major issues:
1. The component is forced to rerender so it will flash and affect UX.
2. In `mode="BADGE"`, if you click the badge, it will cause error. `Cannot convert undefined value to object`

**Comment by ProVival** [comment]
> > 
> 
> I tried this method for multiple selections. I can only pick one option every time. Any idea to make it work?
> 
> ```js
> ...
>   const [open, setOpen] = useState(false)
>   const items = [
>     { label: "Spain", value: "spain" },
>     { label: "Italy", value: "italy" },
>     { label: "Finland", value: "finland" },
>   ]
> ...
>       <Controller
>         defaultValue={[]}
>         name="country"
>         control={control}
>         render={({ field: { onChange, value } }) => (
>             <DropDownPicker
>               open={open}
>               setOpen={setOpen}
>               items={items}
>               value={value}
>               setValue={(callback: any) => onChange(callback())}
>               multiple={true}
>               mode="BADGE"
>             />
>         )}
>       />
> ```
> 
> edit: I tried to manipulate the value from callback(), but it's not working properly when I select multiple items. It only keeps the latest selection.
> 
> ```js
> ...
>     <Controller
> ...
>           setValue={(callback: any) => {
>                 const prev = value
>                 const now = [...callback()]
> 
>                 const commonItems = prev.filter((item) => now.includes(item))
>                 const uniquePrev = prev.filter(
>                   (item) => !commonItems.includes(item)
>                 )
>                 const uniqueNow = now.filter(
>                   (item) => !commonItems.includes(item)
>                 )
> 
>                 onChange([...uniquePrev, ...uniqueNow])
>               }}
> ...
> ```
> 
> Then I added this
> 
> ```js
>   const [key, setKey] = useState(0)
> ...
>     <Controller
> ...
>           onChangeValue={() => setKey(key + 1)}
> ...
> ```
> 
> Finally it works but still has major issues:
> 
> 1. The component is forced to rerender so it will flash and affect UX.
> 2. In `mode="BADGE"`, if you click the badge, it will cause error. `Cannot convert undefined value to object`

Have you ever solved this issue? I am having the same issue right now and it is driving me crazy :(

**Comment by ProVival** [comment]
Okay i solved it: 
i used `useController` hook from `react-hook-forms` instead of `Controller` component.

Basically using `useEffect` to update the form values
Structure of the code looks like this:
```
const RoleDropdown = ({
  control,
  name,
  rules = {},
  placeholder,
  isMultiple = false,
  zIndex,
  zIndexInverse,
}) => {
  const [open, setOpen] = useState(false);
  const [multiValue, setMultiValue] = useState(null);
  const [items, setItems] = useState([]);
 setItems([
          { label: "Car", value: "car" },
          { label: "Truck", value: "truck" },
        ]);
  const {
    field: { onChange, value },
  } = useController({ name, control, rules });

  useEffect(() => {
    console.log("multval: ", multiValue);
    onChange(multiValue);
  }, [multiValue]);
return (
    <View
      style={{
        zIndex: zIndex,
        zIndexInverse: zIndexInverse,
        alignItems: "center",
        marginBottom: 10,
      }}
    ><DropDownPicker
        mode="BADGE"
        multiple={isMultiple}
        searchable
        searchPlaceholder="Arama..."
        loading={loading}
        language="TR"
        value={multiValue}
        setValue={setMultiValue}
        placeholder={placeholder}
        placeholderStyle={{
          color: "grey",
          fontWeight: "bold",
        }}
        open={open}
        setOpen={setOpen}
        items={items}
        setItems={setItems}
      />
    </View>
  );
};
```
