### ISSUE TITLE
Example code from the screenshots?

### ISSUE THREAD

**Issue by bronz3son** [hossein-zare/react-native-dropdown-picker#449]
Hello, thanks for all the work on this library! It's great, and the documentation has been super helpful.

I am having a hard time getting my dropdown picker to look clean, though. For example, I can't get the arrow to the right of the placeholder like it is in the screenshots on the README.

Example code to reproduce the screenshots would be really helpful if it's possible to add them. Thanks!

**Comment by hossein-zare** [comment]
Hello,

Are you working on a RTL project? Otherwise the arrow must not be on the left side.
Currently i can't give you the code.

Try the `rtl` prop instead:
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/localization#rtl

**Comment by bronz3son** [comment]
Thanks for responding!
It's not RTL. The arrow is actually rendered below the text. I've attached a screenshot.

Here's my code: 
```
                      <DropDownPicker
                            placeholder="Select an item"
                            placeholderStyle={{
                                color: "black",
                                paddingLeft: 5,
                                paddingTop: 12,
                            }}
                            labelStyle={{
                                paddingLeft: 5,
                                paddingTop: 12,
                            }}
                            open={open}
                            value={value}
                            items={items}
                            setOpen={setOpen}
                            setValue={() => { console.log("selected") }}
                            setItems={setItems}
                            loading={loading}
                            searchable={true}
                            searchPlaceholder="Search..."
                            containerStyle={{ height: 100, backgroundColor: 'gray.50' }}
                            style={{ backgroundColor: '#D3D3D3', borderRadius: 5, height: 45, width: 200 }}
                            showArrowIcon={true}
                        />
```

![dropdownscreeshot](https://user-images.githubusercontent.com/93016505/139966386-7647915a-d679-4322-89c0-4b4849ffb004.png)

**Comment by hossein-zare** [comment]
All the `height` and `width` style props should live in the `containerStyle` prop.

```jsx
containerStyle={{ width: 200, height: 100, backgroundColor: 'gray.50' }}
style={{ backgroundColor: '#D3D3D3', borderRadius: 5, height: 45 }} // removed width: 200 and added to containerStyle
```

I didn't touch additional style keys, you may need to unset them yourself.

**Comment by bronz3son** [comment]
![Screen Shot 2021-11-03 at 8 47 42 AM](https://user-images.githubusercontent.com/93016505/140094582-27a83116-f731-44b5-8924-8a40aebac61c.png)

I got the arrow to the right with 
```
arrowIconContainerStyle={{ alignSelf: 'flex-end' }}
```

But it's still below the text. I was playing around and couldn't figure out how to easily center it. 

The checkmarks when I select an item also show up below. 

Are you saying that if I just use the defaults with no styling I should end up with the example screenshots?

Thank you for answering questions!

**Comment by hossein-zare** [comment]
You shouldn't play with flex-related keys.

Did you try https://github.com/hossein-zare/react-native-dropdown-picker/issues/449#issuecomment-959119199? What happened?

Just replace the style prop with:
```jsx
style={{ backgroundColor: '#D3D3D3', borderRadius: 5, height: 45 }}
```

**Comment by scerdal** [comment]
for anyone running into this issue, you're probably using this library on RN Web. So that's why the div's are rendered in columns. To fix this, you have to set `style={{flexDirection: 'row'}}`.
