### ISSUE TITLE
Dropdown list performance improvement 

### ISSUE THREAD

**Issue by dilinade** [hossein-zare/react-native-dropdown-picker#45]
**Is your feature request related to a problem? Please describe.**
I was trying to populate the dropdown with nearly 300 text items, then it get's bit laggy when opening the picker as all data items get populated.

**Describe the solution you'd like**
Use of a flatlist other than a scrollview would do. (I think)

**Describe alternatives you've considered**
Implementing a flatlist over the default scrollview.

**Comment by hossein-zare** [comment]
Hello,

Thank you for the pull request. I'll check it out for bugs and compatibility then merge it soon.
