### ISSUE TITLE
zIndex not working

### ISSUE THREAD

**Issue by ankit-abylle** [hossein-zare/react-native-dropdown-picker#450]
I am using this component but the dropdown menu is not showing properly.
![image](https://user-images.githubusercontent.com/89969214/140056599-53fb1b34-029d-4fab-b301-c0c6d32dcb8f.png)
 <DropDownPicker
        zIndex={1000}
                              open={isopen}
                              value={value}
                              items={items}
                              setOpen={setisOpen}
                              onChangeValue={(value) =>console.log(value)}
                              setItems={setItems} 
                              setValue={setValue}   
                              dropDownContainerStyle={{ zIndex:10000,backgroundColor:'white',elevation:1000}} />

**Comment by ankit-abylle** [comment]
I am using this in expo React native application.

**Comment by mikehardy** [comment]
#376

**Comment by ankit-abylle** [comment]
Hi @mikehardy Thanks for the reply.
but the other dropdown are different packages that i am replacing currently.
Also I tried removing all other Picker then also its the same .
![image](https://user-images.githubusercontent.com/89969214/140079067-809f602a-12e8-44ca-a727-63883207d35e.png)

**Comment by mikehardy** [comment]
There's a distinct lack of ability to help without a complete example https://stackoverflow.com/help/minimal-reproducible-example

The strategy I showed you can actually toggle the zIndexing of the entire app if needed so I believe it should not matter what other packages you are trying to use

**Comment by ankit-abylle** [comment]
@mikehardy Thanks Let me try the above steps you mentioned .
If found issue will create a example.

**Comment by KhanhDuy-123** [comment]
<View style={{zIndex: 1000}}>
 <DropDownPicker
   open={isopen}
   value={value}
   items={items}
   setOpen={setisOpen}
   onChangeValue={(value) =>console.log(value)}
   setItems={setItems}
   setValue={setValue}
  dropDownContainerStyle={{ zIndex:10000,backgroundColor:'white',elevation:1000}} />
</View>

i succeeded to wrap the view outside @ankit-abylle

**Comment by ankit-abylle** [comment]
@KhanhDuy-123  Thanks for the reply.
I tried with this but faced the same issue . Don't know why zIndex is not working for me.
At last I switched to [react-native-picker-select](https://github.com/lawnstarter/react-native-picker-select).
This package worked for both android and ios.

**Comment by hossein-zare** [comment]
@ankit-abylle 
@KhanhDuy-123 Your solution only works on iOS.

**Solution:**
```jsx
const isAndroid = Platform.OS === 'android';

<View style={! isAndroid && {zIndex: 100}}>
  <DropDownPicker
    ...
    dropDownContainerStyle={{backgroundColor:'white'}}
    zIndex={100} />
</View>

<View style={! isAndroid && {zIndex: 50}}>
  <DropDownPicker
    ...
    dropDownContainerStyle={{backgroundColor:'white'}}
    zIndex={50} />
</View>
```

You should also read https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers

As @mikehardy has said, Consider reproducing your issue in a **[Snack](https://snack.expo.dev/)**. 
> There's a distinct lack of ability to help without a complete example https://stackoverflow.com/help/minimal-reproducible-example
> 
> The strategy I showed you can actually toggle the zIndexing of the entire app if needed so I believe it should not matter what other packages you are trying to use

**Comment by chuantran3796** [comment]
ios: zIndex, android: elevation. it woking

**Comment by ospfranco** [comment]
Even with the wrapping view with zIndex, it doesn't seem to be working for me

<img width="1127" alt="Screenshot 000441" src="https://user-images.githubusercontent.com/1634213/167620092-c697eaae-9a8b-4075-9d2e-d8b4b64a7f72.png">

Any suggestion how to fix this?

**Comment by ospfranco** [comment]
Putting a zIndex value on the bottom one fixes this

**Comment by Linh-Vo** [comment]
> 

still didn't work on IOS

**Comment by Everkers** [comment]
In android sit the z-index of the element that you want it to appear above to -1
