### ISSUE TITLE
Working example for ArrowDownIconComponent

### ISSUE THREAD

**Issue by mugdho-debnath-hb** [hossein-zare/react-native-dropdown-picker#452]
Hi,
I wanted to customize the up and down arrows in the component and I imagine thats being done by the `ArrowDownIconComponent` and `ArrowUpIconComponent` attributes.

Right now I did this for a 64x64 image, but the image doesnt show up correctly.

```js
ArrowUpIconComponent={({style}) => (
    <Image
    source={require("../../../assets/chevron-up-font-awesome.png")}
    />
)}
```

I think I may be missing something. Do we have a working example somewhere I could use?
Thanks

**Comment by hossein-zare** [comment]
Hi, Give it a width and height.

```jsx
<Image source={...} style={{width: 35, height: 35}} />
```

If nothing changes, I'll dot it myself.
