### ISSUE TITLE
dropdown-picker picker.js does not support testID

### ISSUE THREAD

**Issue by salopeklm** [hossein-zare/react-native-dropdown-picker#453]
I added 'testID = {testID]' at line 155 right after 'theme = THEMES.DEFAULT'

And then modified line 1690 to
<TouchableOpacity style={_style} onPress={__onPress} onLayout={__onLayout} {...props} ref={onRef} pointerEvents={pointerEvents} disabled={disabled} testID={testID}>

And now my Dropdown component has a testID I can use to click the dropdown to expose the option list

I really have no idea how to go about making this change, sorry.

**Comment by mikehardy** [comment]
I think you can just click the little pencil button at the top right of the file on github and the web UI walks you through the process of making the PR - this link should open it right there for you ready to go https://github.com/hossein-zare/react-native-dropdown-picker/edit/dev-5.x/src/components/Picker.js

**Comment by salopeklm** [comment]
Thank you, I will try that

**Comment by salopeklm** [comment]
That worked!
https://github.com/hossein-zare/react-native-dropdown-picker/compare/dev-5.x...salopeklm:patch-1
https://github.com/hossein-zare/react-native-dropdown-picker/pull/454
Now what?

**Comment by mikehardy** [comment]
Really cool - I reviewed it and asked for a the original author to check it. It's open source so there are no time estimates provided :-), but one or the other of us can publish the change, it won't sit too long. Thanks for contributing!

Oh, in the meantime if you have never used https://github.com/ds300/patch-package - it was invented for things like this. You can integrate it (it's fast) then keep the patch in your own source control locally so it's a more "professional" patch. patch-package will give you a clean + friendly warning when a new version here comes out which will prompt you to remove the patch, assuming we've merged it here for release. That's what I do when I patch modules while waiting for PRs to review+merge+release

**Comment by salopeklm** [comment]
Thank you!
