### ISSUE TITLE
addCustomItem: duplicate items

### ISSUE THREAD

**Issue by saeedhabibi** [hossein-zare/react-native-dropdown-picker#456]
Hi
I tried to use the addCustomItem item feature.
But every time I add an item to it and select it again, another is added to it.

Take a look at this snack:

https://snack.expo.dev/@devsaeedhabibi/-add-item-dropdown

How can I solve it?

Thank you
![Screenshot_2021-11-10-02-13-25-338_host.exp.exponent.jpg](https://user-images.githubusercontent.com/15168601/141017367-c1935063-35dc-48ce-b97f-6c789ccfe033.jpg)

**Comment by hossein-zare** [comment]
**v5.3.0**
