### ISSUE TITLE
Clear current value button

### ISSUE THREAD

**Issue by justinwerd** [hossein-zare/react-native-dropdown-picker#458]
Hi, big fan of the component. One thing I can't seem to figure out is how to clear the contents of the dropdown if I happen to select a value I didn't want. Is there currently a way to do that?

**Comment by hossein-zare** [comment]
Hi,

You can simply filter the selected values and exclude the one you want or unselect them one by one.
```jsx
const [value, setValue] = useState(['a', 'b', 'c']);

// exclude 'a'
setValue(state => state.filter(item => item !== 'a'));

// unselect latest values
setValue(state => state.slice(0, state.length - 1));
```
