### ISSUE TITLE
Long labels handling

### ISSUE THREAD

**Issue by CyberTron88** [hossein-zare/react-native-dropdown-picker#460]
Is it possible to show multiple lines or wrap text on the list for each item label, but on the main label, it will show a single line with ellipsis ?

Right now, I see the default behaviour is reversed. There is not wrapping on the list item, each item is a long line with overflow hidden while there is wrapping on the main label itself.

**Comment by hossein-zare** [comment]
You should play with style props listed on https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items

I think it's achievable.

**Comment by omercankorkmaz** [comment]
@CyberTron88, @hossein-zare 

I achieved label handling:

            renderListItem={(props) => {
                return (
                    <TouchableOpacity 
                    {...props} 
                    style={[props.listItemContainerStyle, { backgroundColor: props.isSelected ? primaryColors.grey[200] : primaryColors.grey[100] } ]} 
                    onPress={() => { componentProps.setValue(props.value); componentProps.setOpen(false) }} 
                    >
                        <MaterialCommunityIcons name={ props.isSelected ? 'check' : 'circle-small'} size={20} />
                        <Text numberOfLines={1} ellipsizeMode='tail' style={props.listItemLabelStyle}>
                            {props.label}
                        </Text>
                    </TouchableOpacity>
                );
            }}

with using JSX attributes (numberOfLines={1} ellipsizeMode='tail') on Text tag,
for sure you need to create custom component for listing items like above.

**Comment by jcanabarro** [comment]
Hey i don't know if is still relevant, but i was able to solve with a much simpler solution, just add the following options on the style

```typescript
listItemContainerStyle={{
            flex: 1,
            padding: 5
        }}
```

And on the `style` prop you could add `flex: 1` as well.

Works like a charm
