### ISSUE TITLE
Make it possible to render icon only for label

### ISSUE THREAD

**Issue by jmontenegronc** [hossein-zare/react-native-dropdown-picker#463]
I'm trying to render an icon but only at the label level. I don't want the dropdown items themselves to have icons, but only have an icon render next to the dropdown label. Is this possible?

**Comment by hossein-zare** [comment]
You should customize the `RenderListItem` component.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#renderlistitem

https://github.com/hossein-zare/react-native-dropdown-picker/blob/de81392cda0f270584a201244a6ce1b59559fe24/src/components/RenderListItem.js#L164-L167
Simply take out the `{IconComponent}`, That's it.

**Comment by jmontenegronc** [comment]
Hi @hossein-zare. Thanks for your prompt response. I saw that method but I was hoping that there was another way of achieving this without having to copy the whole `RenderListItem.js` file and only removing a couple of lines. It seems like for now that's the only way of doing this though so I'll close the issue.

**Comment by mikehardy** [comment]
patch-package! https://github.com/ds300/patch-package

**Comment by jmontenegronc** [comment]
@mikehardy thanks for that recommendation! The only issue I see with that is if later we do need to show the icons on the dropdown on some other part of the app. Passing a prop to `DropDownPicker` that'd determine that behavior would be more extensible in that case. I might submit a PR for this feature if I see we need this in the future, or in case other people need it as well.
