### ISSUE TITLE
side borders not showing on black background on android

### ISSUE THREAD

**Issue by vigdikshit** [hossein-zare/react-native-dropdown-picker#466]
Hi,

I am using the picker on black background but the side borders are not showing on black background on android. Borders can be seen in ios.

Screenshot from android: 
![dropdown_picker_issue](https://user-images.githubusercontent.com/39395991/143789101-c1232c34-d66a-4bf3-b78b-614d676a3fe7.PNG)

Code:
 <View style={[tailwind('pt-12'), (Platform.OS === 'ios' ? {zIndex: open ? 1 : 0} : {})]}>
                <DropDownPicker
                    open={open}
                    value={country}
                    items={items}
                    setOpen={setOpen}
                    setValue={setCountry}
                    setItems={setItems}
                    style={[tailwind('bg-black border border-gray-700')]}
                    textStyle={[tailwind('text-white text-lg')]}
                    dropDownContainerStyle={[tailwind('bg-black border-gray-700')]}
                  //  listMode={'SCROLLVIEW'}
                />
            </View>

**Comment by hossein-zare** [comment]
Hi,
Could you please create a snack?
