### ISSUE TITLE
Items in my dropdown component depending on a hook

### ISSUE THREAD

**Issue by rochijacob** [hossein-zare/react-native-dropdown-picker#470]
Hi, I am using Dropdown Picker in order to filter content. As you can see in the picture i have various fields and i want the picker's data to depend on the radio button I select previously, otherwise, if no "Provincia" is selected, the dropdown is disabled. I can't manage to get my head around this issue, and I want to understand if its possible to render items dynamically

![image](https://user-images.githubusercontent.com/57420970/144599075-a801879c-c4d0-4756-b911-27b8971d4292.png)

In the image, the picker does not activate until I click on a radio buttons. 

Here is the data structure used to render items in the Dropdown: 

export const zona = [
  {
    label: "Adrogué",
    value: "adrogué",
    provincia: "gba sur",
  },
  {
    label: "Agronomía",
    value: "agronomía",
    provincia: "caba",
  } ......., ]

so if the field provincia matches with my selection, those items should be rendered. The following code returns the full list of 'zonas'. 

![image](https://user-images.githubusercontent.com/57420970/144599324-77e33a74-a067-467b-bb2f-1db32e010aa6.png)

**Comment by mikehardy** [comment]
From your issue, I don't see a clear detailed problem statement.

I propose you make a runnable Snack so others can actually see it, and describe *exactly what is not working* versus just a loose description of an idea.

I believe at any time you can 
- have buttons (your filters) call handlers that change state
- have a useEffect that is conditional on that state
- in that useEffect you can mutate your list of possible values for the dropdown and set them as state
- have the dropdown render what is currently in list of possible values in dropdown state

In general this is just an API usage question then, I don't think it will result in any change on the module. It might be best asked on stackoverflow as the issues list should be for bugs, not usage problems

**Comment by rochijacob** [comment]
Thank you, I think with the use state you just answerd my question. The general idea was related to wether the state of the dropdown items was changable. 

Sorry for not being clear enough! Im slowly learning react native and my question making is not so good!

**Comment by mikehardy** [comment]
No problem, I've actually been doing it *too long* so I'm used to class components. You should see my hooks code! not so good. But we'll all get there. Good luck with your project
