### ISSUE TITLE
Display value instead of label

### ISSUE THREAD

**Issue by Maharshi01** [hossein-zare/react-native-dropdown-picker#471]
Is it possible to display the value selected instead of the label after selecting any label from dropdown?

**Comment by hossein-zare** [comment]
Hello, No.

**Comment by uyend** [comment]
Hey @hossein-zare can we re-open this, it would be nice if the selected label was customisable instead of being so strict on having it the same label as the options. 

Should just be updating the item config to accept selectedLabel and this is what we display and fallback being the label

**Comment by dayoolacodes** [comment]
Hi @hossein-zare can we re-open this. display value needs to be customisable.
