### ISSUE TITLE
dropdown displaying under the collapsible header

### ISSUE THREAD

**Issue by Maharshi01** [hossein-zare/react-native-dropdown-picker#472]
Looks like there is an issue when the dropdown is rendered inside the collapsible. The collapsible header is displaying on top of the dropdown which making the dropdown not visible. 

<img width="343" alt="Screenshot 2021-12-03 at 8 49 39 PM" src="https://user-images.githubusercontent.com/48430425/144627243-0e0ffaed-b078-4485-b3aa-c90a30cace0e.png">

**Comment by hossein-zare** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker/issues/376
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#zindex
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/multiple-pickers
