### ISSUE TITLE
Loading not showing ActivityIndicator

### ISSUE THREAD

**Issue by mauricionuup** [hossein-zare/react-native-dropdown-picker#473]
I'm not seeing the Activity Indicator when loading is set to true. 
Should something like this show an Activity indicator instead of the Picker, or am I getting this wrong. 
```javascript
    <View >
      <DropDownPicker
          open={open}
          value={1}
          items={items}
          setOpen={setOpen}
          setValue={setvalue}
          setItems={setItems}
          loading={true}
        />
    </View>
```

(obviously should be a variable, but I'm just not being able to see the Activity Indicator ever)

**Comment by hossein-zare** [comment]
When there are no items (`ListEmptyComponent` is rendered) an `ActivityIndicator` is inside the component, So make sure you have nothing assigned to `items`.

**Condition:** `items = []`

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#listemptycomponent
