### ISSUE TITLE
Get selected Item instead of selected item.value in callback

### ISSUE THREAD

**Issue by Maxfurry** [hossein-zare/react-native-dropdown-picker#474]
I am having a use case where I need the full item selected instead of the item.label.
I would have use array.find or any other loop but the list is thousands long and also paginated. This makes looping through the list to get the item (object) selected inefficient.

I checked previous versions and I saw that there was a prop "onChangeItem" in version before 5.0, which fits my use case but has been removed.
Is there any way to achieve this effect?

Thanks.

**Comment by hossein-zare** [comment]
No, It'll be added in the next version.

**Comment by Maxfurry** [comment]
> No, It'll be added in the next version.

@hossein-zare Please, how long to the release of this next version?

**Comment by hossein-zare** [comment]
I don't know, 2 / 3 weeks later.

**Comment by Maxfurry** [comment]
@hossein-zare I am seeing a done label. Has this issue been resolved and what callback should be used?

**Comment by hossein-zare** [comment]
@Maxfurry It has not yet been released.

Prop:
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/usage#onselectitem

**Comment by Maxfurry** [comment]
@hossein-zare Thanks a lot. When will it be released?

**Comment by hossein-zare** [comment]
Before 2022

**Comment by Maxfurry** [comment]
@hossein-zare Thanks a lot. Will be expecting it sometime next week.

**Comment by hossein-zare** [comment]
@Maxfurry 

This beta version may have bugs, Please let me know.
`react-native-dropdown-picker@5.2.5-beta.0`

**Comment by hossein-zare** [comment]
**v5.3.0**
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/usage#onselectitem
