### ISSUE TITLE
keyboardShouldPersistTaps is not working with MODAL listmode.

### ISSUE THREAD

**Issue by jackwullems** [hossein-zare/react-native-dropdown-picker#475]
I have created a pull request #75 to support passing ScrollView props into the dropdown picker. You can pass scrollView props by passing 

`<DropDownPicker
    {...props}
    scrollViewProps={{
        keyboardShouldPersistTaps='handled'
    }}
/>`

_Originally posted by @thebluewall2 in https://github.com/hossein-zare/react-native-dropdown-picker/issues/59#issuecomment-664216416_

**Comment by hossein-zare** [comment]
If you are using the `FLATLIST` mode you should add the same object to `flatListProps`.
And it's `keyboardShouldPersistTaps: 'handled'` not `keyboardShouldPersistTaps='handled'`

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes

**Comment by jackwullems** [comment]
I am using MODAL listmode. keyboardShouldPersistTaps is not available in modalprops.
