### ISSUE TITLE
I am using MODAL listmode. keyboardShouldPersistTaps is not available in modalprops.

### ISSUE THREAD

**Issue by jackwullems** [hossein-zare/react-native-dropdown-picker#476]
I am using MODAL listmode. keyboardShouldPersistTaps is not available in modalprops.

_Originally posted by @jackwullems in https://github.com/hossein-zare/react-native-dropdown-picker/issues/475#issuecomment-986091518_

**Comment by hossein-zare** [comment]
For `MODAL` add it to the `flatListProps` prop.
```js
flatListProps={{keyboardShouldPersistTaps: 'handled'}}
```

**Comment by jackwullems** [comment]
it works.
thank you.
is it not supported typescript?
It's warnning defining keyboardShouldPersistTaps in flatListProps.
![image](https://user-images.githubusercontent.com/51687189/144787297-1295b368-6bf7-4b6f-b4a0-0b96177c8596.png)

**Comment by hossein-zare** [comment]
**Quick fix:**
```js
// @ts-ignore
flatListProps={{ ... }}
```

I'll fix it later.

**Comment by mikehardy** [comment]
Alternatively @jackwullems post a PR to the types! It would really help - community contributions will help this library move forward faster
