### ISSUE TITLE
Unable to change placeholder

### ISSUE THREAD

**Issue by MarioQuiroga32** [hossein-zare/react-native-dropdown-picker#477]
Hi. I'm currently using version 5.2.3, and I'm having trouble trying to use a custom placeholder. This is what my component looks like:

```
<DropdownPicker
	open={open}
	value={value}
	setOpen={setOpen}
	setValue={setValue}
	buildFilters={buildFilters}
	placeholder={'Test'}
/>
```

I guess it should be rendering the word 'Test' as a placeholder but it is instead using the default ones. 'Select an item' when no items are selected and '_n_ item(s) have been selected' when one or more items are selected.

**Comment by hossein-zare** [comment]
Hi,

Its seems that you have wrapped the picker in another component which means that some of the props arent passed to the picker.

❗You've not provided enough code and information.

**Comment by MarioQuiroga32** [comment]
That's indeed the case, thanks a lot.
