### ISSUE TITLE
Customize Label and list items

### ISSUE THREAD

**Issue by buscanopaul** [hossein-zare/react-native-dropdown-picker#479]
Hi, Is there a way to customize the design or the label and the list items look like this?
<img width="276" alt="Screen Shot 2021-12-13 at 4 45 02 PM" src="https://user-images.githubusercontent.com/17734014/145779990-8bc3a927-63a0-499e-8e5a-9aa83e6880a5.png">

Below is the sample array:
```
const remoteItems = [
  {id: 1, title: 'Item 1', image: 'http.........', phone: 09235 , val: 'item-1'},
  {id: 2, title: 'Item 2', image: 'http.........', phone: 09235, val: 'item-2'},
];
```

Hoping for your response. Thank you

**Comment by mikehardy** [comment]
What have you tried? Share your snack
