### ISSUE TITLE
selectedLabelStyle ? (image in description)

### ISSUE THREAD

**Issue by usersina** [hossein-zare/react-native-dropdown-picker#48]
**Description:**
labelStyle edits all of the label styles.
activeLabelStyle edits the active label style in the dropdown window only (when you open the dropdown).
However, the one that is seen before pressing on the dropdown (not sure what to call it) doesn't have a style to it.

Here's an [image](https://i.imgur.com/TvTgNL3.jpg)

**Solution:**
Adding a selectedtLabelStyle to edit the selected label text separately. (Maybe it's there and I missed it ?)

**Comment by hossein-zare** [comment]
Hello,

Today i'm going to release a new version with the suggested property.

**Comment by hossein-zare** [comment]
**v3.1.1** is out.
`selectedtLabelStyle` has been added.

**Comment by usersina** [comment]
The property doesn't work, tried disabling other styles in case one of them was interfering but no result.

**Comment by hossein-zare** [comment]
Try ***v3.1.5***

There was a typo. `selectedtLabelStyle` -> `selectedLabelStyle`.
https://snack.expo.io/@hossein-zare/v3.1.5
