### ISSUE TITLE
Close modal when back button pressed

### ISSUE THREAD

**Issue by herbertizidro** [hossein-zare/react-native-dropdown-picker#480]
Could you add this functionality to the modal?
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/5.0/advanced/list-modes

**Comment by herbertizidro** [comment]
@hossein-zare it will be necessary to declare a prop?

**Comment by hossein-zare** [comment]
@herbertizidro Yes
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/changelog

**Comment by herbertizidro** [comment]
thank you

**Comment by herbertizidro** [comment]
ok. thank you!

**Comment by hossein-zare** [comment]
**v5.3.0**
