### ISSUE TITLE
Undefined is not an object (evaluating '_ref8.label')

### ISSUE THREAD

**Issue by krishna11124** [hossein-zare/react-native-dropdown-picker#481]
Hello i Using "react-native-dropdown-picker": "^5.0.0", When i Pick selected value i m facing this issue.
![screenshot-1639650738429](https://user-images.githubusercontent.com/38029697/146361553-f3397014-5e36-4046-8766-00cfbfa77c3c.png)
.

Please See And Revert Me Thanks

**Comment by mikehardy** [comment]
Google minimum reproducible example stackoverflow

Google how to ask stackoverflow
