### ISSUE TITLE
Can't press item or search when dropdown is open on Android

### ISSUE THREAD

**Issue by huytq98** [hossein-zare/react-native-dropdown-picker#486]
Can't press item or search when dropdown is open on Android

<img width="342" alt="Screen Shot 2021-12-29 at 22 59 28" src="https://user-images.githubusercontent.com/68173339/147680742-be71553a-2f03-4148-8331-00735c87114d.png">

Here is my code on snack
https://snack.expo.dev/@kulboiz/d208f2

Here my code
<View style={{flexDirection: 'row'}}>

        <View
           style={{
            ...(Platform.OS !== 'android' && {
              zIndex: 10,
            }),
          }}>

          <DropDownPicker
            style={{zIndex: 10,
            width: '90@s',
            borderWidth: 0,
            borderBottomWidth: 1,
            }
            containerStyle={{ width: s(85), zIndex: 10 }}
            dropDownContainerStyle={{ zIndex: 10,
                 width: '90@s',
                 borderTopWidth: 1,
                 borderWidth: 0,
            }
            placeholder={'Choice'}
            placeholderStyle={styles.placeholder}
            open={showData}
            value={valueSelect}
            items={items}
            setOpen={setShowData}
            setValue={setValueSelect}
            searchPlaceholder={'Search'}
            searchTextInputProps={{ keyboardType: 'number-pad' }}
            searchable
            listMode={'SCROLLVIEW'}
            itemSeparator={true}
            itemSeparatorStyle={{ backgroundColor: Color.GRAY_1 }}
            showTickIcon={false}
            ArrowUpIconComponent={() => <FastImage source={images.arrow_up} style={styles.icon} />}
            ArrowDownIconComponent={() => <FastImage source={images.arrow_down} style={styles.icon} />}
            selectedItemLabelStyle={{ fontFamily: 'Montserrat-SemiBold' }}
            textStyle={styles.textDropdown}
          />

        </View>

        <View style={{ flexDirection: 'row', flex: 1 }}>
          <TextInput
            placeholder={t('placeholder_phone')}
            placeholderTextColor={Color.GRAY}
            style={styles.input}
            onChangeText={onValueText}
            value={value}
            keyboardType={'number-pad'}
            maxLength={15}
            onBlur={onBlur}
          />
          <AppButton
            containerStyle={styles.btn}
            title={confirm ? 'RE-SEND' : 'SEND'}
            onPress={_handleSend}
            disable={_checkSend()}
          />
        </View>
      </View>

I have tried put zIndex in every style relative to dropdown but it still working on Android
It can press when I put <View style={{height : 300}} /> below the Dropdown but the layout look ridiculous
Any solution?

**Comment by whytdan** [comment]
This is my solution: 
```
<View
    style={[
      styles.pickerParent,
      Platform.OS === "android" && isSkillsPickerOpen
        ? styles.pickerAndroidParent
        : null,
    ]}
  >
    <DropDownPicker
      open={isSkillsPickerOpen}
      ...
    />
 </View>
```
and for style
```
pickerAndroidParent: {
    minHeight: 250,
  },
```
P.S. About layout looking ridiculous, adjust the minHeight of a wrapping view so that it would look natural to the content below picker be pushed down.
![IMAGE 2021-12-31 03:51:04](https://user-images.githubusercontent.com/43886010/147790300-a042b354-7e62-491d-9054-fdc2eb3a142a.jpg)
![IMAGE 2021-12-31 03:51:21](https://user-images.githubusercontent.com/43886010/147790310-9d07da27-298a-488c-9e99-cc690f471997.jpg)
