### ISSUE TITLE
Limiting the number of lines of the selected label

### ISSUE THREAD

**Issue by usersina** [hossein-zare/react-native-dropdown-picker#49]
**Description**
Not exactly a bug

**Expected behavior**
Limiting the number of lines that can be shown in the text.

Here's an [image.](https://i.imgur.com/jTtnUwr.jpg)

**Comment by hossein-zare** [comment]
There's no way, You have to map and `string.substr(start, length)` your label text.

**Comment by usersina** [comment]
How about making the label a JSX, same with the searchableError so that the label can easily be customized.

**Comment by hossein-zare** [comment]
I'll think of that when getting the next version ready.

**Comment by hossein-zare** [comment]
```javascript
labelLength={10}
selectedLabelLength={10}
```
