### ISSUE TITLE
Default values doesn't show when mode is set to 'BADGE'

### ISSUE THREAD

**Issue by erez-unitronics** [hossein-zare/react-native-dropdown-picker#492]
Hi,

I am trying to display default values (as badges) on my picker (which should replacing the placeholder) by initialize the value at the beginning but the only thing i can see is the placeholder and no items are already picked.

example: 

const [open, setOpen] = useState(false);
const [items, setItems] = useState(props.items);
const [value, setValue] =  useState(props.defaultValues);  // defaultValues is an array of objects which are part of the items;

        <DropDownPicker
            listMode={'MODAL'}
            mode={'BADGE'}
            showBadgeDot={true}
            multiple={true}
            min={0}
            max={5}
            searchable={true}
            showTickIcon={true}
            dropDownDirection={'BOTTOM'}
            placeholder={props.placeholder}
            open={open}
            setOpen={setOpen}
            items={props.items}
            setItems={setItems}
            value={value}
            setValue={setValue}
/>

Am I doing something wrong?

Thanks!

**Comment by ahmadsyed** [comment]
Hi @erez-unitronics , did you got any solution for this ?

**Comment by dacapoo** [comment]
Any solution ?

**Comment by ahmadsyed** [comment]
Yes, @dacapoo , I was passing the whole object into setValue(), had to pass just the Ids like [2,5,9]. comment here if it helps.
