### ISSUE TITLE
Item selection is not working

### ISSUE THREAD

**Issue by aezhcr** [hossein-zare/react-native-dropdown-picker#495]
Hi I am not able to select items from the drop-down menu please help.

  <DropDownPicker
          listMode="SCROLLVIEW"
          scrollViewProps={{
            decelerationRate: 'fast',
          }}
          maxHeight={300}
          containerStyle={{
            width: 250,
          }}
          renderListItem={props => {
              <View>
                <View
                  style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    justifyContent: 'flex-end',
                  }}>
                  <Text style={{color: '#000'}}>{props.label}</Text>
                  <Image
                    style={{height: 20, width: 20, margin: 8}}
                    source={props.value}
                  />
                </View>
                <View
                  style={{
                    borderBottomColor: '#7B8288',
                    borderBottomWidth: 1,
                    opacity: 0.15,
                  }}
                />
              </View>
          }}
          open={open}
          value={value}
          items={coinSalesList}
          setOpen={setOpen}
          setValue={setValue}
          // setItems={setCoinSalesList}
        />

**Comment by hossein-zare** [comment]
Hi,

Please create a snack.
