### ISSUE TITLE
TypeError:TypeError: undefined is not an object (evaluating 'iter[Symbol.iterator]') inside the setValue when using dropdownpicker with multiple values.The setValue is not returning the array of values selected although it works if the component is not multiple.

### ISSUE THREAD

**Issue by yousef71** [hossein-zare/react-native-dropdown-picker#496]
<DropDownPicker
                                key={inputItem.id}
                                ArrowDownIconComponent={() => <DropDownIcon />}
                                style={styles.DropDownPickerStyle}
                                multiple={true}
                                min={1}
                                max={3}
                                open={isOpenAtt[index].open}
                                setOpen={() => updateFieldChangedAtt(index)}
                                value={dynamicAttributesValues[index]}
                                setValue={v => {
                                  console.log('v', v());
                                }}
                                items={inputItem.options
                                  .map((i: any) => {
                                    return {label: i.label, value: i.value};
                                  })
                                  .sort((a: any, b: any) =>
                                    a.label.localeCompare(b.label),
                                  )}
                                listMode="SCROLLVIEW"
                                scrollViewProps={{
                                  nestedScrollEnabled: true,
                                }}
                              />

**Comment by hossein-zare** [comment]
You've passed `console.log('v', v());` rather than a real `setState` function to the `setValue` prop!

**Comment by yousef71** [comment]
I am using a dynamic drop down with dynamic values. I Can't put it as a useState.
@hossein-zare

**Comment by hossein-zare** [comment]
So how are your values stored? Simplify your data/component and send it here, i'll help you.
