### ISSUE TITLE
No defaultValue prop for DropDownPicker

### ISSUE THREAD

**Issue by zeroxjackson** [hossein-zare/react-native-dropdown-picker#497]
Currently I'm using the workaround of making my placeholder the value that I want as my initial value, but this is pretty annoying because then when you open the drop down it isn't selected in the list.

If there was a defaultValue or initialValue prop, that would improve the usability of this component a lot.

**Comment by hossein-zare** [comment]
Have you ever tried the `useEffect` hook?

```js 
import { useEffect } from 'react';

function App() {
    ...

    useEffect(() => {
        setValue('item-value');
    }, []);

    ...
}
```

**Comment by jacksonet00** [comment]
Definitely aware of how to work around this, defaultValue prop would be a big improvement.
