### ISSUE TITLE
background style issue

### ISSUE THREAD

**Issue by shikhawebvillee** [hossein-zare/react-native-dropdown-picker#5]
Hello @hossein-zare

Can we set background style ? 
 we have an issue on set borderWidth in containerStyle , dropdown list is not showing properly.

![dropdown](https://user-images.githubusercontent.com/25429822/81148568-25322400-8f9a-11ea-9d40-c75cd6ce87f3.png)

Without borderWidth it's working fine.Please help

Thanks.

**Comment by hossein-zare** [comment]
Hello @shikhawebvillee 

**Update the package to 2.1.1**
Try to add your `borderWidth` or background styles to the `style` property not `containerStyle`
