### ISSUE TITLE
Search bar is not responsive if the dropdown is on top

### ISSUE THREAD

**Issue by usersina** [hossein-zare/react-native-dropdown-picker#50]
**TL;DR**
Here's an [image.](https://i.imgur.com/Xaqf9JE.jpg)

**Bug description:**
The dropdown is below other views (they display on top of it).
If I try to add an elevation to the dropdown style, the view looks good however the search doesn't display the keyboard when pressed.
zIndex has no effect (maybe I used it wrong).

**Here's the code:**
App.js:
```Javascript
return (
    <SafeAreaView>
      <MyDropView />
      <AdComponent />
      <OtherComponent />
    </SafeAreaView>
  );
```
MyDropView.js:
```Javascript
return (
    <View style={{flexDirection: 'row'}}>
      <DropDownPicker
        searchable={true}
        searchablePlaceholder="Search..."
        searchableError={() => 'Not found'}
        ...
        containerStyle={{height: 40, width: '100%'}}
        dropDownStyle={{ elevation: 1 }} // The dropdown is on top, but search in unresponsive
      />
    </View>
  );
```

**Expected behavior**
The dropdown is displayed on top of all view and the search feature works.

**Info:**
 - OS: [Android]
 - Package version [28]

**Comment by hossein-zare** [comment]
Hello,
Does it happen without `elevation`?

Try this:
```javascript
import { Platform } from 'react-native';
 
<View style={{
    flexDirection: 'row',

    ...(Platform.OS !== 'android' && {
        zIndex: 10
     })

}}>
      <DropDownPicker
          searchable={true}
          searchablePlaceholder="Search..."
          searchableError={() => 'Not found'}
          ...
          containerStyle={{height: 40, width: '100%'}}
          dropDownStyle={{ elevation: 1 }} // The dropdown is on top, but search in unresponsive
      />
</View>
```

**Comment by usersina** [comment]
Without elevation, the dropdown is behind everything else in the view.
With elevation, the dropdown is on top of everything else but the click detection is still behind everything else.
If it's not clear, I'll try to demonstrate it using a gif

**Comment by hossein-zare** [comment]
Try the suggested code without `elevation`

**Comment by usersina** [comment]
Already did, here are the current results:
With the suggested code: [without_elevation](https://i.imgur.com/iWzvOhS.jpg)
With elevation (with or without zIndex): [with_elevation](https://i.imgur.com/WLI3NDj.jpg)
Clickable area: [Image](https://i.imgur.com/ypTOilO.jpg)
Clickable area: [Gif](https://i.imgur.com/QkYRL30.gifv)

Here's a [stackoverflow link](https://stackoverflow.com/questions/62754685/react-native-using-selectable-style-to-make-a-dropdown-picker-on-top-of-all-vie) with better explanation.

**Comment by hossein-zare** [comment]
I created a snack which is working fine.
https://snack.expo.io/@hossein-zare/d38de5

You can edit the code and reproduce the unexpected behavior then send your snack to me.

**Comment by usersina** [comment]
Couldn't replicate the error. 
However -oddly enough- when I toggle the inspector on and off, the dropdown behaves normally

**Comment by hossein-zare** [comment]
Unfortunately i can't help you without having an exact and static behavior.
The `elevation` property is not a solution and must be avoided.
Check the other components if they have any `zIndex`.

**Comment by usersina** [comment]
I've wrapped the dropdown picker and the below components under a `ScrollView` and it's working. However I'm getting the following [VirtualizedLists warning](https://stackoverflow.com/questions/58243680/react-native-another-virtualizedlist-backed-container). Should I simply ignore it ?

Anyway, the issue shouldn't even happen on android from what I've seen. Do you have an idea to what might be causing it ?

**Comment by hossein-zare** [comment]
No, Try to get rid of the warning by fixing the issue.
I believe it's a zIndex conflict or nested views problem.
