### ISSUE TITLE
How to remove modal header

### ISSUE THREAD

**Issue by LucasHimelfarb** [hossein-zare/react-native-dropdown-picker#501]
I need remove header or add style. but in the documentation I do not find how

![Screenshot_2022-01-26-12-20-12-727_com oliverapp](https://user-images.githubusercontent.com/46998551/151192453-2314f970-ff11-4cc3-bc53-6f14bd2dbe56.jpg)

**Comment by hossein-zare** [comment]
You can't remove the header but stylable.

**Useful links:**
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#styling
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/search#styling
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/themes

```jsx
searchContainerStyle={{
  borderBottomColor: "#dfdfdf"
}}
```

**Comment by LucasHimelfarb** [comment]
ok! Works for me. So the header is "searchable" content. Thanks for your fast answer 💯
