### ISSUE TITLE
SVGs don't appear beside the list item

### ISSUE THREAD

**Issue by asamiz** [hossein-zare/react-native-dropdown-picker#504]
Hello,

Firstly, Thank you so much for your efforts!

I am trying to render an SVG element as an icon for the element but It doesn't appear.

Here's my simple code:

```TypeScript
export const DropDown = () => {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState(null);
  const [items, setItems] = useState([
    {
      label: 'Brazil',
      value: 'Br',
      icon: () => <BrFlag />, // this is an SVG for Brazil flag
    },
  ]);
  return (
    <DropDownPicker
      schema={{
        label: 'label',
        value: 'value',
        icon: 'icon',
      }}
      open={open}
      value={value}
      items={items}
      setOpen={setOpen}
      setValue={setValue}
      setItems={setItems}
    />
  );
};
```

and here is the output of this code:

![Output](https://user-images.githubusercontent.com/22711584/151717689-c8008f2a-e397-4aa0-9b2f-2699f441e2ef.png)

Thanks in advance!

**Comment by hossein-zare** [comment]
Hi,

is the SVG component visible if you put it in a plain view?

Try `width` and `height` props with it.
> Import your .svg file inside a React component:
> `import Logo from './logo.svg';`
>
> You can then use your image as a component:
> `<Logo width={120} height={40} />`
>
> _https://github.com/react-native-svg/react-native-svg#use-with-svg-files_

**Comment by asamiz** [comment]
@hossein-zare 
Ooops, so sorry I thought I passed the width and height for the SVG.
Thank you so much for your help.
