### ISSUE TITLE
Documentation or Examples to match Screenshots

### ISSUE THREAD

**Issue by Welborn09** [hossein-zare/react-native-dropdown-picker#505]
Hello, I heard about this control from openbase and thought I would try it. The screenshot you have there shows the panel open, items checkboxed and Chips or Tags of the selected items in the panel. However, I cannot find anywhere an example showing how to do this. I see a tutorial with very little relevant information but nothing that helps.

Do you know of a site where someone has created what you show in the screenshot?

Here is what I am referencing:
https://openbase.com/js/react-native-dropdown-picker

**Comment by hossein-zare** [comment]
Hello,

```jsx
const [items, setItems] = useState([
  {label: 'North America', value: 'na'},
  {label: 'United States', value: 'usa', parent: 'na'},
  {label: 'Canada', value: 'canada', parent: 'na'},

  {label: 'Europe', value: 'eu'},
  {label: 'Norway', value: 'norway', parent: 'eu'},
  {label: 'Belgium', value: 'belgium', parent: 'eu'},
]);

<DropDownPicker
  items={items}
  setItems={setItems}
  mode="BADGE"
  ... />
```

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/category
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/modes
