### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by hiteshk086** [hossein-zare/react-native-dropdown-picker#506]
export const Menu_screens = [
  {
    id: 1,
    label: "India",
    value: "India",
    food: [
      {
        id: 1,
        name: "Panjabi",
      },
      {
        id: 2,
        name: "Chaines",
      },
      {
        id: 3,
        name: "Dhosa",
      },
    ],
  },
  {
    id: 2,
    label: "USA",
    value: "USA",
    food: [
      {
        id: 1,
        name: "Pizza",
      },
      {
        id: 2,
        name: "Burger",
      },
      {
        id: 3,
        name: "Pasta",
      },
    ],
  },
  {
    id: 3,
    label: "Chaina",
    value: "Chaina",
    food: [
      {
        id: 1,
        name: "Nuddels",
      },
      {
        id: 2,
        name: "Sushi",
      },
      {
        id: 3,
        name: "Soup",
      },
    ],
  },
  {
    id: 4,
    label: "Malaysia",
    value: "Malaysia",
    food: [
      {
        id: 1,
        name: "Mee goreng mamak",
      },
      {
        id: 2,
        name: "Apam balik",
      },
      {
        id: 3,
        name: "Nasi kerabu",
      },
    ],
  },
];

**Comment by fmcalado** [comment]
How did u fix it @hiteshk086 ?
