### ISSUE TITLE
ModalContentContainerStyle prop does not allow me to change the height of the Content

### ISSUE THREAD

**Issue by 4RGUS** [hossein-zare/react-native-dropdown-picker#507]
Currently the modal opens full screen. What I need is to create a smaller card shaped modal. I tried to use ModalContentContainerStyle. But the it does not respond to height property. Also it does not align and justify to center.

**Comment by hhgandhi** [comment]
@4RGUS , Did you find any solution? For align and center I have set using a window size in modalContentContainerStyle. but it's not the proper way to do this.

```
backgroundColor: 'rgba(255, 255, 255, 1)',
marginLeft: Dimensions.get('window').width / 2,
borderRadius: 5,
width: 145
```

Can you please guide me? @hossein-zare

**Comment by hossein-zare** [comment]
@4RGUS @hhgandhi 
React native's Modal component doesn't support customizing the width and height.

But if you really want to do that somehow:
```jsx
listMode="MODAL"
modalContentContainerStyle={{
  backgroundColor: '#fff',
  borderColor: '#000',
  borderWidth: 1,
  marginVertical: 200,
  marginHorizontal: 20,
  borderRadius: 15
}}
modalProps={{
  transparent: true,
  presentationStyle: 'overFullScreen' // for iOS, but raises a warning on android if not present
}}
```

![asdasd](https://user-images.githubusercontent.com/56504893/153477040-e70d1f0b-0f01-447c-89e6-619a31cd806f.png)


Note: Implement some logic for appropriate margin values on all devices.

**Comment by 4RGUS** [comment]
I used this:

```
  modalContentContainerStyle={{
      zIndex:1,
      borderRadius:5,
      position:"absolute",
      height:wp("90%"),
      width:wp("80%"),
      top:200,
      left:40,
      backgroundColor:"grey",
  }}

  modalProps={{
      transparent:true,
  }}
```

I am not sure if this will work for various resolutions.
