### ISSUE TITLE
How not to show an item

### ISSUE THREAD

**Issue by aezhcr** [hossein-zare/react-native-dropdown-picker#509]
I saw in the site how to disabled an item , but I could not find a solution for how to not show in drop down , please help

My code:

  const [coinSalesList, setCoinSalesList] = useState([
    {disabled: true},
    {
      label: 'Bitcoin',
      CoinTag: 'BTC',
      value: require('../../image/BTC.png'),
    },
    {
      label: 'Ethereum',
      CoinTag: 'ETH',
      value: require('../../image/ETH.png'),
    },
    {
      label: 'Litecoin',
      CoinTag: 'LTC',
      value: require('../../image/LTC.png'),
    },...........

https://s6.uupload.ir/files/1_4um3.jpg

**Comment by hossein-zare** [comment]
There's no such thing, filter your items.
