### ISSUE TITLE
Support for focus reference on keyboard next inside a Form

### ISSUE THREAD

**Issue by MarlonAEC** [hossein-zare/react-native-dropdown-picker#514]
It will be amazing if we can support focus the dropdown when we hit next in keyboard inside a form using references, it's difficult to give a good UX to the user without this functionality... also I would like to contribute on this! Do you have some docs on how to do it!?. Thanks in advance! 🙂✌🏻

**Comment by hossein-zare** [comment]
Hi @MarlonAEC 
Can you do it without refs? like calling `setOpen(true);` when you hit the button in turn.
