### ISSUE TITLE
Height is not working

### ISSUE THREAD

**Issue by bigbean17** [hossein-zare/react-native-dropdown-picker#515]
I'm trying to change the height of the box but it seems not working. 

The following is the code I'm using

![1646049684(1)](https://user-images.githubusercontent.com/69971426/155980140-828510f0-a4ed-4286-89ba-faf4ae1c34b8.png)

I'm trying to make the height of the box the same as the text and is there any way to change the width of the box?
![1646049602(1)](https://user-images.githubusercontent.com/69971426/155979966-275c1de5-b4df-4856-97ed-410e3b26e57f.png)

Thanks!

**Comment by hossein-zare** [comment]
Wrong property!
> ### `maxHeight`
> Max height of the drop-down box.

Use https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#style
```jsx
style={{
  height: 50
}}
```

**Comment by joshua7v** [comment]
@hossein-zare hi, it seems the picker has a min height internally.
when I set height to a small value like 20, picker does not shrink down any more at some point
is there a way to further compress picker height, (remove padding vertical?)

**Comment by hossein-zare** [comment]
Hi @joshua7v 
Is this what you want?

```jsx
style={{
  minHeight: 50,
  paddingVertical: 3,
}}
```

**Comment by joshua7v** [comment]
@hossein-zare thanks for the quick reply.
Yes, it turns out that was all I need
