### ISSUE TITLE
Get value in `setValue`

### ISSUE THREAD

**Issue by KrisLau** [hossein-zare/react-native-dropdown-picker#516]
I'm trying to make a conditional in my `setValue` like this:
```
setValue={
   value !== 'custom' ? props.setValue(value) : props.setIsOverlayVisible(true)
}
```

However, the `setValue` callback returns a function instead of the value and I can't do it in `onChangeValue` because I need it to retain the previous value if "custom" is selected. How do I go about getting the value in `setValue` ?

**Comment by hossein-zare** [comment]
You shoudn't touch the `setValue` prop.

```jsx
setValue={props.setValue}
```

to retain values:
```jsx
const currentValueRef = useRef(null);

<DropDownPicker
  setValue={props.setValue}
  onChangeValue={(value) => {
    if (value === 'custom') {
      props.setIsOverlayVisible(true);
      setValue(currentValueRef.current);
    } else {
      currentValueRef.current = value;
    }
  }}
  ...
/>
```

**Comment by KrisLau** [comment]
@hossein-zare That worked for me thanks!

**Comment by KrisLau** [comment]
@hossein-zare Quick question, so it seems that setting the overlay to visible in `onChangeValue` is causing the overlay to open whenever I open the screen. As a workaround to fix it I had to set the `isOverlayVisible` to false in the `onLayout` event. However, this seems to be causing a quick white flash of the overlay being opened and closed. Is there a way to prevent the behavior on the initial load?

**Comment by KrisLau** [comment]
@hossein-zare `onChangeValue` is causing a lot of problems for me as I need to call `setSlotItems` when values in my other components change and that triggers the `onChangeValue`

**Comment by hossein-zare** [comment]
Please create a snack and tell me what you want to do, what problems you face, ...

**Comment by KrisLau** [comment]
@hossein-zare It's because of the issue I have in https://github.com/hossein-zare/react-native-dropdown-picker/issues/516

**Comment by KrisLau** [comment]
Your comment in https://github.com/hossein-zare/react-native-dropdown-picker/issues/256#issuecomment-1072655805 solved my issue thank you!
