### ISSUE TITLE
Unable to cancel opacity in dropdown

### ISSUE THREAD

**Issue by EliranGabay** [hossein-zare/react-native-dropdown-picker#520]
How do I cancel opacity in dropdown to white background color only with no transparency?
![image](https://user-images.githubusercontent.com/34740857/159224843-a0b37212-4529-48b9-a045-17cf819f37e6.png)

**Comment by zeeshan-shabbir** [comment]
Did you find

> How do I cancel opacity in dropdown to white background color only with no transparency? ![image](https://user-images.githubusercontent.com/34740857/159224843-a0b37212-4529-48b9-a045-17cf819f37e6.png)

Did you find any solution? i also want to add active opacity =0.

**Comment by sefam-stoussaint** [comment]
Same problem here, any solution ?
