### ISSUE TITLE
Feature Request: Non-Fullscreen Modal List Mode

### ISSUE THREAD

**Issue by ddikodroid** [hossein-zare/react-native-dropdown-picker#521]
Could you add a non-fullscreen modal as a new list mode? 

Something like this
![image](https://user-images.githubusercontent.com/4207774/159243716-3e6f0172-3af4-4023-8481-103e723a65db.gif)

Actually, I get that pic from [react-native-modal-picker](https://github.com/vishaldhanotiya/react-native-modal-picker), but the package seems not actively maintained by the author.

Thank you

**Comment by mikehardy** [comment]
I do a non-fullscreen modal by setting styles on the modal, it seems to work?
I just add padding on the modal container style and it squeezes it in?

**Comment by ddikodroid** [comment]
> I do a non-fullscreen modal by setting styles on the modal, it seems to work? I just add padding on the modal container style and it squeezes it in?

Thank you for the insight. I'll try that.

**Comment by hossein-zare** [comment]
I'm going to close this issue...
