### ISSUE TITLE
dropdown items not scrolling inside parent flatlist with listMode="FLATLIST"

### ISSUE THREAD

**Issue by ramzihere** [hossein-zare/react-native-dropdown-picker#522]
I have more than 800 cities listed inside the dropdown when I use listMode=" SCROLLVIEW" it slows down and takes too much time to open the dropdown but when I use listMode="FLATLIST" drawdown items scroll freeze. working fine listMode="MODAL"

**Comment by hossein-zare** [comment]
Hi @ramzihere 
Please create a snack and reproduce the behavior.
