### ISSUE TITLE
Examples that can be seen in the images

### ISSUE THREAD

**Issue by Angelk90** [hossein-zare/react-native-dropdown-picker#523]
Hi @hossein-zare , 
It would be possible to see the examples that are seen in the images.

For example if you posted them on https://snack.expo.dev, anyone could try them.

P.s.
Do they work on both react-native-web and react-native on macos?

**Comment by hossein-zare** [comment]
Hi,

I'll add a snack to the README.md file.

> Do they work on both react-native-web and react-native on macos?

React-native-web not implemented. (Related PRs are welcomed)
If you mean iOS, Yes.

**Comment by Angelk90** [comment]
@hossein-zare : 

I did some tests on:
- react-native-web

<img width="331" alt="Schermata 2022-03-27 alle 17 34 57" src="https://user-images.githubusercontent.com/20476002/160289025-91e4a8dd-eab4-4aec-a677-9121e0e35e6a.png">

- [react-native on macos](https://github.com/microsoft/react-native-macos)

https://user-images.githubusercontent.com/20476002/160289109-c980edb6-27e3-46d9-912a-319c8d9607a0.mov

On macOs it seems to work fine, the only problem at the moment that you notice is that the focus is not made when clicking on the input field, as you can see from the video.

P.s.

My text editor gives me the following problem on the `setValue` props:

<img width="872" alt="Schermata 2022-03-27 alle 17 41 02" src="https://user-images.githubusercontent.com/20476002/160289269-53ab81fb-bc62-4168-a595-0aa79adf7f12.png">

**Comment by mikehardy** [comment]
I use it extensively on react-native-web @hossein-zare it works great - it's one of the reasons I use this package vs other dropdown packages, since it's pure JS :-)

**Comment by hossein-zare** [comment]
@Angelk90 hmm, i see.

This may fix the error.
```jsx
const [value, setValue] = useState<string | null>(null);
```

**Comment by Angelk90** [comment]
@hossein-zare : Error remains, if you have webstorm you can check it for yourself.

**Comment by hossein-zare** [comment]
@mikehardy I didn't know that. 😁

So it's a [snack.expo.dev](https://snack.expo.dev) bug.

**Comment by hossein-zare** [comment]
@Angelk90 Oh sorry, i haven't released a newer version.
`@ts-ignore` the error.

**Comment by Angelk90** [comment]
@hossein-zare : I'm not understanding.

**Comment by Angelk90** [comment]
@hossein-zare : I'm not understanding.

<img width="872" alt="Schermata 2022-03-27 alle 17 41 02" src="https://user-images.githubusercontent.com/20476002/160290173-b22e31c8-8a0a-447d-9a72-1ddb958cd7da.png">

**Comment by hossein-zare** [comment]
```jsx
<DropDownPicker
...

// @ts-ignore
setValue={setValue}

...
/>
```

**Comment by Angelk90** [comment]
@hossein-zare :
OK, I had copied an example from the documentation and there is no use of the ignore.

**Comment by hossein-zare** [comment]
@Angelk90 Are you using the single item or multiple items with (`multiple={true}`)?

For multiple
```jsx
const [value, setValue] = useState([]); // Put [], not null
```

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#single-item
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#multiple-items

**Comment by Angelk90** [comment]
@hossein-zare : OK, if you can upload the examples, I'd like to test them.

**Comment by hossein-zare** [comment]
@Angelk90 

Single: https://snack.expo.dev/yTiXXoFB9
Multiple: https://snack.expo.dev/YMpb4u6VG

**Comment by Angelk90** [comment]
@hossein-zare :  I was hoping you would put these ;)

<p float="left">
    <img src="https://user-images.githubusercontent.com/56504893/116790110-e0b36880-aac7-11eb-9ebd-196acee64f7a.png" width="250" alt="Screenshot">
    <img src="https://user-images.githubusercontent.com/56504893/116789802-faec4700-aac5-11eb-837b-86f18cbfcf3d.png" width="250" alt="Screenshot">
    <img src="https://user-images.githubusercontent.com/56504893/116789839-2c651280-aac6-11eb-99e0-b43b608ed8c7.png" width="250" alt="Screenshot">
</p>

**Comment by hossein-zare** [comment]
@Angelk90 
😅 Here you go https://snack.expo.dev/8mHmLfcZf

**Comment by Angelk90** [comment]
@hossein-zare :  Thx, why did you decide to use `TouchableOpacity` instead of using` TouchableWithoutFeedback` or `TouchableHighlight`, opacity effect when clicking on the input is not the best.

https://github.com/hossein-zare/react-native-dropdown-picker/blob/71c166b68d3d8fc0ac8356eb487c091c0aa1253c/src/components/Picker.js#L1744-L1747

**Comment by hossein-zare** [comment]
@Angelk90 This package was for personal use, `TouchableOpacity` was my favorite component. This is why i used it everywhere.

**Comment by Angelk90** [comment]
@hossein-zare : Have a look here: https://snack.expo.dev/F_9yooUBD  ;)

**Comment by Angelk90** [comment]
@hossein-zare : You could use the props `activeOpacity= {1}` would be great.

**Comment by hossein-zare** [comment]
@Angelk90

Try

```jsx
<DropDownPicker
  props={{
    activeOpacity: 1
  }}

  ... />
```

**Comment by Angelk90** [comment]
@hossein-zare : Great, you happen to know how to use animation?

**Comment by hossein-zare** [comment]
@Angelk90 I've forgotten the animated api. (the last time i used react native was 2 years ago)

**Comment by Angelk90** [comment]
@hossein-zare : I'm not very experienced with animations you used them a long time ago.
When the arrow moves from bottom to top or vice versa, it would have been a nice effect to use animations with a rotation from 0 to 180 to give that motion effect.

**Comment by hossein-zare** [comment]
@Angelk90 It's an easy-peasy animation.

**Comment by Angelk90** [comment]
@hossein-zare : If you have time you could add the following animation.

**Comment by hossein-zare** [comment]
@Angelk90 ok

**Comment by Angelk90** [comment]
@hossein-zare : For the arrow animation, is there any news?

**Comment by hossein-zare** [comment]
@Angelk90 I didn't have enough time, So not for now.
