### ISSUE TITLE
Theme change problem

### ISSUE THREAD

**Issue by Angelk90** [hossein-zare/react-native-dropdown-picker#525]
Hi @hossein-zare , I left the `default` theme, shouldn't it change automatically?
As you can see the text below disappears when I change from dark to light and vice versa.

https://user-images.githubusercontent.com/20476002/160290832-f14c80c4-d52e-48ff-bc5f-bc8743636c5e.mov

**Comment by hossein-zare** [comment]
Hi,

You should change the theme accordingly.

```jsx
<DropDownPicker
  theme={themeName}
  ...
/>
```

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/themes

**Comment by Angelk90** [comment]
@hossein-zare : 
I know, but if you just notice them the problem happens.
When the theme changes from light to dark, either the text `Select an item` or the item elements are displayed correctly.

Although I think when it should be in default mode it should change the color automatically to suit the system.
Or create another theme that fits your system.

**Comment by hossein-zare** [comment]
Ok, I'll test the theme behavior.

**Comment by hossein-zare** [comment]
@Angelk90

I created a snack https://snack.expo.dev/pMPCjmm-0 (Test it on Android or iOS)

**Comment by Angelk90** [comment]
@hossein-zare : 

With the dark theme read the message, when in mode: `searchable = {true}`

<img width="282" alt="Schermata 2022-03-27 alle 19 10 46" src="https://user-images.githubusercontent.com/20476002/160292624-95828e61-d686-4cb7-9bfb-bea007e46bcb.png">

**Comment by hossein-zare** [comment]
@Angelk90 I got it. Thanks.

**Comment by hossein-zare** [comment]
I think it's fixed now.
Later i'll release a new version with some new features / improvements and bugfixes.
