### ISSUE TITLE
Correct use of RenderListItem

### ISSUE THREAD

**Issue by Angelk90** [hossein-zare/react-native-dropdown-picker#526]
Hi @hossein-zare , I have elements in an array that have a structure other than like this:

```js
[
  {label: 'Apple', value: 'apple'},
  {label: 'Banana', value: 'banana'}
]
```

Example:

```js
[
 {"code": "af", "flag": "🇿🇦", "name": "Afrikaans"},
 {"code": "sq", "flag": "🇦🇱", "name": "Albanian"}
]
```

Reading the documentation, considering my case I thought I would use: `itemKey="code"`

Then I use `renderListItem` to display the various elements, but I can't import the `renderListItem`.

I tried like this:
`import DropDownPicker, {renderListItem} from 'react-native-dropdown-picker';`

But it doesn't seem to work, what is the right approach?

**Comment by hossein-zare** [comment]
Hi,

I think you should customize the schema.
Here's what you need: https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/item-schema

`renderListItem` is not a component, it's a property.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#renderlistitem

**Comment by Angelk90** [comment]
@hossein-zare : Ok, the problem is as you can see I should show the flag next to the name.
But the flag is not an icon.

If I put flag in place of name it works, but I can't put both.

```js
schema={{
                  label: 'name', // required
                  value: 'code', // required
                  icon: 'icon',
                  parent: 'parent',
                  selectable: 'selectable',
                  disabled: 'disabled',
                  testID: 'testID',
                  containerStyle: 'containerStyle',
                  labelStyle: 'labelStyle'
              }}
```

**Comment by hossein-zare** [comment]
You should copy https://github.com/hossein-zare/react-native-dropdown-picker/blob/5.x/src/components/RenderListItem.js and create a custom component.

```jsx
renderListItem={(props) => <MyCustomItem {...props} />}
```
