### ISSUE TITLE
Elements selected in vertical list

### ISSUE THREAD

**Issue by Angelk90** [hossein-zare/react-native-dropdown-picker#527]
Hi @hossein-zare , instead of having the elements that are put in the list in the case of multiple selection and to see the selected elements you have to scroll the list.

There is a way to have an effect similar to that of video.

That when the elements no longer find their place horizontally, they are placed vertically.

https://user-images.githubusercontent.com/20476002/160418384-5e25ae3e-0c77-42cc-95e9-c4a2bad2bf6a.mov

**Comment by hossein-zare** [comment]
Use `extendableBadgeContainer={true}`

**New Version:**
https://github.com/hossein-zare/react-native-dropdown-picker/releases/tag/v5.4.0

**Comment by Angelk90** [comment]
@hossein-zare : It seems to work.
