### ISSUE TITLE
Dropdown open/close event

### ISSUE THREAD

**Issue by sathwik77** [hossein-zare/react-native-dropdown-picker#53]
**Dropdown event**
Is there a way to know if the dropdown is open or closed programatically, something like isDropdownOpen() that returns a boolean?

**Comment by hossein-zare** [comment]
Hello,

There are 3 properties called `isVisible` `onOpen` `onClose`.
```javascript
this.state = {
    isVisible: false
}

<DropDownPicker
    isVisible={this.state.isVisible}
    onOpen={() => this.setState({
        isVisible: true
    })}
    onClose={() => this.setState({
        isVisible: false
    })}
/>
```
To check if the dropdown is visible/open:
```javascript
console.log(this.state.isVisible);
```


https://github.com/hossein-zare/react-native-dropdown-picker#multiple-pickers-and-the-open-dropdown-issue
