### ISSUE TITLE
How to custom input value

### ISSUE THREAD

**Issue by Trung229** [hossein-zare/react-native-dropdown-picker#530]
# Hi guys
I am doing a task related to dropdown picker, specifically I want to customize the value in the input, as shown below,

<img width="110" alt="image" src="https://user-images.githubusercontent.com/52306399/161487822-916f1eaa-f53b-4e0e-ab0a-8f20c20c86bf.png">

But I have researched as well as searched in the doc, but there are no supporting props,

Hope everyone can help me

Thanks

**Comment by hossein-zare** [comment]
Hi,

What do you want to do exactly?

**Comment by Trung229** [comment]
Hi thank for your reply,

I want to customize the value in the input field like the image below

This is my value input:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/52306399/162078144-470fc05b-adb2-4d51-aa24-c6a5624745c9.png">

And this is what i expected:

<img width="90" alt="image" src="https://user-images.githubusercontent.com/52306399/162078430-24438312-0610-401a-9aaa-d78798ac8df3.png">

**Comment by hossein-zare** [comment]
If it's an icon / flag, See https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/icons

_For your information, The icon is always on the left side._
