### ISSUE TITLE
exclude icon from selected item label

### ISSUE THREAD

**Issue by ddikodroid** [hossein-zare/react-native-dropdown-picker#531]
i want to add icon on the list item, but exclude it from the selected item label. how to achieve this condition?

example below: i want to remove strong indicator from the label, so the label should be `UX Designer` only
![Screen Shot 2022-04-05 at 15 53 27](https://user-images.githubusercontent.com/4207774/161717258-d7d9bd05-9c98-42f8-af23-93d5543ba36e.png)

**Comment by hossein-zare** [comment]
You can't hide the icon.

**Comment by hossein-zare** [comment]
Use `hideSelectedItemIcon={true}`

**New Version:**
https://github.com/hossein-zare/react-native-dropdown-picker/releases/tag/v5.4.0

**Comment by ddikodroid** [comment]
works as expected.
thank you @hossein-zare

**Comment by yousef71** [comment]
hello @hossein-zare is there a way to do the opposite ? I only want to show the icon in the selected item and not in the drop down list

**Comment by hossein-zare** [comment]
Hi @yousef71 
You should customize the component.

See: https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-and-items#renderlistitem
