### ISSUE TITLE
Scroll in dropdown not working inside a Scrollview.

### ISSUE THREAD

**Issue by Mansi-Bigstep** [hossein-zare/react-native-dropdown-picker#538]

**Comment by mikehardy** [comment]
Hi there! This is a low-quality issue report.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

Please try again, after reading: https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes
