### ISSUE TITLE
Picker Gets Distorted on adding border properties on container Style

### ISSUE THREAD

**Issue by Yashirathore11** [hossein-zare/react-native-dropdown-picker#54]
It Works fine when in container style we don't add border properties in container style .
<DropDownPicker
      items={props.data}
      defaultValue={props.value}
      placeholder={'Grade set'}
      placeholderStyle={{
        fontFamily: Aller,
        fontWeight: 'normal',
        fontSize: 19 ,
        color: ourLightTheme.colors.lightBlue
      }}
      labelStyle={{
        fontFamily: Aller,
        fontWeight: 'normal',
        fontSize: 15 ,
        color: ourLightTheme.colors.lightBlue
      }}
      selectedtLabelStyle={{
        color: 'red'
       }}
      containerStyle={{
        height: 40,
        width: 150 ,
        marginTop: 15,
        // backgroundColor: ourLightTheme.colors.white ,
        // borderWidth: 2 ,
        // borderColor: ourLightTheme.colors.darkBlue ,
        // borderRadius: 5
      }}
      style={{ backgroundColor: ourLightTheme.colors.white }}
      itemStyle={{
        justifyContent: 'flex-start'
      }}
      dropDownStyle={{backgroundColor: ourLightTheme.colors.white ,borderColor: ourLightTheme.colors.darkBlue, borderWidth: 2 }}
      isVisible={visiblity}
      onOpen={() => setVisiblity(true)}
      onClose={() => setVisiblity(false)}
      onChangeItem={item => props.onChangeItem(item.value)}
    />

But when I add border propeties to component style it completely gets distorted .

![Screenshot (544)](https://user-images.githubusercontent.com/47051790/86785516-60c39a00-c080-11ea-8644-83809becf505.png)
![Screenshot (545)](https://user-images.githubusercontent.com/47051790/86785542-6b7e2f00-c080-11ea-8da9-7659ec4a24cb.png)

**Comment by hossein-zare** [comment]
Hello,

The `style` property is where you can style the dropdown picker not `containerStyle`.

Please read **Styling the component** section:
https://github.com/hossein-zare/react-native-dropdown-picker#styling-the-component
