### ISSUE TITLE
delay when opening large list

### ISSUE THREAD

**Issue by ddikodroid** [hossein-zare/react-native-dropdown-picker#541]
**explanation**
so, i have a list with 289 item and put it on the dropdown picker. when i want to open the dropdown, there is a slightly noticeable delay. is it supposed to be like that? the delay happens on ios simulator iphone 13 with ios 15.2

**video**
https://youtu.be/hTqL_VQ-ho0

**version** 
"react-native-dropdown-picker": "^5.4.0"

**code**
```
<DropdownPicker
          schema={{
            label: 'roleName',
            value: 'jobRoleId',
          }}
          open={open}
          value={newRole}
          items={searchResult}
          setOpen={setOpen}
          setValue={setNewRole}
          hideSelectedItemIcon={true}
          searchable
          showTickIcon={false}
          listItemContainerStyle={styles.listItemContainer}
          translation={{
            PLACEHOLDER: 'Choose a role',
            SEARCH_PLACEHOLDER: 'Type something to find a role...',
          }}
          style={styles.dropdown}
          listMode="SCROLLVIEW"
 />
```

**Comment by hossein-zare** [comment]
If you have too many items, You **MUST** use `listMode="FLATLIST"` or `listMode="MODAL"`.

_on `SCROLLVIEW` the items are rendered at once._

**Comment by ddikodroid** [comment]
@hossein-zare fixed, thank you!
