### ISSUE TITLE
overlapping with bottom components when in IOS in modal

### ISSUE THREAD

**Issue by yasin459** [hossein-zare/react-native-dropdown-picker#543]
hi, when using dropPownPicker in ios we may face overlapping, sometimes it can be fixed using zIndex.
however recently I used Picker in a **modal**.
if it opens toward the top, everything is ok but when it opens toward down, it **overlaps with the bottom content**.
i tried different zIndex such as zIndex =1 or 10 or 100 etc  for parent. but nothing changed.
is there any solution?
![unnamed](https://user-images.githubusercontent.com/60640286/165830490-0ea6716c-7a07-4bc3-94c4-41c8fd34e7ea.jpg)
above is when opens toward down(which is bad behavior)
![unnamed](https://user-images.githubusercontent.com/60640286/165830789-2344a629-df1a-4232-bd3a-db4367d16703.jpg)
above is when opens toward the top(which is fine)

**Comment by hossein-zare** [comment]
Hi,

See: https://github.com/hossein-zare/react-native-dropdown-picker/issues/450#issuecomment-976497649 and https://github.com/hossein-zare/react-native-dropdown-picker/issues/376
There are some closed issues similar to yours, You may find the solution.
