### ISSUE TITLE
Unable to npm install react-native dropdown-picker

### ISSUE THREAD

**Issue by erictang0220** [hossein-zare/react-native-dropdown-picker#544]
![Screen Shot 2022-05-04 at 6 11 09 PM](https://user-images.githubusercontent.com/50003319/166850658-1f5b373e-822c-40a9-b6fa-8df041900263.jpg)
When I tried to `npm install` the package, it shows a whole bunch of errors. I have tried uninstalling and reinstalled it but still didn't work.

**Comment by hossein-zare** [comment]
react-native-drop**dwon**-picker ❌
react-native-dropdown-picker ✔
