### ISSUE TITLE
zIndex and zIndexInverse not working with disabled prop for multiple pickers

### ISSUE THREAD

**Issue by yogendrajs** [hossein-zare/react-native-dropdown-picker#545]
when having multiple pickers, if the second dropdown is disabled unless the first dropdown has been selected with a value, I use the `disabled` prop with the useState hook, but that doesn't seem to be working in Android, I'm unable to select the value from the second dropdown (after it is enabled)

**Comment by hossein-zare** [comment]
@yogendrajs 
Please reproduce the behavior using an expo snack.

**Comment by yogendrajs** [comment]
> @yogendrajs Please reproduce the behavior using an expo snack.

@hossein-zare, please refer to this snack - https://snack.expo.dev/@yogendraexpo/react-native-dropdown-picker-bug

This problem only arises if the dropdowns are disabled for the very first time (see the second dropdown overlapping with the third one when selecting a value). Also, note that this is working fine in iOS, just the Android is causing the issue.

**Comment by hossein-zare** [comment]
I released a new version **v5.4.2**.

Make sure that fixes the bug.
Snack is unable to find the new version so try it on your real project.

```json
"react-native-dropdown-picker": "5.4.2"
```

**Comment by yogendrajs** [comment]
thanks for the quick response @hossein-zare, I'll definitely give it a try. Can you please mention what was causing the issue?

**Comment by hossein-zare** [comment]
https://snack.expo.dev/UQMiu9ntS works well.

The `disabledStyle` styles were being applied to the wrong view, The **[Avoid inappropriate styles](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules#avoid-inappropriate-styles)** rule was broken.

**Comment by yogendrajs** [comment]
Gotcha! Thank you, closing this issue here :)
