### ISSUE TITLE
Dropdown too high by default

### ISSUE THREAD

**Issue by Keane06** [hossein-zare/react-native-dropdown-picker#549]
Hi,

Dropdown is too high by default. 

See attached. How do I slim this down?
![screenshot](https://user-images.githubusercontent.com/73553212/167458134-af378563-7143-435f-a0b7-232b19008443.jpeg)

Thanks
Keane

**Comment by Keane06** [comment]
Hi, this is urgent. Can the developer please respond...

**Comment by mikehardy** [comment]
With apologies, you're doing open source wrong: https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

if it's urgent, get in there and figure it out! *That* is open source. You have the *ability* to fix things. No one has the obligation to fix things for you.

**Comment by hossein-zare** [comment]
Hi @Keane06 

What do you mean by too high? the height?
```jsx
style={{
  minHeight: 50,
  paddingVertical: 3,
}}
```

**Comment by hossein-zare** [comment]
Hi @Keane06 

What do you mean by too high? the height?
```jsx
style={{
  minHeight: 50,
  paddingVertical: 3,
}}
```

**Comment by Keane06** [comment]
@mikehardy - thanks for the advice - I'm new to this.

@hossein-zare: the default dropdown box height is high not slim like before. In the image, the blue outline is the height it used to be and when I upgraded SDK, CLI in react native (expo), it become "bigger" or higher.

I tried the above, doesn't work. It's a visual problem - the dropdown works perfectly.

Thanks,

**Comment by hossein-zare** [comment]
@Keane06 Try to decrease the value of the `minHeight`.

**Comment by Keane06** [comment]
@hossein-zare - this worked. Thanks a lot. Really appreciate your time and effort.
