### ISSUE TITLE
Using DropDownPicker as a wrapper

### ISSUE THREAD

**Issue by usersina** [hossein-zare/react-native-dropdown-picker#55]
**Feature description:** 
Ability to use `<DropDownPicker>` as a wrapper.
Something that looks like this:
```javascript
<DropDownPicker
...
>
   <View>
      <Text numberOfLines={1}>{my_selected_label}</Text>
   </View>
</DropDownPicker>
```

**Why ?**
For better customization when it comes to what's displayed to the user.
My label is too big and I wanted to limit it to one line in the View only, however I want it to still display the whole text when the dropdown is pressed so making the label a `substring` is not an option.

**Screenshot:**
Here's an [image](https://i.imgur.com/JQiJNEJ.jpg).

Edit: We've discussed `numberOfLines` in a [previous issue](https://github.com/hossein-zare/react-native-dropdown-picker/issues/49). I ultimately think using a wrapper is better than simply making the label a JSX because the wrapper is easily scalable.

**Comment by hossein-zare** [comment]
That way it looks like you're doing it all manually, We need it to be rendered automatically with the styles.
It also obsoletes all the styling properties.

I'll introduce a new property to limit label length later.
