### ISSUE TITLE
IOS only zindex not working in IOS only

### ISSUE THREAD

**Issue by abdulrehmansiddiqui** [hossein-zare/react-native-dropdown-picker#551]
"react": "17.0.2",
"react-native": "0.68.1",
"react-native-dropdown-picker": "^5.4.2",
 
in android working file having issue only in the IOS

<DropDownPicker
                style={[st.mT8,
                {
                  borderColor: validPTI ? "red" : "#272727",
                  borderWidth: 0.7,
                  zIndex: 999,
                }
                ]}
                listItemContainerStyle={{
                  backgroundColor: "lightgreen",
                  zIndex: 999,
                }}
                zIndex={999}
                open={true || open}
                value={property_sub_type_id}
                items={property_sub_type_array}
                setOpen={setOpen}
                setValue={setproperty_sub_type_id}
                setItems={setproperty_sub_type_array}
              />

<img width="833" alt="Screen Shot 2022-05-13 at 7 47 51 PM" src="https://user-images.githubusercontent.com/34935108/168320223-09053aaa-7d0c-45f7-b2f0-c970e3cad2ab.png">

**Comment by hossein-zare** [comment]
See: https://github.com/hossein-zare/react-native-dropdown-picker/issues/450#issuecomment-976497649 and https://github.com/hossein-zare/react-native-dropdown-picker/issues/376

If not solved, Try to find similar issues.
