### ISSUE TITLE
Prop to set custom empty list message

### ISSUE THREAD

**Issue by julian-george** [hossein-zare/react-native-dropdown-picker#552]
As far as I can tell, currently you have to pass a whole component `ListEmptyComponent` to change what the dropdown says when there are no results that match a search term. Maybe this is so the message can always be translated? Anyways, it would be nice but not essential for me to be able to change the empty message to something different. I'd be down to make a quick PR about this if it's deemed worthwhile.

**Comment by hossein-zare** [comment]
Please visit
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/localization#change-the-translation

**Example**
```jsx
translation={{
  NOTHING_TO_SHOW: "😢"
}}
```

**Comment by julian-george** [comment]
Thanks for the quick response! Works perfectly for me.
