### ISSUE TITLE
Unwanted slow border radius transition when opening dropdown

### ISSUE THREAD

**Issue by julian-george** [hossein-zare/react-native-dropdown-picker#554]
Hey again! This package has been working swimmingly for me, I just have one final thing I want to solve before I finalize my implementation. Both my dropdown and the input have a border radius, and when I open the dropdown, the input's top border becomes flat, as desired. However, there's this weird transition as the border becomes flat - it doesn't do so instantly. See the video for a demonstration. It's a quick transition but it's definitely noticeable, and it makes the dropdown feel less smooth.

https://user-images.githubusercontent.com/5896294/168506838-31cefdec-9005-42ea-86f4-8c17e973f8b9.mov

I've tried changing the border radius on my end upon opening the dropdown but it has no effect: ```<DropDownPicker style={[styles.innerDropdown, open && { borderTopEndRadius: 0 }]} ... />```. Is there a way to remove this transition and have the top border radius flatten instantly?

**Comment by hossein-zare** [comment]
Hi,

I believe your screen isn't optimized or you have too many items.

No transitions or animations, everything is changed directly.
