### ISSUE TITLE
Change label

### ISSUE THREAD

**Issue by robinlindhout** [hossein-zare/react-native-dropdown-picker#558]
Hi! Is there any prop to change the label?

![label](https://user-images.githubusercontent.com/79744544/170257110-d872de01-1255-471f-9884-7f6d2e49c3ae.png)

**Comment by hossein-zare** [comment]
Hi

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/placeholder#placeholder-text

**Comment by robinlindhout** [comment]
Thanks so much
