### ISSUE TITLE
Virtualizedlist should never be nested inside scrollview

### ISSUE THREAD

**Issue by cbothra** [hossein-zare/react-native-dropdown-picker#56]
I am using this dropdown plugin in a scrollview and getting a following warning:

_**VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList - backed contained instead.**_

Any help would be highly appreciated.

Thank-in-advance.

**Comment by usersina** [comment]
If you comment out the `ScrollView`, does the dropdown by any chance stay behind the other components if you open it ? 
Sort of like [this](https://imgur.com/iWzvOhS).

**Comment by cbothra** [comment]
Nope the dropdown works just perfect. All I am facing is this warning _Virtualizedlist should never be nested inside scrollview_. I googled this error and there are some solutions for this. This is a common error which appears when we put a Flatlist inside Scrollview. I was not sure how to resolve that in the plugin plus I dont want to alter the node modules packages. So I thought to bring it to your notice. 

I am taking body measurements in my app which can be in inch/cms and pounds/kg . So I wanted to have dropdown along side each input. And all these measurements inputs are wrapped in a Scrollview container.

**Comment by hossein-zare** [comment]
Hello @cbothra ,
Before updating the package, I did some research on how to use `FlatList` inside `ScrollView`, I ended up with these:
https://stackoverflow.com/questions/51098599/flatlist-inside-scrollview-doesnt-scroll
https://reactnative.dev/docs/scrollview#nestedscrollenabled

```javascript
<ScrollView nestedScrollEnabled={true} />
    <DropDownPicker  ... />
</ScrollView>
```

If the example doesn't solve the problem, please let me know.

### Update
Update the package to **v3.1.8**.

**Comment by usersina** [comment]
I also have the same warning, tried adding `nestedScrollEnabled={true}` but it didn't work.
I should note that my app looks like this:

App.js:
```JAVASCRIPT
<ScrollView nestedScrollEnabled={true} />
    <SomeComponent1 />
    <SomeComponent2 />
    <TheDropView />
</ScrollView>
```

TheDropView.js: 
```JAVASCRIPT
<View style={{flexDirection: 'row'}}>
    <DropDownPicker  ... />
</View>
```

**Comment by kimkong88** [comment]
Same issue here, One way to fix is have horizontal ScrollView wrapped outside of dropdown, it will make the warning disappear, but obviously not a right solution.

**Comment by cbothra** [comment]
@hossein-zare Nope, just adding `nestedScrollEnabled={true}` didn't worked. Also note that I updated the library to the latest version.

My case is exactly same as @UserSina.

@kimkong88 This hack works but yes you are are right. This is not an optimal solution. Besides that you have to give height to the scrollview so that the options gets displayed.

**Comment by hossein-zare** [comment]
@cbothra @UserSina @kimkong88 

I got rid of `FlatList`, `ScrollView` replaced.

**New update: 3.1.9**

**Comment by cbothra** [comment]
Doesn't make any difference. Warning still persists. I think its not related to flatlists or scrollview. The core problem is using scrollview/flatlist inside another scrollview/flatlist.

@hossein-zare You should checkout this link for solutions: https://github.com/GeekyAnts/NativeBase/issues/2947

**Comment by hossein-zare** [comment]
Make sure you're using **v3.1.9**, The warning has to go away.

**Comment by usersina** [comment]
Solved !

**Comment by singhprabhanshu** [comment]
No, warning is there in  version 3.1.9. i have installed and configured it. Also the scroll of dropdown option is not going to happen if we are using it inside scrollView or content(native base). To scroll option of dropdown inside scroll view, i need to press scroll view and then scroll is going to happen on dropdown option. Anybody have solution??

**Comment by cbothra** [comment]
@hossein-zare Yep Now I can confirm that there is no more Yellow Box Warning. 

Btw just out of curiosity what was your solution. I hope you didn't just hide the warning :D (Just Kidding).

**Comment by hossein-zare** [comment]
I replaced `FlatList` with `Scrollview`

**Comment by codoffer** [comment]
I am facing the same issue. Getting a warning - "VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead."

I have fixed this by using a different mode

https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/5.0/advanced/list-modes#scrollviewprops

**Comment by hossein-zare** [comment]
@codoffer 
If that happens, You have to use `listMode="SCROLLVIEW"` or `listMode="MODAL"`.

**Comment by alessandro-bottamedi** [comment]
Problem still happens in ver 5.1.17 (solved with listMode="SCROLLVIEW")

**Comment by SatalBill** [comment]
@alessandro-bottamedi  and @hossein-zare 's answers saved my time.
```
<DropDownPicker
  open={open}
  value={value}
  items={items}
  setOpen={setOpen}
  setValue={setValue}
  setItems={setItems}
  style={{backgroundColor: 'crimson',}}
  listMode="SCROLLVIEW"                      // This line solved my issue.
/>
```
Reference link is [here](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes)

**Comment by impe93** [comment]
This configuration worked form me:

```html
<ScrollView nestedScrollEnabled={true}> // Add nestedScrollEnabled={true}
  <DropDownPicker
    open={open}
    value={value}
    items={items}
    setOpen={setOpen}
    setValue={setValue}
    setItems={setItems}
    listMode="SCROLLVIEW" // Add this line 
  />
</ScrollView>
```

**Comment by Paramesh98** [comment]
Hi, I had the same issue, the library provides listMode props. Adding this props solved my issue.

```
 listMode="SCROLLVIEW"
        scrollViewProps={{
          nestedScrollEnabled: true,
  }}

```
check this documentation for more information https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/advanced/list-modes#scrollviewprops

**Comment by Nouhack** [comment]
the way to avoid this type of warning was mentioned in the doc , please take a look :
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes

**Comment by fajarprayoga** [comment]
> Saya menghadapi masalah yang sama. Mendapatkan peringatan - "VirtualizedLists tidak boleh bersarang di dalam ScrollViews biasa dengan orientasi yang sama karena dapat merusak jendela dan fungsionalitas lainnya - gunakan wadah lain yang didukung VirtualizedList sebagai gantinya."
> 
> Saya telah memperbaikinya dengan menggunakan mode yang berbeda
> 
> https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/5.0/advanced/list-modes#scrollviewprops

this work for me

**Comment by cyberDever** [comment]
Still not working on my end.
when the dropdown position is top, it's working as expected, but on bottom, still overlapped and unable to select.

**Comment by mikehardy** [comment]
@ironwebstar I won't have time to troubleshoot your project personally, however in general for anyone to help anyone you should do your best to produce a https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Satyam-code143** [comment]
I am not getting any error but the `listMode="SCROLLVIEW"` doesn't open the dropdown. I don't want to use `MODAL` in my app. So, please can someone help.

I have created a project over Snack. [DropDown](https://snack.expo.dev/@satyam143/dropdown). In this project, it is working on the web but it isn't showing up on mobile, please help me out to solve this.

Thank You!!

**Comment by Roundups** [comment]
I am also having issues, it works ok on iOS but not on android. It will open the dropdown but I can't then scroll or choose another option within the dropdown. I am using listMode="MODAL" for the time being.

**Comment by fadinasr** [comment]
@hossein-zare do we lose any performance if we use Scroll View instead of Flat List? keep in mind the items are pretty simple text items.

**Comment by hossein-zare** [comment]
Hello @Satyam-code143 @Roundups ,

Unsolvable, Consider using a `View` element instead of the `ScrollView`

**Comment by hossein-zare** [comment]
@fadinasr 
It depends on the number and simplicity of your items.
If they are +(~20), it'll impact the performance.

**Comment by PranatoshRoy** [comment]
> Hi, I had the same issue, the library provides listMode props. Adding this props solved my issue.
> 
> ```
>  listMode="SCROLLVIEW"
>         scrollViewProps={{
>           nestedScrollEnabled: true,
>   }}
> ```
> 
> check this documentation for more information https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/advanced/list-modes#scrollviewprops

Wroks like a charm. Thanks @Pramesh98

**Comment by DracoZona** [comment]
> @alessandro-bottamedi and @hossein-zare 's answers saved my time.
> 
> ```
> <DropDownPicker
>   open={open}
>   value={value}
>   items={items}
>   setOpen={setOpen}
>   setValue={setValue}
>   setItems={setItems}
>   style={{backgroundColor: 'crimson',}}
>   listMode="SCROLLVIEW"                      // This line solved my issue.
> />
> ```
> 
> Reference link is [here](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes)

This works for me.

**Comment by Mukthayar1** [comment]
> SCROLLVIEW

Thanks thats solve my prblem

**Comment by Mukthayar1** [comment]
> @codoffer If that happens, You have to use `listMode="SCROLLVIEW"` or `listMode="MODAL"`.

@hossein-zare 
listMode="SCROLLVIEW" its make list very slow

**Comment by amirVirtuenetz** [comment]
> Hello @cbothra , Before updating the package, I did some research on how to use `FlatList` inside `ScrollView`, I ended up with these: https://stackoverflow.com/questions/51098599/flatlist-inside-scrollview-doesnt-scroll https://reactnative.dev/docs/scrollview#nestedscrollenabled
> 
> ```js
> <ScrollView nestedScrollEnabled={true} />
>     <DropDownPicker  ... />
> </ScrollView>
> ```
> 
> If the example doesn't solve the problem, please let me know.
> 
> ### Update
> Update the package to **v3.1.8**.

I have tried your solution but i faced the error same like that 
i ahve a ScrollView in main Container of Screen and inside multiple children like input button and alos Dropdown picker
but i cannot resolve the issue
i am using 
"react-native-dropdown-picker": "^5.4.2",
"react-native": "0.68.2",

**Comment by amirVirtuenetz** [comment]
> > @alessandro-bottamedi and @hossein-zare 's answers saved my time.
> > ```
> > <DropDownPicker
> >   open={open}
> >   value={value}
> >   items={items}
> >   setOpen={setOpen}
> >   setValue={setValue}
> >   setItems={setItems}
> >   style={{backgroundColor: 'crimson',}}
> >   listMode="SCROLLVIEW"                      // This line solved my issue.
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reference link is [here](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/list-modes#notes)
> 
> This works for me.

Thanks , it solved my issue

**Comment by TommysG** [comment]
> Hello @Satyam-code143 @Roundups ,
> 
> Unsolvable, Consider using a `View` element instead of the `ScrollView`

@hossein-zare  Have you consider changing a little bit the implementation and render the dropdown inside a modal( and inside the modal the flatlist) and place it exactly under the dropdown button with the same width as the button container? I think this will solve all the compatibility problems between iOS & Android (nested scrolls etc) and the z-index bugs.

**Comment by hossein-zare** [comment]
@TommysG 

Modals are `fixed` (position) on the screen so if you scroll up and down, the modal won't move.

**Comment by TommysG** [comment]
@hossein-zare 

Yes. The concept is that if you touch anything outside the dropdown(modal) or if you try to scroll on the parent container, then close the dropdown.

**Comment by zulkifli0201** [comment]
> Saya menghadapi masalah yang sama. Mendapatkan peringatan - "VirtualizedLists tidak boleh bersarang di dalam ScrollViews biasa dengan orientasi yang sama karena dapat merusak jendela dan fungsionalitas lainnya - gunakan wadah lain yang didukung VirtualizedList sebagai gantinya."
> 
> Saya telah memperbaikinya dengan menggunakan mode yang berbeda
> 
> https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/5.0/advanced/list-modes#scrollviewprops

thankyou

**Comment by wanderlust252** [comment]
> 

this work well on IOS but android, it didn't show the list

**Comment by ghost** [comment]
I added both but it doesn't seems to work. Modal works but I want the list

![image](https://user-images.githubusercontent.com/59139918/208186749-380a7215-c889-40cd-a641-03a1bcc2ba55.png)
![image](https://user-images.githubusercontent.com/59139918/208186755-00acbf82-c707-4413-a66b-3d17a01f6548.png)

It doesn't show the dropdown list

**Comment by umairm1alik** [comment]
If I use listemode = 'SCROLLVIEW'  it makes dropdown performance very slow and if I use 'FLATLIST'  dropdown become not scrollable plus virtualization warning.

**Comment by tragicmj** [comment]
I can completely relate to @umairm1alik , facing the same issue. If I use Flatlist see virtualization warning and if I use Modal, freezing issue.

**Comment by ghost** [comment]
Yes, you are right. It's really feel slow and weird.

**Comment by Bayramito** [comment]
the issue still existing with the latest version

**Comment by Jeeet-patel** [comment]
> I am not getting any error but the `listMode="SCROLLVIEW"` doesn't open the dropdown. I don't want to use `MODAL` in my app. So, please can someone help.
> 
> I have created a project over Snack. [DropDown](https://snack.expo.dev/@satyam143/dropdown). In this project, it is working on the web but it isn't showing up on mobile, please help me out to solve this.
> 
> Thank You!!

@Satyam-code143 Try giving height to the container of dropdown component i tried it worked for me

**Comment by CyborgCodes** [comment]
This is my solution for this problem 

I have a Container Component
`export const Container = ({ children, padding = false, center = false, scrollable = false }: Props) => {

  return (
    <SafeAreaView style={styles.safeAreaStyles}>
      {scrollable ? (
        <ScrollView>
          <ChildrenComponent children={children} padding={padding} center={center} />
        </ScrollView>
      ) : (
        <ChildrenComponent children={children} padding={padding} center={center} />
      )}
    </SafeAreaView>
  );
};
`
This is my screen 
`    //Only allow scroll if dropdowns are closed
    <Container scrollable={!openTeamList}>
      <View style={styles.mainView}>
        <Text style={styles.title}>Customer Information</Text>

        <View style={styles.formView}>
          <Controller
            control={control}
            rules={{
              required: true,
            }}
            render={({ field: { onChange, onBlur, value } }) => (
              <DropDownPicker
                open={openTeamList}
                items={teamList}
                value={null}
                setOpen={setOpenTeamList}
                setValue={onChange}
                schema={{
                  label: "name",
                  value: "_id"
                }}
                placeholder={t("Select Team")}
                placeholderStyle={{
                  color: theme.colors.gray2
                }}
                style={{ backgroundColor: '#F8F8F8', borderWidth: 0 }}
              />
            )}
            name="team"
          />
        </View>
      </View>
    </Container>
`

This means I only render the <ScrollView/> when my dropdown is Closed.
Hope this works for you too.

**Comment by CyborgCodes** [comment]
This was my solution hope it works for you.

I have a Container Component: 
```jsx
export const Container = ({ 
  children, padding = false, center = false, scrollable = false 
}: Props) => {

  // VIEWS
  return (
    <SafeAreaView style={styles.safeAreaStyles}>
      {scrollable ? (
        <ScrollView>
          <ChildrenComponent children={children} padding={padding} center={center} />
        </ScrollView>
      ) : (
        <ChildrenComponent children={children} padding={padding} center={center} />
      )}
    </SafeAreaView>
  );
};
```

I conditionally render the ScrollView based on if my dropdown is open or closed, in this case i only want to use <ScrollView/> when my dropdown is closed. 

```jsx
    <Container scrollable={!open}>
      <View style={styles.mainView}>
          <Controller
            control={control}
            render={({ field: { onChange, onBlur, value } }) => (
              <DropDownPicker
                open={open}
                items={teamList}
                value={null}
                setOpen={setOpen}
                setValue={() => {}}
              />
            )}
            name="team"
          />
         </View>
      </View>
    </Container>
```

**Comment by williamlegane** [comment]
Add this if you are struggling with DropDownPicker inside ScrollVide

 DropDownPicker.setListMode("SCROLLVIEW");

**Comment by SaraaX404** [comment]
> listMode="SCROLLVIEW"

this one worked, and thanks

**Comment by warmfire540** [comment]
sorry to revive the dead - but is this the final answer?  the performance is super slow on android. it did get rid of the warning though

nm, got this working on my fork
