### ISSUE TITLE
The dropdown picker scroll inside another scroll is not working

### ISSUE THREAD

**Issue by viniciusbitt** [hossein-zare/react-native-dropdown-picker#57]
**Describe the bug**
The dropdown picker scroll inside another scroll is not working

**To Reproduce**

Place ScrollView above DropdownPicker:
```
<View style={{ flex: 1 }}>
                    <ScrollView nestedScrollEnabled={true} horizontal={false}>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <DropDownPicker
                            items={allCategories}
                            searchable={true}
                            searchablePlaceholder="Search"
                            searchableError={() => <CText fontSize={16}>Not found</CText>}
                            searchableStyle={{ fontSize: 18 }}
                            defaultValue={productCategory}
                            containerStyle={{ height: 40 }}
                            style={{ backgroundColor: '#fafafa' }}
                            dropDownStyle={{ backgroundColor: '#fafafa' }}
                            dropDownMaxHeight={300}
                            labelStyle={{ fontSize: 20 }}
                            itemStyle={{
                                justifyContent: 'flex-start'
                            }}
                        />
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                        <View style={{ width: 200, height: 200 }}></View>
                    </ScrollView>
  </View>
```

 - OS: Android
 - Package version 3.1.9

**Comment by hossein-zare** [comment]
Hello,

I tried to reproduce the behavior with your code snippet but it's working fine.
https://snack.expo.io/@hossein-zare/scrollview-issue

**Comment by singhprabhanshu** [comment]
i have same issue when i am using inside content of native base.

**Comment by viniciusbitt** [comment]
Hello,

This is very strange. I am using version 3.1.9 I believe it is the latest, but in my project the Scroll does not work, even though the code is exactly the same as snack.io. I think it's the version

**Comment by hossein-zare** [comment]
Copy and paste the given snack code, Give it a shot. Probably you've missed something.
I think the package doesn't have a bug in that case.
Please double-check your components see if any of your `View` elements have `zIndex` property which will cause issues on Android.

**Comment by viniciusbitt** [comment]
on snack.io it works, but when I put it exactly the same in my project, it doesn't work. But I don't know if the problem is with the version of the React Native package or the DropdownPicker

https://snack.expo.io/@darklayer/a5e34b

**Comment by singhprabhanshu** [comment]
yes @BetaPlays3  it does not work. i used dropdown picker inside content of native base (content is scrollable). when i press the scroll of content and tried to scroll the dropdown option then i am able to scroll options but when i directly scroll the dropdown options then there is no scroll and the content scrolls.

code snippet: 

`<Container>
<Content padder >
<View style={{marginTop:15 }}>
        <DropDownPicker
          items={options}
          containerStyle={{height: 40}}
          style={{backgroundColor: 'transparent', borderTopWidth: 0, borderLeftWidth: 0, borderRightWidth: 0 }}
          itemStyle={{
              justifyContent: 'flex-start'
          }}
          dropDownStyle={{backgroundColor: '#fafafa'}}
          onChangeItem={item => input.onChange(item.value)}
          placeholder={placeholder}
          placeholderStyle={{ color: 'white' }}
          arrowColor='white'
          selectedLabelStyle={{ color: 'white'}}  
        />
     </View>
    </Content>
</Container>`

**Comment by tannguyen05** [comment]
@hossein-zare i have same issue when i am using in bottom of scrollview. it not show dropdown

**Comment by tannguyen05** [comment]
![Uploading Screen Shot 2020-07-14 at 20.26.42.png…]()
like this

**Comment by swizes** [comment]
The problem is that if the dropdown is in scrollview, and there is no content below dropdown. It does not know how much height the dropdown list can have therefore the list won't be visible. This is only an android issue.

**Comment by swizes** [comment]
I think, I found the solution

in the source code check the styles. It uses position:'absolute' for dropdown items list, if you get rid of it, the list will be shown accurately

 ```
dropDownBox: {
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        position: 'relative',// It was absolute
        width: '100%'
    },
```

and then if you want to get rid of the gap, you need to get rid of the top: this.state.top section

```
{
 top: this.state.top,
 maxHeight: this.props.dropDownMaxHeight,
 zIndex: this.props.zIndex
}
```

Unfortunately this makes the views below to be pushed to bottom

**Comment by tannguyen05** [comment]
Many thanks for reply.

Vào 13:51, Th 4, 22 thg 7, 2020 Cumhur Güner <notifications@github.com> đã
viết:

**Comment by RakshithD** [comment]
Hi,

I'm unable to scroll the Dropdown item list, If I place the Dropdown inside the scrollview. I need to show 15 dropdown in one single screen. As you can see in the below screenshot "Filter Thickness (in)" consists of more than 4 items. If I try to scroll Dropdown item list it's not scrolling instead complete screen will scroll.  

 any workaround or any solution for this? Please let me know.
Many thanks in advance. 

![WhatsApp Image 2020-11-17 at 8 40 47 PM](https://user-images.githubusercontent.com/11288991/99407804-85c0f700-2915-11eb-901e-8e2124fa9469.jpeg)

**Comment by ankushShetty1993** [comment]
> Hi,
> 
> I'm unable to scroll the Dropdown item list, If I place the Dropdown inside the scrollview. I need to show 15 dropdown in one single screen. As you can see in the below screenshot "Filter Thickness (in)" consists of more than 4 items. If I try to scroll Dropdown item list it's not scrolling instead complete screen will scroll.
> 
> any workaround or any solution for this? Please let me know.
> Many thanks in advance.
> 
> ![WhatsApp Image 2020-11-17 at 8 40 47 PM](https://user-images.githubusercontent.com/11288991/99407804-85c0f700-2915-11eb-901e-8e2124fa9469.jpeg)

I am also facing the same issue!!

**Comment by shreshthns806** [comment]
+1. I am also facing a similar issue

**Comment by Paramesh98** [comment]
Hi, I had the same issue, the library provides **listMode** props. Adding this props solved my issue.
```
 listMode="SCROLLVIEW"
        scrollViewProps={{
          nestedScrollEnabled: true,
  }}

```
check this documentation for more information https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/advanced/list-modes#scrollviewprops

**Comment by arnaldoquagliatoQuanta** [comment]
> Hi, I had the same issue, the library provides **listMode** props. Adding this props solved my issue.
> 
> ```
>  listMode="SCROLLVIEW"
>         scrollViewProps={{
>           nestedScrollEnabled: true,
>   }}
> ```
> 
> check this documentation for more information https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/advanced/list-modes#scrollviewprops

this solution should be on top, it works for me.

**Comment by Developeranees** [comment]
just use this with optimized flatlist

flatListProps={{
          nestedScrollEnabled: true,
        }}

**Comment by bilal939** [comment]
> Hi, I had the same issue, the library provides **listMode** props. Adding this props solved my issue.
> 
> ```
>  listMode="SCROLLVIEW"
>         scrollViewProps={{
>           nestedScrollEnabled: true,
>   }}
> ```
> 
> check this documentation for more information https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/next/advanced/list-modes#scrollviewprops

Still not working Here is my code by using scroll View it is not even showing the list items.

 {/* <ScrollView nestedScrollEnabled={true}> */}
              <DropDownPicker
                open={open}
                value={value}
                items={items}
                showTickIcon={true}
                closeAfterSelecting={true}
                setOpen={setOpen}
                stickyHeader={true}
                onSelectItem={(item => {
                  console.log(item.type);
                  setValue(item.id)
                })}
                listMode="SCROLLVIEW"
                scrollViewProps={{
                  nestedScrollEnabled: true,
          }}
                dropDownContainerStyle={{borderColor:'#AAB8DB'}}
                maxHeight={100}
                style={{borderColor: '#AAB8DB'}}
                placeholderStyle={{color: '#AAB8DB', fontSize: 16,}}
                placeholder="Credit Card , Utility.."
                setItems={setItems}
                itemKey='id'
                listItemContainerStyle={{backgroundColor:'pink'}}
                listItemLabelStyle={{color: '#AAB8DB',padding:5}}
                schema={{
                  label: 'type',
                  value: 'id'
                }}
              />
                {/* </ScrollView> */}
              </View>

**Comment by edson-domenech** [comment]
Good Morning

I have the same problem...

Any solution ?

**Comment by josiaharkson** [comment]
@Paramesh98 thanks a million!

**Comment by Tukutlas** [comment]
tried solutions here it isn't working...

**Comment by rexthefex** [comment]
To anyone who can't even get the items to show on Android:

You need to have `contentContainerStyle={{ flexGrow: 1 }}` added to the container ScrollView.
To silence the FlatList warning - set `listMode="SCROLLVIEW"` in the DropDownPicker.

After some testing - `nestedScrollEnabled` doesn't seem to be necessary, but nesting the picker deeper into different views might cause some issues - in some cases it should be fixable with some styling, but I didn't go that deep. Best results would be to place it directly within a ScrollView and avoid nesting.

**Comment by rgupta2423** [comment]
Hi,
listMode="SCROLLVIEW"
scrollViewProps={{
nestedScrollEnabled: true,
}} 

this isn’t working for android. Please help!

Thanks a lot in advance 🙂

**Comment by hasansna** [comment]
Are you using zIndex in the style of the parent element? In short, my problem was that I was using the zIndex of <View> element that is the parent. The solution is to use zIndex as a DropDownPicker prop:

```
            <DropDownPicker
                open={open}
                value={value}
                items={items}
                setOpen={setOpen}
                setValue={setResult}
                setItems={setItems}
                zIndex={zIndex}
                placeholder={placeHolder}
            />
```

**Comment by rajAmukhliS** [comment]
I resolved the **scroll issue of dropdown container** by using  `position: 'relative'` in **dropDownContainerStyle**
```

dropDownContainerStyle={{
borderColor: theme.colors.gray4,
    position: 'relative', // to fix scroll issue ... it is by default 'absolute'
    top: 0, //to fix gap between label box and container
}}
```

**Comment by kesteer** [comment]
Through some extensive testing that I've done, it seems that the best way to handle this in Android is to make sure the `<DropDownPicker>` component is either called in the same parent view, or, as @hasansna  has mentioned make sure that the parent does not have a `zIndex` style attached to it. 

The latest versions of the package already use `nestedScrollEnabled` on the internal `ScrollView` when using `listMode='SCROLLVIEW'` so adding this wont really do anything. 

If anyone runs into an issue on Android where the dropdown properly shows for a few open/close cycles but then reverts to showing beneath other components/views, you can use the following temporary patch file that I made. This should fix the issue with Android not properly rendering things with zIndex. 

At some point I might look into opening up a PR to fix the underlying issues (some of it has to do with how Android renders ScrollViews via React)

```patch

diff --git a/node_modules/react-native-dropdown-picker/src/components/Picker.js b/node_modules/react-native-dropdown-picker/src/components/Picker.js
index c769683..3bdcde6 100644
--- a/node_modules/react-native-dropdown-picker/src/components/Picker.js
+++ b/node_modules/react-native-dropdown-picker/src/components/Picker.js
@@ -1644,11 +1644,11 @@ function Picker({
      * @returns {JSX.Element}
      */
     const DropDownComponentWrapper = useCallback((Component) => (
-        <View style={_dropDownContainerStyle}>
+        <View style={[_dropDownContainerStyle, !open && {borderWidth: 0}]}>
             {SearchComponent}
             {Component}
         </View>
-    ), [_dropDownContainerStyle, SearchComponent]);
+    ), [_dropDownContainerStyle, SearchComponent, open]);
 
     /**
      * The ActivityIndicatorComponent.
@@ -1738,7 +1738,7 @@ function Picker({
      */
     const DropDownScrollViewComponent = useMemo(() => {
         return (
-            <ScrollView ref={scrollViewRef} nestedScrollEnabled={true} stickyHeaderIndices={stickyHeaderIndices} {...scrollViewProps}>
+            <ScrollView style={!open && {maxHeight: 0}} ref={scrollViewRef} nestedScrollEnabled={true} stickyHeaderIndices={stickyHeaderIndices} {...scrollViewProps}>
                 {_items.map((item, index) => { 
                     return (
                         <Fragment key={item[_itemKey]}>
@@ -1750,7 +1750,7 @@ function Picker({
                 {_items.length === 0 && _ListEmptyComponent()}
             </ScrollView>
         );
-    }, [__renderListItem, _itemKey, scrollViewProps, _ListEmptyComponent]);
+    }, [__renderListItem, _itemKey, scrollViewProps, _ListEmptyComponent, open]);
 
     /**
      * The dropdown modal component.
@@ -1789,7 +1789,7 @@ function Picker({
      * @returns {JSX.Element}
      */
     const DropDownBodyComponent = useMemo(() => {
-        if (open || listMode === LIST_MODE.MODAL)
+        if (open || listMode === LIST_MODE.MODAL || listMode === LIST_MODE.SCROLLVIEW)
             return DropDownComponent;
         return null;
     }, [open, listMode, DropDownComponent]);

```

**Comment by Dhrumil2303** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

Its Worked for me

Thank You.

**Comment by amit-owninfotech** [comment]
Its Worked for me

Thank You.

**Comment by loupmasneri** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

This is working perfectly on Android thank you!

**Comment by foresthu2006** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

This pushes down the content below the dropdown when i open it, any ideas?

**Comment by hiagolfMB** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

you might also need to use listMode='SCROLLVIEW', as in my case.

Thanks, saved me.

**Comment by pythonistastic** [comment]
Hi guys I have an issue with the dropdown that it doesnt scroll when inside scrollview, I have this in my scrollview:

```
<ScrollView
        showsVerticalScrollIndicator={false}
        scrollEnabled={scrollEnabled}
      >
```
      
      <```
DropDownPicker
          open={open}
          setOpen={(isOpen) => {
            setOpen(isOpen);
            setScrollEnabled(!isOpen); // Disables the scroll when the dropdown is open
          }}
          items={items}
          zIndex={10000}
          defaultValue={selectedCity}
          containerStyle={{ height: 40, zIndex: 10000 }}
          style={{
            backgroundColor: "#fafafa",
            borderWidth: open ? 2 : 1,
            borderBottomWidth: open ? 0 : 1,
            borderColor: open ? "red" : "silver",
          }}
          itemStyle={{
            justifyContent: "flex-start",

            backgroundColor: "#fafafa",
          }}
          listMode="SCROLLVIEW"
          scrollViewProps={{
          nestedScrollEnabled: true,
          }}
          value={value}
          setValue={setValue}
          dropDownStyle={{ zIndex: 10000, backgroundColor: "#fafafa" }}
          dropDownContainerStyle={{
            backgroundColor: "#fafafa",
            borderWidth: 2,
            borderColor: "red",
            borderTopWidth: 0,
            zIndex: 10000,
          }}
          onChangeItem={(item) => setSelectedCity(item.value)}
        />
```
        
        I have this snippet of code, anyone find the solution?

**Comment by Umair-max** [comment]
I was facing the same issue , i was using it inside of scrollView, the dropdownpicker was working well in IOS but on android the scroll the dropdownpicker was not working so i applied nestedScrollEnabled in parent scrollView or flatlist , then the scroll issue resolved on android

**Comment by zahid502** [comment]
facing same issue

**Comment by ritubhagwasiyadms** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

This solution should be on Top. :) Thanks @rajAmukhliS

**Comment by krushi-jinjurde** [comment]
> I think, I found the solution
> 
> in the source code check the styles. It uses position:'absolute' for dropdown items list, if you get rid of it, the list will be shown accurately
> 
> ```
> dropDownBox: {
>        borderTopLeftRadius: 0,
>        borderTopRightRadius: 0,
>        alignItems: 'center',
>        justifyContent: 'center',
>        textAlign: 'center',
>        position: 'relative',// It was absolute
>        width: '100%'
>    },
> ```
> 
> and then if you want to get rid of the gap, you need to get rid of the top: this.state.top section
> 
> ```
> {
>  top: this.state.top,
>  maxHeight: this.props.dropDownMaxHeight,
>  zIndex: this.props.zIndex
> }
> ```
> 
> Unfortunately this makes the views below to be pushed to bottom

this worked for me i had a list inside a modal

**Comment by MAhnaf** [comment]
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}




This is working for me 
But as dropdown opens it pushes down all the components below it.

Any fix for this ?
Thanks

**Comment by kesteer** [comment]
@MAhnaf 

That is expected because you are now changing the dropdown picker to `relative` instead of `absolute`. The picker needs to be `absolute` so that it doesn't interact with other elements placed below it. 

https://github.com/hossein-zare/react-native-dropdown-picker/issues/57#issuecomment-1401447045

You can try what was suggested by me and @hasansna in other comments.

**Comment by TSD404** [comment]
> I resolved the **scroll issue of dropdown container** by using `position: 'relative'` in **dropDownContainerStyle**
> 
> ```
> 
> dropDownContainerStyle={{
> borderColor: theme.colors.gray4,
>     position: 'relative', // to fix scroll issue ... it is by default 'absolute'
>     top: 0, //to fix gap between label box and container
> }}
> ```

This resolves two issues, the scrolling issue and the overlapping issue. but the other components keep moving up and down every time the dropdown is opened or closed.
