### ISSUE TITLE
Make disabled prop reactive

### ISSUE THREAD

**Issue by fragkp** [hossein-zare/react-native-dropdown-picker#58]
Hey :)

**Is your feature request related to a problem? Please describe.**
We've multiple Pickers implemented that react to each other. When some Picker has only one option left, that Picker should go to a disabled state.

**Describe the solution you'd like**
Make disabled property reactive (state-friendly).

**Comment by hossein-zare** [comment]
Hello,

The `disabled` property is state-friendly.
https://snack.expo.io/@hossein-zare/disabled-property

**Comment by fragkp** [comment]
Then I assume there has been an issue on our part.

Thanks for the fast response!
