### ISSUE TITLE
[IOS] Dropdown height issue

### ISSUE THREAD

**Issue by RutvinBhanderi** [hossein-zare/react-native-dropdown-picker#586]
If I decrease the height of container below 50px it is not decreasing.

**Comment by smohit02** [comment]
This is still an issue. Why was the issue closed?

@RutvinBhanderi

**Comment by rahul-techwondoe** [comment]
> This is still an issue. Why was the issue closed?
> 
> @RutvinBhanderi

@smohit02  This worked for me

https://github.com/hossein-zare/react-native-dropdown-picker/issues/549#issuecomment-1122798528

**Comment by SherifSamirr** [comment]
```
style={{
  minHeight: 30,  // whatever height you want
}}
```
