### ISSUE TITLE
How to enable keyboardShouldPersistTaps?

### ISSUE THREAD

**Issue by Svarto** [hossein-zare/react-native-dropdown-picker#59]
Hi, 

Nice work! I have the dropdown within a ScrollView and I want it to follow keyboardShouldPersistTaps="handled". 

It works when initially clicking the dropdown to appear but when selecting an option the keyboard closes. I assume somehow the ScrollView does not see the selecting of an option in the dropdown as a handled event.

Would really appreciate some help in getting this to work!

**Comment by thebluewall2** [comment]
I have created a pull request #75 to support passing ScrollView props into the dropdown picker. You can pass scrollView props by passing 

`<DropDownPicker
    {...props}
    scrollViewProps={{
        keyboardShouldPersistTaps='handled'
    }}
/>`

**Comment by Svarto** [comment]
That is awesome! Thanks a lot @thebluewall2. @hossein-zare let us know when you publish a new version with this included, will update it in my app then. Thanks a lot for all the work here!

**Comment by jakobwak** [comment]
Hey, I have a case, where I have a normal TextInput field (which opens the Keyboard), then clicking into the DropdownPicker, which first will close the Keyboard, then another click is needed to open the DropdownPicker. Do you have a solution or suggestion to open the DropdownPicker in one click? Many Thanks.
