### ISSUE TITLE
How to handle z index issue

### ISSUE THREAD

**Issue by Saikedo** [hossein-zare/react-native-dropdown-picker#596]
Is there a good way to force the dropdown to render on top of other components without using the modal approach ?

If you look at [this example](https://snack.expo.dev/@saikedo/example), you will see that the dropdown opens behind the other view.

Of course, it is possible to indicate the zIndex for the parent view to be 1 in this case but in some other circumstances, this might be a bit more problematic.

**Comment by mikehardy** [comment]
Yes https://github.com/hossein-zare/react-native-dropdown-picker/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc

I did this, it worked well
https://github.com/hossein-zare/react-native-dropdown-picker/issues/376

**Comment by brada1703** [comment]
hey @Saikedo , add the zIndex property to the View that the DropDownPicker is contained in. Like this: https://snack.expo.dev/_vBICNg22 (Note line 29)
