### ISSUE TITLE
Only 4 options?

### ISSUE THREAD

**Issue by oscarsales** [hossein-zare/react-native-dropdown-picker#6]
All of my dropdowns show only maximum 4 options, though they have more. When the number of options is > 4, at least the dropdown should have an inner scroll.

I don't know if I can display more options by increasing the height, but anyway, in one case I'm using the dropdown to select your birthdate, and the selector for the year includes the last 80 years. I can't increase the height for 80 options, that's crazy. In another case, you select your Country, that's not 80 options but there are a lot too. The content should be scrollable.

**Comment by hossein-zare** [comment]
Hello,

I've created an Expo Snack to test the ScrollView, [https://snack.expo.io/v5yOnG7Cp](https://snack.expo.io/v5yOnG7Cp )
It's ok with both iOS & Android, I didn't see anything. You can double-check your parent elements.
Make sure you're using the latest version of the package.

**Comment by hossein-zare** [comment]
Wrong styling can result in unexpected behaviors.

**For example:**
This will make the ScrollView untouchable.
```
containerStyle={{flex: 1, height: 40, borderBottomRightRadius: 0, borderTopRightRadius: 0}}
```

The right way to style the component.
```
containerStyle={{flex: 1, height: 40}}
style={{borderBottomRightRadius: 0, borderTopRightRadius: 0}}
```
