### ISSUE TITLE
Limit loaded list items to increase performance

### ISSUE THREAD

**Issue by usersina** [hossein-zare/react-native-dropdown-picker#62]
**Description:**
My `DropDownPicker` has over 160 entries which causes the application to stutter a little bit when it's opened.

**Possible solution:**
Limiting the number of items loaded in the dropdown initially, then expanding it every time the user scrolls to the bottom.

**Additional context (not related):**
Any updates on the [selected label text limit](https://i.imgur.com/JQiJNEJ.jpg) ?

EDIT: It's probably not that big of a deal, I've tried the app in release build and it's way faster than the debug build.

**Comment by hossein-zare** [comment]
Not yet.

**Comment by ferras1** [comment]
I'm stuck with the same situation, with the difference that my dataset for the dropdown is over 3.000 entries. Is it possible to get the input search value ? and maybe filter the array on the run and update the dataset

**Comment by alihaider589** [comment]
the same issue I faced the data I received is over 300, so the entires go below the scroll bar

**Comment by Vitor-Felix** [comment]
I was going to suggest something like that. Maybe even simpler, just the part of 

> Limiting the number of items loaded in the dropdown initially

The `react-native-dropdown-picker` is almost perfect for my need, but when the list has too many items it broke!
If I could limit rendering only 3, 5 or 7 items and let only the "search mode" running, it would be great!

**Comment by hossein-zare** [comment]
Hello again,

I'll resolve this issue, most likely. But i don't promise. And i'll let you know about the bugfix in the next versions. 🙂

**Comment by hossein-zare** [comment]
**v5.x is out**,
I'm closing this issue.
