### ISSUE TITLE
Disable dropdown press animation

### ISSUE THREAD

**Issue by JatB01** [hossein-zare/react-native-dropdown-picker#624]
Hi all,

I can't seem to find the prop or method to disable the touchable opacity fade animation on the dropdown container. Every time I click it has a fade animation that I want to remove. 

Any way to achieve this?

**Comment by JatB01** [comment]
Nevermind, I found the solution by adding:

`props={{activeOpacity: 1}}` to the DropDownPicker component. This passes down to the `TouchableOpacity` render

**Comment by ryansherby** [comment]
Just wanted to let you know you're awesome for discovering this
