### ISSUE TITLE
Border radius is not working for style property 

### ISSUE THREAD

**Issue by sailywebvillee** [hossein-zare/react-native-dropdown-picker#63]
Hello @hossein-zare 

Border radius property is not working for the style property as I need a rounded background. 

**Describe the bug**

**To Reproduce**

Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker#borderradius

**Comment by xiaohengpan** [comment]
@hossein-zare borderRadius are individually set per documentation, however, upon opening the popup, the bottom radius disappears (see gif). any ideas? 

```
      style={{
        backgroundColor: theme.colors.ctaMain10,
        borderWidth: 0,
        width: 80,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10
      }}
```

![bug](https://user-images.githubusercontent.com/74780418/105907508-088bbf80-5ff3-11eb-9f50-fcccbc648f8b.gif)

**Comment by arman-sapient** [comment]
disableBorderRadius={true}
