### ISSUE TITLE
Loading true and items=[] does not show ActivityIndicator

### ISSUE THREAD

**Issue by sakshambhatt** [hossein-zare/react-native-dropdown-picker#649]
Hello,
I was unable to see the ActivityIndicator when items was an empty array and loading true while fetching data from API.
So, I tried to invoke the component is loading=true and items=[]. It still doesn't show the ActivityIndicator.
Could someone please help?

```
const TzActivityIndication = useCallback(
    ({color, size}: {color: string; size: number}) => (
      <ActivityIndicator color={color} size={size} />
    ),
    [],
  );

return (<DropDownPicker
        open={isOpen}
        setOpen={setIsOpen}
        value={currentTzValue}
        setValue={setCurrentTzValue}
        items={[]}
        loading={true}
        searchable={true}
        listMode="MODAL"
        style={styles.dropdown}
        containerStyle={styles.dropdownContainer}
        itemSeparator={true}
        itemSeparatorStyle={{
          backgroundColor: colors.inputBorderColor,
        }}
        listItemContainerStyle={styles.listItemContainer}
        ActivityIndicatorComponent={TzActivityIndication}
        activityIndicatorColor={colors.secondaryColor}
        activityIndicatorSize={30}
      />)
```

Screenshot: 
![image](https://user-images.githubusercontent.com/33225002/222904539-4c17d7b5-f045-469e-96aa-9f7d5ad2cb1e.png)

Similar issues: [Issue 473](https://github.com/hossein-zare/react-native-dropdown-picker/issues/473), [Issue 485](https://github.com/hossein-zare/react-native-dropdown-picker/issues/485)

**Comment by hossein-zare** [comment]
Hi,
It worked, Start with a simple picker and add additional props one by one.

**Comment by sakshambhatt** [comment]
Sorry to have missed your comment. Will try this out today, and share my findings with you

**Comment by sakshambhatt** [comment]
I have created a simple component, where the data is fetched from an API. While the promise is in progress, loading is true. And once the promise is settled, the loading state becomes false. 
I have added another ActivityIndicator for reference which works fine.
Could you please tell me if I am doing something wrong?

[Component github link](https://github.com/sakshambhatt/TestActivityIndicator/blob/main/src/components/CarDropdown.tsx)
I am attaching a recording of this component below for your reference:
![dropdown](https://user-images.githubusercontent.com/33225002/227786778-8265ffc5-72de-45d7-8e48-8b8938e0c927.gif)

Thanks for your help!

**Comment by hossein-zare** [comment]
Press the picker (Select an item) while `loading` is `true`.
You'll see an ActivityIndicator.

```js
// Set the open state to TRUE for testing so you don't need to press the picker
const [open, setOpen] = useState(true);
```

**Important!**
Your `items` state **MUST** be **empty**.
You always see the `Select an item` message whether `loading` is `true`.

**Comment by sakshambhatt** [comment]
Thank you for clearing it up.
Here is how the ActivityIndicator looks
![dd1](https://user-images.githubusercontent.com/33225002/227831862-5f42fe00-db6f-41fc-a015-6ecac43e7f75.gif)
