### ISSUE TITLE
DropdownList doesnt load items after state change

### ISSUE THREAD

**Issue by luizproenca** [hossein-zare/react-native-dropdown-picker#66]
**Describe the bug**
I am passing a list of items through this.state.list and the dropdown does not load any items.
This this.state.list is filled with a list from an api.
The component loads before this.state.list is populated and the component is not updated.

**To Reproduce**
When loading the screen with the dropdown for the first time nothing is displayed in the list.
When I save the file in my vscode the emulator screen is loaded and the dropdown displays my list.

**Expected behavior**
The dropdown should be rendered again if the list was changed.

**Screenshots**
First load
![image](https://user-images.githubusercontent.com/22194946/87686552-fe8f2700-c75a-11ea-8dd1-8c24a6242fc8.png)

After CTRL+S on my file.js
![image](https://user-images.githubusercontent.com/22194946/87686730-3ac28780-c75b-11ea-9812-50ee976a5030.png)

**Info (please complete the following information):**
 - OS: Android
 - Package version 28

**Font**
import React, { useEffect, useState } from 'react';
import { View, TextInput, Text, StyleSheet, TouchableOpacity } from 'react-native';
import DropDownPicker from 'react-native-dropdown-picker';
import _ from 'lodash';
import auth from '@react-native-firebase/auth';
import database from '@react-native-firebase/database';

import { lightTheme } from '../styles/theme';
import { dimensions } from '../Constants';

export const InputProduct = ({ text, selectedValue, onValueChange }) => {
    const [iconColor, setIconColor] = useState(lightTheme.SECONDARY_ICON_COLOR);

    const [products, setProducts] = useState([]);
    const [itemList, setItemList] = useState([]);

    const _filled = (item, index) => {
        if (item != null) {
            setIconColor(lightTheme.PRIMARY_ICON_COLOR);
        }
        else {
            setIconColor(lightTheme.SECONDARY_ICON_COLOR);
        }

        const itemProduct = products.find(item => item.uid = item);
        onValueChange(item, index, itemProduct)
    }

    const adjustArray = (lista) => {
        const cust = _.map(lista, (val, uid) => {
            return { ...val, uid }
        })
        setProducts(cust);
        console.log("lista_convertida" + JSON.stringify(products));
        const newArray = [];
        products.forEach(element => {
            newArray.push({ label: element.name, value: element.uid });
        });
        setItemList(newArray);
        console.log("lista_newArray" + JSON.stringify(itemList));
    }

    useEffect(() => {
        var user = auth().currentUser;
        //console.log("USER_ID" + " -- " + user.uid + " -- ")

        database().ref('/users/' + user.uid + '/products/')
            .on('value', snapshot => adjustArray(snapshot.val()))
    }, []);

    return (
        <DropDownPicker
            items={itemList}
            defaultValue={null}
            placeholder="Select product"
            arrowSize={30}
            arrowColor={lightTheme.PRIMARY_BUTTON_COLOR}
            containerStyle={{ height: 60, width: "100%", marginTop: 8, }}
            style={{
                borderTopLeftRadius: 30, borderTopRightRadius: 30,
                borderBottomLeftRadius: 30, borderBottomRightRadius: 30
            }}
            dropDownStyle={{
                borderBottomLeftRadius: 30, borderBottomRightRadius: 30
            }}
            itemStyle={{
                justifyContent: "space-between"
            }}
            labelStyle={{
                marginLeft: 8, fontSize: dimensions.FONT_SIZE_NORMAL,
                fontFamily: dimensions.FONT_FAMILY_MEDIUM, color: iconColor
            }}
            dropDownStyle={{ backgroundColor: '#fafafa', }}
            onChangeItem={_filled}
            //searchable={true}
            searchablePlaceholder="Search product..."
            searchableStyle={styles.input}
        />
    );

}

const styles = StyleSheet.create({
    inputContainer: {
        borderWidth: 1,
        height: dimensions.BUTTON_HEIGHT_DEFAULT,
        borderRadius: 8,
        marginTop: 8,
        paddingHorizontal: 8,
        paddingBottom: 16
    },
    input: {
        height: 30,
    },
    label: {
        height: 20,

    },
    input: {
        flex: 1,
        fontFamily: dimensions.FONT_FAMILY_MEDIUM,
        fontSize: dimensions.FONT_SIZE_NORMAL,
        marginLeft: 8,
        height: "100%",
        color: lightTheme.PRIMARY_BUTTON_COLOR,
    },

});

**Comment by usersina** [comment]
**adjustArray.js**

Instead of:
```JAVASCRIPT
products.forEach(...
````
Try doing:
```JAVASCRIPT
cust.forEach(...
````
