### ISSUE TITLE
Android Styling issue 

### ISSUE THREAD

**Issue by Shubhankar-appstango** [hossein-zare/react-native-dropdown-picker#667]
While opening the drop down box in android it goes behind the next View

Here is the Information 

System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 33.32 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.01.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/shubhankarkoner/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found  
![Screenshot_1683033741](https://user-images.githubusercontent.com/130644419/235679103-e665c864-3a4a-47b7-8eff-961eb396ff0b.png)

Please help me with the correct styling if anything I am doing wrong

**Comment by denzelwas** [comment]
Have the same issue!

**Comment by RayKay91** [comment]
Wrap the overlapping item with a style of `{ zIndex: -1 }`

this solves it for me.

**Comment by Shubhankar-appstango** [comment]
> Wrap the overlapping item with a style of `{ zIndex: -1 }`
> 
> this solves it for me.

Thank you @RayKay91 for the lovely suggestions, Its working with android.

So I am closing this issue.

Than you once again.

**Comment by MirzaArslan124** [comment]
If you are using 2 dropdown and facing such issue then you can try 
     zIndex={-1}
     in second DropDown
