### ISSUE TITLE
Custome Arrow

### ISSUE THREAD

**Issue by iamir4g** [hossein-zare/react-native-dropdown-picker#67]
hi, I want to show my custom Arrow down and up in `.png` format. how to use my custom png arrow in the **left** side of the container?

**Comment by hossein-zare** [comment]
Hello,

**PNG Arrow Icons:**
```javascript
import { Image } from 'react-native';

<DropDownPicker
    customArrowUp={size => <Image source={require('path-to-icon')} style={{width: size, height: size}} />}
    ...
    arrowSize={20}
/>
```

Currently it's not possible to modify the alignment of the icons, but _in the next version_ or unless your app supports RTL it'll be aligned automatically.
