### ISSUE TITLE
Dropdown items overlapping other TextInput

### ISSUE THREAD

**Issue by jeremycod** [hossein-zare/react-native-dropdown-picker#68]
Hi,

I'm having Dropdown picker just above TextInput so dropdown items open above the text input (see the screenshot)

![Screen Shot 2020-07-22 at 9 09 57 PM](https://user-images.githubusercontent.com/5204745/88251785-c3ac5800-cc60-11ea-921b-a52f1dfbdd31.png)

That makes impossible to select Dropdown item and instead Text input field gets focus. Is there some solution to solve this issue?

**Comment by hossein-zare** [comment]
Hello,

**Please read the zIndex conflicts section:**
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by jeremycod** [comment]
Thanks for your quick response. The problem was that container style has some properties such as:
```
      borderWidth: 1,
        borderRadius: 10,
        borderColor: 'lightgray',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 0.41,

```

and these are not accepted. Once I've removed it, Dropdown picker works as expected.

Now, I have another problem by not being able to style container. All my form fields in the app are having the borders styled as above, and Dropdown picker is sticking out with different design. Is there some way to fix this?

**Comment by hossein-zare** [comment]
You can use the `style` property instead.

**Comment by jeremycod** [comment]
I've tried that already, but non of these styles are having effect when I add it to style. I can only change backgroundColor, but other properties are not having effect.

**Comment by hossein-zare** [comment]
https://snack.expo.io/@hossein-zare/dropdownpicker-style
Works as expected.

**Comment by jeremycod** [comment]
Thanks. That works. borderRadius doesn't work for some reason and there were some other properties whose use causing no style to be applied.
Everything is good now when I'm aware of that.

**Comment by hossein-zare** [comment]
**For** `borderRadius`
https://github.com/hossein-zare/react-native-dropdown-picker#borderradius

**Comment by 1337developer1337** [comment]
Why closed? There is no solution to the original problem.
