### ISSUE TITLE
showArrow doesn't display arrow

### ISSUE THREAD

**Issue by jeremycod** [hossein-zare/react-native-dropdown-picker#69]
I've set showArrow to true, but arrow is not displayed. Here is the code:

```
               <DropDownPicker
                    items={data}
                    defaultValue={everyChoice}
                    containerStyle={styles.dropdownContainerStyle}
                    style={styles.dropdownStyle}
                    labelStyle={styles.dropdownLabel}
                    activeLabelStyle={styles.dropdownLabel}
                    placeholder={'Select an item'}
                    dropDownStyle={{backgroundColor: '#fafafa'}}
                    onChangeItem={item => setEveryChoice(item.value)}
                    showArrow={true}
                />
....
dropdownContainerStyle: {
        marginTop: 10,
        marginBottom: 10,
        flex: 0.8,
        borderWidth: 1,
        borderRadius: 10,
        borderColor: 'lightgray',
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 0.41,
    },
    dropdownStyle: {

        paddingBottom: 10,
        paddingTop: 10,
        marginTop: 0,
        marginBottom: 0,
        borderRadius: 10,
        height: 50
    },
    dropdownLabel: {
        justifyContent: 'flex-start',
        fontSize: 15,
        color: '#a4a4a4',
    },

**Comment by hossein-zare** [comment]
Hello.

**Please read the styling the component section:**
https://github.com/hossein-zare/react-native-dropdown-picker#styling-the-component

Your `containerStyle` contains illegal props, If you see a crossed out square, that's a [oblador/react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) issue.
By the way the `showArrow` property isn't necessary because it's default value is always `true` unless you change it to `false`. 
If none of the above apply to your issue, please attach your screenshot.

**Comment by jeremycod** [comment]
I've simplified design so it's now look like this:

  ```
          <DropDownPicker
                    items={data}
                    placeholder='Select frequency'
                    containerStyle={{flex: 0.8, height: 50}}
                    style={{ backgroundColor: '#ffffff'}}
                    dropDownStyle={{ backgroundColor: 'white' }}
                />
```
But arrow is still not visible. Please check screenshots:

![Screen Shot 2020-07-23 at 7 55 01 AM](https://user-images.githubusercontent.com/5204745/88301789-ed459d80-ccb9-11ea-9989-67afb31df2a0.png)
![Screen Shot 2020-07-23 at 7 55 32 AM](https://user-images.githubusercontent.com/5204745/88301817-f46cab80-ccb9-11ea-8c70-0a11d2594f6c.png)

**Comment by hossein-zare** [comment]
It seems more like a **react-native-vector-icons** issue.

This may help you:
https://github.com/oblador/react-native-vector-icons/issues/463

**Comment by jeremycod** [comment]
You're right
react-native link react-native-vector-icons
solved it.
Thanks
