### ISSUE TITLE
zIndex has no effect

### ISSUE THREAD

**Issue by plaporte** [hossein-zare/react-native-dropdown-picker#7]
Using iOS simulator the dropdowns are going behind my other text inputs on the screen when open. I've set the zIndex as high as 50000 with no luck.

` <DropDownPicker
                    items={[
                      { label: "1", value: 1 },
                      { label: "2", value: 2 },
                      { label: "3", value: 3 },
                      { label: "4", value: 4 },
                      { label: "5", value: 5 },
                    ]}
                    containerStyle={{
                      marginHorizontal: 12,
                      marginVertical: 10,
                      flex: 1,
                      width: "50%",
                    }}
                    zIndex={50000}
                    defaultNull
                    placeholder="Total Courts"
                    onChangeItem={(item) => console.log(item.label, item.value)}
                  />`

**Comment by hossein-zare** [comment]
Hello,

It's working fine.
https://snack.expo.io/ieWYr1e3d

If this is not your case please create an Expo Snack and help me find out what's causing the problem.

**Comment by hossein-zare** [comment]
#6

**Comment by leslielyj** [comment]
Hey guys, zIndex still does not work as of v2.1.3, however you can put zIndex as a style in a View component:
```
<View style={{zIndex: 99999}}>
          <DropDownPicker
            items={[
              {label: '1', value: 1},
              {label: '2', value: 2},
              {label: '3', value: 3},
            ]}
            containerStyle={{height: 40, width: "20%",flex: 1}}
            
            onChangeItem={item => this.setState({ no_of_people: item.value })}
            dropDownMaxHeight={100}
          />
</View>
```

@plaporte @hossein-zare

**Comment by hossein-zare** [comment]
Hello @leslielyj 
Please send me your `render()` function which contains DropDownPicker that has zIndex issues if possible.

**Comment by leslielyj** [comment]
![image](https://user-images.githubusercontent.com/17871490/83025336-88771980-a061-11ea-8713-38af564072cc.png)

**Comment by hossein-zare** [comment]
Thank you @leslielyj ,
As of [https://github.com/hossein-zare/react-native-dropdown-picker/issues/6#issuecomment-633239417](https://github.com/hossein-zare/react-native-dropdown-picker/issues/6#issuecomment-633239417), Please share the `styles.dropdown`.

**Comment by FaysalBsata** [comment]
I think the problem occurs when nesting in a scrollview!

**Comment by TheDude70** [comment]
Having same issue on iOS when using a scrollView 😞 . Will have to look for other solution if this does not work with iOS.

**Comment by rajeshyg6** [comment]
not using scrollView still zIndex not working in iOS, works fine in Android
