### ISSUE TITLE
Scroll View Not going automatically to selected item on open

### ISSUE THREAD

**Issue by karanmartian** [hossein-zare/react-native-dropdown-picker#71]
So this may be a bug, but is very important from a visual standpoint.

If I have a long scroll list with many items, if I have selected item A, then it will show up as the active and selected item. However, if the user opens the dropdown again he should be automaticallly taken to the current selected item in the list. Instead the scroll view remains at the top. Any way to fix this?

**Describe the bug**

**To Reproduce**

Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by hossein-zare** [comment]
Hello,

No, not a bug but can be a new feature request.
I'll fulfill it in the next version.

**Comment by karanmartian** [comment]
Thanks, also could you add a prop for persistentScrollbar?

It gives a good visual indication when the list is long that there are more items.
Right now I am having to do this in the source code.

<ScrollView
                        style={{ width: "100%" }}
                        nestedScrollEnabled={true}
                        **persistentScrollbar={true}**
                    >

**Comment by hossein-zare** [comment]
Yeah, it'll be added.

**Comment by krishna-bhatta** [comment]
@karanmartian You can pass scrollViewProps to fix this.
Here's my example within ScrollView and working perfectly:

```
<ScrollView>
<DropDownPicker
    scrollViewProps={{ nestedScrollEnabled: true, persistentScrollbar: true }}
    items={options}
    containerStyle={{ height: 40 }}
    itemStyle={{
      justifyContent: "flex-start",
    }}
    dropDownStyle={{ backgroundColor: _colors.platinum_dark }}
    onChangeItem={(item) => {
      setDropDownValue(item);
    }}
  />
</ScrollView>
```
