### ISSUE TITLE
DropDown menu is behind a view with elevation on Android

### ISSUE THREAD

**Issue by jyepesr1** [hossein-zare/react-native-dropdown-picker#74]
**Describe the bug**
When de DropDown menu is displayed and we have a view below with elevation style to add shadow, so the menu is behind if we change the elevation of the picker or the zIndex in Android it won't work, the items become untouchable.

**To Reproduce**
1. Create the DropDown picker
2. Add below a View with elevation property

Create an expo snack:
https://snack.expo.io/2GRruC02k

**Expected behavior**
The Picker should be displayed on top of the view when the elevation is higher

**Info (please complete the following information):**
 - OS: Android
 - Package version Expo SDK 38

**Comment by hossein-zare** [comment]
Hello,

The `elevation` property is in conflict with the `zIndex` prop.

**Here's the solution:**
```javascript
<View style={{flex: 0.2, zIndex: -1}}>
    <View style={styles.btnCartView}>
        <TouchableOpacity>
            <Text style={styles.btnCart}>Add to Cart</Text>
        </TouchableOpacity>
    </View>
</View>

btnCartView: {
    flex: 1,
    ...
}
```
https://snack.expo.io/@hossein-zare/dropdownpicker-elevation

**Comment by jyepesr1** [comment]
Hello @hossein-zare,

Thank you for your quick reply. I see the problem. I will add the negative `zIndex`

Additionally, I'm having an issue with two pickers, the common FAQ you have posted in the README "Clicking on another picker doesn't close the other pickers?", for me, the proposed solution is not working. Do I need to create another issue for this problem or can you check it in this same thread?

This is the expo snack:
https://snack.expo.io/eBaj5scxD

**Comment by hossein-zare** [comment]
You've forgotten to set `isVisible` property.
https://snack.expo.io/w_8_HBXjo

**Comment by jyepesr1** [comment]
Thank you @hossein-zare, that helped me a lot!
