### ISSUE TITLE
dropdown list conflict with below View

### ISSUE THREAD

**Issue by saaspeter** [hossein-zare/react-native-dropdown-picker#754]
Hi:   When I use this good lib, I encounter a problem, see below picture:
<img width="331" alt="截屏2024-05-16 15 49 36" src="https://github.com/hossein-zare/react-native-dropdown-picker/assets/3772321/2df4d855-0b51-4673-b5b2-44637f72fea6">

the View is under the select dropdown list, they are conflicted. The component's version is: 5.4.6.  The code like this:
"< View style={styles.pickerView} >
  <DropDownPicker  containerStyle={styles.pickerStyles}
    style={{ backgroundColor: "crimson" }}
    open={open}
    value={drugDose.unitType}
    items={items}
    mode={"SIMPLE"}
    textStyle={{ fontSize: 17 }}
    setOpen={setOpen}
    setValue={handleSlectChange}
    setItems={setItems}
  />
</ View>
< View style={styles.footerView}>
    < Text text="Generally, the dosage instructions... " />
</ View>"

I tried to add zIndex=1000 in DropDownPicker or add zIndex=1000 in its parent's View style (pickerView), but they all don't take effect in IOS simulator.  **My solution is to set zIndex=-1 in its below text view: styles.footerView, but I don't think it is a good solution, I think there should has a property in DropDownPicker to control the overlap problem**. (unfortunately zIndex don't work), Is there any good solution?

(I found this issue: https://github.com/hossein-zare/react-native-dropdown-picker/issues/103, but the solution link in it cannot find this section: "[zindex-conflicts-untouchable-items-overlapping-pickers](https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers)")

**Comment by AtulCube** [comment]
<img width="296" alt="Screenshot 2024-05-24 at 3 12 20 PM" src="https://github.com/hossein-zare/react-native-dropdown-picker/assets/170718393/5aa5de2d-4388-4180-9229-f4417317a263">
same here

**Comment by AtulCube** [comment]
<img width="269" alt="Screenshot 2024-05-24 at 3 13 01 PM" src="https://github.com/hossein-zare/react-native-dropdown-picker/assets/170718393/551758a2-fd4a-4a51-9009-693fa62b4928">

**Comment by Awnish-10** [comment]
i have 2 DropDownPicker one below another adding this styling property fixes overlap problem for me
      containerProps={{
        style: {
          zIndex: open ? 10 : 1,
        },
      }}
      my entire custom component looks like
      import React, { useState } from 'react';

import { StyleSheet } from 'react-native';

import DropDownPicker from 'react-native-dropdown-picker';
import { horizontalScale, verticalScale, scale } from '../../utils/scaling';

export default function CustomDropdown({ value, setValue, items }) {
  const [open, setOpen] = useState(false);

  return (
    <DropDownPicker
      open={open}
      value={value}
      items={items}
      setOpen={setOpen}
      setValue={setValue}
      theme="DARK"
      style={styles.container}
      containerProps={{
        style: {
          zIndex: open ? 10 : 1,
        },
      }}
    />
  );
}
const styles = StyleSheet.create({
  container: {
    backgroundColor: '#1A1C24',
    borderRadius: scale(24),
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(16),
    color: '#FEFEFE',
    fontSize: scale(14),
    fontWeight: '600',
  },
});

**Comment by IuriKintschev** [comment]
![image](https://github.com/hossein-zare/react-native-dropdown-picker/assets/42626497/9fd20b01-601a-48e5-8c41-76dfa2a63a12)
same problem here.

Unfortunately the solution above didn't work for me.

**Comment by Awnish-10** [comment]
@IuriKintschev 
you can refer to this example
https://codesandbox.io/s/xenodochial-hopper-vmjfsf?file=/src/CustomDropdown.js

**Comment by ferdiamg** [comment]
Just went like this as props for `<DropDownPicker>`:
```javascript
zIndex={3000}
zIndexInverse={1000}
``` 

and it was solved.

**Comment by saaspeter** [comment]
Thank you all, I switched another simple component. [react-native-picker-select], so I close this issue.

**Comment by mauriciofullana** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker/issues/248
