### ISSUE TITLE
zIndex not work in Flatlist

### ISSUE THREAD

**Issue by Ruslan-BG** [hossein-zare/react-native-dropdown-picker#79]
https://snack.expo.io/TKqxrDWuA
 - OS: [iOS, Android]

**Comment by victormongi** [comment]
Same issue here

**Comment by hossein-zare** [comment]
Hello @Ruslan-BG @victormongi ,

I found a solution for iOS but not for Android yet.
https://snack.expo.io/JSCf3UNRM

Please share your solutions if found any.

**Comment by shorya-stanza** [comment]
```
CellRendererComponent={({ children, index, style, ...props }) => {
            const cellStyle = [
              style,
              {
                zIndex: arr.length - index,
                elevation: arr.length - index,
              }
            ]
        
            return (
                <View style={cellStyle} index={index} {...props}>
                    {children}
                </View>
            )
        }}
```

Add elevation for android

**Comment by hossein-zare** [comment]
@shorya-stanza 
It makes the dropdown untouchable and doesn't solve the issue.

**Comment by pikooli** [comment]
what is the CellRendererComponent ? i never saw it and don't find it on the docs @shorya-stanza

**Comment by shorya-stanza** [comment]
> what is the CellRendererComponent ? i never saw it and don't find it on the docs @shorya-stanza

check this
https://reactnative.dev/docs/virtualizedlist#cellrenderercomponent

**Comment by pikooli** [comment]
thanks

**Comment by mawans** [comment]
Hi,
I am also facing the same issue i used the zIndex and elevation but it makes the items untouchable if anyone find the solution kindly share with me please.

**Comment by mawans** [comment]
> Hi,
> I am also facing the same issue i used the zIndex and elevation but it makes the items untouchable if anyone find the solution kindly share with me please.

Hi this works for me. https://www.npmjs.com/package/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

**Comment by hossein-zare** [comment]
https://github.com/hossein-zare/react-native-dropdown-picker/issues/134

**Comment by Anushuyaseeni** [comment]
import * as React from 'react';
import { Text, View, StyleSheet, FlatList, Platform } from 'react-native';
import Constants from 'expo-constants';

// DropDownPicker
import DropDownPicker from "react-native-dropdown-picker";

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.paragraph}>
        React native dropdown picker
      </Text>

      <View
        style={{
          // The solution: Apply zIndex to any device except Android
          ...(Platform.OS !== 'android' && {
            zIndex: 10
          })
          
        }}
      >
        <DropDownPicker
          items={[
            { label: 'UK', value: 'uk' },
            { label: 'France', value: 'france' },
            { label: 'Germany', value: 'germany' },
          ]}
          placeholder="Select a country"
          containerStyle={{height: 40}}
          style={{ backgroundColor: '#ffffff' }}
          dropDownStyle={{ backgroundColor: 'white' }}
          // dropDownMaxHeight={100}
        />

          <DropDownPicker
          items={[
            { label: 'UK', value: 'uk' },
            { label: 'France', value: 'france' },
            { label: 'Germany', value: 'germany' },
          ]}
          placeholder="Select a country"
          containerStyle={{height: 40}}
          style={{ backgroundColor: '#ffffff' }}
          dropDownStyle={{ backgroundColor: 'white' }}
          zIndex={40}
        />
      </View>
    
      <FlatList
        data={[
          {title: '1. Das Leben ist nicht fair'},
          {title: '2. Wir werden trotzdem sterben'},
          {title: '3. Aber lass uns so leben, wie wir wollen'},
          {title: '4. Das ist besser'},
        ]}
        renderItem={(item, index) => <Text>{item.item.title}</Text>}
        keyExtractor={(item, index) => index.toString()}
        style={{
          marginTop: 60
        }}
        contentContainerStyle={{
          borderRadius: 5,
          padding: 15,
          backgroundColor: 'red'
        }}
      />


    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

this code will help for IOS and android dropdown picker
