### ISSUE TITLE
unrecognized font family feather

### ISSUE THREAD

**Issue by MianJawadAhmad** [hossein-zare/react-native-dropdown-picker#8]
when I include this library it gives me an error.

unrecognized font family feather

**Comment by hossein-zare** [comment]
Hello,
Please install `react-native-vector-icons`
```
npm i react-native-vector-icons
```

**Comment by MianJawadAhmad** [comment]
I have already installed react-native-vector-icons

**Comment by hossein-zare** [comment]
The error is not related to this package, `react-native-vector-icons` is responsible for the error.
There are a bunch of issues created by other users.

This may help you
[https://github.com/oblador/react-native-vector-icons/issues/328](https://github.com/oblador/react-native-vector-icons/issues/328)

**Comment by MianJawadAhmad** [comment]
Thank you resolved.

**Comment by BenHurMartins** [comment]
solution:

```
import Feather from "react-native-vector-icons/Feather";
Feather.loadFont();
```

I did the code above and worked for me

**Comment by phillipkey** [comment]
shouldn't this be added to the installation steps in the readme since it's a required dependency?

**Comment by hossein-zare** [comment]
@phillipkey Yes, You're right. It'll be added with the next version.

**Comment by Sudarshan101** [comment]
follow the below link for solution
https://www.devhubspot.net/post/detail/react-native-unrecognised-font-family-error-solution
