### ISSUE TITLE
How to change border color of the picker?

### ISSUE THREAD

**Issue by hassan-akhtar** [hossein-zare/react-native-dropdown-picker#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rahulkr204** [comment]
You can use this:
`style={{
       borderWidth: 0, 
                                    fontSize: 16
                                }}`

**Comment by Rahulkr204** [comment]
You can use this:
`style={{
                                    borderColor: "red"
                                }}`
