### ISSUE TITLE
Can't pick dropdown on android, ios works

### ISSUE THREAD

**Issue by victormongi** [hossein-zare/react-native-dropdown-picker#82]
Can't pick dropdown on android, ios works

**Comment by dev-seasia** [comment]
@victormongi have you solved this issue? I am facing the same.

**Comment by vinaygoyal20** [comment]
if we add style props to containerStyle it causes issue but if we add to style then it doesn't cause issue.

**Comment by rofisudiyono** [comment]
how to solve it?

**Comment by MukhametzhanDev** [comment]
+++

**Comment by AireshBhat** [comment]
+1
