### ISSUE TITLE
dropdown items are untouchable outside of parent view in android

### ISSUE THREAD

**Issue by pfndesign** [hossein-zare/react-native-dropdown-picker#85]
dropdown items are untouchable in android. you can touch part of the item that is inside of the parent view but not outside it. 
I tried everything that was mentioned in the FAQ section and none of them worked

[stack expo](https://snack.expo.io/@pfndesign/06e828)

**Comment by hossein-zare** [comment]
Hello,

> **DropDownPicker wrapped by <View style={{backgroundColor: '...'}}>**
> Remove the backgroundColor from the parent element.
> https://github.com/hossein-zare/react-native-dropdown-picker/issues/40#issuecomment-651744446
`borderRadius` included.

I commented out all the lines causing issues.
Note that React Native is responsible for the unexpected behavior!
https://snack.expo.io/t!9Z1an0!

**Comment by pfndesign** [comment]
> Hello,
> 
> > **DropDownPicker wrapped by <View style={{backgroundColor: '...'}}>**
> > Remove the backgroundColor from the parent element.
> > [#40 (comment)](https://github.com/hossein-zare/react-native-dropdown-picker/issues/40#issuecomment-651744446)
> > `borderRadius` included.
> 
> I commented out all the lines causing issues.
> Note that React Native is responsible for the unexpected behavior!
> https://snack.expo.io/t!9Z1an0!

thanks, I can't access your expo
"Oops!
We couldn't find the Snack you're looking for"

**Comment by pfndesign** [comment]
> Hello,
> 
> > **DropDownPicker wrapped by <View style={{backgroundColor: '...'}}>**
> > Remove the backgroundColor from the parent element.
> > [#40 (comment)](https://github.com/hossein-zare/react-native-dropdown-picker/issues/40#issuecomment-651744446)
> > `borderRadius` included.
> 
> I commented out all the lines causing issues.
> Note that React Native is responsible for the unexpected behavior!
> https://snack.expo.io/t!9Z1an0!

thanks, your changes fixed the issue for me but I had to reload the app too to see the difference.
it sucks that we can't use borderRadius or backgroundColor for parent view but that can be fixed with an absolute view as the background.
also ارادت و تشکر

**Comment by yogendrajs** [comment]
@hossein-zare it would've been very great to know what did you modify in the code, as the expo link is no longer found to be working
