### ISSUE TITLE
Dropdown Doesn't appear correctly on android if put at the bottom of scrollview.

### ISSUE THREAD

**Issue by vinaygoyal20** [hossein-zare/react-native-dropdown-picker#86]
**Describe the bug**
Dropdown Doesn't appear correctly on android if put at the bottom of scrollview.If i want to see it properly i had to add extra height in the scrollview so that the dropdown list became properly visible. 

**To Reproduce**
<ScrollView style={{flex:1}}>
<View style={{height:height*90}}>
</View>
<DropDownPicker
            items={[
              {
                label: 'asd',
                value: 'asd',
              },
              {
                label: 'ts',
                value: 'ast',
              },
            ]}
            defaultValue={natureOffence}
            containerStyle={{
              height: moderateScaleVertical(43),
            }}
            dropDownStyle={{
              position:'relative',
              minHeight:200
            }}
            style={{
              ...commonStyles.shadowStyle,
              borderRadius: 0,
              borderTopRightRadius: 0,
              borderBottomLeftRadius: 0,
              borderTopLeftRadius: 0,
              borderBottomRightRadius: 0,
            }}
            itemStyle={{
              justifyContent: 'flex-start',
              fontSize: 16,
              fontWeight: 'bold',
            }}
            
          />
</ScrollView>

**Comment by hossein-zare** [comment]
Hello,
```javascript
dropDownMaxHeight={200}
```

**Comment by vinaygoyal20** [comment]
I already tried this but the thing is Scrollview inside which dropdown component is put only scrolls up to height when the dropdown is close. when we open the dropdown, the scrollview's height doesn't increase as the dropdown list increase.
if i just put a view with extra height equivalent to dropdown height just before the scrollview closes everything work just perfect but then when dropdown is closed that extra height looks weird.

**Comment by hossein-zare** [comment]
@vinaygoyal20 
Sorry for the late reply.
That is because the position of the dropdown is `absolute`
You can do this trick:

```javascript
const [pickerOpen, setPickerOpen] = useState(false);

<DropDownPicker
    onOpen={() => setPickerOpen(true)}
    onClose={() => setPickerOpen(false)}
    dropDownStyle={{
        minHeight:200
    }}
    dropDownMaxHeight={200}
/>

{pickerOpen && <View style={{ height: 210 }} />}
```

**Comment by vinaygoyal20** [comment]
Thanks @hossein-zare and kudos to you for build such a library,I was looking for something like this from a quite long time, I thought of build one from scratch but didn't got enough time, After using this i am pretty sure that  my search has ended. Building is one thing and maintaining it is different thing but you are doing both pretty well. All the best for future!!
