### ISSUE TITLE
Can't set default value

### ISSUE THREAD

**Issue by redwolfgang24** [hossein-zare/react-native-dropdown-picker#87]
When setting the default value I always got an error says undefined even if the value I set is not undefined.

**Comment by hossein-zare** [comment]
Hello,
If the default value doesn't exists in the items, You'll get the error.

```javascript
<DropDownPicker
    items={[
        {label: 'Label A', value: 'labelA'},
        {label: 'Label B', value: 'labelB'},
    ]}
    defaultValue={'labelB'}
/>
```

**Comment by redwolfgang24** [comment]
I already did that one, but still I got undefined error. The value I set exists but still got undefined error. I'll send you a screen shots.

**Comment by redwolfgang24** [comment]
Thanks @hossein-zare I found a workaround solution.
