### ISSUE TITLE
Dropdown behind the views

### ISSUE THREAD

**Issue by mtalhagaoglu** [hossein-zare/react-native-dropdown-picker#89]
I have 4 dropdown side by side. when i open one of them dropdown appear behind views. How can i fix that? I tried zIndex but it didnt' help my problem. and adding elevation makes untouchable.

![Screenshot_1598391016](https://user-images.githubusercontent.com/47723198/91230105-9eb17600-e733-11ea-848e-89e39d78e052.png)

I'm using bare react-native not expo.

`import React, {Component} from 'react';
import {
  SafeAreaView,
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Dimensions,
  FlatList,
  ScrollView,
} from 'react-native';
import Header from '../components/header';
import TopBar from '../components/topBar';
import DropDownPicker from 'react-native-dropdown-picker';
import Product from '../components/product';

const width = Dimensions.get('window').width;

export default class StoreScreen extends Component {
  state = {
    products: [
      {
        id: 0,
        image:
          'https://s3.us-east-2.amazonaws.com/fm-detroitaxle-cdn/images/products/R-53051FBK_681565783852/main.jpg',
        title: 'Front Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
      {
        id: 1,
        image:
          'https://images-na.ssl-images-amazon.com/images/I/61iq3VkhPiL._AC_SL1500_.jpg',
        title: 'Rear Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
      {
        id: 2,
        image:
          'https://s3.us-east-2.amazonaws.com/fm-detroitaxle-cdn/images/products/R-53051FBK_681565783852/main.jpg',
        title: 'Front Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
      {
        id: 3,
        image:
          'https://images-na.ssl-images-amazon.com/images/I/61iq3VkhPiL._AC_SL1500_.jpg',
        title: 'Rear Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
      {
        id: 4,
        image:
          'https://s3.us-east-2.amazonaws.com/fm-detroitaxle-cdn/images/products/R-53051FBK_681565783852/main.jpg',
        title: 'Front Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
      {
        id: 5,
        image:
          'https://images-na.ssl-images-amazon.com/images/I/61iq3VkhPiL._AC_SL1500_.jpg',
        title: 'Rear Brake',
        brandImage:
          'https://s19538.pcdn.co/wp-content/uploads/2017/07/Brembo-2-Logo.png',
        description: 'This is the original brake of Brembo',
      },
    ],
  };

  dropdown(label, state) {
    return (
      <View style={styles.dropdownContainer}>
        <Text style={styles.dropdownLabel}>{label}</Text>
        <DropDownPicker
          items={[
            {
              label: 'UK',
              value: 'uk',
            },
            {
              label: 'France',
              value: 'france',
            },
          ]}
          defaultValue={'uk'}
          containerStyle={{height: 30}}
          style={styles.dropdown}
          itemStyle={{
            justifyContent: 'flex-start',
          }}
          arrowColor={'white'}
          dropDownStyle={{width: '90%'}}
          onChangeItem={(item) =>
            this.setState({
              country: item.value,
            })
          }
        />
      </View>
    );
  }
  render() {
    const {navigation} = this.props;
    const {products} = this.state;
    return (
      <SafeAreaView style={styles.container}>
        <Header navigation={navigation} />
        <TopBar navigation={navigation} />
        <View style={styles.bodyContainer}>
          <View style={styles.dropdowns}>
            {this.dropdown('Makes')}
            {this.dropdown('Models')}
            {this.dropdown('Years')}
            {this.dropdown('Groups')}
          </View>
          <View style={styles.products}>
            <View style={styles.titleContainer}>
              <Text style={styles.title}>Filtered Store Products</Text>
            </View>
            <FlatList
              showsVerticalScrollIndicator={false}
              data={products}
              numColumns={2}
              style={{marginBottom: 100}}
              renderItem={({item}) => (
                <Product
                  image={item.image}
                  title={item.title}
                  brand={item.brandImage}
                  description={item.description}
                />
              )}
              keyExtractor={(item) => item.id}
            />
          </View>
        </View>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  bodyContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  dropdowns: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 8,
    marginTop: 8,
  },
  dropdownContainer: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  dropdownLabel: {
    color: '#979797',
  },
  dropdown: {
    width: '90%',
    backgroundColor: '#979797',
  },
  title: {
    fontWeight: 'bold',
    color: '#00008B',
    fontSize: 16,
  },
  titleContainer: {
    borderColor: '#eee',
    borderBottomWidth: 1,
    width: '100%',
    paddingVertical: 8,
    marginTop: 16,
  },
  products: {
    width: '96%',
    alignItems: 'center',
  },
});
`

**Comment by hossein-zare** [comment]
Hello,

Please reproduce the behavior on Snack, Your code is complicated.
https://snack.expo.io/

**Comment by hastagurung** [comment]
Did you found solution to this issue? came across with the same one
