### ISSUE TITLE
Placeholder styles

### ISSUE THREAD

**Issue by eazzyLEE** [hossein-zare/react-native-dropdown-picker#9]
Is there a way to implement placeholder styles such as font-family and colour? because the default placeholder style is bold and can come off as a pre-selected value.

**Comment by hossein-zare** [comment]
Hello,
I added the property to the package.

**Comment by eazzyLEE** [comment]
Thank you for your prompt response @hossein-zare it's very much appreciated, I will definitely try this out 😎. 
I also have had an issue with the `value` prop- I can't seem to find the comparison with the `value` prop  from react-native's **Picker** component, i.e. the prop that holds the current selected value of the component.

**Comment by hossein-zare** [comment]
Thank you for the feature request.
Sorry, I didn't get it, Please explain more if needed.

**Comment by eazzyLEE** [comment]
what I mean is, the `selectedValue` prop in the react-native [Picker](https://github.com/react-native-community/react-native-picker) component handles the selected value of the component at any time (the selected item that appears in the dropdown box),

<img width="230" alt="Screenshot 2020-05-23 at 11 34 17 PM" src="https://user-images.githubusercontent.com/29065790/82741811-febc0900-9d4d-11ea-93a6-6154b87fecef.png">
what is the equivalent prop in this package?

**Comment by hossein-zare** [comment]
I implemented the feature temporarily on an Expo Snack, but not sure if i want to change the way it handles the `defaultValue` or  `defaultIndex`.

[https://snack.expo.io/dv6H2oIWm](https://snack.expo.io/dv6H2oIWm)

**Comment by eazzyLEE** [comment]
Okay. but will this work with a placeholder too? According to the doc, placeholders work with the `defaultNull` property, so I'm assuming, to get placeholders to work, I have to set `defaultNull`, `placeholder` and `defaultValue` except if setting `defaultValue` to an initial value of **''** (empty string) will also work with placeholder.

**Comment by hossein-zare** [comment]
Simply add these two props to the component
```
defaultNull={this.state.value === null}
placeholder="Select your country"
```
It's working fine with the current change.
https://snack.expo.io/kQ52mfmQ5

You can also read **Dynamic Placeholder** in the doc.
