### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.state.props.items.findIndex')]

### ISSUE THREAD

**Issue by shorya-stanza** [hossein-zare/react-native-dropdown-picker#90]
**Description**
After selecting an item in the list getting this error

**To Reproduce**
Select any item

**Expected behavior**
In previous version it was working fine.

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [3.5.0]

**Additional context**

![Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 15 43 40](https://user-images.githubusercontent.com/63775111/91291901-5f2a6e80-e7b3-11ea-942f-bcc57b9439c9.png)

**Comment by hossein-zare** [comment]
Hello,
Please share your <DropDownPicker ... /> code.

**Comment by JonathanHallen1991** [comment]
I get the same error and this is my picker code:

<DropDownPicker
        items={[
          {
            label: 'English',
            value: 'en',
            icon: () => <Icon name="flag" size={18} color="#900" />,
          },
          {
            label: 'France',
            value: 'fr',
            icon: () => <Icon name="flag" size={18} color="#900" />,
          },
        ]}
        defaultValue={settings.selectedLanguage}
        containerStyle={styles.dropDownContainer}
        style={styles.dropDownStyle}
        itemStyle={styles.dropDownItem}
        dropDownStyle={styles.dropDownListStyle}
        onChangeItem={(item) => {
          setSettings({ ...settings, selectedLanguage: item.value });
        }}
      />

**Comment by hossein-zare** [comment]
@JonathanHallen1991 
What's the initial value for `settings.selectedLanguage`?

**Comment by JonathanHallen1991** [comment]
> @JonathanHallen1991
> What's the initial value for `settings.selectedLanguage`?

'en'

const [settings, setSettings] = useState({ selectedLanguage: 'en' });

**Comment by arbazz** [comment]
i am getting the same issue using functional component

**Comment by hossein-zare** [comment]
**Bug fixed**
Please install `react-native-dropdown-picker@3.5.1`
