### ISSUE TITLE
Arrow style: change position

### ISSUE THREAD

**Issue by ma3x-rus** [hossein-zare/react-native-dropdown-picker#91]
Hi there!
How can I change position of Arrow? I have two buttons and I need arrow on the right side at left button and arrow on the left side at right button. 
![m7dvdMckjSk](https://user-images.githubusercontent.com/70295953/91362528-5bbed380-e803-11ea-9daf-32451a6327e6.jpg)

**Comment by hossein-zare** [comment]
Hi,
You can't do that, unless i implement the feature.
Tomorrow i'll publish a version for it.

**Comment by ma3x-rus** [comment]
@hossein-zare Thank you!

**Comment by hossein-zare** [comment]
Hello again,

Please install `react-native-dropdown-picker@3.6.6`
https://github.com/hossein-zare/react-native-dropdown-picker#rtl-support

**Comment by ma3x-rus** [comment]
Hi there!
I updated react-native-dropdown-picker but it still doesn`t work for me
help please, what can I do wrong?
my styles:
itemStyle={{flexDirection: 'row-reverse', justifyContent: 'flex-end'}}
style={{
    backgroundColor: 'rgba(255,22,255,0)',
    width:width(47),
    borderRadius:width(0),
    flexDirection: 'row-reverse',
    borderColor: 'rgba(255,22,255,0)',
  },}

**Comment by rodrigodiasf1984** [comment]
> itemStyle={{flexDirection: 'row-reverse', justifyContent: 'flex-end'}}

   <DropDownPicker
          open={open}
          value={selectedValue}
          items={items}
          setOpen={setOpen}
          setValue={setSelectedValue}
          setItems={setItems}
          placeholder="Selecciona una opción"
          dropDownContainerStyle={{
            borderColor: '#dfdfdf',
          }}
          style={{
            borderColor: '#dfdfdf',
            flexDirection: 'row-reverse',
            alignItems: 'center',
          }}
        />
        
![image](https://user-images.githubusercontent.com/30758309/157908800-74610052-d067-4b71-b248-670dd049ebf6.png)


I hope this can help you!
