### ISSUE TITLE
Manual Option?

### ISSUE THREAD

**Issue by jasonpraful** [hossein-zare/react-native-dropdown-picker#92]
If there is no relevant dropdown option is there a way to key in manual values? and then save that value to the dropdown? I tried reading through the documentation but couldn't find anything relevant.

Cheers

**Comment by hossein-zare** [comment]
Hello,

Adding new items to the list?

**Comment by hossein-zare** [comment]
Please install `react-native-dropdown-picker@3.6.1`

You can add or reset the items maually:
https://github.com/hossein-zare/react-native-dropdown-picker#controller

**Comment by jasonpraful** [comment]
Hi Hossein,
Thanks for the swift reply. With the help of the search bar, I want to be able to add manual entries. so for example in the below screenshot if the option is not available I want the user to pick the text they have typed in. so in this example, since "Bleh" is not available I want the user to have a new option called bleh. So is there a way I can capture the text in that searchable box and then use it in the controller to add an item?

![image](https://user-images.githubusercontent.com/32552408/91581642-9aa97200-e946-11ea-9756-ab39ec8f454e.png)

**Comment by hossein-zare** [comment]
Unfortunately it's not possible.
I'll implement this feature soon.

**Comment by jasonpraful** [comment]
Hi Hossein - just wanted to know if you have had a chance to work on this yet?

Jason

**Comment by hossein-zare** [comment]
Hi @jasonpraful ,

Not yet, but i'll work on it, I'm busy these days.

**Comment by aravi365** [comment]
@hossein-zare  any updates

**Comment by hossein-zare** [comment]
@aravi365 You can use the `onSearch` property, it's not exactly the feature you want, but you need to spend hours.

**Comment by erkankarabulut** [comment]
@hossein-zare  I tried to add a new item with addItem method, inside onSearch method. But unfortunately it didn't add anything. Should I run any other method to achieve this?

```
<DropDownPicker
                items={...}
                controller={instance => this.measurementTypePickerController = instance}
                defaultValue={this.state.selectedMeasurementType}
                searchable={true}
                ...other stuff...
                onSearch={text => {
 this.measurementTypePickerController.removeItem(this.state.previousText, {
                        changeDefaultValue: true
                    });
                    this.measurementTypePickerController.addItem({
                        value: text,
                        label: text
                    });
                    this.setState({previousText: text});
                }}
                onChangeItem={item => {
                    this.setState({...: item.label})
                }}
            />
```

**Comment by hossein-zare** [comment]
Sorry for my late response.

Upgrade to v5.x.
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/search
