### ISSUE TITLE
Not able to access controller

### ISSUE THREAD

**Issue by hassan-akhtar** [hossein-zare/react-native-dropdown-picker#95]
- OS: [iOS]
 - Package version [3.5.1]

```
 constructor(props) {
    super(props);
    this.categoryController;
    this.state = {
    category: null
                  }
}
```
```

 <DropDownPicker
                  items={this.state.categoryList}
                  placeholder={"Select category"}
                  defaultValue={this.state.category}
                  controller={(instance) =>
                    (this.categoryController = instance)
                  }
                 .....
                ...../>
```

When I try to access the controller
`this.categoryController.reset();`

Crash:
Error:
<img width="218" alt="Screenshot 2020-08-28 at 19 58 32" src="https://user-images.githubusercontent.com/22542876/91605793-ed942100-e968-11ea-8cff-5ab6ec4dcd88.png">

**Comment by hossein-zare** [comment]
Hello,

Try this:
```javascript
controller={(instance) => this.categoryController = instance}
```

By the way, Please install `react-native-dropdown-picker@3.6.3`

**Comment by hassan-akhtar** [comment]
Hi,
I tried:
`controller={(instance) => this.categoryController = instance}`

Still same exception, I also update the version to 3.6.3

**Comment by hossein-zare** [comment]
https://snack.expo.io/o5jDyOdTo (Updated)

Please add your component code fully (not just the picker).

**Comment by hassan-akhtar** [comment]
I tried to copy your code from **https://snack.expo.io/o5jDyOdTo** it didn't work on my component but it works on the expo.
Not sure what the issue is.

(When I paste my code there it shows errors)

**Comment by hossein-zare** [comment]
Okay, I'll test it on a real project and let you know if the controller has issues.

**Comment by hossein-zare** [comment]
It's working well.
Make sure you're using the latest version.
Uninstall and install it.

**Comment by CorpOnThron** [comment]
@hossein-zare I have the same problem in my project.

Reinstalling does not help.

**Comment by hassan-akhtar** [comment]
I cleared the cache using 

`npm start -- --reset-cache`


and ran the project again, now i'm not getting the exception anymore

**Comment by CorpOnThron** [comment]
That seems to work! Thanks!
