### ISSUE TITLE
Items are not getting added to the drop down list after API response

### ISSUE THREAD

**Issue by CorpOnThron** [hossein-zare/react-native-dropdown-picker#96]
**Describe the bug**
After upgrade to the latest version, all items are not getting added to the list after they are received from API.

Items are added by reassigning array

**State**
![image](https://user-images.githubusercontent.com/39676808/91622241-267dc700-e964-11ea-9e9e-8eff2230c88a.png)

**API call**
![image](https://user-images.githubusercontent.com/39676808/91622260-3dbcb480-e964-11ea-85c6-5ae2ba7adc3e.png)

**Dropdownpicker:**

![image](https://user-images.githubusercontent.com/39676808/91622195-f7675580-e963-11ea-857c-f52703d061ed.png)

**View:**
![image](https://user-images.githubusercontent.com/39676808/91622111-9fc8ea00-e963-11ea-828d-7c7b5765edcd.png)

 - OS: Android

**Comment by Sbarcenas** [comment]
Hello, thanks for the excellent library =).
I have the same Issue, the component not refresh the items when the state is update or data change.

**Comment by DurgeshSupraDigit** [comment]
Yup  I am also facing the same Issue  after the new Updated Version , a fix would be really appreciated ! 
Thank You for such a great Library :)

**Comment by hossein-zare** [comment]
Hello again,

**Bug fixed.**
Install `react-native-dropdown-picker@3.6.6`

If you're using **The Controller**, You should also read the **Usage** section of it.
https://github.com/hossein-zare/react-native-dropdown-picker#controller
