### ISSUE TITLE
do not open picker by deafult when clicking on it

### ISSUE THREAD

**Issue by mitesh-db** [hossein-zare/react-native-dropdown-picker#97]
Hi @hossein-zare , I am facing one issue.

I want to check some condition on picker press, if condition matches then I want to open picker, else picker should not open by default.

I have set isVisible false inside onOpen, but it still opens when clicking on it.

Is there anyway to not open picker by default when pressing on it?

**Comment by hossein-zare** [comment]
Hello,

Are you looking for `disabled`?
If not, Please create an Expo Snack and reproduce the behavior.

**Comment by mitesh-db** [comment]
Here is simple expo snack demo, https://snack.expo.io/aAuTNJLbL

Here I have put `isVisible=false` so I guess picker should not open by Default when clicking on it.

I have also done custom logic with demo on my computer where I'm setting pointerEvents with conditions which is working fine but zIndex is not working with all Touchables (TouchableOpacity, TouchableHighlight, etc..) so I'm facing overlapping issues there, and putting simple View makes picker open by default when click.

**Comment by mitesh-db** [comment]
Wait I think i can work around with disabled={true/false}
Is there anything like disabled text style or something? so I can make placeholder color black when dropdown is disabled

**Comment by hossein-zare** [comment]
No, But you can modify the package which exists in the node_modules directory,
